In [1]:
import os
import scanpy as sc
import pandas as pd
import anndata as ad
import numpy as np
import matplotlib.pyplot as plt
import json
import time
import logging
from tqdm import tqdm

import czbenchmarks.datasets.utils_single_cell as scp
from czbenchmarks.datasets.utils_control_cells import get_matched_controls

## Load Data

In [2]:
# filtered_data_path = f"{os.environ['HOME']}/.cz-benchmarks/datasets/replogle_k562_essential_perturbpredict_de_results_control_cells.h5ad"
filtered_data_path = "/data2/czbenchmarks/replogle2022/K562_essential_raw_singlecell_01.h5ad"
adata_filtered = sc.read_h5ad(filtered_data_path, backed=None)
adata_filtered.obs = adata_filtered.obs.rename(columns={'gene_id':'condition', 'gene':'condition_name'})
adata_filtered.var = adata_filtered.var.rename(columns={'gene_name':'gene'})
adata_filtered.obs['condition'] = adata_filtered.obs['condition'].astype(str)

In [3]:
# cr4_data_path = (
#     "/data2/czbenchmarks/replogle2022/raw_h5ad_from_cr4/K562_essential_mtx.h5ad"
# )
# adata_cr4 = ad.read_h5ad(cr4_data_path, backed=None)
# adata_cr4.var.index.name = "gene_id"
# adata_cr4.var.rename(columns={"gene_name": "gene"}, inplace=True)
# adata_cr4.obs.rename(columns={"gene_id": "condition"}, inplace=True)

## Run Generation

In [4]:
condition_list = np.asarray([x for x in adata_filtered.obs.condition.unique() if x != 'non-targeting'])

control_cells_ids = {}
total_conditions = len(condition_list)
with tqdm(
        total=total_conditions, desc="Processing conditions", unit="item"
    ) as pbar:
    for condition in condition_list:
        print(f"Getting matched controls for {condition}")
        pert_cells, matched_controls = get_matched_controls(
            adata=adata_filtered,
            perturbation=condition,
            min_cells=1,
            matchtype="GEM",
            verbose=False,
            dict_ctrls=None,
            dataset=None, # 'replogle'
            pert_column='condition',
            ctrl_condition='non-targeting',
            gem_column='gem_group',
            libsize_column='UMI_count',
        )
        if matched_controls:
            control_cells_ids[condition] = matched_controls
            print(f"Found {len(matched_controls)} matched controls for {condition}")
            
        pbar.set_postfix_str(f"Completed {pbar.n + 1}/{total_conditions}")
        pbar.update(1)

print("Saving new control cells ids to json")
with open("/data2/czbenchmarks/control_cells_ids_replogle_k562_essential_perturbpredict_v2.json", "w") as f:
    json.dump(control_cells_ids, f)

Processing conditions:   0%|                                                                                                 | 0/2057 [00:00<?, ?item/s]

Getting matched controls for ENSG00000145414

Processing conditions:   0%|                                                                       | 1/2057 [00:00<07:42,  4.45item/s, Completed 1/2057]

Found 94 matched controls for ENSG00000145414
Getting matched controls for ENSG00000169679

Processing conditions:   0%|                                                                       | 2/2057 [00:01<24:52,  1.38item/s, Completed 2/2057]

Found 648 matched controls for ENSG00000169679
Getting matched controls for ENSG00000198258

Processing conditions:   0%|                                                                       | 3/2057 [00:01<19:55,  1.72item/s, Completed 3/2057]

Found 232 matched controls for ENSG00000198258
Getting matched controls for ENSG00000171159

Processing conditions:   0%|▏                                                                      | 4/2057 [00:02<17:10,  1.99item/s, Completed 4/2057]

Found 212 matched controls for ENSG00000171159
Getting matched controls for ENSG00000100575

Processing conditions:   0%|▏                                                                      | 6/2057 [00:02<12:13,  2.80item/s, Completed 6/2057]

Found 201 matched controls for ENSG00000100575
Getting matched controls for ENSG00000198952
Found 83 matched controls for ENSG00000198952
Getting matched controls for ENSG00000143373

Processing conditions:   0%|▏                                                                      | 7/2057 [00:02<12:20,  2.77item/s, Completed 7/2057]

Found 205 matched controls for ENSG00000143373
Getting matched controls for ENSG00000141026

Processing conditions:   0%|▎                                                                      | 8/2057 [00:03<10:58,  3.11item/s, Completed 8/2057]

Found 119 matched controls for ENSG00000141026
Getting matched controls for ENSG00000100316

Processing conditions:   0%|▎                                                                      | 9/2057 [00:06<45:18,  1.33s/item, Completed 9/2057]

Found 1996 matched controls for ENSG00000100316
Getting matched controls for ENSG00000179988

Processing conditions:   0%|▎                                                                    | 10/2057 [00:07<37:57,  1.11s/item, Completed 10/2057]

Found 379 matched controls for ENSG00000179988
Getting matched controls for ENSG00000112130

Processing conditions:   1%|▎                                                                    | 11/2057 [00:07<30:08,  1.13item/s, Completed 11/2057]

Found 176 matched controls for ENSG00000112130
Getting matched controls for ENSG00000125686

Processing conditions:   1%|▍                                                                    | 12/2057 [00:08<25:31,  1.34item/s, Completed 12/2057]

Found 254 matched controls for ENSG00000125686
Getting matched controls for ENSG00000169045

Processing conditions:   1%|▍                                                                    | 13/2057 [00:08<21:06,  1.61item/s, Completed 13/2057]

Found 160 matched controls for ENSG00000169045
Getting matched controls for ENSG00000198755

Processing conditions:   1%|▌                                                                    | 15/2057 [00:09<15:12,  2.24item/s, Completed 15/2057]

Found 257 matched controls for ENSG00000198755
Getting matched controls for ENSG00000121073
Found 70 matched controls for ENSG00000121073
Getting matched controls for ENSG00000189308

Processing conditions:   1%|▌                                                                    | 16/2057 [00:09<16:11,  2.10item/s, Completed 16/2057]

Found 306 matched controls for ENSG00000189308
Getting matched controls for ENSG00000173674

Processing conditions:   1%|▌                                                                    | 17/2057 [00:09<14:05,  2.41item/s, Completed 17/2057]

Found 134 matched controls for ENSG00000173674
Getting matched controls for ENSG00000185385

Processing conditions:   1%|▌                                                                    | 18/2057 [00:10<12:03,  2.82item/s, Completed 18/2057]

Found 108 matched controls for ENSG00000185385
Getting matched controls for ENSG00000110713

Processing conditions:   1%|▋                                                                    | 19/2057 [00:11<17:30,  1.94item/s, Completed 19/2057]

Found 510 matched controls for ENSG00000110713
Getting matched controls for ENSG00000104147

Processing conditions:   1%|▋                                                                    | 20/2057 [00:11<14:55,  2.28item/s, Completed 20/2057]

Found 137 matched controls for ENSG00000104147
Getting matched controls for ENSG00000110200

Processing conditions:   1%|▋                                                                    | 21/2057 [00:12<17:37,  1.93item/s, Completed 21/2057]

Found 424 matched controls for ENSG00000110200
Getting matched controls for ENSG00000171848

Processing conditions:   1%|▋                                                                    | 22/2057 [00:12<21:54,  1.55item/s, Completed 22/2057]

Found 577 matched controls for ENSG00000171848
Getting matched controls for ENSG00000156239

Processing conditions:   1%|▊                                                                    | 23/2057 [00:13<17:58,  1.89item/s, Completed 23/2057]

Found 138 matched controls for ENSG00000156239
Getting matched controls for ENSG00000008988

Processing conditions:   1%|▊                                                                    | 24/2057 [00:13<17:31,  1.93item/s, Completed 24/2057]

Found 273 matched controls for ENSG00000008988
Getting matched controls for ENSG00000146457

Processing conditions:   1%|▊                                                                    | 25/2057 [00:14<15:20,  2.21item/s, Completed 25/2057]

Found 165 matched controls for ENSG00000146457
Getting matched controls for ENSG00000058729

Processing conditions:   1%|▊                                                                    | 26/2057 [00:14<14:18,  2.37item/s, Completed 26/2057]

Found 174 matched controls for ENSG00000058729
Getting matched controls for ENSG00000144021

Processing conditions:   1%|▉                                                                    | 27/2057 [00:14<14:29,  2.33item/s, Completed 27/2057]

Found 255 matched controls for ENSG00000144021
Getting matched controls for ENSG00000172336

Processing conditions:   1%|▉                                                                    | 28/2057 [00:15<14:08,  2.39item/s, Completed 28/2057]

Found 218 matched controls for ENSG00000172336
Getting matched controls for ENSG00000104408

Processing conditions:   1%|▉                                                                    | 29/2057 [00:15<14:22,  2.35item/s, Completed 29/2057]

Found 232 matched controls for ENSG00000104408
Getting matched controls for ENSG00000120333

Processing conditions:   1%|█                                                                    | 30/2057 [00:15<12:10,  2.77item/s, Completed 30/2057]

Found 92 matched controls for ENSG00000120333
Getting matched controls for ENSG00000174527

Processing conditions:   2%|█                                                                    | 31/2057 [00:16<10:58,  3.08item/s, Completed 31/2057]

Found 124 matched controls for ENSG00000174527
Getting matched controls for ENSG00000112651

Processing conditions:   2%|█                                                                    | 32/2057 [00:16<10:40,  3.16item/s, Completed 32/2057]

Found 147 matched controls for ENSG00000112651
Getting matched controls for ENSG00000133398

Processing conditions:   2%|█                                                                    | 33/2057 [00:17<16:17,  2.07item/s, Completed 33/2057]

Found 516 matched controls for ENSG00000133398
Getting matched controls for ENSG00000136527

Processing conditions:   2%|█▏                                                                   | 34/2057 [00:17<15:32,  2.17item/s, Completed 34/2057]

Found 222 matched controls for ENSG00000136527
Getting matched controls for ENSG00000013275

Processing conditions:   2%|█▏                                                                   | 35/2057 [00:18<15:08,  2.23item/s, Completed 35/2057]

Found 242 matched controls for ENSG00000013275
Getting matched controls for ENSG00000183011

Processing conditions:   2%|█▏                                                                   | 36/2057 [00:18<16:53,  1.99item/s, Completed 36/2057]

Found 368 matched controls for ENSG00000183011
Getting matched controls for ENSG00000167615

Processing conditions:   2%|█▏                                                                   | 37/2057 [00:18<14:13,  2.37item/s, Completed 37/2057]

Found 121 matched controls for ENSG00000167615
Getting matched controls for ENSG00000140326

Processing conditions:   2%|█▎                                                                   | 38/2057 [00:19<12:34,  2.68item/s, Completed 38/2057]

Found 137 matched controls for ENSG00000140326
Getting matched controls for ENSG00000174996

Processing conditions:   2%|█▎                                                                   | 39/2057 [00:19<11:18,  2.97item/s, Completed 39/2057]

Found 127 matched controls for ENSG00000174996
Getting matched controls for ENSG00000110172

Processing conditions:   2%|█▎                                                                   | 40/2057 [00:19<12:47,  2.63item/s, Completed 40/2057]

Found 259 matched controls for ENSG00000110172
Getting matched controls for ENSG00000149923

Processing conditions:   2%|█▍                                                                   | 42/2057 [00:20<09:57,  3.37item/s, Completed 42/2057]

Found 171 matched controls for ENSG00000149923
Getting matched controls for ENSG00000099246
Found 43 matched controls for ENSG00000099246
Getting matched controls for ENSG00000130640

Processing conditions:   2%|█▍                                                                   | 43/2057 [00:20<11:25,  2.94item/s, Completed 43/2057]

Found 238 matched controls for ENSG00000130640
Getting matched controls for ENSG00000149100

Processing conditions:   2%|█▍                                                                   | 44/2057 [00:21<12:16,  2.73item/s, Completed 44/2057]

Found 246 matched controls for ENSG00000149100
Getting matched controls for ENSG00000105767

Processing conditions:   2%|█▌                                                                   | 45/2057 [00:21<15:16,  2.19item/s, Completed 45/2057]

Found 381 matched controls for ENSG00000105767
Getting matched controls for ENSG00000122406

Processing conditions:   2%|█▌                                                                   | 46/2057 [00:22<14:41,  2.28item/s, Completed 46/2057]

Found 200 matched controls for ENSG00000122406
Getting matched controls for ENSG00000140534

Processing conditions:   2%|█▌                                                                   | 47/2057 [00:22<13:23,  2.50item/s, Completed 47/2057]

Found 157 matched controls for ENSG00000140534
Getting matched controls for ENSG00000167526

Processing conditions:   2%|█▌                                                                   | 48/2057 [00:23<15:19,  2.19item/s, Completed 48/2057]

Found 337 matched controls for ENSG00000167526
Getting matched controls for ENSG00000138160

Processing conditions:   2%|█▋                                                                   | 49/2057 [00:24<27:12,  1.23item/s, Completed 49/2057]

Found 974 matched controls for ENSG00000138160
Getting matched controls for ENSG00000105011

Processing conditions:   2%|█▋                                                                   | 50/2057 [00:25<24:27,  1.37item/s, Completed 50/2057]

Found 284 matched controls for ENSG00000105011
Getting matched controls for ENSG00000088038

Processing conditions:   2%|█▋                                                                   | 51/2057 [00:26<23:01,  1.45item/s, Completed 51/2057]

Found 332 matched controls for ENSG00000088038
Getting matched controls for ENSG00000134987

Processing conditions:   3%|█▋                                                                   | 52/2057 [00:26<21:16,  1.57item/s, Completed 52/2057]

Found 285 matched controls for ENSG00000134987
Getting matched controls for ENSG00000071082

Processing conditions:   3%|█▊                                                                   | 53/2057 [00:27<20:08,  1.66item/s, Completed 53/2057]

Found 294 matched controls for ENSG00000071082
Getting matched controls for ENSG00000164975

Processing conditions:   3%|█▊                                                                   | 54/2057 [00:27<17:53,  1.87item/s, Completed 54/2057]

Found 212 matched controls for ENSG00000164975
Getting matched controls for ENSG00000184634

Processing conditions:   3%|█▊                                                                   | 55/2057 [00:28<23:33,  1.42item/s, Completed 55/2057]

Found 573 matched controls for ENSG00000184634
Getting matched controls for ENSG00000100033

Processing conditions:   3%|█▉                                                                   | 56/2057 [00:29<23:01,  1.45item/s, Completed 56/2057]

Found 379 matched controls for ENSG00000100033
Getting matched controls for ENSG00000151779

Processing conditions:   3%|█▉                                                                   | 57/2057 [00:29<18:15,  1.83item/s, Completed 57/2057]

Found 107 matched controls for ENSG00000151779
Getting matched controls for ENSG00000175216

Processing conditions:   3%|█▉                                                                   | 58/2057 [00:29<18:08,  1.84item/s, Completed 58/2057]

Found 315 matched controls for ENSG00000175216
Getting matched controls for ENSG00000170291

Processing conditions:   3%|█▉                                                                   | 59/2057 [00:30<15:54,  2.09item/s, Completed 59/2057]

Found 177 matched controls for ENSG00000170291
Getting matched controls for ENSG00000215421

Processing conditions:   3%|██                                                                   | 60/2057 [00:30<13:21,  2.49item/s, Completed 60/2057]

Found 112 matched controls for ENSG00000215421
Getting matched controls for ENSG00000110025

Processing conditions:   3%|██                                                                   | 61/2057 [00:31<19:50,  1.68item/s, Completed 61/2057]

Found 637 matched controls for ENSG00000110025
Getting matched controls for ENSG00000137154

Processing conditions:   3%|██                                                                   | 62/2057 [00:31<17:06,  1.94item/s, Completed 62/2057]

Found 178 matched controls for ENSG00000137154
Getting matched controls for ENSG00000108423

Processing conditions:   3%|██▏                                                                  | 64/2057 [00:32<12:07,  2.74item/s, Completed 64/2057]

Found 190 matched controls for ENSG00000108423
Getting matched controls for ENSG00000157020
Found 56 matched controls for ENSG00000157020
Getting matched controls for ENSG00000151247

Processing conditions:   3%|██▏                                                                  | 65/2057 [00:32<14:29,  2.29item/s, Completed 65/2057]

Found 357 matched controls for ENSG00000151247
Getting matched controls for ENSG00000164032

Processing conditions:   3%|██▏                                                                  | 66/2057 [00:33<12:16,  2.70item/s, Completed 66/2057]

Found 106 matched controls for ENSG00000164032
Getting matched controls for ENSG00000254772

Processing conditions:   3%|██▏                                                                  | 67/2057 [00:33<11:48,  2.81item/s, Completed 67/2057]

Found 175 matched controls for ENSG00000254772
Getting matched controls for ENSG00000086061

Processing conditions:   3%|██▎                                                                  | 68/2057 [00:34<13:14,  2.50item/s, Completed 68/2057]

Found 292 matched controls for ENSG00000086061
Getting matched controls for ENSG00000041802

Processing conditions:   3%|██▎                                                                  | 69/2057 [00:34<11:34,  2.86item/s, Completed 69/2057]

Found 116 matched controls for ENSG00000041802
Getting matched controls for ENSG00000112029

Processing conditions:   3%|██▎                                                                  | 70/2057 [00:34<13:40,  2.42item/s, Completed 70/2057]

Found 326 matched controls for ENSG00000112029
Getting matched controls for ENSG00000198793

Processing conditions:   3%|██▍                                                                  | 71/2057 [00:35<11:52,  2.79item/s, Completed 71/2057]

Found 101 matched controls for ENSG00000198793
Getting matched controls for ENSG00000061936

Processing conditions:   4%|██▍                                                                  | 73/2057 [00:35<09:44,  3.39item/s, Completed 73/2057]

Found 172 matched controls for ENSG00000061936
Getting matched controls for ENSG00000138592
Found 74 matched controls for ENSG00000138592
Getting matched controls for ENSG00000102241

Processing conditions:   4%|██▍                                                                  | 74/2057 [00:35<08:47,  3.76item/s, Completed 74/2057]

Found 96 matched controls for ENSG00000102241
Getting matched controls for ENSG00000196235

Processing conditions:   4%|██▌                                                                  | 75/2057 [00:36<12:54,  2.56item/s, Completed 75/2057]

Found 406 matched controls for ENSG00000196235
Getting matched controls for ENSG00000160193

Processing conditions:   4%|██▌                                                                  | 76/2057 [00:37<15:10,  2.17item/s, Completed 76/2057]

Found 347 matched controls for ENSG00000160193
Getting matched controls for ENSG00000161203

Processing conditions:   4%|██▌                                                                  | 78/2057 [00:37<11:27,  2.88item/s, Completed 78/2057]

Found 215 matched controls for ENSG00000161203
Getting matched controls for ENSG00000092020
Found 52 matched controls for ENSG00000092020
Getting matched controls for ENSG00000213906

Processing conditions:   4%|██▋                                                                  | 79/2057 [00:37<11:37,  2.84item/s, Completed 79/2057]

Found 188 matched controls for ENSG00000213906
Getting matched controls for ENSG00000114867

Processing conditions:   4%|██▋                                                                  | 80/2057 [00:38<14:46,  2.23item/s, Completed 80/2057]

Found 372 matched controls for ENSG00000114867
Getting matched controls for ENSG00000132383

Processing conditions:   4%|██▋                                                                  | 81/2057 [00:39<18:26,  1.79item/s, Completed 81/2057]

Found 469 matched controls for ENSG00000132383
Getting matched controls for ENSG00000196367

Processing conditions:   4%|██▊                                                                  | 82/2057 [00:40<20:30,  1.60item/s, Completed 82/2057]

Found 427 matched controls for ENSG00000196367
Getting matched controls for ENSG00000185024

Processing conditions:   4%|██▊                                                                  | 83/2057 [00:40<17:23,  1.89item/s, Completed 83/2057]

Found 166 matched controls for ENSG00000185024
Getting matched controls for ENSG00000155561

Processing conditions:   4%|██▊                                                                  | 84/2057 [00:41<24:42,  1.33item/s, Completed 84/2057]

Found 735 matched controls for ENSG00000155561
Getting matched controls for ENSG00000196504

Processing conditions:   4%|██▊                                                                  | 85/2057 [00:42<19:50,  1.66item/s, Completed 85/2057]

Found 118 matched controls for ENSG00000196504
Getting matched controls for ENSG00000113013

Processing conditions:   4%|██▉                                                                  | 86/2057 [00:42<20:50,  1.58item/s, Completed 86/2057]

Found 420 matched controls for ENSG00000113013
Getting matched controls for ENSG00000164609

Processing conditions:   4%|██▉                                                                  | 87/2057 [00:43<18:33,  1.77item/s, Completed 87/2057]

Found 225 matched controls for ENSG00000164609
Getting matched controls for ENSG00000145833

Processing conditions:   4%|██▉                                                                  | 88/2057 [00:43<16:46,  1.96item/s, Completed 88/2057]

Found 214 matched controls for ENSG00000145833
Getting matched controls for ENSG00000048162

Processing conditions:   4%|██▉                                                                  | 89/2057 [00:43<14:29,  2.26item/s, Completed 89/2057]

Found 149 matched controls for ENSG00000048162
Getting matched controls for ENSG00000165688

Processing conditions:   4%|███                                                                  | 90/2057 [00:44<12:46,  2.57item/s, Completed 90/2057]

Found 140 matched controls for ENSG00000165688
Getting matched controls for ENSG00000117481

Processing conditions:   4%|███                                                                  | 92/2057 [00:44<09:43,  3.37item/s, Completed 92/2057]

Found 156 matched controls for ENSG00000117481
Getting matched controls for ENSG00000112855
Found 62 matched controls for ENSG00000112855
Getting matched controls for ENSG00000101868

Processing conditions:   5%|███                                                                  | 93/2057 [00:44<10:45,  3.04item/s, Completed 93/2057]

Found 230 matched controls for ENSG00000101868
Getting matched controls for ENSG00000060688

Processing conditions:   5%|███▏                                                                 | 94/2057 [00:45<11:11,  2.92item/s, Completed 94/2057]

Found 210 matched controls for ENSG00000060688
Getting matched controls for ENSG00000125037

Processing conditions:   5%|███▏                                                                 | 95/2057 [00:45<11:34,  2.83item/s, Completed 95/2057]

Found 195 matched controls for ENSG00000125037
Getting matched controls for ENSG00000100632
Found 86 matched controls for ENSG00000100632

Processing conditions:   5%|███▏                                                                 | 96/2057 [00:45<10:04,  3.24item/s, Completed 96/2057]

Getting matched controls for ENSG00000125445

Processing conditions:   5%|███▎                                                                 | 97/2057 [00:46<09:24,  3.47item/s, Completed 97/2057]

Found 123 matched controls for ENSG00000125445
Getting matched controls for ENSG00000151849

Processing conditions:   5%|███▎                                                                 | 98/2057 [00:46<11:47,  2.77item/s, Completed 98/2057]

Found 282 matched controls for ENSG00000151849
Getting matched controls for ENSG00000147586

Processing conditions:   5%|███▎                                                                 | 99/2057 [00:46<11:29,  2.84item/s, Completed 99/2057]

Found 158 matched controls for ENSG00000147586
Getting matched controls for ENSG00000103257

Processing conditions:   5%|███▎                                                               | 100/2057 [00:47<14:43,  2.22item/s, Completed 100/2057]

Found 378 matched controls for ENSG00000103257
Getting matched controls for ENSG00000177954

Processing conditions:   5%|███▎                                                               | 101/2057 [00:47<13:41,  2.38item/s, Completed 101/2057]

Found 174 matched controls for ENSG00000177954
Getting matched controls for ENSG00000109111

Processing conditions:   5%|███▎                                                               | 102/2057 [00:48<14:45,  2.21item/s, Completed 102/2057]

Found 288 matched controls for ENSG00000109111
Getting matched controls for ENSG00000163714

Processing conditions:   5%|███▎                                                               | 103/2057 [00:49<15:31,  2.10item/s, Completed 103/2057]

Found 290 matched controls for ENSG00000163714
Getting matched controls for ENSG00000127554

Processing conditions:   5%|███▍                                                               | 105/2057 [00:49<11:44,  2.77item/s, Completed 105/2057]

Found 222 matched controls for ENSG00000127554
Getting matched controls for ENSG00000035141
Found 50 matched controls for ENSG00000035141
Getting matched controls for ENSG00000155666

Processing conditions:   5%|███▍                                                               | 106/2057 [00:49<09:34,  3.40item/s, Completed 106/2057]

Found 56 matched controls for ENSG00000155666
Getting matched controls for ENSG00000108561

Processing conditions:   5%|███▍                                                               | 107/2057 [00:50<10:20,  3.14item/s, Completed 107/2057]

Found 210 matched controls for ENSG00000108561
Getting matched controls for ENSG00000213221

Processing conditions:   5%|███▌                                                               | 108/2057 [00:50<09:49,  3.30item/s, Completed 108/2057]

Found 140 matched controls for ENSG00000213221
Getting matched controls for ENSG00000146007

Processing conditions:   5%|███▌                                                               | 109/2057 [00:51<14:11,  2.29item/s, Completed 109/2057]

Found 436 matched controls for ENSG00000146007
Getting matched controls for ENSG00000137876

Processing conditions:   5%|███▌                                                               | 110/2057 [00:51<13:06,  2.48item/s, Completed 110/2057]

Found 179 matched controls for ENSG00000137876
Getting matched controls for ENSG00000105819

Processing conditions:   5%|███▋                                                               | 112/2057 [00:52<14:17,  2.27item/s, Completed 112/2057]

Found 553 matched controls for ENSG00000105819
Getting matched controls for ENSG00000169062
Found 76 matched controls for ENSG00000169062
Getting matched controls for ENSG00000110700

Processing conditions:   5%|███▋                                                               | 113/2057 [00:52<12:38,  2.56item/s, Completed 113/2057]

Found 135 matched controls for ENSG00000110700
Getting matched controls for ENSG00000105705

Processing conditions:   6%|███▋                                                               | 115/2057 [00:53<09:50,  3.29item/s, Completed 115/2057]

Found 149 matched controls for ENSG00000105705
Getting matched controls for ENSG00000145741
Found 79 matched controls for ENSG00000145741
Getting matched controls for ENSG00000142657

Processing conditions:   6%|███▊                                                               | 116/2057 [00:53<09:16,  3.49item/s, Completed 116/2057]

Found 115 matched controls for ENSG00000142657
Getting matched controls for ENSG00000144028

Processing conditions:   6%|███▊                                                               | 117/2057 [00:53<10:01,  3.23item/s, Completed 117/2057]

Found 169 matched controls for ENSG00000144028
Getting matched controls for ENSG00000116752

Processing conditions:   6%|███▊                                                               | 118/2057 [00:54<10:56,  2.96item/s, Completed 118/2057]

Found 227 matched controls for ENSG00000116752
Getting matched controls for ENSG00000167535

Processing conditions:   6%|███▉                                                               | 119/2057 [00:54<13:04,  2.47item/s, Completed 119/2057]

Found 316 matched controls for ENSG00000167535
Getting matched controls for ENSG00000051180

Processing conditions:   6%|███▉                                                               | 120/2057 [00:55<14:00,  2.31item/s, Completed 120/2057]

Found 241 matched controls for ENSG00000051180
Getting matched controls for ENSG00000029364

Processing conditions:   6%|███▉                                                               | 121/2057 [00:56<22:14,  1.45item/s, Completed 121/2057]

Found 752 matched controls for ENSG00000029364
Getting matched controls for ENSG00000105281

Processing conditions:   6%|███▉                                                               | 122/2057 [00:57<23:38,  1.36item/s, Completed 122/2057]

Found 490 matched controls for ENSG00000105281
Getting matched controls for ENSG00000090273

Processing conditions:   6%|████                                                               | 124/2057 [00:57<14:18,  2.25item/s, Completed 124/2057]

Found 117 matched controls for ENSG00000090273
Getting matched controls for ENSG00000142207
Found 33 matched controls for ENSG00000142207
Getting matched controls for ENSG00000165060

Processing conditions:   6%|████                                                               | 125/2057 [00:58<13:19,  2.42item/s, Completed 125/2057]

Found 174 matched controls for ENSG00000165060
Getting matched controls for ENSG00000165494

Processing conditions:   6%|████                                                               | 126/2057 [00:59<17:20,  1.86item/s, Completed 126/2057]

Found 499 matched controls for ENSG00000165494
Getting matched controls for ENSG00000142230

Processing conditions:   6%|████▏                                                              | 127/2057 [00:59<14:55,  2.16item/s, Completed 127/2057]

Found 121 matched controls for ENSG00000142230
Getting matched controls for ENSG00000142864

Processing conditions:   6%|████▏                                                              | 128/2057 [00:59<12:51,  2.50item/s, Completed 128/2057]

Found 109 matched controls for ENSG00000142864
Getting matched controls for ENSG00000131269

Processing conditions:   6%|████▏                                                              | 129/2057 [00:59<12:57,  2.48item/s, Completed 129/2057]

Found 199 matched controls for ENSG00000131269
Getting matched controls for ENSG00000100567

Processing conditions:   6%|████▎                                                              | 131/2057 [01:00<12:20,  2.60item/s, Completed 131/2057]

Found 372 matched controls for ENSG00000100567
Getting matched controls for ENSG00000100109
Found 61 matched controls for ENSG00000100109
Getting matched controls for ENSG00000197728

Processing conditions:   6%|████▎                                                              | 132/2057 [01:00<10:36,  3.02item/s, Completed 132/2057]

Found 87 matched controls for ENSG00000197728
Getting matched controls for ENSG00000198042

Processing conditions:   6%|████▎                                                              | 133/2057 [01:01<11:20,  2.83item/s, Completed 133/2057]

Found 213 matched controls for ENSG00000198042
Getting matched controls for ENSG00000172497

Processing conditions:   7%|████▎                                                              | 134/2057 [01:01<11:25,  2.80item/s, Completed 134/2057]

Found 180 matched controls for ENSG00000172497
Getting matched controls for ENSG00000204152

Processing conditions:   7%|████▍                                                              | 135/2057 [01:02<16:12,  1.98item/s, Completed 135/2057]

Found 498 matched controls for ENSG00000204152
Getting matched controls for ENSG00000109519

Processing conditions:   7%|████▍                                                              | 136/2057 [01:02<14:00,  2.29item/s, Completed 136/2057]

Found 123 matched controls for ENSG00000109519
Getting matched controls for ENSG00000131174

Processing conditions:   7%|████▍                                                              | 137/2057 [01:03<12:27,  2.57item/s, Completed 137/2057]

Found 120 matched controls for ENSG00000131174
Getting matched controls for ENSG00000211456

Processing conditions:   7%|████▍                                                              | 138/2057 [01:03<12:04,  2.65item/s, Completed 138/2057]

Found 193 matched controls for ENSG00000211456
Getting matched controls for ENSG00000107581

Processing conditions:   7%|████▌                                                              | 139/2057 [01:04<14:41,  2.17item/s, Completed 139/2057]

Found 379 matched controls for ENSG00000107581
Getting matched controls for ENSG00000111142

Processing conditions:   7%|████▌                                                              | 141/2057 [01:04<10:39,  3.00item/s, Completed 141/2057]

Found 161 matched controls for ENSG00000111142
Getting matched controls for ENSG00000131732
Found 54 matched controls for ENSG00000131732
Getting matched controls for ENSG00000155975

Processing conditions:   7%|████▋                                                              | 142/2057 [01:04<09:14,  3.45item/s, Completed 142/2057]

Found 75 matched controls for ENSG00000155975
Getting matched controls for ENSG00000188186

Processing conditions:   7%|████▋                                                              | 143/2057 [01:05<09:28,  3.37item/s, Completed 143/2057]

Found 136 matched controls for ENSG00000188186
Getting matched controls for ENSG00000145592

Processing conditions:   7%|████▋                                                              | 144/2057 [01:05<14:09,  2.25item/s, Completed 144/2057]

Found 382 matched controls for ENSG00000145592
Getting matched controls for ENSG00000171490

Processing conditions:   7%|████▊                                                              | 146/2057 [01:06<10:47,  2.95item/s, Completed 146/2057]

Found 211 matched controls for ENSG00000171490
Getting matched controls for ENSG00000136518
Found 55 matched controls for ENSG00000136518
Getting matched controls for ENSG00000100410

Processing conditions:   7%|████▊                                                              | 147/2057 [01:06<11:26,  2.78item/s, Completed 147/2057]

Found 231 matched controls for ENSG00000100410
Getting matched controls for ENSG00000117174

Processing conditions:   7%|████▊                                                              | 148/2057 [01:07<10:13,  3.11item/s, Completed 148/2057]

Found 117 matched controls for ENSG00000117174
Getting matched controls for ENSG00000143228

Processing conditions:   7%|████▊                                                              | 149/2057 [01:07<15:03,  2.11item/s, Completed 149/2057]

Found 503 matched controls for ENSG00000143228
Getting matched controls for ENSG00000132603

Processing conditions:   7%|████▉                                                              | 150/2057 [01:08<15:18,  2.08item/s, Completed 150/2057]

Found 279 matched controls for ENSG00000132603
Getting matched controls for ENSG00000154473

Processing conditions:   7%|████▉                                                              | 151/2057 [01:09<17:37,  1.80item/s, Completed 151/2057]

Found 409 matched controls for ENSG00000154473
Getting matched controls for ENSG00000136807

Processing conditions:   7%|████▉                                                              | 152/2057 [01:09<15:26,  2.06item/s, Completed 152/2057]

Found 140 matched controls for ENSG00000136807
Getting matched controls for ENSG00000100347

Processing conditions:   7%|████▉                                                              | 153/2057 [01:09<12:46,  2.49item/s, Completed 153/2057]

Found 102 matched controls for ENSG00000100347
Getting matched controls for ENSG00000068784

Processing conditions:   7%|█████                                                              | 154/2057 [01:09<11:34,  2.74item/s, Completed 154/2057]

Found 150 matched controls for ENSG00000068784
Getting matched controls for ENSG00000102924

Processing conditions:   8%|█████                                                              | 155/2057 [01:10<11:40,  2.71item/s, Completed 155/2057]

Found 214 matched controls for ENSG00000102924
Getting matched controls for ENSG00000140259

Processing conditions:   8%|█████                                                              | 156/2057 [01:10<11:43,  2.70item/s, Completed 156/2057]

Found 197 matched controls for ENSG00000140259
Getting matched controls for ENSG00000119523

Processing conditions:   8%|█████                                                              | 157/2057 [01:11<12:17,  2.58item/s, Completed 157/2057]

Found 247 matched controls for ENSG00000119523
Getting matched controls for ENSG00000161057

Processing conditions:   8%|█████▏                                                             | 158/2057 [01:11<15:37,  2.03item/s, Completed 158/2057]

Found 432 matched controls for ENSG00000161057
Getting matched controls for ENSG00000124207

Processing conditions:   8%|█████▏                                                             | 159/2057 [01:12<17:59,  1.76item/s, Completed 159/2057]

Found 432 matched controls for ENSG00000124207
Getting matched controls for ENSG00000110203

Processing conditions:   8%|█████▏                                                             | 160/2057 [01:13<17:34,  1.80item/s, Completed 160/2057]

Found 304 matched controls for ENSG00000110203
Getting matched controls for ENSG00000105698

Processing conditions:   8%|█████▏                                                             | 161/2057 [01:13<15:36,  2.03item/s, Completed 161/2057]

Found 185 matched controls for ENSG00000105698
Getting matched controls for ENSG00000138071

Processing conditions:   8%|█████▎                                                             | 162/2057 [01:13<14:53,  2.12item/s, Completed 162/2057]

Found 236 matched controls for ENSG00000138071
Getting matched controls for ENSG00000013561

Processing conditions:   8%|█████▎                                                             | 163/2057 [01:14<14:22,  2.20item/s, Completed 163/2057]

Found 240 matched controls for ENSG00000013561
Getting matched controls for ENSG00000138326

Processing conditions:   8%|█████▎                                                             | 164/2057 [01:14<14:07,  2.23item/s, Completed 164/2057]

Found 243 matched controls for ENSG00000138326
Getting matched controls for ENSG00000105372

Processing conditions:   8%|█████▎                                                             | 165/2057 [01:15<16:32,  1.91item/s, Completed 165/2057]

Found 422 matched controls for ENSG00000105372
Getting matched controls for ENSG00000134884

Processing conditions:   8%|█████▍                                                             | 166/2057 [01:16<19:27,  1.62item/s, Completed 166/2057]

Found 498 matched controls for ENSG00000134884
Getting matched controls for ENSG00000213780

Processing conditions:   8%|█████▍                                                             | 167/2057 [01:16<15:55,  1.98item/s, Completed 167/2057]

Found 115 matched controls for ENSG00000213780
Getting matched controls for ENSG00000141279

Processing conditions:   8%|█████▌                                                             | 169/2057 [01:16<11:20,  2.78item/s, Completed 169/2057]

Found 153 matched controls for ENSG00000141279
Getting matched controls for ENSG00000197265
Found 70 matched controls for ENSG00000197265
Getting matched controls for ENSG00000072756

Processing conditions:   8%|█████▌                                                             | 170/2057 [01:17<11:19,  2.78item/s, Completed 170/2057]

Found 203 matched controls for ENSG00000072756
Getting matched controls for ENSG00000137497

Processing conditions:   8%|█████▌                                                             | 171/2057 [01:17<12:30,  2.51item/s, Completed 171/2057]

Found 284 matched controls for ENSG00000137497
Getting matched controls for ENSG00000170248

Processing conditions:   8%|█████▌                                                             | 172/2057 [01:18<12:58,  2.42item/s, Completed 172/2057]

Found 257 matched controls for ENSG00000170248
Getting matched controls for ENSG00000120948

Processing conditions:   8%|█████▋                                                             | 173/2057 [01:18<12:02,  2.61item/s, Completed 173/2057]

Found 169 matched controls for ENSG00000120948
Getting matched controls for ENSG00000178773

Processing conditions:   8%|█████▋                                                             | 174/2057 [01:18<10:23,  3.02item/s, Completed 174/2057]

Found 101 matched controls for ENSG00000178773
Getting matched controls for ENSG00000125971

Processing conditions:   9%|█████▋                                                             | 175/2057 [01:19<11:49,  2.65item/s, Completed 175/2057]

Found 282 matched controls for ENSG00000125971
Getting matched controls for ENSG00000111615

Processing conditions:   9%|█████▋                                                             | 176/2057 [01:20<15:18,  2.05item/s, Completed 176/2057]

Found 449 matched controls for ENSG00000111615
Getting matched controls for ENSG00000131652

Processing conditions:   9%|█████▊                                                             | 177/2057 [01:20<12:51,  2.44item/s, Completed 177/2057]

Found 116 matched controls for ENSG00000131652
Getting matched controls for ENSG00000164941

Processing conditions:   9%|█████▊                                                             | 178/2057 [01:20<14:06,  2.22item/s, Completed 178/2057]

Found 323 matched controls for ENSG00000164941
Getting matched controls for ENSG00000077380

Processing conditions:   9%|█████▊                                                             | 179/2057 [01:21<14:41,  2.13item/s, Completed 179/2057]

Found 300 matched controls for ENSG00000077380
Getting matched controls for ENSG00000044574

Processing conditions:   9%|█████▊                                                             | 180/2057 [01:22<17:08,  1.83item/s, Completed 180/2057]

Found 438 matched controls for ENSG00000044574
Getting matched controls for ENSG00000100911

Processing conditions:   9%|█████▉                                                             | 182/2057 [01:22<12:00,  2.60item/s, Completed 182/2057]

Found 151 matched controls for ENSG00000100911
Getting matched controls for ENSG00000104738
Found 87 matched controls for ENSG00000104738
Getting matched controls for ENSG00000109332

Processing conditions:   9%|█████▉                                                             | 184/2057 [01:22<09:16,  3.36item/s, Completed 184/2057]

Found 142 matched controls for ENSG00000109332
Getting matched controls for ENSG00000108671
Found 80 matched controls for ENSG00000108671
Getting matched controls for ENSG00000174780

Processing conditions:   9%|██████                                                             | 185/2057 [01:23<10:11,  3.06item/s, Completed 185/2057]

Found 224 matched controls for ENSG00000174780
Getting matched controls for ENSG00000162910

Processing conditions:   9%|██████                                                             | 186/2057 [01:23<10:03,  3.10item/s, Completed 186/2057]

Found 170 matched controls for ENSG00000162910
Getting matched controls for ENSG00000101444

Processing conditions:   9%|██████                                                             | 187/2057 [01:23<09:36,  3.24item/s, Completed 187/2057]

Found 147 matched controls for ENSG00000101444
Getting matched controls for ENSG00000116774

Processing conditions:   9%|██████                                                             | 188/2057 [01:24<09:40,  3.22item/s, Completed 188/2057]

Found 173 matched controls for ENSG00000116774
Getting matched controls for ENSG00000101343

Processing conditions:   9%|██████▏                                                            | 189/2057 [01:24<11:01,  2.82item/s, Completed 189/2057]

Found 261 matched controls for ENSG00000101343
Getting matched controls for ENSG00000101158

Processing conditions:   9%|██████▏                                                            | 190/2057 [01:25<11:03,  2.81item/s, Completed 190/2057]

Found 201 matched controls for ENSG00000101158
Getting matched controls for ENSG00000121764

Processing conditions:   9%|██████▏                                                            | 191/2057 [01:25<09:52,  3.15item/s, Completed 191/2057]

Found 116 matched controls for ENSG00000121764
Getting matched controls for ENSG00000136930

Processing conditions:   9%|██████▎                                                            | 192/2057 [01:25<13:13,  2.35item/s, Completed 192/2057]

Found 404 matched controls for ENSG00000136930
Getting matched controls for ENSG00000116754

Processing conditions:   9%|██████▎                                                            | 193/2057 [01:26<16:03,  1.94item/s, Completed 193/2057]

Found 437 matched controls for ENSG00000116754
Getting matched controls for ENSG00000158526

Processing conditions:   9%|██████▎                                                            | 194/2057 [01:27<19:19,  1.61item/s, Completed 194/2057]

Found 523 matched controls for ENSG00000158526
Getting matched controls for ENSG00000130816

Processing conditions:   9%|██████▎                                                            | 195/2057 [01:27<16:28,  1.88item/s, Completed 195/2057]

Found 170 matched controls for ENSG00000130816
Getting matched controls for ENSG00000148843

Processing conditions:  10%|██████▍                                                            | 196/2057 [01:28<13:24,  2.31item/s, Completed 197/2057]

Found 98 matched controls for ENSG00000148843
Getting matched controls for ENSG00000099341
Found 22 matched controls for ENSG00000099341
Getting matched controls for ENSG00000114503

Processing conditions:  10%|██████▍                                                            | 199/2057 [01:30<16:14,  1.91item/s, Completed 199/2057]

Found 992 matched controls for ENSG00000114503
Getting matched controls for ENSG00000146576
Found 86 matched controls for ENSG00000146576
Getting matched controls for ENSG00000172262

Processing conditions:  10%|██████▍                                                            | 199/2057 [01:30<16:14,  1.91item/s, Completed 200/2057]

Found 23 matched controls for ENSG00000172262
Getting matched controls for ENSG00000117399

Processing conditions:  10%|██████▌                                                            | 201/2057 [01:30<11:31,  2.69item/s, Completed 201/2057]

Found 115 matched controls for ENSG00000117399
Getting matched controls for ENSG00000137656

Processing conditions:  10%|██████▌                                                            | 203/2057 [01:30<09:37,  3.21item/s, Completed 203/2057]

Found 174 matched controls for ENSG00000137656
Getting matched controls for ENSG00000088986
Found 71 matched controls for ENSG00000088986
Getting matched controls for ENSG00000104859

Processing conditions:  10%|██████▋                                                            | 205/2057 [01:31<07:34,  4.07item/s, Completed 205/2057]

Found 127 matched controls for ENSG00000104859
Getting matched controls for ENSG00000067533
Found 32 matched controls for ENSG00000067533
Getting matched controls for ENSG00000100028

Processing conditions:  10%|██████▋                                                            | 206/2057 [01:31<08:39,  3.56item/s, Completed 206/2057]

Found 182 matched controls for ENSG00000100028
Getting matched controls for ENSG00000135775

Processing conditions:  10%|██████▋                                                            | 207/2057 [01:32<11:19,  2.72item/s, Completed 207/2057]

Found 343 matched controls for ENSG00000135775
Getting matched controls for ENSG00000173599

Processing conditions:  10%|██████▊                                                            | 208/2057 [01:32<11:34,  2.66item/s, Completed 208/2057]

Found 225 matched controls for ENSG00000173599
Getting matched controls for ENSG00000116560

Processing conditions:  10%|██████▊                                                            | 209/2057 [01:33<13:03,  2.36item/s, Completed 209/2057]

Found 303 matched controls for ENSG00000116560
Getting matched controls for ENSG00000143751

Processing conditions:  10%|██████▊                                                            | 210/2057 [01:33<11:46,  2.62item/s, Completed 210/2057]

Found 151 matched controls for ENSG00000143751
Getting matched controls for ENSG00000112110

Processing conditions:  10%|██████▊                                                            | 211/2057 [01:33<11:47,  2.61item/s, Completed 211/2057]

Found 180 matched controls for ENSG00000112110
Getting matched controls for ENSG00000008128

Processing conditions:  10%|██████▉                                                            | 212/2057 [01:34<12:40,  2.43item/s, Completed 212/2057]

Found 269 matched controls for ENSG00000008128
Getting matched controls for ENSG00000134086

Processing conditions:  10%|██████▉                                                            | 213/2057 [01:34<11:49,  2.60item/s, Completed 213/2057]

Found 162 matched controls for ENSG00000134086
Getting matched controls for ENSG00000109475

Processing conditions:  10%|██████▉                                                            | 214/2057 [01:35<13:52,  2.21item/s, Completed 214/2057]

Found 330 matched controls for ENSG00000109475
Getting matched controls for ENSG00000054116

Processing conditions:  10%|███████                                                            | 215/2057 [01:35<12:39,  2.42item/s, Completed 215/2057]

Found 163 matched controls for ENSG00000054116
Getting matched controls for ENSG00000170190

Processing conditions:  11%|███████                                                            | 216/2057 [01:35<12:12,  2.51item/s, Completed 216/2057]

Found 179 matched controls for ENSG00000170190
Getting matched controls for ENSG00000149273

Processing conditions:  11%|███████                                                            | 217/2057 [01:36<13:13,  2.32item/s, Completed 217/2057]

Found 276 matched controls for ENSG00000149273
Getting matched controls for ENSG00000164134

Processing conditions:  11%|███████▏                                                           | 219/2057 [01:36<09:51,  3.11item/s, Completed 219/2057]

Found 128 matched controls for ENSG00000164134
Getting matched controls for ENSG00000113312
Found 69 matched controls for ENSG00000113312
Getting matched controls for ENSG00000159147

Processing conditions:  11%|███████▏                                                           | 220/2057 [01:38<18:20,  1.67item/s, Completed 220/2057]

Found 745 matched controls for ENSG00000159147
Getting matched controls for ENSG00000114982

Processing conditions:  11%|███████▏                                                           | 221/2057 [01:38<15:58,  1.92item/s, Completed 221/2057]

Found 187 matched controls for ENSG00000114982
Getting matched controls for ENSG00000186395

Processing conditions:  11%|███████▏                                                           | 222/2057 [01:38<14:15,  2.15item/s, Completed 222/2057]

Found 182 matched controls for ENSG00000186395
Getting matched controls for ENSG00000087470

Processing conditions:  11%|███████▎                                                           | 223/2057 [01:39<13:28,  2.27item/s, Completed 223/2057]

Found 168 matched controls for ENSG00000087470
Getting matched controls for ENSG00000076201

Processing conditions:  11%|███████▎                                                           | 224/2057 [01:39<12:14,  2.50item/s, Completed 224/2057]

Found 140 matched controls for ENSG00000076201
Getting matched controls for ENSG00000111229

Processing conditions:  11%|███████▎                                                           | 225/2057 [01:39<11:24,  2.68item/s, Completed 225/2057]

Found 141 matched controls for ENSG00000111229
Getting matched controls for ENSG00000136709

Processing conditions:  11%|███████▎                                                           | 226/2057 [01:39<10:09,  3.00item/s, Completed 226/2057]

Found 103 matched controls for ENSG00000136709
Getting matched controls for ENSG00000053900

Processing conditions:  11%|███████▍                                                           | 227/2057 [01:40<09:38,  3.16item/s, Completed 227/2057]

Found 63 matched controls for ENSG00000053900
Getting matched controls for ENSG00000118363

Processing conditions:  11%|███████▍                                                           | 229/2057 [01:40<07:56,  3.84item/s, Completed 229/2057]

Found 122 matched controls for ENSG00000118363
Getting matched controls for ENSG00000047249
Found 84 matched controls for ENSG00000047249
Getting matched controls for ENSG00000166685

Processing conditions:  11%|███████▍                                                           | 230/2057 [01:40<06:36,  4.61item/s, Completed 230/2057]

Found 40 matched controls for ENSG00000166685
Getting matched controls for ENSG00000111704

Processing conditions:  11%|███████▌                                                           | 231/2057 [01:41<06:56,  4.39item/s, Completed 231/2057]

Found 125 matched controls for ENSG00000111704
Getting matched controls for ENSG00000149636

Processing conditions:  11%|███████▌                                                           | 232/2057 [01:41<08:54,  3.42item/s, Completed 232/2057]

Found 245 matched controls for ENSG00000149636
Getting matched controls for ENSG00000159377

Processing conditions:  11%|███████▌                                                           | 233/2057 [01:41<08:10,  3.72item/s, Completed 233/2057]

Found 101 matched controls for ENSG00000159377
Getting matched controls for ENSG00000269858

Processing conditions:  11%|███████▌                                                           | 234/2057 [01:42<11:22,  2.67item/s, Completed 235/2057]

Found 362 matched controls for ENSG00000269858
Getting matched controls for ENSG00000113593
Found 24 matched controls for ENSG00000113593
Getting matched controls for ENSG00000177600

Processing conditions:  11%|███████▋                                                           | 236/2057 [01:42<09:33,  3.18item/s, Completed 236/2057]

Found 222 matched controls for ENSG00000177600
Getting matched controls for ENSG00000148308

Processing conditions:  12%|███████▋                                                           | 237/2057 [01:43<09:31,  3.18item/s, Completed 237/2057]

Found 166 matched controls for ENSG00000148308
Getting matched controls for ENSG00000146282

Processing conditions:  12%|███████▊                                                           | 239/2057 [01:43<08:06,  3.74item/s, Completed 239/2057]

Found 148 matched controls for ENSG00000146282
Getting matched controls for ENSG00000141030
Found 73 matched controls for ENSG00000141030
Getting matched controls for ENSG00000084072

Processing conditions:  12%|███████▊                                                           | 240/2057 [01:43<06:53,  4.40item/s, Completed 240/2057]

Found 46 matched controls for ENSG00000084072
Getting matched controls for ENSG00000164405

Processing conditions:  12%|███████▊                                                           | 241/2057 [01:44<07:34,  4.00item/s, Completed 241/2057]

Found 166 matched controls for ENSG00000164405
Getting matched controls for ENSG00000117133

Processing conditions:  12%|███████▉                                                           | 242/2057 [01:44<07:32,  4.01item/s, Completed 242/2057]

Found 125 matched controls for ENSG00000117133
Getting matched controls for ENSG00000142252

Processing conditions:  12%|███████▉                                                           | 243/2057 [01:44<07:38,  3.95item/s, Completed 243/2057]

Found 136 matched controls for ENSG00000142252
Getting matched controls for ENSG00000106355

Processing conditions:  12%|███████▉                                                           | 244/2057 [01:44<08:37,  3.50item/s, Completed 244/2057]

Found 202 matched controls for ENSG00000106355
Getting matched controls for ENSG00000116809

Processing conditions:  12%|███████▉                                                           | 245/2057 [01:45<08:45,  3.45item/s, Completed 245/2057]

Found 160 matched controls for ENSG00000116809
Getting matched controls for ENSG00000058272

Processing conditions:  12%|████████                                                           | 246/2057 [01:45<09:06,  3.31item/s, Completed 246/2057]

Found 179 matched controls for ENSG00000058272
Getting matched controls for ENSG00000132768

Processing conditions:  12%|████████                                                           | 247/2057 [01:45<09:08,  3.30item/s, Completed 247/2057]

Found 164 matched controls for ENSG00000132768
Getting matched controls for ENSG00000168002

Processing conditions:  12%|████████                                                           | 248/2057 [01:46<09:01,  3.34item/s, Completed 248/2057]

Found 155 matched controls for ENSG00000168002
Getting matched controls for ENSG00000213741

Processing conditions:  12%|████████                                                           | 249/2057 [01:46<12:20,  2.44item/s, Completed 250/2057]

Found 403 matched controls for ENSG00000213741
Getting matched controls for ENSG00000070814
Found 97 matched controls for ENSG00000070814

Processing conditions:  12%|████████▏                                                          | 251/2057 [01:47<09:11,  3.27item/s, Completed 251/2057]

Getting matched controls for ENSG00000168872
Found 103 matched controls for ENSG00000168872
Getting matched controls for ENSG00000161654

Processing conditions:  12%|████████▏                                                          | 252/2057 [01:47<07:47,  3.86item/s, Completed 252/2057]

Found 63 matched controls for ENSG00000161654
Getting matched controls for ENSG00000104979

Processing conditions:  12%|████████▎                                                          | 254/2057 [01:47<07:15,  4.14item/s, Completed 254/2057]

Found 169 matched controls for ENSG00000104979
Getting matched controls for ENSG00000123416
Found 74 matched controls for ENSG00000123416
Getting matched controls for ENSG00000168883

Processing conditions:  12%|████████▎                                                          | 256/2057 [01:48<07:01,  4.27item/s, Completed 256/2057]

Found 220 matched controls for ENSG00000168883
Getting matched controls for ENSG00000166337
Found 39 matched controls for ENSG00000166337
Getting matched controls for ENSG00000136273

Processing conditions:  12%|████████▎                                                          | 257/2057 [01:48<08:12,  3.65item/s, Completed 257/2057]

Found 201 matched controls for ENSG00000136273
Getting matched controls for ENSG00000106105

Processing conditions:  13%|████████▍                                                          | 258/2057 [01:49<09:47,  3.06item/s, Completed 258/2057]

Found 256 matched controls for ENSG00000106105
Getting matched controls for ENSG00000125107

Processing conditions:  13%|████████▍                                                          | 260/2057 [01:49<08:48,  3.40item/s, Completed 260/2057]

Found 269 matched controls for ENSG00000125107
Getting matched controls for ENSG00000111642
Found 44 matched controls for ENSG00000111642
Getting matched controls for ENSG00000128159

Processing conditions:  13%|████████▌                                                          | 261/2057 [01:50<08:46,  3.41item/s, Completed 261/2057]

Found 153 matched controls for ENSG00000128159
Getting matched controls for ENSG00000081665

Processing conditions:  13%|████████▌                                                          | 262/2057 [01:50<09:02,  3.31item/s, Completed 262/2057]

Found 177 matched controls for ENSG00000081665
Getting matched controls for ENSG00000163807

Processing conditions:  13%|████████▌                                                          | 263/2057 [01:50<09:31,  3.14item/s, Completed 263/2057]

Found 198 matched controls for ENSG00000163807
Getting matched controls for ENSG00000082898

Processing conditions:  13%|████████▌                                                          | 264/2057 [01:51<10:16,  2.91item/s, Completed 264/2057]

Found 207 matched controls for ENSG00000082898
Getting matched controls for ENSG00000175467

Processing conditions:  13%|████████▋                                                          | 265/2057 [01:51<12:01,  2.48item/s, Completed 265/2057]

Found 306 matched controls for ENSG00000175467
Getting matched controls for ENSG00000188687

Processing conditions:  13%|████████▋                                                          | 266/2057 [01:52<11:59,  2.49item/s, Completed 266/2057]

Found 226 matched controls for ENSG00000188687
Getting matched controls for ENSG00000165280

Processing conditions:  13%|████████▋                                                          | 267/2057 [01:52<12:07,  2.46item/s, Completed 267/2057]

Found 239 matched controls for ENSG00000165280
Getting matched controls for ENSG00000124614

Processing conditions:  13%|████████▋                                                          | 268/2057 [01:52<10:24,  2.86item/s, Completed 268/2057]

Found 106 matched controls for ENSG00000124614
Getting matched controls for ENSG00000181610

Processing conditions:  13%|████████▊                                                          | 269/2057 [01:52<09:23,  3.17item/s, Completed 269/2057]

Found 119 matched controls for ENSG00000181610
Getting matched controls for ENSG00000126821

Processing conditions:  13%|████████▊                                                          | 270/2057 [01:53<09:12,  3.23item/s, Completed 270/2057]

Found 159 matched controls for ENSG00000126821
Getting matched controls for ENSG00000138750

Processing conditions:  13%|████████▊                                                          | 271/2057 [01:53<11:04,  2.69item/s, Completed 271/2057]

Found 291 matched controls for ENSG00000138750
Getting matched controls for ENSG00000047315

Processing conditions:  13%|████████▊                                                          | 272/2057 [01:54<12:49,  2.32item/s, Completed 272/2057]

Found 320 matched controls for ENSG00000047315
Getting matched controls for ENSG00000176248

Processing conditions:  13%|████████▉                                                          | 274/2057 [01:54<10:00,  2.97item/s, Completed 274/2057]

Found 237 matched controls for ENSG00000176248
Getting matched controls for ENSG00000073584
Found 31 matched controls for ENSG00000073584
Getting matched controls for ENSG00000104884

Processing conditions:  13%|████████▉                                                          | 275/2057 [01:55<09:29,  3.13item/s, Completed 275/2057]

Found 117 matched controls for ENSG00000104884
Getting matched controls for ENSG00000100216

Processing conditions:  13%|████████▉                                                          | 276/2057 [01:55<08:40,  3.42item/s, Completed 276/2057]

Found 104 matched controls for ENSG00000100216
Getting matched controls for ENSG00000146143

Processing conditions:  13%|█████████                                                          | 277/2057 [01:55<08:40,  3.42item/s, Completed 277/2057]

Found 156 matched controls for ENSG00000146143
Getting matched controls for ENSG00000113575

Processing conditions:  14%|█████████                                                          | 278/2057 [01:56<09:44,  3.04item/s, Completed 278/2057]

Found 184 matched controls for ENSG00000113575
Getting matched controls for ENSG00000130695

Processing conditions:  14%|█████████                                                          | 279/2057 [01:56<09:02,  3.28item/s, Completed 279/2057]

Found 129 matched controls for ENSG00000130695
Getting matched controls for ENSG00000010322

Processing conditions:  14%|█████████                                                          | 280/2057 [01:56<08:46,  3.38item/s, Completed 280/2057]

Found 144 matched controls for ENSG00000010322
Getting matched controls for ENSG00000149136

Processing conditions:  14%|█████████▏                                                         | 281/2057 [01:57<14:27,  2.05item/s, Completed 281/2057]

Found 562 matched controls for ENSG00000149136
Getting matched controls for ENSG00000198056

Processing conditions:  14%|█████████▏                                                         | 282/2057 [01:57<13:02,  2.27item/s, Completed 282/2057]

Found 181 matched controls for ENSG00000198056
Getting matched controls for ENSG00000152404

Processing conditions:  14%|█████████▏                                                         | 283/2057 [01:58<12:22,  2.39item/s, Completed 283/2057]

Found 194 matched controls for ENSG00000152404
Getting matched controls for ENSG00000142168

Processing conditions:  14%|█████████▎                                                         | 285/2057 [01:58<09:26,  3.13item/s, Completed 285/2057]

Found 165 matched controls for ENSG00000142168
Getting matched controls for ENSG00000135972
Found 76 matched controls for ENSG00000135972
Getting matched controls for ENSG00000065518

Processing conditions:  14%|█████████▎                                                         | 287/2057 [01:59<08:04,  3.65item/s, Completed 287/2057]

Found 166 matched controls for ENSG00000065518
Getting matched controls for ENSG00000100027
Found 72 matched controls for ENSG00000100027
Getting matched controls for ENSG00000159140

Processing conditions:  14%|█████████▍                                                         | 289/2057 [02:00<10:53,  2.70item/s, Completed 289/2057]

Found 515 matched controls for ENSG00000159140
Getting matched controls for ENSG00000085415
Found 60 matched controls for ENSG00000085415
Getting matched controls for ENSG00000242252

Processing conditions:  14%|█████████▍                                                         | 290/2057 [02:00<11:18,  2.61item/s, Completed 290/2057]

Found 236 matched controls for ENSG00000242252
Getting matched controls for ENSG00000164068

Processing conditions:  14%|█████████▍                                                         | 291/2057 [02:00<10:00,  2.94item/s, Completed 291/2057]

Found 111 matched controls for ENSG00000164068
Getting matched controls for ENSG00000113649

Processing conditions:  14%|█████████▌                                                         | 292/2057 [02:01<09:16,  3.17item/s, Completed 292/2057]

Found 105 matched controls for ENSG00000113649
Getting matched controls for ENSG00000103035

Processing conditions:  14%|█████████▌                                                         | 293/2057 [02:01<12:21,  2.38item/s, Completed 293/2057]

Found 373 matched controls for ENSG00000103035
Getting matched controls for ENSG00000134759

Processing conditions:  14%|█████████▌                                                         | 294/2057 [02:02<11:59,  2.45item/s, Completed 294/2057]

Found 189 matched controls for ENSG00000134759
Getting matched controls for ENSG00000164338

Processing conditions:  14%|█████████▌                                                         | 295/2057 [02:02<11:15,  2.61item/s, Completed 295/2057]

Found 152 matched controls for ENSG00000164338
Getting matched controls for ENSG00000073111

Processing conditions:  14%|█████████▋                                                         | 296/2057 [02:02<10:07,  2.90item/s, Completed 296/2057]

Found 123 matched controls for ENSG00000073111
Getting matched controls for ENSG00000174243

Processing conditions:  14%|█████████▋                                                         | 297/2057 [02:03<09:40,  3.03item/s, Completed 297/2057]

Found 159 matched controls for ENSG00000174243
Getting matched controls for ENSG00000165416

Processing conditions:  14%|█████████▋                                                         | 298/2057 [02:03<09:00,  3.26item/s, Completed 298/2057]

Found 107 matched controls for ENSG00000165416
Getting matched controls for ENSG00000159086

Processing conditions:  15%|█████████▋                                                         | 299/2057 [02:03<08:58,  3.26item/s, Completed 299/2057]

Found 129 matched controls for ENSG00000159086
Getting matched controls for ENSG00000037897

Processing conditions:  15%|█████████▊                                                         | 300/2057 [02:03<09:39,  3.03item/s, Completed 300/2057]

Found 208 matched controls for ENSG00000037897
Getting matched controls for ENSG00000145734

Processing conditions:  15%|█████████▊                                                         | 301/2057 [02:04<11:57,  2.45item/s, Completed 301/2057]

Found 331 matched controls for ENSG00000145734
Getting matched controls for ENSG00000138778

Processing conditions:  15%|█████████▊                                                         | 302/2057 [02:04<11:12,  2.61item/s, Completed 302/2057]

Found 177 matched controls for ENSG00000138778
Getting matched controls for ENSG00000204899

Processing conditions:  15%|█████████▊                                                         | 303/2057 [02:05<14:31,  2.01item/s, Completed 303/2057]

Found 455 matched controls for ENSG00000204899
Getting matched controls for ENSG00000130332

Processing conditions:  15%|█████████▉                                                         | 304/2057 [02:05<12:39,  2.31item/s, Completed 304/2057]

Found 140 matched controls for ENSG00000130332
Getting matched controls for ENSG00000119720

Processing conditions:  15%|█████████▉                                                         | 306/2057 [02:06<12:36,  2.31item/s, Completed 306/2057]

Found 504 matched controls for ENSG00000119720
Getting matched controls for ENSG00000106077
Found 49 matched controls for ENSG00000106077
Getting matched controls for ENSG00000138867

Processing conditions:  15%|█████████▉                                                         | 307/2057 [02:07<13:10,  2.21item/s, Completed 307/2057]

Found 279 matched controls for ENSG00000138867
Getting matched controls for ENSG00000121350

Processing conditions:  15%|██████████                                                         | 308/2057 [02:07<11:00,  2.65item/s, Completed 308/2057]

Found 100 matched controls for ENSG00000121350
Getting matched controls for ENSG00000170322

Processing conditions:  15%|██████████                                                         | 309/2057 [02:08<11:22,  2.56item/s, Completed 309/2057]

Found 228 matched controls for ENSG00000170322
Getting matched controls for ENSG00000122218

Processing conditions:  15%|██████████                                                         | 310/2057 [02:08<11:52,  2.45item/s, Completed 310/2057]

Found 243 matched controls for ENSG00000122218
Getting matched controls for ENSG00000144867

Processing conditions:  15%|██████████▏                                                        | 311/2057 [02:08<11:06,  2.62item/s, Completed 311/2057]

Found 164 matched controls for ENSG00000144867
Getting matched controls for ENSG00000164587

Processing conditions:  15%|██████████▏                                                        | 312/2057 [02:09<10:47,  2.70item/s, Completed 312/2057]

Found 181 matched controls for ENSG00000164587
Getting matched controls for ENSG00000265681

Processing conditions:  15%|██████████▏                                                        | 314/2057 [02:09<08:08,  3.57item/s, Completed 314/2057]

Found 149 matched controls for ENSG00000265681
Getting matched controls for ENSG00000145216
Found 21 matched controls for ENSG00000145216
Getting matched controls for ENSG00000181555

Processing conditions:  15%|██████████▎                                                        | 315/2057 [02:09<07:45,  3.74item/s, Completed 315/2057]

Found 109 matched controls for ENSG00000181555
Getting matched controls for ENSG00000163933

Processing conditions:  15%|██████████▎                                                        | 316/2057 [02:10<08:02,  3.61item/s, Completed 316/2057]

Found 121 matched controls for ENSG00000163933
Getting matched controls for ENSG00000164167

Processing conditions:  15%|██████████▎                                                        | 317/2057 [02:10<12:37,  2.30item/s, Completed 317/2057]

Found 461 matched controls for ENSG00000164167
Getting matched controls for ENSG00000183048

Processing conditions:  15%|██████████▎                                                        | 318/2057 [02:11<13:17,  2.18item/s, Completed 318/2057]

Found 303 matched controls for ENSG00000183048
Getting matched controls for ENSG00000100220

Processing conditions:  16%|██████████▍                                                        | 319/2057 [02:11<12:01,  2.41item/s, Completed 319/2057]

Found 171 matched controls for ENSG00000100220
Getting matched controls for ENSG00000062485

Processing conditions:  16%|██████████▍                                                        | 320/2057 [02:12<11:59,  2.41item/s, Completed 320/2057]

Found 222 matched controls for ENSG00000062485
Getting matched controls for ENSG00000176473

Processing conditions:  16%|██████████▍                                                        | 321/2057 [02:12<11:05,  2.61item/s, Completed 321/2057]

Found 159 matched controls for ENSG00000176473
Getting matched controls for ENSG00000142534

Processing conditions:  16%|██████████▍                                                        | 322/2057 [02:12<11:45,  2.46item/s, Completed 322/2057]

Found 268 matched controls for ENSG00000142534
Getting matched controls for ENSG00000122026

Processing conditions:  16%|██████████▌                                                        | 323/2057 [02:13<12:08,  2.38item/s, Completed 323/2057]

Found 262 matched controls for ENSG00000122026
Getting matched controls for ENSG00000134717

Processing conditions:  16%|██████████▌                                                        | 324/2057 [02:13<10:49,  2.67item/s, Completed 324/2057]

Found 141 matched controls for ENSG00000134717
Getting matched controls for ENSG00000164902

Processing conditions:  16%|██████████▌                                                        | 325/2057 [02:14<13:51,  2.08item/s, Completed 325/2057]

Found 412 matched controls for ENSG00000164902
Getting matched controls for ENSG00000137288

Processing conditions:  16%|██████████▌                                                        | 326/2057 [02:14<11:45,  2.46item/s, Completed 326/2057]

Found 101 matched controls for ENSG00000137288
Getting matched controls for ENSG00000204392

Processing conditions:  16%|██████████▋                                                        | 327/2057 [02:15<13:50,  2.08item/s, Completed 327/2057]

Found 357 matched controls for ENSG00000204392
Getting matched controls for ENSG00000114573

Processing conditions:  16%|██████████▋                                                        | 328/2057 [02:15<11:35,  2.49item/s, Completed 328/2057]

Found 96 matched controls for ENSG00000114573
Getting matched controls for ENSG00000162231

Processing conditions:  16%|██████████▋                                                        | 329/2057 [02:15<12:04,  2.38item/s, Completed 329/2057]

Found 251 matched controls for ENSG00000162231
Getting matched controls for ENSG00000143977

Processing conditions:  16%|██████████▋                                                        | 330/2057 [02:16<15:19,  1.88item/s, Completed 330/2057]

Found 402 matched controls for ENSG00000143977
Getting matched controls for ENSG00000090989

Processing conditions:  16%|██████████▊                                                        | 331/2057 [02:17<13:50,  2.08item/s, Completed 331/2057]

Found 182 matched controls for ENSG00000090989
Getting matched controls for ENSG00000233927

Processing conditions:  16%|██████████▊                                                        | 332/2057 [02:17<14:30,  1.98item/s, Completed 332/2057]

Found 309 matched controls for ENSG00000233927
Getting matched controls for ENSG00000126883

Processing conditions:  16%|██████████▊                                                        | 333/2057 [02:17<12:29,  2.30item/s, Completed 333/2057]

Found 132 matched controls for ENSG00000126883
Getting matched controls for ENSG00000101161

Processing conditions:  16%|██████████▉                                                        | 334/2057 [02:18<12:14,  2.34item/s, Completed 334/2057]

Found 232 matched controls for ENSG00000101161
Getting matched controls for ENSG00000266412

Processing conditions:  16%|██████████▉                                                        | 335/2057 [02:18<10:57,  2.62item/s, Completed 335/2057]

Found 134 matched controls for ENSG00000266412
Getting matched controls for ENSG00000064666

Processing conditions:  16%|██████████▉                                                        | 336/2057 [02:19<10:52,  2.64item/s, Completed 336/2057]

Found 197 matched controls for ENSG00000064666
Getting matched controls for ENSG00000108963

Processing conditions:  16%|███████████                                                        | 338/2057 [02:19<10:33,  2.71item/s, Completed 338/2057]

Found 335 matched controls for ENSG00000108963
Getting matched controls for ENSG00000171634
Found 56 matched controls for ENSG00000171634
Getting matched controls for ENSG00000099326

Processing conditions:  16%|███████████                                                        | 339/2057 [02:20<09:39,  2.97item/s, Completed 339/2057]

Found 128 matched controls for ENSG00000099326
Getting matched controls for ENSG00000205090

Processing conditions:  17%|███████████                                                        | 340/2057 [02:20<09:31,  3.00item/s, Completed 340/2057]

Found 176 matched controls for ENSG00000205090
Getting matched controls for ENSG00000126561

Processing conditions:  17%|███████████                                                        | 341/2057 [02:20<10:05,  2.83item/s, Completed 341/2057]

Found 204 matched controls for ENSG00000126561
Getting matched controls for ENSG00000183770

Processing conditions:  17%|███████████▏                                                       | 342/2057 [02:21<09:52,  2.90item/s, Completed 342/2057]

Found 164 matched controls for ENSG00000183770
Getting matched controls for ENSG00000133606

Processing conditions:  17%|███████████▏                                                       | 343/2057 [02:21<10:28,  2.73item/s, Completed 343/2057]

Found 160 matched controls for ENSG00000133606
Getting matched controls for ENSG00000204316

Processing conditions:  17%|███████████▏                                                       | 344/2057 [02:21<09:51,  2.90item/s, Completed 344/2057]

Found 155 matched controls for ENSG00000204316
Getting matched controls for ENSG00000177889

Processing conditions:  17%|███████████▏                                                       | 345/2057 [02:22<09:53,  2.88item/s, Completed 345/2057]

Found 174 matched controls for ENSG00000177889
Getting matched controls for ENSG00000094914

Processing conditions:  17%|███████████▎                                                       | 346/2057 [02:22<10:35,  2.69item/s, Completed 347/2057]

Found 212 matched controls for ENSG00000094914
Getting matched controls for ENSG00000278463
Found 97 matched controls for ENSG00000278463

Processing conditions:  17%|███████████▎                                                       | 348/2057 [02:23<08:06,  3.51item/s, Completed 348/2057]

Getting matched controls for ENSG00000174276
Found 96 matched controls for ENSG00000174276
Getting matched controls for ENSG00000084090

Processing conditions:  17%|███████████▎                                                       | 349/2057 [02:23<07:38,  3.72item/s, Completed 349/2057]

Found 117 matched controls for ENSG00000084090
Getting matched controls for ENSG00000268043

Processing conditions:  17%|███████████▍                                                       | 350/2057 [02:23<07:59,  3.56item/s, Completed 350/2057]

Found 150 matched controls for ENSG00000268043
Getting matched controls for ENSG00000067704

Processing conditions:  17%|███████████▍                                                       | 351/2057 [02:23<09:02,  3.15item/s, Completed 351/2057]

Found 216 matched controls for ENSG00000067704
Getting matched controls for ENSG00000155868

Processing conditions:  17%|███████████▍                                                       | 353/2057 [02:24<09:02,  3.14item/s, Completed 353/2057]

Found 272 matched controls for ENSG00000155868
Getting matched controls for ENSG00000275835
Found 72 matched controls for ENSG00000275835
Getting matched controls for ENSG00000186591

Processing conditions:  17%|███████████▌                                                       | 354/2057 [02:25<09:16,  3.06item/s, Completed 354/2057]

Found 194 matched controls for ENSG00000186591
Getting matched controls for ENSG00000176809

Processing conditions:  17%|███████████▌                                                       | 355/2057 [02:25<08:36,  3.30item/s, Completed 355/2057]

Found 114 matched controls for ENSG00000176809
Getting matched controls for ENSG00000170312

Processing conditions:  17%|███████████▌                                                       | 356/2057 [02:25<10:59,  2.58item/s, Completed 356/2057]

Found 347 matched controls for ENSG00000170312
Getting matched controls for ENSG00000197054

Processing conditions:  17%|███████████▋                                                       | 358/2057 [02:26<08:42,  3.25item/s, Completed 358/2057]

Found 148 matched controls for ENSG00000197054
Getting matched controls for ENSG00000213551
Found 84 matched controls for ENSG00000213551
Getting matched controls for ENSG00000110768

Processing conditions:  17%|███████████▋                                                       | 359/2057 [02:27<12:25,  2.28item/s, Completed 359/2057]

Found 434 matched controls for ENSG00000110768
Getting matched controls for ENSG00000033327

Processing conditions:  18%|███████████▋                                                       | 360/2057 [02:28<18:14,  1.55item/s, Completed 360/2057]

Found 674 matched controls for ENSG00000033327
Getting matched controls for ENSG00000162385

Processing conditions:  18%|███████████▊                                                       | 361/2057 [02:28<16:23,  1.72item/s, Completed 361/2057]

Found 242 matched controls for ENSG00000162385
Getting matched controls for ENSG00000149554

Processing conditions:  18%|███████████▊                                                       | 362/2057 [02:29<15:46,  1.79item/s, Completed 362/2057]

Found 295 matched controls for ENSG00000149554
Getting matched controls for ENSG00000176225

Processing conditions:  18%|███████████▊                                                       | 363/2057 [02:29<13:07,  2.15item/s, Completed 363/2057]

Found 125 matched controls for ENSG00000176225
Getting matched controls for ENSG00000240871

Processing conditions:  18%|███████████▊                                                       | 364/2057 [02:29<11:48,  2.39item/s, Completed 364/2057]

Found 168 matched controls for ENSG00000240871
Getting matched controls for ENSG00000126653

Processing conditions:  18%|███████████▉                                                       | 365/2057 [02:30<11:47,  2.39item/s, Completed 365/2057]

Found 237 matched controls for ENSG00000126653
Getting matched controls for ENSG00000067334

Processing conditions:  18%|███████████▉                                                       | 367/2057 [02:30<09:56,  2.83item/s, Completed 367/2057]

Found 264 matched controls for ENSG00000067334
Getting matched controls for ENSG00000124787
Found 78 matched controls for ENSG00000124787
Getting matched controls for ENSG00000175582

Processing conditions:  18%|████████████                                                       | 369/2057 [02:31<07:02,  4.00item/s, Completed 369/2057]

Found 59 matched controls for ENSG00000175582
Getting matched controls for ENSG00000177693
Found 66 matched controls for ENSG00000177693
Getting matched controls for ENSG00000135940

Processing conditions:  18%|████████████                                                       | 370/2057 [02:31<07:08,  3.94item/s, Completed 370/2057]

Found 118 matched controls for ENSG00000135940
Getting matched controls for ENSG00000119718

Processing conditions:  18%|████████████                                                       | 371/2057 [02:31<09:34,  2.94item/s, Completed 371/2057]

Found 319 matched controls for ENSG00000119718
Getting matched controls for ENSG00000138663

Processing conditions:  18%|████████████▏                                                      | 373/2057 [02:32<09:14,  3.04item/s, Completed 373/2057]

Found 262 matched controls for ENSG00000138663
Getting matched controls for ENSG00000137878
Found 62 matched controls for ENSG00000137878
Getting matched controls for ENSG00000104299

Processing conditions:  18%|████████████▏                                                      | 374/2057 [02:32<10:12,  2.75item/s, Completed 374/2057]

Found 229 matched controls for ENSG00000104299
Getting matched controls for ENSG00000186716

Processing conditions:  18%|████████████▏                                                      | 375/2057 [02:33<15:19,  1.83item/s, Completed 375/2057]

Found 561 matched controls for ENSG00000186716
Getting matched controls for ENSG00000130935

Processing conditions:  18%|████████████▏                                                      | 376/2057 [02:34<14:39,  1.91item/s, Completed 376/2057]

Found 271 matched controls for ENSG00000130935
Getting matched controls for ENSG00000147677

Processing conditions:  18%|████████████▎                                                      | 377/2057 [02:35<15:34,  1.80item/s, Completed 377/2057]

Found 369 matched controls for ENSG00000147677
Getting matched controls for ENSG00000160201

Processing conditions:  18%|████████████▎                                                      | 378/2057 [02:35<13:10,  2.12item/s, Completed 378/2057]

Found 141 matched controls for ENSG00000160201
Getting matched controls for ENSG00000013573

Processing conditions:  18%|████████████▎                                                      | 379/2057 [02:35<11:19,  2.47item/s, Completed 379/2057]

Found 128 matched controls for ENSG00000013573
Getting matched controls for ENSG00000214114

Processing conditions:  18%|████████████▍                                                      | 380/2057 [02:35<11:04,  2.52item/s, Completed 380/2057]

Found 208 matched controls for ENSG00000214114
Getting matched controls for ENSG00000165271

Processing conditions:  19%|████████████▍                                                      | 381/2057 [02:36<09:42,  2.88item/s, Completed 381/2057]

Found 114 matched controls for ENSG00000165271
Getting matched controls for ENSG00000136875

Processing conditions:  19%|████████████▍                                                      | 382/2057 [02:36<08:47,  3.18item/s, Completed 382/2057]

Found 117 matched controls for ENSG00000136875
Getting matched controls for ENSG00000104897

Processing conditions:  19%|████████████▌                                                      | 384/2057 [02:37<09:23,  2.97item/s, Completed 384/2057]

Found 321 matched controls for ENSG00000104897
Getting matched controls for ENSG00000136810
Found 94 matched controls for ENSG00000136810
Getting matched controls for ENSG00000113712

Processing conditions:  19%|████████████▌                                                      | 385/2057 [02:37<09:14,  3.02item/s, Completed 385/2057]

Found 172 matched controls for ENSG00000113712
Getting matched controls for ENSG00000181789

Processing conditions:  19%|████████████▌                                                      | 386/2057 [02:37<10:19,  2.70item/s, Completed 386/2057]

Found 261 matched controls for ENSG00000181789
Getting matched controls for ENSG00000105568

Processing conditions:  19%|████████████▋                                                      | 388/2057 [02:38<11:21,  2.45item/s, Completed 388/2057]

Found 455 matched controls for ENSG00000105568
Getting matched controls for ENSG00000110367
Found 76 matched controls for ENSG00000110367
Getting matched controls for ENSG00000213782

Processing conditions:  19%|████████████▋                                                      | 389/2057 [02:39<12:40,  2.19item/s, Completed 389/2057]

Found 313 matched controls for ENSG00000213782
Getting matched controls for ENSG00000159111

Processing conditions:  19%|████████████▋                                                      | 390/2057 [02:39<10:45,  2.58item/s, Completed 390/2057]

Found 102 matched controls for ENSG00000159111
Getting matched controls for ENSG00000164815

Processing conditions:  19%|████████████▊                                                      | 392/2057 [02:40<07:49,  3.55item/s, Completed 392/2057]

Found 89 matched controls for ENSG00000164815
Getting matched controls for ENSG00000172409
Found 55 matched controls for ENSG00000172409
Getting matched controls for ENSG00000103502

Processing conditions:  19%|████████████▊                                                      | 393/2057 [02:40<09:29,  2.92item/s, Completed 393/2057]

Found 247 matched controls for ENSG00000103502
Getting matched controls for ENSG00000105202

Processing conditions:  19%|████████████▊                                                      | 394/2057 [02:40<08:50,  3.14item/s, Completed 394/2057]

Found 132 matched controls for ENSG00000105202
Getting matched controls for ENSG00000204604

Processing conditions:  19%|████████████▊                                                      | 395/2057 [02:41<09:27,  2.93item/s, Completed 395/2057]

Found 207 matched controls for ENSG00000204604
Getting matched controls for ENSG00000004897

Processing conditions:  19%|████████████▉                                                      | 396/2057 [02:41<11:56,  2.32item/s, Completed 396/2057]

Found 366 matched controls for ENSG00000004897
Getting matched controls for ENSG00000125944

Processing conditions:  19%|████████████▉                                                      | 397/2057 [02:42<10:46,  2.57item/s, Completed 397/2057]

Found 149 matched controls for ENSG00000125944
Getting matched controls for ENSG00000228716

Processing conditions:  19%|████████████▉                                                      | 398/2057 [02:42<09:55,  2.78item/s, Completed 398/2057]

Found 125 matched controls for ENSG00000228716
Getting matched controls for ENSG00000166508

Processing conditions:  19%|█████████████                                                      | 400/2057 [02:42<07:47,  3.54item/s, Completed 400/2057]

Found 160 matched controls for ENSG00000166508
Getting matched controls for ENSG00000105671
Found 45 matched controls for ENSG00000105671
Getting matched controls for ENSG00000244537

Processing conditions:  19%|█████████████                                                      | 401/2057 [02:43<07:55,  3.48item/s, Completed 401/2057]

Found 132 matched controls for ENSG00000244537
Getting matched controls for ENSG00000273703

Processing conditions:  20%|█████████████                                                      | 402/2057 [02:43<07:56,  3.47item/s, Completed 402/2057]

Found 156 matched controls for ENSG00000273703
Getting matched controls for ENSG00000205571

Processing conditions:  20%|█████████████▏                                                     | 403/2057 [02:44<10:05,  2.73item/s, Completed 403/2057]

Found 319 matched controls for ENSG00000205571
Getting matched controls for ENSG00000204655

Processing conditions:  20%|█████████████▏                                                     | 404/2057 [02:44<09:03,  3.04item/s, Completed 404/2057]

Found 124 matched controls for ENSG00000204655
Getting matched controls for ENSG00000115073

Processing conditions:  20%|█████████████▏                                                     | 405/2057 [02:44<09:23,  2.93item/s, Completed 405/2057]

Found 206 matched controls for ENSG00000115073
Getting matched controls for ENSG00000110092

Processing conditions:  20%|█████████████▏                                                     | 406/2057 [02:44<08:58,  3.07item/s, Completed 406/2057]

Found 146 matched controls for ENSG00000110092
Getting matched controls for ENSG00000140395

Processing conditions:  20%|█████████████▎                                                     | 407/2057 [02:45<08:16,  3.32item/s, Completed 407/2057]

Found 108 matched controls for ENSG00000140395
Getting matched controls for ENSG00000169288

Processing conditions:  20%|█████████████▎                                                     | 408/2057 [02:45<08:34,  3.21item/s, Completed 408/2057]

Found 165 matched controls for ENSG00000169288
Getting matched controls for ENSG00000167522

Processing conditions:  20%|█████████████▎                                                     | 409/2057 [02:46<10:12,  2.69item/s, Completed 409/2057]

Found 260 matched controls for ENSG00000167522
Getting matched controls for ENSG00000010256

Processing conditions:  20%|█████████████▎                                                     | 410/2057 [02:46<11:42,  2.34item/s, Completed 410/2057]

Found 316 matched controls for ENSG00000010256
Getting matched controls for ENSG00000166451

Processing conditions:  20%|█████████████▍                                                     | 411/2057 [02:46<10:44,  2.55item/s, Completed 411/2057]

Found 147 matched controls for ENSG00000166451
Getting matched controls for ENSG00000152942

Processing conditions:  20%|█████████████▍                                                     | 413/2057 [02:47<08:05,  3.39item/s, Completed 413/2057]

Found 129 matched controls for ENSG00000152942
Getting matched controls for ENSG00000119801
Found 76 matched controls for ENSG00000119801
Getting matched controls for ENSG00000102967

Processing conditions:  20%|█████████████▍                                                     | 414/2057 [02:47<08:54,  3.08item/s, Completed 414/2057]

Found 223 matched controls for ENSG00000102967
Getting matched controls for ENSG00000110104

Processing conditions:  20%|█████████████▌                                                     | 415/2057 [02:48<09:55,  2.76item/s, Completed 415/2057]

Found 253 matched controls for ENSG00000110104
Getting matched controls for ENSG00000169756

Processing conditions:  20%|█████████████▌                                                     | 416/2057 [02:48<11:18,  2.42item/s, Completed 416/2057]

Found 287 matched controls for ENSG00000169756
Getting matched controls for ENSG00000196531

Processing conditions:  20%|█████████████▌                                                     | 417/2057 [02:49<12:50,  2.13item/s, Completed 417/2057]

Found 354 matched controls for ENSG00000196531
Getting matched controls for ENSG00000143742

Processing conditions:  20%|█████████████▌                                                     | 418/2057 [02:49<11:30,  2.37item/s, Completed 418/2057]

Found 168 matched controls for ENSG00000143742
Getting matched controls for ENSG00000170892

Processing conditions:  20%|█████████████▋                                                     | 420/2057 [02:50<09:47,  2.79item/s, Completed 420/2057]

Found 275 matched controls for ENSG00000170892
Getting matched controls for ENSG00000171858
Found 75 matched controls for ENSG00000171858
Getting matched controls for ENSG00000100519

Processing conditions:  20%|█████████████▋                                                     | 421/2057 [02:50<09:36,  2.84item/s, Completed 421/2057]

Found 151 matched controls for ENSG00000100519
Getting matched controls for ENSG00000111639

Processing conditions:  21%|█████████████▋                                                     | 422/2057 [02:50<08:42,  3.13item/s, Completed 422/2057]

Found 111 matched controls for ENSG00000111639
Getting matched controls for ENSG00000164615

Processing conditions:  21%|█████████████▊                                                     | 423/2057 [02:51<07:44,  3.51item/s, Completed 423/2057]

Found 99 matched controls for ENSG00000164615
Getting matched controls for ENSG00000164151

Processing conditions:  21%|█████████████▊                                                     | 424/2057 [02:51<11:21,  2.39item/s, Completed 424/2057]

Found 429 matched controls for ENSG00000164151
Getting matched controls for ENSG00000177084

Processing conditions:  21%|█████████████▊                                                     | 425/2057 [02:52<10:28,  2.60item/s, Completed 425/2057]

Found 168 matched controls for ENSG00000177084
Getting matched controls for ENSG00000101882

Processing conditions:  21%|█████████████▉                                                     | 426/2057 [02:52<09:30,  2.86item/s, Completed 426/2057]

Found 123 matched controls for ENSG00000101882
Getting matched controls for ENSG00000106399

Processing conditions:  21%|█████████████▉                                                     | 427/2057 [02:52<09:49,  2.76item/s, Completed 427/2057]

Found 208 matched controls for ENSG00000106399
Getting matched controls for ENSG00000164109

Processing conditions:  21%|█████████████▉                                                     | 428/2057 [02:53<09:37,  2.82item/s, Completed 428/2057]

Found 154 matched controls for ENSG00000164109
Getting matched controls for ENSG00000239306

Processing conditions:  21%|██████████████                                                     | 430/2057 [02:53<08:45,  3.10item/s, Completed 430/2057]

Found 228 matched controls for ENSG00000239306
Getting matched controls for ENSG00000196865
Found 91 matched controls for ENSG00000196865
Getting matched controls for ENSG00000127515

Processing conditions:  21%|██████████████                                                     | 432/2057 [02:53<05:53,  4.60item/s, Completed 432/2057]

Found 38 matched controls for ENSG00000127515
Getting matched controls for ENSG00000123737
Found 40 matched controls for ENSG00000123737
Getting matched controls for ENSG00000074800

Processing conditions:  21%|██████████████▏                                                    | 434/2057 [02:54<05:18,  5.09item/s, Completed 434/2057]

Found 70 matched controls for ENSG00000074800
Getting matched controls for ENSG00000074319
Found 87 matched controls for ENSG00000074319
Getting matched controls for ENSG00000131931

Processing conditions:  21%|██████████████▏                                                    | 436/2057 [02:54<05:23,  5.01item/s, Completed 436/2057]

Found 110 matched controls for ENSG00000131931
Getting matched controls for ENSG00000174173
Found 88 matched controls for ENSG00000174173
Getting matched controls for ENSG00000145191

Processing conditions:  21%|██████████████▎                                                    | 438/2057 [02:55<09:02,  2.98item/s, Completed 438/2057]

Found 461 matched controls for ENSG00000145191
Getting matched controls for ENSG00000182093
Found 73 matched controls for ENSG00000182093
Getting matched controls for ENSG00000135521

Processing conditions:  21%|██████████████▎                                                    | 439/2057 [02:56<10:40,  2.52item/s, Completed 439/2057]

Found 318 matched controls for ENSG00000135521
Getting matched controls for ENSG00000158106

Processing conditions:  21%|██████████████▎                                                    | 440/2057 [02:56<10:40,  2.52item/s, Completed 440/2057]

Found 225 matched controls for ENSG00000158106
Getting matched controls for ENSG00000196449

Processing conditions:  21%|██████████████▎                                                    | 441/2057 [02:56<09:13,  2.92item/s, Completed 441/2057]

Found 106 matched controls for ENSG00000196449
Getting matched controls for ENSG00000070495

Processing conditions:  21%|██████████████▍                                                    | 442/2057 [02:57<09:17,  2.90item/s, Completed 442/2057]

Found 193 matched controls for ENSG00000070495
Getting matched controls for ENSG00000181418

Processing conditions:  22%|██████████████▍                                                    | 444/2057 [02:57<08:13,  3.27item/s, Completed 444/2057]

Found 249 matched controls for ENSG00000181418
Getting matched controls for ENSG00000102901
Found 65 matched controls for ENSG00000102901
Getting matched controls for ENSG00000111237

Processing conditions:  22%|██████████████▍                                                    | 445/2057 [02:58<08:19,  3.23item/s, Completed 445/2057]

Found 165 matched controls for ENSG00000111237
Getting matched controls for ENSG00000123374

Processing conditions:  22%|██████████████▌                                                    | 446/2057 [02:58<07:32,  3.56item/s, Completed 446/2057]

Found 105 matched controls for ENSG00000123374
Getting matched controls for ENSG00000171552

Processing conditions:  22%|██████████████▌                                                    | 447/2057 [02:58<07:50,  3.42item/s, Completed 447/2057]

Found 173 matched controls for ENSG00000171552
Getting matched controls for ENSG00000013810

Processing conditions:  22%|██████████████▌                                                    | 449/2057 [02:59<06:48,  3.93item/s, Completed 449/2057]

Found 132 matched controls for ENSG00000013810
Getting matched controls for ENSG00000127564
Found 92 matched controls for ENSG00000127564
Getting matched controls for ENSG00000108424

Processing conditions:  22%|██████████████▋                                                    | 450/2057 [02:59<09:40,  2.77item/s, Completed 450/2057]

Found 366 matched controls for ENSG00000108424
Getting matched controls for ENSG00000198301

Processing conditions:  22%|██████████████▋                                                    | 451/2057 [03:00<10:09,  2.64item/s, Completed 451/2057]

Found 240 matched controls for ENSG00000198301
Getting matched controls for ENSG00000111364

Processing conditions:  22%|██████████████▋                                                    | 452/2057 [03:00<09:32,  2.80item/s, Completed 452/2057]

Found 163 matched controls for ENSG00000111364
Getting matched controls for ENSG00000147604

Processing conditions:  22%|██████████████▊                                                    | 453/2057 [03:01<11:06,  2.41item/s, Completed 453/2057]

Found 301 matched controls for ENSG00000147604
Getting matched controls for ENSG00000104835

Processing conditions:  22%|██████████████▊                                                    | 455/2057 [03:01<08:38,  3.09item/s, Completed 455/2057]

Found 163 matched controls for ENSG00000104835
Getting matched controls for ENSG00000168522
Found 80 matched controls for ENSG00000168522
Getting matched controls for ENSG00000099995

Processing conditions:  22%|██████████████▊                                                    | 456/2057 [03:02<10:35,  2.52item/s, Completed 456/2057]

Found 332 matched controls for ENSG00000099995
Getting matched controls for ENSG00000150316

Processing conditions:  22%|██████████████▉                                                    | 457/2057 [03:02<10:07,  2.63item/s, Completed 457/2057]

Found 184 matched controls for ENSG00000150316
Getting matched controls for ENSG00000163931

Processing conditions:  22%|██████████████▉                                                    | 458/2057 [03:02<10:00,  2.66item/s, Completed 458/2057]

Found 202 matched controls for ENSG00000163931
Getting matched controls for ENSG00000168118

Processing conditions:  22%|██████████████▉                                                    | 459/2057 [03:03<11:08,  2.39item/s, Completed 459/2057]

Found 303 matched controls for ENSG00000168118
Getting matched controls for ENSG00000171530

Processing conditions:  22%|██████████████▉                                                    | 460/2057 [03:03<10:25,  2.55item/s, Completed 460/2057]

Found 179 matched controls for ENSG00000171530
Getting matched controls for ENSG00000176953

Processing conditions:  22%|███████████████                                                    | 461/2057 [03:03<09:09,  2.91item/s, Completed 461/2057]

Found 118 matched controls for ENSG00000176953
Getting matched controls for ENSG00000014123

Processing conditions:  23%|███████████████                                                    | 463/2057 [03:04<07:29,  3.55item/s, Completed 463/2057]

Found 162 matched controls for ENSG00000014123
Getting matched controls for ENSG00000115163
Found 76 matched controls for ENSG00000115163
Getting matched controls for ENSG00000164163

Processing conditions:  23%|███████████████                                                    | 464/2057 [03:04<08:46,  3.03item/s, Completed 464/2057]

Found 249 matched controls for ENSG00000164163
Getting matched controls for ENSG00000198901

Processing conditions:  23%|███████████████▏                                                   | 465/2057 [03:05<08:52,  2.99item/s, Completed 465/2057]

Found 187 matched controls for ENSG00000198901
Getting matched controls for ENSG00000176108

Processing conditions:  23%|███████████████▏                                                   | 467/2057 [03:06<11:34,  2.29item/s, Completed 467/2057]

Found 624 matched controls for ENSG00000176108
Getting matched controls for ENSG00000117751
Found 69 matched controls for ENSG00000117751
Getting matched controls for ENSG00000166902

Processing conditions:  23%|███████████████▎                                                   | 469/2057 [03:06<07:48,  3.39item/s, Completed 469/2057]

Found 85 matched controls for ENSG00000166902
Getting matched controls for ENSG00000100387
Found 57 matched controls for ENSG00000100387
Getting matched controls for ENSG00000205323

Processing conditions:  23%|███████████████▎                                                   | 470/2057 [03:06<07:02,  3.75item/s, Completed 470/2057]

Found 93 matched controls for ENSG00000205323
Getting matched controls for ENSG00000113460

Processing conditions:  23%|███████████████▎                                                   | 471/2057 [03:07<06:57,  3.80item/s, Completed 471/2057]

Found 132 matched controls for ENSG00000113460
Getting matched controls for ENSG00000154719

Processing conditions:  23%|███████████████▎                                                   | 472/2057 [03:07<07:10,  3.69item/s, Completed 472/2057]

Found 154 matched controls for ENSG00000154719
Getting matched controls for ENSG00000125630

Processing conditions:  23%|███████████████▍                                                   | 474/2057 [03:07<06:36,  3.99item/s, Completed 474/2057]

Found 181 matched controls for ENSG00000125630
Getting matched controls for ENSG00000161547
Found 69 matched controls for ENSG00000161547
Getting matched controls for ENSG00000124383

Processing conditions:  23%|███████████████▌                                                   | 476/2057 [03:08<05:16,  5.00item/s, Completed 476/2057]

Found 43 matched controls for ENSG00000124383
Getting matched controls for ENSG00000149925
Found 78 matched controls for ENSG00000149925
Getting matched controls for ENSG00000277075

Processing conditions:  23%|███████████████▌                                                   | 477/2057 [03:08<05:35,  4.71item/s, Completed 477/2057]

Found 123 matched controls for ENSG00000277075
Getting matched controls for ENSG00000156603

Processing conditions:  23%|███████████████▌                                                   | 479/2057 [03:09<09:18,  2.83item/s, Completed 479/2057]

Found 544 matched controls for ENSG00000156603
Getting matched controls for ENSG00000117682
Found 96 matched controls for ENSG00000117682
Getting matched controls for ENSG00000103356

Processing conditions:  23%|███████████████▋                                                   | 480/2057 [03:09<09:13,  2.85item/s, Completed 480/2057]

Found 192 matched controls for ENSG00000103356
Getting matched controls for ENSG00000135040

Processing conditions:  23%|███████████████▋                                                   | 482/2057 [03:10<07:30,  3.50item/s, Completed 482/2057]

Found 193 matched controls for ENSG00000135040
Getting matched controls for ENSG00000070366
Found 54 matched controls for ENSG00000070366
Getting matched controls for ENSG00000172247

Processing conditions:  24%|███████████████▊                                                   | 484/2057 [03:10<07:08,  3.67item/s, Completed 484/2057]

Found 199 matched controls for ENSG00000172247
Getting matched controls for ENSG00000183763
Found 87 matched controls for ENSG00000183763
Getting matched controls for ENSG00000133997

Processing conditions:  24%|███████████████▊                                                   | 485/2057 [03:11<08:22,  3.13item/s, Completed 485/2057]

Found 246 matched controls for ENSG00000133997
Getting matched controls for ENSG00000125952

Processing conditions:  24%|███████████████▊                                                   | 487/2057 [03:11<06:49,  3.83item/s, Completed 487/2057]

Found 180 matched controls for ENSG00000125952
Getting matched controls for ENSG00000083520
Found 43 matched controls for ENSG00000083520
Getting matched controls for ENSG00000106246

Processing conditions:  24%|███████████████▉                                                   | 488/2057 [03:12<08:24,  3.11item/s, Completed 488/2057]

Found 267 matched controls for ENSG00000106246
Getting matched controls for ENSG00000183479

Processing conditions:  24%|███████████████▉                                                   | 489/2057 [03:12<09:36,  2.72item/s, Completed 489/2057]

Found 275 matched controls for ENSG00000183479
Getting matched controls for ENSG00000007866

Processing conditions:  24%|███████████████▉                                                   | 490/2057 [03:13<10:21,  2.52item/s, Completed 490/2057]

Found 267 matched controls for ENSG00000007866
Getting matched controls for ENSG00000100084

Processing conditions:  24%|███████████████▉                                                   | 491/2057 [03:13<12:13,  2.13item/s, Completed 491/2057]

Found 341 matched controls for ENSG00000100084
Getting matched controls for ENSG00000213218

Processing conditions:  24%|████████████████                                                   | 492/2057 [03:14<11:34,  2.25item/s, Completed 492/2057]

Found 179 matched controls for ENSG00000213218
Getting matched controls for ENSG00000147457

Processing conditions:  24%|████████████████                                                   | 493/2057 [03:14<11:26,  2.28item/s, Completed 493/2057]

Found 240 matched controls for ENSG00000147457
Getting matched controls for ENSG00000105171

Processing conditions:  24%|████████████████                                                   | 494/2057 [03:14<10:05,  2.58item/s, Completed 494/2057]

Found 128 matched controls for ENSG00000105171
Getting matched controls for ENSG00000143252

Processing conditions:  24%|████████████████▏                                                  | 496/2057 [03:15<07:44,  3.36item/s, Completed 496/2057]

Found 104 matched controls for ENSG00000143252
Getting matched controls for ENSG00000160075
Found 85 matched controls for ENSG00000160075
Getting matched controls for ENSG00000157349

Processing conditions:  24%|████████████████▏                                                  | 497/2057 [03:15<09:39,  2.69item/s, Completed 497/2057]

Found 285 matched controls for ENSG00000157349
Getting matched controls for ENSG00000170445

Processing conditions:  24%|████████████████▏                                                  | 498/2057 [03:16<10:36,  2.45item/s, Completed 498/2057]

Found 289 matched controls for ENSG00000170445
Getting matched controls for ENSG00000114391

Processing conditions:  24%|████████████████▎                                                  | 499/2057 [03:17<13:23,  1.94item/s, Completed 499/2057]

Found 460 matched controls for ENSG00000114391
Getting matched controls for ENSG00000184432

Processing conditions:  24%|████████████████▎                                                  | 500/2057 [03:17<11:18,  2.30item/s, Completed 500/2057]

Found 129 matched controls for ENSG00000184432
Getting matched controls for ENSG00000170160

Processing conditions:  24%|████████████████▎                                                  | 501/2057 [03:17<09:43,  2.67item/s, Completed 501/2057]

Found 117 matched controls for ENSG00000170160
Getting matched controls for ENSG00000117505

Processing conditions:  24%|████████████████▎                                                  | 502/2057 [03:17<09:07,  2.84item/s, Completed 502/2057]

Found 126 matched controls for ENSG00000117505
Getting matched controls for ENSG00000166260

Processing conditions:  24%|████████████████▍                                                  | 503/2057 [03:18<08:14,  3.14item/s, Completed 503/2057]

Found 109 matched controls for ENSG00000166260
Getting matched controls for ENSG00000142794

Processing conditions:  25%|████████████████▍                                                  | 505/2057 [03:18<06:55,  3.74item/s, Completed 505/2057]

Found 133 matched controls for ENSG00000142794
Getting matched controls for ENSG00000077514
Found 68 matched controls for ENSG00000077514
Getting matched controls for ENSG00000144231

Processing conditions:  25%|████████████████▍                                                  | 506/2057 [03:19<08:56,  2.89item/s, Completed 506/2057]

Found 281 matched controls for ENSG00000144231
Getting matched controls for ENSG00000136450

Processing conditions:  25%|████████████████▌                                                  | 507/2057 [03:19<08:32,  3.03item/s, Completed 507/2057]

Found 159 matched controls for ENSG00000136450
Getting matched controls for ENSG00000159761

Processing conditions:  25%|████████████████▌                                                  | 508/2057 [03:19<08:41,  2.97item/s, Completed 508/2057]

Found 184 matched controls for ENSG00000159761
Getting matched controls for ENSG00000197102

Processing conditions:  25%|████████████████▌                                                  | 509/2057 [03:20<09:55,  2.60item/s, Completed 509/2057]

Found 291 matched controls for ENSG00000197102
Getting matched controls for ENSG00000186026

Processing conditions:  25%|████████████████▌                                                  | 510/2057 [03:20<09:55,  2.60item/s, Completed 510/2057]

Found 218 matched controls for ENSG00000186026
Getting matched controls for ENSG00000198356

Processing conditions:  25%|████████████████▋                                                  | 512/2057 [03:21<07:05,  3.63item/s, Completed 512/2057]

Found 121 matched controls for ENSG00000198356
Getting matched controls for ENSG00000102384
Found 42 matched controls for ENSG00000102384
Getting matched controls for ENSG00000110321

Processing conditions:  25%|████████████████▋                                                  | 513/2057 [03:21<09:29,  2.71item/s, Completed 513/2057]

Found 342 matched controls for ENSG00000110321
Getting matched controls for ENSG00000095139

Processing conditions:  25%|████████████████▊                                                  | 515/2057 [03:22<08:42,  2.95item/s, Completed 515/2057]

Found 333 matched controls for ENSG00000095139
Getting matched controls for ENSG00000198929
Found 54 matched controls for ENSG00000198929
Getting matched controls for ENSG00000132780

Processing conditions:  25%|████████████████▊                                                  | 516/2057 [03:22<08:38,  2.97item/s, Completed 516/2057]

Found 184 matched controls for ENSG00000132780
Getting matched controls for ENSG00000066422

Processing conditions:  25%|████████████████▊                                                  | 517/2057 [03:22<08:09,  3.15item/s, Completed 517/2057]

Found 146 matched controls for ENSG00000066422
Getting matched controls for ENSG00000162458

Processing conditions:  25%|████████████████▊                                                  | 518/2057 [03:23<07:40,  3.34item/s, Completed 518/2057]

Found 133 matched controls for ENSG00000162458
Getting matched controls for ENSG00000167985

Processing conditions:  25%|████████████████▉                                                  | 519/2057 [03:23<07:15,  3.53item/s, Completed 519/2057]

Found 126 matched controls for ENSG00000167985
Getting matched controls for ENSG00000196584

Processing conditions:  25%|████████████████▉                                                  | 520/2057 [03:23<07:19,  3.50item/s, Completed 520/2057]

Found 157 matched controls for ENSG00000196584
Getting matched controls for ENSG00000013503

Processing conditions:  25%|████████████████▉                                                  | 521/2057 [03:24<06:54,  3.70item/s, Completed 521/2057]

Found 113 matched controls for ENSG00000013503
Getting matched controls for ENSG00000101057

Processing conditions:  25%|█████████████████                                                  | 522/2057 [03:24<06:28,  3.96item/s, Completed 522/2057]

Found 106 matched controls for ENSG00000101057
Getting matched controls for ENSG00000105732

Processing conditions:  25%|█████████████████                                                  | 523/2057 [03:24<08:37,  2.97item/s, Completed 523/2057]

Found 314 matched controls for ENSG00000105732
Getting matched controls for ENSG00000113643

Processing conditions:  25%|█████████████████                                                  | 524/2057 [03:25<11:25,  2.24item/s, Completed 524/2057]

Found 404 matched controls for ENSG00000113643
Getting matched controls for ENSG00000125977

Processing conditions:  26%|█████████████████                                                  | 525/2057 [03:25<09:48,  2.60item/s, Completed 525/2057]

Found 120 matched controls for ENSG00000125977
Getting matched controls for ENSG00000137955

Processing conditions:  26%|█████████████████▏                                                 | 526/2057 [03:26<09:26,  2.70item/s, Completed 526/2057]

Found 169 matched controls for ENSG00000137955
Getting matched controls for ENSG00000215784

Processing conditions:  26%|█████████████████▏                                                 | 527/2057 [03:26<08:24,  3.03item/s, Completed 527/2057]

Found 120 matched controls for ENSG00000215784
Getting matched controls for ENSG00000144559

Processing conditions:  26%|█████████████████▏                                                 | 528/2057 [03:26<07:41,  3.31item/s, Completed 528/2057]

Found 120 matched controls for ENSG00000144559
Getting matched controls for ENSG00000251192

Processing conditions:  26%|█████████████████▏                                                 | 529/2057 [03:26<07:15,  3.51item/s, Completed 529/2057]

Found 126 matched controls for ENSG00000251192
Getting matched controls for ENSG00000146731

Processing conditions:  26%|█████████████████▎                                                 | 530/2057 [03:27<07:23,  3.44item/s, Completed 530/2057]

Found 131 matched controls for ENSG00000146731
Getting matched controls for ENSG00000113407

Processing conditions:  26%|█████████████████▎                                                 | 531/2057 [03:27<07:09,  3.55item/s, Completed 531/2057]

Found 132 matched controls for ENSG00000113407
Getting matched controls for ENSG00000140694

Processing conditions:  26%|█████████████████▎                                                 | 533/2057 [03:27<06:11,  4.10item/s, Completed 533/2057]

Found 123 matched controls for ENSG00000140694
Getting matched controls for ENSG00000099381
Found 69 matched controls for ENSG00000099381
Getting matched controls for ENSG00000125676

Processing conditions:  26%|█████████████████▍                                                 | 534/2057 [03:28<07:14,  3.50item/s, Completed 534/2057]

Found 190 matched controls for ENSG00000125676
Getting matched controls for ENSG00000125846

Processing conditions:  26%|█████████████████▍                                                 | 535/2057 [03:28<06:38,  3.82item/s, Completed 535/2057]

Found 102 matched controls for ENSG00000125846
Getting matched controls for ENSG00000092199

Processing conditions:  26%|█████████████████▍                                                 | 536/2057 [03:28<08:55,  2.84item/s, Completed 536/2057]

Found 334 matched controls for ENSG00000092199
Getting matched controls for ENSG00000175550

Processing conditions:  26%|█████████████████▍                                                 | 537/2057 [03:29<09:16,  2.73item/s, Completed 537/2057]

Found 227 matched controls for ENSG00000175550
Getting matched controls for ENSG00000127337

Processing conditions:  26%|█████████████████▌                                                 | 538/2057 [03:29<10:02,  2.52item/s, Completed 538/2057]

Found 231 matched controls for ENSG00000127337
Getting matched controls for ENSG00000137100

Processing conditions:  26%|█████████████████▌                                                 | 539/2057 [03:30<09:52,  2.56item/s, Completed 539/2057]

Found 201 matched controls for ENSG00000137100
Getting matched controls for ENSG00000114767

Processing conditions:  26%|█████████████████▌                                                 | 540/2057 [03:30<08:35,  2.94item/s, Completed 540/2057]

Found 110 matched controls for ENSG00000114767
Getting matched controls for ENSG00000120699

Processing conditions:  26%|█████████████████▌                                                 | 541/2057 [03:30<07:52,  3.21item/s, Completed 541/2057]

Found 126 matched controls for ENSG00000120699
Getting matched controls for ENSG00000165792

Processing conditions:  26%|█████████████████▋                                                 | 542/2057 [03:30<07:19,  3.45item/s, Completed 542/2057]

Found 122 matched controls for ENSG00000165792
Getting matched controls for ENSG00000196950

Processing conditions:  26%|█████████████████▋                                                 | 543/2057 [03:31<07:20,  3.43item/s, Completed 543/2057]

Found 153 matched controls for ENSG00000196950
Getting matched controls for ENSG00000105254

Processing conditions:  26%|█████████████████▋                                                 | 544/2057 [03:31<06:43,  3.75item/s, Completed 544/2057]

Found 102 matched controls for ENSG00000105254
Getting matched controls for ENSG00000204822

Processing conditions:  26%|█████████████████▊                                                 | 545/2057 [03:31<06:51,  3.67item/s, Completed 545/2057]

Found 153 matched controls for ENSG00000204822
Getting matched controls for ENSG00000014919

Processing conditions:  27%|█████████████████▊                                                 | 546/2057 [03:31<06:24,  3.93item/s, Completed 546/2057]

Found 103 matched controls for ENSG00000014919
Getting matched controls for ENSG00000205981

Processing conditions:  27%|█████████████████▊                                                 | 547/2057 [03:32<09:31,  2.64item/s, Completed 547/2057]

Found 398 matched controls for ENSG00000205981
Getting matched controls for ENSG00000095787

Processing conditions:  27%|█████████████████▊                                                 | 548/2057 [03:32<08:55,  2.82item/s, Completed 548/2057]

Found 162 matched controls for ENSG00000095787
Getting matched controls for ENSG00000011376

Processing conditions:  27%|█████████████████▉                                                 | 549/2057 [03:33<08:21,  3.00item/s, Completed 549/2057]

Found 149 matched controls for ENSG00000011376
Getting matched controls for ENSG00000171863

Processing conditions:  27%|█████████████████▉                                                 | 551/2057 [03:33<07:51,  3.19item/s, Completed 551/2057]

Found 265 matched controls for ENSG00000171863
Getting matched controls for ENSG00000145375
Found 70 matched controls for ENSG00000145375
Getting matched controls for ENSG00000171903

Processing conditions:  27%|█████████████████▉                                                 | 552/2057 [03:33<07:15,  3.45item/s, Completed 552/2057]

Found 120 matched controls for ENSG00000171903
Getting matched controls for ENSG00000126698

Processing conditions:  27%|██████████████████                                                 | 553/2057 [03:34<08:50,  2.83item/s, Completed 553/2057]

Found 277 matched controls for ENSG00000126698
Getting matched controls for ENSG00000160783

Processing conditions:  27%|██████████████████                                                 | 554/2057 [03:34<09:47,  2.56item/s, Completed 554/2057]

Found 265 matched controls for ENSG00000160783
Getting matched controls for ENSG00000172053

Processing conditions:  27%|██████████████████                                                 | 555/2057 [03:35<12:47,  1.96item/s, Completed 555/2057]

Found 400 matched controls for ENSG00000172053
Getting matched controls for ENSG00000042429

Processing conditions:  27%|██████████████████                                                 | 556/2057 [03:36<11:23,  2.20item/s, Completed 556/2057]

Found 151 matched controls for ENSG00000042429
Getting matched controls for ENSG00000109534

Processing conditions:  27%|██████████████████▏                                                | 557/2057 [03:36<10:22,  2.41item/s, Completed 557/2057]

Found 146 matched controls for ENSG00000109534
Getting matched controls for ENSG00000108784

Processing conditions:  27%|██████████████████▏                                                | 558/2057 [03:36<11:05,  2.25item/s, Completed 558/2057]

Found 265 matched controls for ENSG00000108784
Getting matched controls for ENSG00000176407

Processing conditions:  27%|██████████████████▏                                                | 559/2057 [03:37<09:56,  2.51item/s, Completed 559/2057]

Found 154 matched controls for ENSG00000176407
Getting matched controls for ENSG00000170421

Processing conditions:  27%|██████████████████▏                                                | 560/2057 [03:37<11:23,  2.19item/s, Completed 560/2057]

Found 347 matched controls for ENSG00000170421
Getting matched controls for ENSG00000084463

Processing conditions:  27%|██████████████████▎                                                | 561/2057 [03:38<12:07,  2.06item/s, Completed 561/2057]

Found 312 matched controls for ENSG00000084463
Getting matched controls for ENSG00000065328

Processing conditions:  27%|██████████████████▎                                                | 562/2057 [03:38<12:01,  2.07item/s, Completed 562/2057]

Found 219 matched controls for ENSG00000065328
Getting matched controls for ENSG00000060069

Processing conditions:  27%|██████████████████▎                                                | 563/2057 [03:39<10:10,  2.45item/s, Completed 563/2057]

Found 117 matched controls for ENSG00000060069
Getting matched controls for ENSG00000173692

Processing conditions:  27%|██████████████████▎                                                | 564/2057 [03:39<11:19,  2.20item/s, Completed 564/2057]

Found 281 matched controls for ENSG00000173692
Getting matched controls for ENSG00000171566

Processing conditions:  27%|██████████████████▍                                                | 565/2057 [03:39<09:40,  2.57item/s, Completed 565/2057]

Found 94 matched controls for ENSG00000171566
Getting matched controls for ENSG00000100813

Processing conditions:  28%|██████████████████▍                                                | 566/2057 [03:40<09:44,  2.55item/s, Completed 566/2057]

Found 191 matched controls for ENSG00000100813
Getting matched controls for ENSG00000107862

Processing conditions:  28%|██████████████████▌                                                | 568/2057 [03:40<08:04,  3.07item/s, Completed 568/2057]

Found 161 matched controls for ENSG00000107862
Getting matched controls for ENSG00000124641
Found 80 matched controls for ENSG00000124641
Getting matched controls for ENSG00000100522

Processing conditions:  28%|██████████████████▌                                                | 569/2057 [03:41<07:20,  3.38item/s, Completed 569/2057]

Found 112 matched controls for ENSG00000100522
Getting matched controls for ENSG00000204482

Processing conditions:  28%|██████████████████▌                                                | 570/2057 [03:41<07:37,  3.25item/s, Completed 570/2057]

Found 149 matched controls for ENSG00000204482
Getting matched controls for ENSG00000159259

Processing conditions:  28%|██████████████████▌                                                | 571/2057 [03:41<06:51,  3.61item/s, Completed 571/2057]

Found 84 matched controls for ENSG00000159259
Getting matched controls for ENSG00000072849

Processing conditions:  28%|██████████████████▋                                                | 572/2057 [03:41<06:51,  3.61item/s, Completed 572/2057]

Found 124 matched controls for ENSG00000072849
Getting matched controls for ENSG00000176294

Processing conditions:  28%|██████████████████▋                                                | 573/2057 [03:42<06:37,  3.74item/s, Completed 573/2057]

Found 118 matched controls for ENSG00000176294
Getting matched controls for ENSG00000178502

Processing conditions:  28%|██████████████████▋                                                | 574/2057 [03:42<06:28,  3.82item/s, Completed 574/2057]

Found 125 matched controls for ENSG00000178502
Getting matched controls for ENSG00000214367

Processing conditions:  28%|██████████████████▊                                                | 576/2057 [03:42<05:53,  4.19item/s, Completed 576/2057]

Found 164 matched controls for ENSG00000214367
Getting matched controls for ENSG00000132300
Found 65 matched controls for ENSG00000132300
Getting matched controls for ENSG00000172613

Processing conditions:  28%|██████████████████▊                                                | 577/2057 [03:42<05:08,  4.79item/s, Completed 577/2057]

Found 41 matched controls for ENSG00000172613
Getting matched controls for ENSG00000136819

Processing conditions:  28%|██████████████████▊                                                | 578/2057 [03:43<06:30,  3.79item/s, Completed 578/2057]

Found 201 matched controls for ENSG00000136819
Getting matched controls for ENSG00000108298

Processing conditions:  28%|██████████████████▊                                                | 579/2057 [03:43<07:38,  3.22item/s, Completed 579/2057]

Found 238 matched controls for ENSG00000108298
Getting matched controls for ENSG00000143952

Processing conditions:  28%|██████████████████▉                                                | 580/2057 [03:44<09:22,  2.63item/s, Completed 580/2057]

Found 321 matched controls for ENSG00000143952
Getting matched controls for ENSG00000138442

Processing conditions:  28%|██████████████████▉                                                | 581/2057 [03:44<09:33,  2.57item/s, Completed 581/2057]

Found 213 matched controls for ENSG00000138442
Getting matched controls for ENSG00000198830

Processing conditions:  28%|██████████████████▉                                                | 583/2057 [03:45<06:50,  3.59item/s, Completed 583/2057]

Found 107 matched controls for ENSG00000198830
Getting matched controls for ENSG00000111641
Found 58 matched controls for ENSG00000111641
Getting matched controls for ENSG00000136937

Processing conditions:  28%|███████████████████                                                | 584/2057 [03:45<05:58,  4.11item/s, Completed 585/2057]

Found 60 matched controls for ENSG00000136937
Getting matched controls for ENSG00000135372
Found 30 matched controls for ENSG00000135372
Getting matched controls for ENSG00000142700

Processing conditions:  29%|███████████████████                                                | 587/2057 [03:45<04:52,  5.03item/s, Completed 587/2057]

Found 107 matched controls for ENSG00000142700
Getting matched controls for ENSG00000152944
Found 63 matched controls for ENSG00000152944
Getting matched controls for ENSG00000185122

Processing conditions:  29%|███████████████████▏                                               | 588/2057 [03:46<05:26,  4.50item/s, Completed 588/2057]

Found 131 matched controls for ENSG00000185122
Getting matched controls for ENSG00000185163

Processing conditions:  29%|███████████████████▏                                               | 589/2057 [03:46<05:44,  4.27item/s, Completed 589/2057]

Found 128 matched controls for ENSG00000185163
Getting matched controls for ENSG00000165501

Processing conditions:  29%|███████████████████▏                                               | 590/2057 [03:46<05:56,  4.12item/s, Completed 590/2057]

Found 122 matched controls for ENSG00000165501
Getting matched controls for ENSG00000155463

Processing conditions:  29%|███████████████████▎                                               | 592/2057 [03:47<07:12,  3.39item/s, Completed 592/2057]

Found 344 matched controls for ENSG00000155463
Getting matched controls for ENSG00000184203
Found 80 matched controls for ENSG00000184203
Getting matched controls for ENSG00000133773

Processing conditions:  29%|███████████████████▎                                               | 594/2057 [03:47<05:49,  4.18item/s, Completed 594/2057]

Found 125 matched controls for ENSG00000133773
Getting matched controls for ENSG00000136152
Found 56 matched controls for ENSG00000136152
Getting matched controls for ENSG00000155438

Processing conditions:  29%|███████████████████▍                                               | 595/2057 [03:48<07:09,  3.40item/s, Completed 595/2057]

Found 240 matched controls for ENSG00000155438
Getting matched controls for ENSG00000165819

Processing conditions:  29%|███████████████████▍                                               | 596/2057 [03:48<06:55,  3.52item/s, Completed 596/2057]

Found 138 matched controls for ENSG00000165819
Getting matched controls for ENSG00000100804

Processing conditions:  29%|███████████████████▍                                               | 597/2057 [03:48<08:14,  2.95item/s, Completed 597/2057]

Found 270 matched controls for ENSG00000100804
Getting matched controls for ENSG00000175334

Processing conditions:  29%|███████████████████▍                                               | 598/2057 [03:49<07:57,  3.06item/s, Completed 598/2057]

Found 162 matched controls for ENSG00000175334
Getting matched controls for ENSG00000172116

Processing conditions:  29%|███████████████████▌                                               | 599/2057 [03:49<07:11,  3.38item/s, Completed 599/2057]

Found 112 matched controls for ENSG00000172116
Getting matched controls for ENSG00000152684

Processing conditions:  29%|███████████████████▌                                               | 600/2057 [03:49<08:36,  2.82item/s, Completed 600/2057]

Found 286 matched controls for ENSG00000152684
Getting matched controls for ENSG00000092036

Processing conditions:  29%|███████████████████▌                                               | 602/2057 [03:50<07:07,  3.40item/s, Completed 602/2057]

Found 189 matched controls for ENSG00000092036
Getting matched controls for ENSG00000205097
Found 51 matched controls for ENSG00000205097
Getting matched controls for ENSG00000075856

Processing conditions:  29%|███████████████████▋                                               | 603/2057 [03:50<07:05,  3.42item/s, Completed 603/2057]

Found 154 matched controls for ENSG00000075856
Getting matched controls for ENSG00000110921

Processing conditions:  29%|███████████████████▋                                               | 604/2057 [03:50<06:51,  3.53item/s, Completed 604/2057]

Found 136 matched controls for ENSG00000110921
Getting matched controls for ENSG00000250571

Processing conditions:  29%|███████████████████▋                                               | 605/2057 [03:51<07:05,  3.41item/s, Completed 605/2057]

Found 156 matched controls for ENSG00000250571
Getting matched controls for ENSG00000075914

Processing conditions:  30%|███████████████████▊                                               | 607/2057 [03:51<05:50,  4.14item/s, Completed 607/2057]

Found 113 matched controls for ENSG00000075914
Getting matched controls for ENSG00000071243
Found 65 matched controls for ENSG00000071243
Getting matched controls for ENSG00000050820

Processing conditions:  30%|███████████████████▊                                               | 608/2057 [03:52<07:20,  3.29item/s, Completed 608/2057]

Found 246 matched controls for ENSG00000050820
Getting matched controls for ENSG00000005448

Processing conditions:  30%|███████████████████▊                                               | 609/2057 [03:52<07:49,  3.08item/s, Completed 609/2057]

Found 208 matched controls for ENSG00000005448
Getting matched controls for ENSG00000108094

Processing conditions:  30%|███████████████████▊                                               | 610/2057 [03:52<07:02,  3.42item/s, Completed 610/2057]

Found 94 matched controls for ENSG00000108094
Getting matched controls for ENSG00000144713

Processing conditions:  30%|███████████████████▉                                               | 611/2057 [03:53<07:36,  3.17item/s, Completed 611/2057]

Found 208 matched controls for ENSG00000144713
Getting matched controls for ENSG00000101166

Processing conditions:  30%|███████████████████▉                                               | 613/2057 [03:53<07:37,  3.16item/s, Completed 613/2057]

Found 273 matched controls for ENSG00000101166
Getting matched controls for ENSG00000109805
Found 79 matched controls for ENSG00000109805
Getting matched controls for ENSG00000175792

Processing conditions:  30%|███████████████████▉                                               | 614/2057 [03:54<08:01,  3.00item/s, Completed 614/2057]

Found 211 matched controls for ENSG00000175792
Getting matched controls for ENSG00000118193

Processing conditions:  30%|████████████████████                                               | 615/2057 [03:54<07:19,  3.28item/s, Completed 615/2057]

Found 118 matched controls for ENSG00000118193
Getting matched controls for ENSG00000136891

Processing conditions:  30%|████████████████████                                               | 616/2057 [03:54<07:19,  3.28item/s, Completed 616/2057]

Found 162 matched controls for ENSG00000136891
Getting matched controls for ENSG00000153767

Processing conditions:  30%|████████████████████▏                                              | 618/2057 [03:55<06:40,  3.59item/s, Completed 618/2057]

Found 181 matched controls for ENSG00000153767
Getting matched controls for ENSG00000127586
Found 97 matched controls for ENSG00000127586
Getting matched controls for ENSG00000156482

Processing conditions:  30%|████████████████████▏                                              | 619/2057 [03:55<09:04,  2.64item/s, Completed 619/2057]

Found 365 matched controls for ENSG00000156482
Getting matched controls for ENSG00000120158

Processing conditions:  30%|████████████████████▏                                              | 620/2057 [03:56<07:53,  3.03item/s, Completed 620/2057]

Found 106 matched controls for ENSG00000120158
Getting matched controls for ENSG00000101773

Processing conditions:  30%|████████████████████▎                                              | 622/2057 [03:56<06:00,  3.98item/s, Completed 622/2057]

Found 117 matched controls for ENSG00000101773
Getting matched controls for ENSG00000168906
Found 52 matched controls for ENSG00000168906
Getting matched controls for ENSG00000165389

Processing conditions:  30%|████████████████████▎                                              | 624/2057 [03:56<05:15,  4.54item/s, Completed 624/2057]

Found 124 matched controls for ENSG00000165389
Getting matched controls for ENSG00000106636
Found 63 matched controls for ENSG00000106636
Getting matched controls for ENSG00000138095

Processing conditions:  30%|████████████████████▍                                              | 626/2057 [03:57<05:26,  4.38item/s, Completed 626/2057]

Found 110 matched controls for ENSG00000138095
Getting matched controls for ENSG00000123064
Found 95 matched controls for ENSG00000123064
Getting matched controls for ENSG00000118412

Processing conditions:  30%|████████████████████▍                                              | 627/2057 [03:57<06:30,  3.66item/s, Completed 627/2057]

Found 211 matched controls for ENSG00000118412
Getting matched controls for ENSG00000090889

Processing conditions:  31%|████████████████████▍                                              | 629/2057 [03:58<05:31,  4.31item/s, Completed 629/2057]

Found 129 matched controls for ENSG00000090889
Getting matched controls for ENSG00000111602
Found 64 matched controls for ENSG00000111602
Getting matched controls for ENSG00000167967

Processing conditions:  31%|████████████████████▌                                              | 630/2057 [03:58<05:42,  4.16item/s, Completed 630/2057]

Found 134 matched controls for ENSG00000167967
Getting matched controls for ENSG00000175203

Processing conditions:  31%|████████████████████▌                                              | 631/2057 [03:58<05:46,  4.12item/s, Completed 631/2057]

Found 126 matched controls for ENSG00000175203
Getting matched controls for ENSG00000132313

Processing conditions:  31%|████████████████████▌                                              | 633/2057 [03:59<05:25,  4.38item/s, Completed 633/2057]

Found 171 matched controls for ENSG00000132313
Getting matched controls for ENSG00000172466
Found 59 matched controls for ENSG00000172466
Getting matched controls for ENSG00000124486

Processing conditions:  31%|████████████████████▋                                              | 634/2057 [03:59<05:23,  4.40item/s, Completed 634/2057]

Found 112 matched controls for ENSG00000124486
Getting matched controls for ENSG00000182774

Processing conditions:  31%|████████████████████▋                                              | 635/2057 [03:59<06:47,  3.49item/s, Completed 635/2057]

Found 223 matched controls for ENSG00000182774
Getting matched controls for ENSG00000131475

Processing conditions:  31%|████████████████████▋                                              | 637/2057 [04:00<05:38,  4.20item/s, Completed 637/2057]

Found 84 matched controls for ENSG00000131475
Getting matched controls for ENSG00000135069
Found 72 matched controls for ENSG00000135069
Getting matched controls for ENSG00000037241

Processing conditions:  31%|████████████████████▊                                              | 639/2057 [04:00<05:29,  4.31item/s, Completed 639/2057]

Found 148 matched controls for ENSG00000037241
Getting matched controls for ENSG00000203760
Found 72 matched controls for ENSG00000203760
Getting matched controls for ENSG00000130255

Processing conditions:  31%|████████████████████▊                                              | 640/2057 [04:00<07:03,  3.35item/s, Completed 640/2057]

Found 204 matched controls for ENSG00000130255
Getting matched controls for ENSG00000155115

Processing conditions:  31%|████████████████████▉                                              | 642/2057 [04:01<06:57,  3.39item/s, Completed 642/2057]

Found 243 matched controls for ENSG00000155115
Getting matched controls for ENSG00000169976
Found 84 matched controls for ENSG00000169976
Getting matched controls for ENSG00000134597

Processing conditions:  31%|████████████████████▉                                              | 643/2057 [04:02<08:11,  2.87item/s, Completed 643/2057]

Found 244 matched controls for ENSG00000134597
Getting matched controls for ENSG00000100353

Processing conditions:  31%|████████████████████▉                                              | 644/2057 [04:02<08:22,  2.81item/s, Completed 644/2057]

Found 186 matched controls for ENSG00000100353
Getting matched controls for ENSG00000115484

Processing conditions:  31%|█████████████████████                                              | 646/2057 [04:03<07:33,  3.11item/s, Completed 646/2057]

Found 251 matched controls for ENSG00000115484
Getting matched controls for ENSG00000084623
Found 61 matched controls for ENSG00000084623
Getting matched controls for ENSG00000205937

Processing conditions:  31%|█████████████████████                                              | 647/2057 [04:03<07:16,  3.23item/s, Completed 647/2057]

Found 131 matched controls for ENSG00000205937
Getting matched controls for ENSG00000100023

Processing conditions:  32%|█████████████████████                                              | 648/2057 [04:03<07:04,  3.32item/s, Completed 648/2057]

Found 130 matched controls for ENSG00000100023
Getting matched controls for ENSG00000130177

Processing conditions:  32%|█████████████████████▏                                             | 649/2057 [04:04<07:34,  3.10item/s, Completed 649/2057]

Found 165 matched controls for ENSG00000130177
Getting matched controls for ENSG00000215021

Processing conditions:  32%|█████████████████████▏                                             | 650/2057 [04:04<10:32,  2.22item/s, Completed 650/2057]

Found 415 matched controls for ENSG00000215021
Getting matched controls for ENSG00000160111

Processing conditions:  32%|█████████████████████▏                                             | 652/2057 [04:05<08:36,  2.72item/s, Completed 652/2057]

Found 233 matched controls for ENSG00000160111
Getting matched controls for ENSG00000262664
Found 76 matched controls for ENSG00000262664
Getting matched controls for ENSG00000104671

Processing conditions:  32%|█████████████████████▎                                             | 653/2057 [04:05<07:03,  3.31item/s, Completed 653/2057]

Found 64 matched controls for ENSG00000104671
Getting matched controls for ENSG00000088356

Processing conditions:  32%|█████████████████████▎                                             | 654/2057 [04:05<06:34,  3.56item/s, Completed 654/2057]

Found 116 matched controls for ENSG00000088356
Getting matched controls for ENSG00000181938

Processing conditions:  32%|█████████████████████▎                                             | 655/2057 [04:06<06:09,  3.80item/s, Completed 655/2057]

Found 100 matched controls for ENSG00000181938
Getting matched controls for ENSG00000124784

Processing conditions:  32%|█████████████████████▎                                             | 656/2057 [04:06<08:19,  2.80item/s, Completed 656/2057]

Found 326 matched controls for ENSG00000124784
Getting matched controls for ENSG00000076924

Processing conditions:  32%|█████████████████████▍                                             | 658/2057 [04:07<06:54,  3.38item/s, Completed 658/2057]

Found 153 matched controls for ENSG00000076924
Getting matched controls for ENSG00000117395
Found 82 matched controls for ENSG00000117395
Getting matched controls for ENSG00000067596

Processing conditions:  32%|█████████████████████▍                                             | 659/2057 [04:07<06:37,  3.52item/s, Completed 660/2057]

Found 115 matched controls for ENSG00000067596
Getting matched controls for ENSG00000141556
Found 28 matched controls for ENSG00000141556
Getting matched controls for ENSG00000120705

Processing conditions:  32%|█████████████████████▌                                             | 661/2057 [04:07<04:48,  4.84item/s, Completed 661/2057]

Found 52 matched controls for ENSG00000120705
Getting matched controls for ENSG00000174444

Processing conditions:  32%|█████████████████████▌                                             | 662/2057 [04:08<07:16,  3.20item/s, Completed 662/2057]

Found 345 matched controls for ENSG00000174444
Getting matched controls for ENSG00000136720

Processing conditions:  32%|█████████████████████▌                                             | 663/2057 [04:08<07:24,  3.13item/s, Completed 663/2057]

Found 172 matched controls for ENSG00000136720
Getting matched controls for ENSG00000085840

Processing conditions:  32%|█████████████████████▋                                             | 664/2057 [04:09<11:16,  2.06item/s, Completed 664/2057]

Found 530 matched controls for ENSG00000085840
Getting matched controls for ENSG00000132507

Processing conditions:  32%|█████████████████████▋                                             | 665/2057 [04:09<09:50,  2.36item/s, Completed 665/2057]

Found 140 matched controls for ENSG00000132507
Getting matched controls for ENSG00000087365

Processing conditions:  32%|█████████████████████▋                                             | 666/2057 [04:10<12:30,  1.85item/s, Completed 666/2057]

Found 500 matched controls for ENSG00000087365
Getting matched controls for ENSG00000173113

Processing conditions:  32%|█████████████████████▋                                             | 667/2057 [04:10<11:17,  2.05item/s, Completed 667/2057]

Found 201 matched controls for ENSG00000173113
Getting matched controls for ENSG00000258366

Processing conditions:  32%|█████████████████████▊                                             | 668/2057 [04:11<09:46,  2.37item/s, Completed 668/2057]

Found 140 matched controls for ENSG00000258366
Getting matched controls for ENSG00000140553

Processing conditions:  33%|█████████████████████▊                                             | 669/2057 [04:11<09:06,  2.54item/s, Completed 669/2057]

Found 178 matched controls for ENSG00000140553
Getting matched controls for ENSG00000187583

Processing conditions:  33%|█████████████████████▊                                             | 670/2057 [04:11<07:50,  2.95item/s, Completed 670/2057]

Found 104 matched controls for ENSG00000187583
Getting matched controls for ENSG00000164880

Processing conditions:  33%|█████████████████████▊                                             | 671/2057 [04:12<08:04,  2.86item/s, Completed 671/2057]

Found 211 matched controls for ENSG00000164880
Getting matched controls for ENSG00000187801

Processing conditions:  33%|█████████████████████▉                                             | 672/2057 [04:12<07:36,  3.04item/s, Completed 672/2057]

Found 151 matched controls for ENSG00000187801
Getting matched controls for ENSG00000130772

Processing conditions:  33%|█████████████████████▉                                             | 673/2057 [04:12<06:44,  3.42item/s, Completed 673/2057]

Found 20 matched controls for ENSG00000130772
Getting matched controls for ENSG00000175110

Processing conditions:  33%|█████████████████████▉                                             | 675/2057 [04:13<05:48,  3.97item/s, Completed 675/2057]

Found 165 matched controls for ENSG00000175110
Getting matched controls for ENSG00000169251
Found 64 matched controls for ENSG00000169251
Getting matched controls for ENSG00000131153

Processing conditions:  33%|██████████████████████                                             | 676/2057 [04:13<05:58,  3.85item/s, Completed 676/2057]

Found 148 matched controls for ENSG00000131153
Getting matched controls for ENSG00000130803

Processing conditions:  33%|██████████████████████                                             | 677/2057 [04:13<05:56,  3.87item/s, Completed 677/2057]

Found 132 matched controls for ENSG00000130803
Getting matched controls for ENSG00000124608

Processing conditions:  33%|██████████████████████                                             | 678/2057 [04:13<06:29,  3.54item/s, Completed 678/2057]

Found 181 matched controls for ENSG00000124608
Getting matched controls for ENSG00000115540

Processing conditions:  33%|██████████████████████                                             | 679/2057 [04:14<06:10,  3.72item/s, Completed 679/2057]

Found 118 matched controls for ENSG00000115540
Getting matched controls for ENSG00000126756

Processing conditions:  33%|██████████████████████▏                                            | 680/2057 [04:14<07:11,  3.19item/s, Completed 680/2057]

Found 215 matched controls for ENSG00000126756
Getting matched controls for ENSG00000243725

Processing conditions:  33%|██████████████████████▏                                            | 682/2057 [04:14<05:47,  3.96item/s, Completed 682/2057]

Found 108 matched controls for ENSG00000243725
Getting matched controls for ENSG00000135913
Found 77 matched controls for ENSG00000135913
Getting matched controls for ENSG00000113812

Processing conditions:  33%|██████████████████████▏                                            | 683/2057 [04:15<07:11,  3.18item/s, Completed 683/2057]

Found 252 matched controls for ENSG00000113812
Getting matched controls for ENSG00000130713

Processing conditions:  33%|██████████████████████▎                                            | 684/2057 [04:15<07:55,  2.89item/s, Completed 684/2057]

Found 226 matched controls for ENSG00000130713
Getting matched controls for ENSG00000038358

Processing conditions:  33%|██████████████████████▎                                            | 685/2057 [04:16<07:40,  2.98item/s, Completed 685/2057]

Found 166 matched controls for ENSG00000038358
Getting matched controls for ENSG00000183527

Processing conditions:  33%|██████████████████████▎                                            | 686/2057 [04:16<06:52,  3.32item/s, Completed 686/2057]

Found 109 matched controls for ENSG00000183527
Getting matched controls for ENSG00000122140

Processing conditions:  33%|██████████████████████▍                                            | 687/2057 [04:16<06:19,  3.61item/s, Completed 687/2057]

Found 109 matched controls for ENSG00000122140
Getting matched controls for ENSG00000135476

Processing conditions:  33%|██████████████████████▍                                            | 688/2057 [04:16<06:02,  3.78item/s, Completed 688/2057]

Found 120 matched controls for ENSG00000135476
Getting matched controls for ENSG00000162004

Processing conditions:  33%|██████████████████████▍                                            | 689/2057 [04:17<06:03,  3.76item/s, Completed 689/2057]

Found 142 matched controls for ENSG00000162004
Getting matched controls for ENSG00000243147

Processing conditions:  34%|██████████████████████▌                                            | 691/2057 [04:17<05:42,  3.99item/s, Completed 691/2057]

Found 150 matched controls for ENSG00000243147
Getting matched controls for ENSG00000205212
Found 87 matched controls for ENSG00000205212
Getting matched controls for ENSG00000197020

Processing conditions:  34%|██████████████████████▌                                            | 692/2057 [04:17<05:30,  4.13item/s, Completed 692/2057]

Found 95 matched controls for ENSG00000197020
Getting matched controls for ENSG00000027001

Processing conditions:  34%|██████████████████████▌                                            | 693/2057 [04:18<05:21,  4.24item/s, Completed 693/2057]

Found 90 matched controls for ENSG00000027001
Getting matched controls for ENSG00000048544

Processing conditions:  34%|██████████████████████▌                                            | 694/2057 [04:18<05:22,  4.22item/s, Completed 694/2057]

Found 121 matched controls for ENSG00000048544
Getting matched controls for ENSG00000213397

Processing conditions:  34%|██████████████████████▋                                            | 696/2057 [04:18<06:02,  3.76item/s, Completed 696/2057]

Found 239 matched controls for ENSG00000213397
Getting matched controls for ENSG00000143374
Found 74 matched controls for ENSG00000143374
Getting matched controls for ENSG00000189366

Processing conditions:  34%|██████████████████████▋                                            | 697/2057 [04:19<06:48,  3.33item/s, Completed 697/2057]

Found 216 matched controls for ENSG00000189366
Getting matched controls for ENSG00000196834

Processing conditions:  34%|██████████████████████▋                                            | 698/2057 [04:19<06:25,  3.53item/s, Completed 698/2057]

Found 126 matched controls for ENSG00000196834
Getting matched controls for ENSG00000101901

Processing conditions:  34%|██████████████████████▊                                            | 699/2057 [04:19<06:37,  3.42item/s, Completed 699/2057]

Found 170 matched controls for ENSG00000101901
Getting matched controls for ENSG00000119203

Processing conditions:  34%|██████████████████████▊                                            | 700/2057 [04:20<11:47,  1.92item/s, Completed 700/2057]

Found 627 matched controls for ENSG00000119203
Getting matched controls for ENSG00000126226

Processing conditions:  34%|██████████████████████▊                                            | 701/2057 [04:21<11:57,  1.89item/s, Completed 701/2057]

Found 307 matched controls for ENSG00000126226
Getting matched controls for ENSG00000087157

Processing conditions:  34%|██████████████████████▊                                            | 702/2057 [04:21<09:57,  2.27item/s, Completed 702/2057]

Found 104 matched controls for ENSG00000087157
Getting matched controls for ENSG00000178105

Processing conditions:  34%|██████████████████████▉                                            | 703/2057 [04:21<08:31,  2.65item/s, Completed 703/2057]

Found 104 matched controls for ENSG00000178105
Getting matched controls for ENSG00000275700

Processing conditions:  34%|██████████████████████▉                                            | 704/2057 [04:22<09:28,  2.38item/s, Completed 704/2057]

Found 298 matched controls for ENSG00000275700
Getting matched controls for ENSG00000126088

Processing conditions:  34%|██████████████████████▉                                            | 705/2057 [04:22<09:03,  2.49item/s, Completed 705/2057]

Found 201 matched controls for ENSG00000126088
Getting matched controls for ENSG00000163161

Processing conditions:  34%|██████████████████████▉                                            | 706/2057 [04:23<08:30,  2.65item/s, Completed 706/2057]

Found 163 matched controls for ENSG00000163161
Getting matched controls for ENSG00000090061

Processing conditions:  34%|███████████████████████                                            | 708/2057 [04:23<07:57,  2.83item/s, Completed 708/2057]

Found 327 matched controls for ENSG00000090061
Getting matched controls for ENSG00000126254
Found 79 matched controls for ENSG00000126254
Getting matched controls for ENSG00000273559

Processing conditions:  34%|███████████████████████                                            | 709/2057 [04:24<07:26,  3.02item/s, Completed 709/2057]

Found 149 matched controls for ENSG00000273559
Getting matched controls for ENSG00000168438

Processing conditions:  35%|███████████████████████▏                                           | 710/2057 [04:24<06:39,  3.37item/s, Completed 710/2057]

Found 107 matched controls for ENSG00000168438
Getting matched controls for ENSG00000068654

Processing conditions:  35%|███████████████████████▏                                           | 711/2057 [04:24<06:18,  3.56item/s, Completed 711/2057]

Found 127 matched controls for ENSG00000068654
Getting matched controls for ENSG00000092148

Processing conditions:  35%|███████████████████████▏                                           | 712/2057 [04:24<06:13,  3.60item/s, Completed 712/2057]

Found 130 matched controls for ENSG00000092148
Getting matched controls for ENSG00000112658

Processing conditions:  35%|███████████████████████▏                                           | 713/2057 [04:25<05:57,  3.76item/s, Completed 713/2057]

Found 123 matched controls for ENSG00000112658
Getting matched controls for ENSG00000165006

Processing conditions:  35%|███████████████████████▎                                           | 714/2057 [04:25<05:35,  4.01item/s, Completed 714/2057]

Found 104 matched controls for ENSG00000165006
Getting matched controls for ENSG00000198900

Processing conditions:  35%|███████████████████████▎                                           | 715/2057 [04:25<05:31,  4.05item/s, Completed 715/2057]

Found 123 matched controls for ENSG00000198900
Getting matched controls for ENSG00000010072

Processing conditions:  35%|███████████████████████▎                                           | 716/2057 [04:25<05:49,  3.83item/s, Completed 716/2057]

Found 139 matched controls for ENSG00000010072
Getting matched controls for ENSG00000198242

Processing conditions:  35%|███████████████████████▍                                           | 718/2057 [04:26<04:58,  4.49item/s, Completed 718/2057]

Found 99 matched controls for ENSG00000198242
Getting matched controls for ENSG00000204619
Found 77 matched controls for ENSG00000204619
Getting matched controls for ENSG00000105258

Processing conditions:  35%|███████████████████████▍                                           | 719/2057 [04:26<06:07,  3.64item/s, Completed 720/2057]

Found 223 matched controls for ENSG00000105258
Getting matched controls for ENSG00000120837
Found 28 matched controls for ENSG00000120837
Getting matched controls for ENSG00000197498

Processing conditions:  35%|███████████████████████▍                                           | 721/2057 [04:26<04:37,  4.81item/s, Completed 721/2057]

Found 68 matched controls for ENSG00000197498
Getting matched controls for ENSG00000134419

Processing conditions:  35%|███████████████████████▌                                           | 722/2057 [04:27<06:39,  3.34item/s, Completed 722/2057]

Found 314 matched controls for ENSG00000134419
Getting matched controls for ENSG00000189091

Processing conditions:  35%|███████████████████████▌                                           | 723/2057 [04:28<08:55,  2.49item/s, Completed 723/2057]

Found 381 matched controls for ENSG00000189091
Getting matched controls for ENSG00000136824

Processing conditions:  35%|███████████████████████▌                                           | 725/2057 [04:28<07:00,  3.16item/s, Completed 725/2057]

Found 134 matched controls for ENSG00000136824
Getting matched controls for ENSG00000136997
Found 74 matched controls for ENSG00000136997
Getting matched controls for ENSG00000148396

Processing conditions:  35%|███████████████████████▋                                           | 726/2057 [04:28<06:50,  3.25item/s, Completed 726/2057]

Found 153 matched controls for ENSG00000148396
Getting matched controls for ENSG00000132432
Found 98 matched controls for ENSG00000132432

Processing conditions:  35%|███████████████████████▋                                           | 727/2057 [04:29<06:08,  3.61item/s, Completed 727/2057]

Getting matched controls for ENSG00000073536

Processing conditions:  35%|███████████████████████▋                                           | 728/2057 [04:29<09:19,  2.37item/s, Completed 728/2057]

Found 413 matched controls for ENSG00000073536
Getting matched controls for ENSG00000174953

Processing conditions:  35%|███████████████████████▊                                           | 730/2057 [04:30<07:55,  2.79item/s, Completed 730/2057]

Found 269 matched controls for ENSG00000174953
Getting matched controls for ENSG00000167842
Found 82 matched controls for ENSG00000167842
Getting matched controls for ENSG00000233822

Processing conditions:  36%|███████████████████████▊                                           | 731/2057 [04:30<07:05,  3.12item/s, Completed 731/2057]

Found 107 matched controls for ENSG00000233822
Getting matched controls for ENSG00000083896

Processing conditions:  36%|███████████████████████▉                                           | 733/2057 [04:31<06:45,  3.27item/s, Completed 733/2057]

Found 237 matched controls for ENSG00000083896
Getting matched controls for ENSG00000247626
Found 75 matched controls for ENSG00000247626
Getting matched controls for ENSG00000069764

Processing conditions:  36%|███████████████████████▉                                           | 734/2057 [04:31<07:14,  3.05item/s, Completed 734/2057]

Found 202 matched controls for ENSG00000069764
Getting matched controls for ENSG00000196655

Processing conditions:  36%|███████████████████████▉                                           | 735/2057 [04:32<07:48,  2.82item/s, Completed 735/2057]

Found 196 matched controls for ENSG00000196655
Getting matched controls for ENSG00000100603

Processing conditions:  36%|███████████████████████▉                                           | 736/2057 [04:32<08:06,  2.72item/s, Completed 736/2057]

Found 226 matched controls for ENSG00000100603
Getting matched controls for ENSG00000125450

Processing conditions:  36%|████████████████████████                                           | 737/2057 [04:32<07:07,  3.09item/s, Completed 737/2057]

Found 111 matched controls for ENSG00000125450
Getting matched controls for ENSG00000183617

Processing conditions:  36%|████████████████████████                                           | 738/2057 [04:33<06:51,  3.20item/s, Completed 738/2057]

Found 142 matched controls for ENSG00000183617
Getting matched controls for ENSG00000198554

Processing conditions:  36%|████████████████████████                                           | 739/2057 [04:33<07:15,  3.03item/s, Completed 739/2057]

Found 182 matched controls for ENSG00000198554
Getting matched controls for ENSG00000006712

Processing conditions:  36%|████████████████████████▏                                          | 741/2057 [04:34<06:43,  3.26item/s, Completed 741/2057]

Found 238 matched controls for ENSG00000006712
Getting matched controls for ENSG00000140943
Found 68 matched controls for ENSG00000140943
Getting matched controls for ENSG00000090054

Processing conditions:  36%|████████████████████████▏                                          | 741/2057 [04:34<06:43,  3.26item/s, Completed 742/2057]

Found 28 matched controls for ENSG00000090054
Getting matched controls for ENSG00000046647

Processing conditions:  36%|████████████████████████▏                                          | 743/2057 [04:34<05:13,  4.19item/s, Completed 743/2057]

Found 86 matched controls for ENSG00000046647
Getting matched controls for ENSG00000187555

Processing conditions:  36%|████████████████████████▏                                          | 744/2057 [04:34<06:35,  3.32item/s, Completed 744/2057]

Found 276 matched controls for ENSG00000187555
Getting matched controls for ENSG00000197170

Processing conditions:  36%|████████████████████████▎                                          | 745/2057 [04:35<07:29,  2.92item/s, Completed 745/2057]

Found 265 matched controls for ENSG00000197170
Getting matched controls for ENSG00000110536

Processing conditions:  36%|████████████████████████▎                                          | 746/2057 [04:35<07:24,  2.95item/s, Completed 746/2057]

Found 183 matched controls for ENSG00000110536
Getting matched controls for ENSG00000099821

Processing conditions:  36%|████████████████████████▎                                          | 747/2057 [04:36<07:46,  2.81item/s, Completed 747/2057]

Found 214 matched controls for ENSG00000099821
Getting matched controls for ENSG00000137692

Processing conditions:  36%|████████████████████████▎                                          | 748/2057 [04:36<07:56,  2.75item/s, Completed 748/2057]

Found 183 matched controls for ENSG00000137692
Getting matched controls for ENSG00000163636

Processing conditions:  36%|████████████████████████▍                                          | 750/2057 [04:37<09:24,  2.32item/s, Completed 750/2057]

Found 555 matched controls for ENSG00000163636
Getting matched controls for ENSG00000087586
Found 58 matched controls for ENSG00000087586
Getting matched controls for ENSG00000166136

Processing conditions:  37%|████████████████████████▍                                          | 752/2057 [04:38<06:56,  3.13item/s, Completed 752/2057]

Found 193 matched controls for ENSG00000166136
Getting matched controls for ENSG00000113068
Found 34 matched controls for ENSG00000113068
Getting matched controls for ENSG00000204560

Processing conditions:  37%|████████████████████████▌                                          | 753/2057 [04:38<08:32,  2.55item/s, Completed 753/2057]

Found 328 matched controls for ENSG00000204560
Getting matched controls for ENSG00000168924

Processing conditions:  37%|████████████████████████▌                                          | 754/2057 [04:38<07:35,  2.86item/s, Completed 754/2057]

Found 124 matched controls for ENSG00000168924
Getting matched controls for ENSG00000185158

Processing conditions:  37%|████████████████████████▌                                          | 755/2057 [04:39<06:45,  3.21item/s, Completed 755/2057]

Found 109 matched controls for ENSG00000185158
Getting matched controls for ENSG00000119013

Processing conditions:  37%|████████████████████████▋                                          | 757/2057 [04:39<05:14,  4.13item/s, Completed 757/2057]

Found 141 matched controls for ENSG00000119013
Getting matched controls for ENSG00000277791
Found 31 matched controls for ENSG00000277791
Getting matched controls for ENSG00000100401

Processing conditions:  37%|████████████████████████▋                                          | 758/2057 [04:39<05:28,  3.95item/s, Completed 758/2057]

Found 130 matched controls for ENSG00000100401
Getting matched controls for ENSG00000135763

Processing conditions:  37%|████████████████████████▋                                          | 759/2057 [04:40<06:10,  3.50item/s, Completed 759/2057]

Found 198 matched controls for ENSG00000135763
Getting matched controls for ENSG00000130725

Processing conditions:  37%|████████████████████████▊                                          | 761/2057 [04:40<05:27,  3.96item/s, Completed 761/2057]

Found 177 matched controls for ENSG00000130725
Getting matched controls for ENSG00000146263
Found 57 matched controls for ENSG00000146263
Getting matched controls for ENSG00000261236

Processing conditions:  37%|████████████████████████▊                                          | 762/2057 [04:41<06:43,  3.21item/s, Completed 762/2057]

Found 253 matched controls for ENSG00000261236
Getting matched controls for ENSG00000141367

Processing conditions:  37%|████████████████████████▊                                          | 763/2057 [04:41<06:39,  3.24item/s, Completed 763/2057]

Found 157 matched controls for ENSG00000141367
Getting matched controls for ENSG00000170545

Processing conditions:  37%|████████████████████████▉                                          | 764/2057 [04:41<06:10,  3.49item/s, Completed 764/2057]

Found 117 matched controls for ENSG00000170545
Getting matched controls for ENSG00000136271

Processing conditions:  37%|████████████████████████▉                                          | 765/2057 [04:41<06:26,  3.34item/s, Completed 765/2057]

Found 174 matched controls for ENSG00000136271
Getting matched controls for ENSG00000278845

Processing conditions:  37%|████████████████████████▉                                          | 767/2057 [04:42<05:48,  3.70item/s, Completed 767/2057]

Found 179 matched controls for ENSG00000278845
Getting matched controls for ENSG00000198000
Found 79 matched controls for ENSG00000198000
Getting matched controls for ENSG00000119616

Processing conditions:  37%|█████████████████████████                                          | 768/2057 [04:42<06:42,  3.20item/s, Completed 768/2057]

Found 231 matched controls for ENSG00000119616
Getting matched controls for ENSG00000137411

Processing conditions:  37%|█████████████████████████                                          | 770/2057 [04:43<05:35,  3.83item/s, Completed 770/2057]

Found 126 matched controls for ENSG00000137411
Getting matched controls for ENSG00000130520
Found 84 matched controls for ENSG00000130520
Getting matched controls for ENSG00000102030

Processing conditions:  38%|█████████████████████████▏                                         | 772/2057 [04:43<05:00,  4.28item/s, Completed 772/2057]

Found 137 matched controls for ENSG00000102030
Getting matched controls for ENSG00000189375
Found 78 matched controls for ENSG00000189375
Getting matched controls for ENSG00000089289

Processing conditions:  38%|█████████████████████████▏                                         | 774/2057 [04:44<05:25,  3.94item/s, Completed 774/2057]

Found 281 matched controls for ENSG00000089289
Getting matched controls for ENSG00000124380
Found 47 matched controls for ENSG00000124380
Getting matched controls for ENSG00000100883

Processing conditions:  38%|█████████████████████████▏                                         | 775/2057 [04:44<04:55,  4.33item/s, Completed 775/2057]

Found 81 matched controls for ENSG00000100883
Getting matched controls for ENSG00000241258

Processing conditions:  38%|█████████████████████████▎                                         | 776/2057 [04:44<05:22,  3.97item/s, Completed 776/2057]

Found 160 matched controls for ENSG00000241258
Getting matched controls for ENSG00000187017

Processing conditions:  38%|█████████████████████████▎                                         | 777/2057 [04:45<08:17,  2.57item/s, Completed 777/2057]

Found 421 matched controls for ENSG00000187017
Getting matched controls for ENSG00000122692

Processing conditions:  38%|█████████████████████████▎                                         | 778/2057 [04:45<07:41,  2.77item/s, Completed 778/2057]

Found 155 matched controls for ENSG00000122692
Getting matched controls for ENSG00000074935

Processing conditions:  38%|█████████████████████████▎                                         | 779/2057 [04:46<07:04,  3.01item/s, Completed 779/2057]

Found 134 matched controls for ENSG00000074935
Getting matched controls for ENSG00000285053

Processing conditions:  38%|█████████████████████████▍                                         | 780/2057 [04:46<06:32,  3.25item/s, Completed 780/2057]

Found 129 matched controls for ENSG00000285053
Getting matched controls for ENSG00000149016

Processing conditions:  38%|█████████████████████████▍                                         | 781/2057 [04:46<06:56,  3.07item/s, Completed 781/2057]

Found 208 matched controls for ENSG00000149016
Getting matched controls for ENSG00000168827

Processing conditions:  38%|█████████████████████████▍                                         | 782/2057 [04:47<08:19,  2.55item/s, Completed 782/2057]

Found 240 matched controls for ENSG00000168827
Getting matched controls for ENSG00000138107

Processing conditions:  38%|█████████████████████████▌                                         | 783/2057 [04:47<07:36,  2.79item/s, Completed 783/2057]

Found 143 matched controls for ENSG00000138107
Getting matched controls for ENSG00000205238

Processing conditions:  38%|█████████████████████████▌                                         | 784/2057 [04:47<07:27,  2.85item/s, Completed 784/2057]

Found 182 matched controls for ENSG00000205238
Getting matched controls for ENSG00000145050

Processing conditions:  38%|█████████████████████████▌                                         | 785/2057 [04:48<07:09,  2.96item/s, Completed 785/2057]

Found 142 matched controls for ENSG00000145050
Getting matched controls for ENSG00000103423

Processing conditions:  38%|█████████████████████████▌                                         | 786/2057 [04:48<06:52,  3.08item/s, Completed 786/2057]

Found 127 matched controls for ENSG00000103423
Getting matched controls for ENSG00000075624

Processing conditions:  38%|█████████████████████████▋                                         | 787/2057 [04:48<06:53,  3.07item/s, Completed 787/2057]

Found 168 matched controls for ENSG00000075624
Getting matched controls for ENSG00000161981

Processing conditions:  38%|█████████████████████████▋                                         | 788/2057 [04:48<06:29,  3.26item/s, Completed 788/2057]

Found 135 matched controls for ENSG00000161981
Getting matched controls for ENSG00000113161

Processing conditions:  38%|█████████████████████████▋                                         | 790/2057 [04:49<05:42,  3.70item/s, Completed 790/2057]

Found 166 matched controls for ENSG00000113161
Getting matched controls for ENSG00000117697
Found 72 matched controls for ENSG00000117697
Getting matched controls for ENSG00000213593

Processing conditions:  38%|█████████████████████████▊                                         | 791/2057 [04:49<05:22,  3.92item/s, Completed 791/2057]

Found 109 matched controls for ENSG00000213593
Getting matched controls for ENSG00000213619

Processing conditions:  39%|█████████████████████████▊                                         | 793/2057 [04:50<04:48,  4.38item/s, Completed 793/2057]

Found 112 matched controls for ENSG00000213619
Getting matched controls for ENSG00000137076
Found 87 matched controls for ENSG00000137076
Getting matched controls for ENSG00000099817

Processing conditions:  39%|█████████████████████████▉                                         | 795/2057 [04:50<05:06,  4.12item/s, Completed 795/2057]

Found 225 matched controls for ENSG00000099817
Getting matched controls for ENSG00000070831
Found 70 matched controls for ENSG00000070831
Getting matched controls for ENSG00000197111

Processing conditions:  39%|█████████████████████████▉                                         | 796/2057 [04:51<05:49,  3.61item/s, Completed 796/2057]

Found 172 matched controls for ENSG00000197111
Getting matched controls for ENSG00000100664

Processing conditions:  39%|█████████████████████████▉                                         | 798/2057 [04:51<05:04,  4.14item/s, Completed 798/2057]

Found 175 matched controls for ENSG00000100664
Getting matched controls for ENSG00000127780
Found 32 matched controls for ENSG00000127780
Getting matched controls for ENSG00000221970

Processing conditions:  39%|██████████████████████████                                         | 799/2057 [04:51<05:41,  3.68item/s, Completed 799/2057]

Found 188 matched controls for ENSG00000221970
Getting matched controls for ENSG00000163468

Processing conditions:  39%|██████████████████████████                                         | 800/2057 [04:52<06:33,  3.19item/s, Completed 800/2057]

Found 234 matched controls for ENSG00000163468
Getting matched controls for ENSG00000178913

Processing conditions:  39%|██████████████████████████                                         | 801/2057 [04:52<05:59,  3.49item/s, Completed 801/2057]

Found 94 matched controls for ENSG00000178913
Getting matched controls for ENSG00000143314

Processing conditions:  39%|██████████████████████████                                         | 802/2057 [04:52<06:36,  3.16item/s, Completed 802/2057]

Found 193 matched controls for ENSG00000143314
Getting matched controls for ENSG00000167088

Processing conditions:  39%|██████████████████████████▏                                        | 803/2057 [04:53<06:21,  3.29item/s, Completed 803/2057]

Found 146 matched controls for ENSG00000167088
Getting matched controls for ENSG00000167085

Processing conditions:  39%|██████████████████████████▏                                        | 805/2057 [04:53<06:10,  3.38item/s, Completed 805/2057]

Found 256 matched controls for ENSG00000167085
Getting matched controls for ENSG00000185085
Found 64 matched controls for ENSG00000185085
Getting matched controls for ENSG00000175756

Processing conditions:  39%|██████████████████████████▎                                        | 807/2057 [04:54<05:00,  4.16item/s, Completed 807/2057]

Found 76 matched controls for ENSG00000175756
Getting matched controls for ENSG00000110906
Found 76 matched controls for ENSG00000110906
Getting matched controls for ENSG00000168538

Processing conditions:  39%|██████████████████████████▎                                        | 808/2057 [04:54<05:06,  4.07item/s, Completed 808/2057]

Found 110 matched controls for ENSG00000168538
Getting matched controls for ENSG00000167118

Processing conditions:  39%|██████████████████████████▍                                        | 810/2057 [04:54<04:38,  4.47item/s, Completed 810/2057]

Found 123 matched controls for ENSG00000167118
Getting matched controls for ENSG00000186665
Found 58 matched controls for ENSG00000186665
Getting matched controls for ENSG00000112685

Processing conditions:  39%|██████████████████████████▍                                        | 811/2057 [04:55<04:37,  4.50item/s, Completed 811/2057]

Found 88 matched controls for ENSG00000112685
Getting matched controls for ENSG00000055950

Processing conditions:  39%|██████████████████████████▍                                        | 812/2057 [04:55<04:33,  4.54item/s, Completed 812/2057]

Found 95 matched controls for ENSG00000055950
Getting matched controls for ENSG00000139697

Processing conditions:  40%|██████████████████████████▍                                        | 813/2057 [04:55<05:15,  3.94item/s, Completed 813/2057]

Found 183 matched controls for ENSG00000139697
Getting matched controls for ENSG00000249915

Processing conditions:  40%|██████████████████████████▌                                        | 815/2057 [04:56<05:11,  3.99item/s, Completed 815/2057]

Found 203 matched controls for ENSG00000249915
Getting matched controls for ENSG00000126457
Found 58 matched controls for ENSG00000126457
Getting matched controls for ENSG00000106153

Processing conditions:  40%|██████████████████████████▌                                        | 816/2057 [04:56<05:00,  4.13item/s, Completed 816/2057]

Found 90 matched controls for ENSG00000106153
Getting matched controls for ENSG00000153814

Processing conditions:  40%|██████████████████████████▋                                        | 818/2057 [04:56<04:52,  4.23item/s, Completed 818/2057]

Found 209 matched controls for ENSG00000153814
Getting matched controls for ENSG00000131236
Found 26 matched controls for ENSG00000131236
Getting matched controls for ENSG00000185721

Processing conditions:  40%|██████████████████████████▋                                        | 819/2057 [04:57<05:48,  3.55item/s, Completed 819/2057]

Found 196 matched controls for ENSG00000185721
Getting matched controls for ENSG00000242028

Processing conditions:  40%|██████████████████████████▋                                        | 820/2057 [04:57<05:39,  3.64item/s, Completed 820/2057]

Found 121 matched controls for ENSG00000242028
Getting matched controls for ENSG00000180992

Processing conditions:  40%|██████████████████████████▋                                        | 821/2057 [04:57<06:15,  3.29item/s, Completed 821/2057]

Found 211 matched controls for ENSG00000180992
Getting matched controls for ENSG00000131100

Processing conditions:  40%|██████████████████████████▊                                        | 822/2057 [04:58<06:28,  3.18item/s, Completed 822/2057]

Found 188 matched controls for ENSG00000131100
Getting matched controls for ENSG00000259224

Processing conditions:  40%|██████████████████████████▊                                        | 823/2057 [04:58<06:30,  3.16item/s, Completed 823/2057]

Found 163 matched controls for ENSG00000259224
Getting matched controls for ENSG00000143384

Processing conditions:  40%|██████████████████████████▊                                        | 824/2057 [04:58<05:50,  3.52item/s, Completed 824/2057]

Found 86 matched controls for ENSG00000143384
Getting matched controls for ENSG00000005194

Processing conditions:  40%|██████████████████████████▊                                        | 825/2057 [04:59<06:12,  3.31item/s, Completed 825/2057]

Found 151 matched controls for ENSG00000005194
Getting matched controls for ENSG00000112096

Processing conditions:  40%|██████████████████████████▉                                        | 826/2057 [04:59<06:32,  3.14item/s, Completed 826/2057]

Found 198 matched controls for ENSG00000112096
Getting matched controls for ENSG00000183684

Processing conditions:  40%|██████████████████████████▉                                        | 828/2057 [05:00<06:26,  3.18item/s, Completed 828/2057]

Found 319 matched controls for ENSG00000183684
Getting matched controls for ENSG00000127980
Found 53 matched controls for ENSG00000127980
Getting matched controls for ENSG00000250067

Processing conditions:  40%|███████████████████████████                                        | 829/2057 [05:00<06:37,  3.09item/s, Completed 829/2057]

Found 179 matched controls for ENSG00000250067
Getting matched controls for ENSG00000148297

Processing conditions:  40%|███████████████████████████                                        | 830/2057 [05:01<07:55,  2.58item/s, Completed 830/2057]

Found 289 matched controls for ENSG00000148297
Getting matched controls for ENSG00000168876

Processing conditions:  40%|███████████████████████████                                        | 831/2057 [05:01<07:14,  2.82item/s, Completed 831/2057]

Found 144 matched controls for ENSG00000168876
Getting matched controls for ENSG00000189403

Processing conditions:  40%|███████████████████████████                                        | 832/2057 [05:01<07:38,  2.67item/s, Completed 832/2057]

Found 241 matched controls for ENSG00000189403
Getting matched controls for ENSG00000133119

Processing conditions:  41%|███████████████████████████▏                                       | 834/2057 [05:02<06:40,  3.06item/s, Completed 834/2057]

Found 229 matched controls for ENSG00000133119
Getting matched controls for ENSG00000097046
Found 95 matched controls for ENSG00000097046
Getting matched controls for ENSG00000169136

Processing conditions:  41%|███████████████████████████▏                                       | 835/2057 [05:02<06:18,  3.23item/s, Completed 835/2057]

Found 141 matched controls for ENSG00000169136
Getting matched controls for ENSG00000100697

Processing conditions:  41%|███████████████████████████▎                                       | 837/2057 [05:03<05:31,  3.68item/s, Completed 837/2057]

Found 158 matched controls for ENSG00000100697
Getting matched controls for ENSG00000130724
Found 93 matched controls for ENSG00000130724
Getting matched controls for ENSG00000125901

Processing conditions:  41%|███████████████████████████▎                                       | 838/2057 [05:03<05:17,  3.84item/s, Completed 838/2057]

Found 120 matched controls for ENSG00000125901
Getting matched controls for ENSG00000180198

Processing conditions:  41%|███████████████████████████▎                                       | 840/2057 [05:03<05:11,  3.91item/s, Completed 840/2057]

Found 226 matched controls for ENSG00000180198
Getting matched controls for ENSG00000146670
Found 61 matched controls for ENSG00000146670
Getting matched controls for ENSG00000137309

Processing conditions:  41%|███████████████████████████▍                                       | 841/2057 [05:04<05:00,  4.05item/s, Completed 841/2057]

Found 114 matched controls for ENSG00000137309
Getting matched controls for ENSG00000108518

Processing conditions:  41%|███████████████████████████▍                                       | 842/2057 [05:04<06:13,  3.25item/s, Completed 842/2057]

Found 259 matched controls for ENSG00000108518
Getting matched controls for ENSG00000139350

Processing conditions:  41%|███████████████████████████▍                                       | 843/2057 [05:04<05:59,  3.38item/s, Completed 843/2057]

Found 142 matched controls for ENSG00000139350
Getting matched controls for ENSG00000185130

Processing conditions:  41%|███████████████████████████▍                                       | 844/2057 [05:05<06:23,  3.17item/s, Completed 844/2057]

Found 204 matched controls for ENSG00000185130
Getting matched controls for ENSG00000168090

Processing conditions:  41%|███████████████████████████▌                                       | 845/2057 [05:05<06:56,  2.91item/s, Completed 845/2057]

Found 235 matched controls for ENSG00000168090
Getting matched controls for ENSG00000179918

Processing conditions:  41%|███████████████████████████▌                                       | 846/2057 [05:05<06:39,  3.03item/s, Completed 846/2057]

Found 158 matched controls for ENSG00000179918
Getting matched controls for ENSG00000132912

Processing conditions:  41%|███████████████████████████▌                                       | 847/2057 [05:06<06:02,  3.33item/s, Completed 847/2057]

Found 77 matched controls for ENSG00000132912
Getting matched controls for ENSG00000127184

Processing conditions:  41%|███████████████████████████▌                                       | 848/2057 [05:06<06:04,  3.31item/s, Completed 848/2057]

Found 165 matched controls for ENSG00000127184
Getting matched controls for ENSG00000108654

Processing conditions:  41%|███████████████████████████▋                                       | 850/2057 [05:06<05:06,  3.94item/s, Completed 850/2057]

Found 151 matched controls for ENSG00000108654
Getting matched controls for ENSG00000113272
Found 43 matched controls for ENSG00000113272
Getting matched controls for ENSG00000099800

Processing conditions:  41%|███████████████████████████▋                                       | 851/2057 [05:07<05:33,  3.62item/s, Completed 851/2057]

Found 178 matched controls for ENSG00000099800
Getting matched controls for ENSG00000179091

Processing conditions:  41%|███████████████████████████▊                                       | 853/2057 [05:07<04:54,  4.09item/s, Completed 853/2057]

Found 98 matched controls for ENSG00000179091
Getting matched controls for ENSG00000243667
Found 66 matched controls for ENSG00000243667
Getting matched controls for ENSG00000157778

Processing conditions:  42%|███████████████████████████▊                                       | 855/2057 [05:08<06:28,  3.09item/s, Completed 855/2057]

Found 439 matched controls for ENSG00000157778
Getting matched controls for ENSG00000179041
Found 72 matched controls for ENSG00000179041
Getting matched controls for ENSG00000128789

Processing conditions:  42%|███████████████████████████▉                                       | 857/2057 [05:09<05:33,  3.60item/s, Completed 857/2057]

Found 164 matched controls for ENSG00000128789
Getting matched controls for ENSG00000132604
Found 50 matched controls for ENSG00000132604
Getting matched controls for ENSG00000100462

Processing conditions:  42%|███████████████████████████▉                                       | 858/2057 [05:09<05:28,  3.65item/s, Completed 858/2057]

Found 127 matched controls for ENSG00000100462
Getting matched controls for ENSG00000184983

Processing conditions:  42%|███████████████████████████▉                                       | 859/2057 [05:09<05:41,  3.51item/s, Completed 859/2057]

Found 169 matched controls for ENSG00000184983
Getting matched controls for ENSG00000137574

Processing conditions:  42%|████████████████████████████                                       | 860/2057 [05:10<06:00,  3.32item/s, Completed 861/2057]

Found 161 matched controls for ENSG00000137574
Getting matched controls for ENSG00000172315
Found 88 matched controls for ENSG00000172315

Processing conditions:  42%|████████████████████████████                                       | 861/2057 [05:10<05:24,  3.69item/s, Completed 861/2057]

Getting matched controls for ENSG00000165526

Processing conditions:  42%|████████████████████████████                                       | 862/2057 [05:10<05:20,  3.73item/s, Completed 862/2057]

Found 126 matched controls for ENSG00000165526
Getting matched controls for ENSG00000171763

Processing conditions:  42%|████████████████████████████                                       | 863/2057 [05:10<05:24,  3.67item/s, Completed 863/2057]

Found 150 matched controls for ENSG00000171763
Getting matched controls for ENSG00000135334

Processing conditions:  42%|████████████████████████████▏                                      | 865/2057 [05:11<05:08,  3.87item/s, Completed 865/2057]

Found 169 matched controls for ENSG00000135334
Getting matched controls for ENSG00000082515
Found 96 matched controls for ENSG00000082515
Getting matched controls for ENSG00000134001

Processing conditions:  42%|████████████████████████████▏                                      | 866/2057 [05:11<06:08,  3.24item/s, Completed 866/2057]

Found 243 matched controls for ENSG00000134001
Getting matched controls for ENSG00000167658

Processing conditions:  42%|████████████████████████████▏                                      | 867/2057 [05:12<07:33,  2.62item/s, Completed 868/2057]

Found 321 matched controls for ENSG00000167658
Getting matched controls for ENSG00000020426
Found 85 matched controls for ENSG00000020426

Processing conditions:  42%|████████████████████████████▎                                      | 869/2057 [05:12<05:55,  3.34item/s, Completed 869/2057]

Getting matched controls for ENSG00000133706
Found 100 matched controls for ENSG00000133706
Getting matched controls for ENSG00000055130

Processing conditions:  42%|████████████████████████████▎                                      | 870/2057 [05:13<06:28,  3.06item/s, Completed 870/2057]

Found 223 matched controls for ENSG00000055130
Getting matched controls for ENSG00000048707

Processing conditions:  42%|████████████████████████████▎                                      | 871/2057 [05:13<06:21,  3.11item/s, Completed 871/2057]

Found 140 matched controls for ENSG00000048707
Getting matched controls for ENSG00000169016

Processing conditions:  42%|████████████████████████████▍                                      | 872/2057 [05:13<06:14,  3.17item/s, Completed 872/2057]

Found 150 matched controls for ENSG00000169016
Getting matched controls for ENSG00000178896

Processing conditions:  42%|████████████████████████████▍                                      | 873/2057 [05:13<05:46,  3.42item/s, Completed 873/2057]

Found 102 matched controls for ENSG00000178896
Getting matched controls for ENSG00000173540

Processing conditions:  42%|████████████████████████████▍                                      | 874/2057 [05:14<06:00,  3.28item/s, Completed 874/2057]

Found 164 matched controls for ENSG00000173540
Getting matched controls for ENSG00000160214

Processing conditions:  43%|████████████████████████████▌                                      | 875/2057 [05:14<05:36,  3.51item/s, Completed 875/2057]

Found 109 matched controls for ENSG00000160214
Getting matched controls for ENSG00000102738

Processing conditions:  43%|████████████████████████████▌                                      | 876/2057 [05:14<05:16,  3.73item/s, Completed 876/2057]

Found 107 matched controls for ENSG00000102738
Getting matched controls for ENSG00000058600

Processing conditions:  43%|████████████████████████████▌                                      | 878/2057 [05:15<05:02,  3.89item/s, Completed 878/2057]

Found 221 matched controls for ENSG00000058600
Getting matched controls for ENSG00000129347
Found 52 matched controls for ENSG00000129347
Getting matched controls for ENSG00000155827

Processing conditions:  43%|████████████████████████████▋                                      | 879/2057 [05:15<05:02,  3.89item/s, Completed 879/2057]

Found 124 matched controls for ENSG00000155827
Getting matched controls for ENSG00000198026

Processing conditions:  43%|████████████████████████████▋                                      | 881/2057 [05:15<04:52,  4.03item/s, Completed 881/2057]

Found 146 matched controls for ENSG00000198026
Getting matched controls for ENSG00000173145
Found 83 matched controls for ENSG00000173145
Getting matched controls for ENSG00000111231

Processing conditions:  43%|████████████████████████████▊                                      | 883/2057 [05:16<05:05,  3.84item/s, Completed 883/2057]

Found 276 matched controls for ENSG00000111231
Getting matched controls for ENSG00000058804
Found 39 matched controls for ENSG00000058804
Getting matched controls for ENSG00000088325

Processing conditions:  43%|████████████████████████████▊                                      | 884/2057 [05:17<07:21,  2.65item/s, Completed 884/2057]

Found 361 matched controls for ENSG00000088325
Getting matched controls for ENSG00000073969

Processing conditions:  43%|████████████████████████████▊                                      | 885/2057 [05:17<07:13,  2.71item/s, Completed 885/2057]

Found 165 matched controls for ENSG00000073969
Getting matched controls for ENSG00000213024

Processing conditions:  43%|████████████████████████████▊                                      | 886/2057 [05:17<06:22,  3.06item/s, Completed 886/2057]

Found 99 matched controls for ENSG00000213024
Getting matched controls for ENSG00000142541

Processing conditions:  43%|████████████████████████████▉                                      | 887/2057 [05:18<06:09,  3.17item/s, Completed 887/2057]

Found 158 matched controls for ENSG00000142541
Getting matched controls for ENSG00000174446

Processing conditions:  43%|████████████████████████████▉                                      | 888/2057 [05:18<05:35,  3.48item/s, Completed 888/2057]

Found 102 matched controls for ENSG00000174446
Getting matched controls for ENSG00000172530

Processing conditions:  43%|████████████████████████████▉                                      | 889/2057 [05:18<05:26,  3.57item/s, Completed 889/2057]

Found 110 matched controls for ENSG00000172530
Getting matched controls for ENSG00000127837

Processing conditions:  43%|████████████████████████████▉                                      | 890/2057 [05:18<05:13,  3.73item/s, Completed 890/2057]

Found 99 matched controls for ENSG00000127837
Getting matched controls for ENSG00000068394

Processing conditions:  43%|█████████████████████████████                                      | 891/2057 [05:19<04:54,  3.96item/s, Completed 891/2057]

Found 107 matched controls for ENSG00000068394
Getting matched controls for ENSG00000115561

Processing conditions:  43%|█████████████████████████████                                      | 892/2057 [05:19<05:02,  3.85item/s, Completed 892/2057]

Found 130 matched controls for ENSG00000115561
Getting matched controls for ENSG00000111667

Processing conditions:  43%|█████████████████████████████                                      | 893/2057 [05:19<05:37,  3.45item/s, Completed 893/2057]

Found 199 matched controls for ENSG00000111667
Getting matched controls for ENSG00000100142

Processing conditions:  43%|█████████████████████████████                                      | 894/2057 [05:20<07:13,  2.68item/s, Completed 894/2057]

Found 337 matched controls for ENSG00000100142
Getting matched controls for ENSG00000135336

Processing conditions:  44%|█████████████████████████████▏                                     | 895/2057 [05:20<06:59,  2.77item/s, Completed 895/2057]

Found 181 matched controls for ENSG00000135336
Getting matched controls for ENSG00000140830

Processing conditions:  44%|█████████████████████████████▏                                     | 896/2057 [05:20<06:36,  2.93item/s, Completed 896/2057]

Found 135 matched controls for ENSG00000140830
Getting matched controls for ENSG00000172531

Processing conditions:  44%|█████████████████████████████▏                                     | 897/2057 [05:21<07:09,  2.70item/s, Completed 897/2057]

Found 248 matched controls for ENSG00000172531
Getting matched controls for ENSG00000203814

Processing conditions:  44%|█████████████████████████████▎                                     | 899/2057 [05:21<05:15,  3.67item/s, Completed 899/2057]

Found 127 matched controls for ENSG00000203814
Getting matched controls for ENSG00000120071
Found 51 matched controls for ENSG00000120071
Getting matched controls for ENSG00000167005

Processing conditions:  44%|█████████████████████████████▎                                     | 900/2057 [05:21<04:58,  3.87item/s, Completed 900/2057]

Found 67 matched controls for ENSG00000167005
Getting matched controls for ENSG00000076003

Processing conditions:  44%|█████████████████████████████▎                                     | 901/2057 [05:22<04:41,  4.11item/s, Completed 901/2057]

Found 102 matched controls for ENSG00000076003
Getting matched controls for ENSG00000108826

Processing conditions:  44%|█████████████████████████████▍                                     | 902/2057 [05:22<04:44,  4.07item/s, Completed 902/2057]

Found 102 matched controls for ENSG00000108826
Getting matched controls for ENSG00000115507

Processing conditions:  44%|█████████████████████████████▍                                     | 903/2057 [05:22<04:33,  4.22item/s, Completed 903/2057]

Found 108 matched controls for ENSG00000115507
Getting matched controls for ENSG00000055483

Processing conditions:  44%|█████████████████████████████▍                                     | 904/2057 [05:22<05:06,  3.76item/s, Completed 904/2057]

Found 174 matched controls for ENSG00000055483
Getting matched controls for ENSG00000134440

Processing conditions:  44%|█████████████████████████████▍                                     | 905/2057 [05:23<05:31,  3.47item/s, Completed 905/2057]

Found 172 matched controls for ENSG00000134440
Getting matched controls for ENSG00000011304

Processing conditions:  44%|█████████████████████████████▌                                     | 906/2057 [05:23<05:29,  3.49item/s, Completed 906/2057]

Found 152 matched controls for ENSG00000011304
Getting matched controls for ENSG00000108312

Processing conditions:  44%|█████████████████████████████▌                                     | 907/2057 [05:23<06:07,  3.13item/s, Completed 907/2057]

Found 202 matched controls for ENSG00000108312
Getting matched controls for ENSG00000137413

Processing conditions:  44%|█████████████████████████████▌                                     | 908/2057 [05:24<05:42,  3.36item/s, Completed 908/2057]

Found 110 matched controls for ENSG00000137413
Getting matched controls for ENSG00000114686

Processing conditions:  44%|█████████████████████████████▋                                     | 910/2057 [05:24<04:51,  3.94item/s, Completed 910/2057]

Found 175 matched controls for ENSG00000114686
Getting matched controls for ENSG00000079134
Found 38 matched controls for ENSG00000079134
Getting matched controls for ENSG00000161016

Processing conditions:  44%|█████████████████████████████▋                                     | 911/2057 [05:25<07:04,  2.70item/s, Completed 911/2057]

Found 384 matched controls for ENSG00000161016
Getting matched controls for ENSG00000164053

Processing conditions:  44%|█████████████████████████████▋                                     | 912/2057 [05:25<06:51,  2.79item/s, Completed 912/2057]

Found 184 matched controls for ENSG00000164053
Getting matched controls for ENSG00000007168

Processing conditions:  44%|█████████████████████████████▋                                     | 913/2057 [05:25<06:26,  2.96item/s, Completed 913/2057]

Found 126 matched controls for ENSG00000007168
Getting matched controls for ENSG00000215251

Processing conditions:  44%|█████████████████████████████▊                                     | 914/2057 [05:26<06:26,  2.96item/s, Completed 914/2057]

Found 187 matched controls for ENSG00000215251
Getting matched controls for ENSG00000119787

Processing conditions:  44%|█████████████████████████████▊                                     | 915/2057 [05:26<05:50,  3.25item/s, Completed 916/2057]

Found 120 matched controls for ENSG00000119787
Getting matched controls for ENSG00000146918
Found 84 matched controls for ENSG00000146918

Processing conditions:  45%|█████████████████████████████▊                                     | 917/2057 [05:26<04:18,  4.41item/s, Completed 917/2057]

Getting matched controls for ENSG00000265241
Found 39 matched controls for ENSG00000265241
Getting matched controls for ENSG00000105058

Processing conditions:  45%|█████████████████████████████▉                                     | 918/2057 [05:27<07:07,  2.67item/s, Completed 918/2057]

Found 396 matched controls for ENSG00000105058
Getting matched controls for ENSG00000111880

Processing conditions:  45%|█████████████████████████████▉                                     | 919/2057 [05:27<06:16,  3.02item/s, Completed 919/2057]

Found 115 matched controls for ENSG00000111880
Getting matched controls for ENSG00000155846

Processing conditions:  45%|█████████████████████████████▉                                     | 920/2057 [05:28<05:55,  3.20item/s, Completed 920/2057]

Found 142 matched controls for ENSG00000155846
Getting matched controls for ENSG00000111581

Processing conditions:  45%|██████████████████████████████                                     | 922/2057 [05:28<06:00,  3.15item/s, Completed 922/2057]

Found 316 matched controls for ENSG00000111581
Getting matched controls for ENSG00000167965
Found 78 matched controls for ENSG00000167965
Getting matched controls for ENSG00000119559

Processing conditions:  45%|██████████████████████████████                                     | 923/2057 [05:29<06:08,  3.08item/s, Completed 923/2057]

Found 189 matched controls for ENSG00000119559
Getting matched controls for ENSG00000168495

Processing conditions:  45%|██████████████████████████████▏                                    | 925/2057 [05:29<05:03,  3.73item/s, Completed 925/2057]

Found 118 matched controls for ENSG00000168495
Getting matched controls for ENSG00000120314
Found 97 matched controls for ENSG00000120314
Getting matched controls for ENSG00000137200

Processing conditions:  45%|██████████████████████████████▏                                    | 927/2057 [05:29<04:39,  4.04item/s, Completed 927/2057]

Found 145 matched controls for ENSG00000137200
Getting matched controls for ENSG00000117614
Found 86 matched controls for ENSG00000117614
Getting matched controls for ENSG00000087087

Processing conditions:  45%|██████████████████████████████▏                                    | 928/2057 [05:30<06:12,  3.03item/s, Completed 928/2057]

Found 307 matched controls for ENSG00000087087
Getting matched controls for ENSG00000139343

Processing conditions:  45%|██████████████████████████████▎                                    | 929/2057 [05:30<05:45,  3.26item/s, Completed 929/2057]

Found 130 matched controls for ENSG00000139343
Getting matched controls for ENSG00000134057

Processing conditions:  45%|██████████████████████████████▎                                    | 931/2057 [05:31<04:52,  3.85item/s, Completed 931/2057]

Found 158 matched controls for ENSG00000134057
Getting matched controls for ENSG00000136045
Found 69 matched controls for ENSG00000136045
Getting matched controls for ENSG00000101639

Processing conditions:  45%|██████████████████████████████▍                                    | 933/2057 [05:31<04:26,  4.21item/s, Completed 933/2057]

Found 202 matched controls for ENSG00000101639
Getting matched controls for ENSG00000108590
Found 38 matched controls for ENSG00000108590
Getting matched controls for ENSG00000163832

Processing conditions:  45%|██████████████████████████████▍                                    | 935/2057 [05:32<03:54,  4.79item/s, Completed 935/2057]

Found 83 matched controls for ENSG00000163832
Getting matched controls for ENSG00000160404
Found 48 matched controls for ENSG00000160404
Getting matched controls for ENSG00000133316

Processing conditions:  46%|██████████████████████████████▍                                    | 936/2057 [05:32<04:32,  4.11item/s, Completed 936/2057]

Found 178 matched controls for ENSG00000133316
Getting matched controls for ENSG00000198856

Processing conditions:  46%|██████████████████████████████▌                                    | 937/2057 [05:32<06:19,  2.95item/s, Completed 937/2057]

Found 235 matched controls for ENSG00000198856
Getting matched controls for ENSG00000153339

Processing conditions:  46%|██████████████████████████████▌                                    | 938/2057 [05:33<06:07,  3.05item/s, Completed 938/2057]

Found 152 matched controls for ENSG00000153339
Getting matched controls for ENSG00000169727

Processing conditions:  46%|██████████████████████████████▌                                    | 940/2057 [05:34<06:34,  2.83item/s, Completed 940/2057]

Found 431 matched controls for ENSG00000169727
Getting matched controls for ENSG00000178999
Found 33 matched controls for ENSG00000178999
Getting matched controls for ENSG00000161970

Processing conditions:  46%|██████████████████████████████▋                                    | 942/2057 [05:34<05:48,  3.20item/s, Completed 942/2057]

Found 209 matched controls for ENSG00000161970
Getting matched controls for ENSG00000102977
Found 77 matched controls for ENSG00000102977
Getting matched controls for ENSG00000130826

Processing conditions:  46%|██████████████████████████████▋                                    | 943/2057 [05:34<04:55,  3.77item/s, Completed 943/2057]

Found 66 matched controls for ENSG00000130826
Getting matched controls for ENSG00000115524

Processing conditions:  46%|██████████████████████████████▋                                    | 944/2057 [05:35<05:08,  3.61item/s, Completed 944/2057]

Found 165 matched controls for ENSG00000115524
Getting matched controls for ENSG00000101138

Processing conditions:  46%|██████████████████████████████▊                                    | 945/2057 [05:35<05:04,  3.65item/s, Completed 945/2057]

Found 141 matched controls for ENSG00000101138
Getting matched controls for ENSG00000094804

Processing conditions:  46%|██████████████████████████████▊                                    | 946/2057 [05:35<05:29,  3.38item/s, Completed 946/2057]

Found 192 matched controls for ENSG00000094804
Getting matched controls for ENSG00000130810

Processing conditions:  46%|██████████████████████████████▊                                    | 947/2057 [05:35<05:00,  3.69item/s, Completed 947/2057]

Found 103 matched controls for ENSG00000130810
Getting matched controls for ENSG00000175029

Processing conditions:  46%|██████████████████████████████▉                                    | 948/2057 [05:36<04:45,  3.88item/s, Completed 948/2057]

Found 110 matched controls for ENSG00000175029
Getting matched controls for ENSG00000167721

Processing conditions:  46%|██████████████████████████████▉                                    | 949/2057 [05:36<05:15,  3.51item/s, Completed 949/2057]

Found 188 matched controls for ENSG00000167721
Getting matched controls for ENSG00000204435

Processing conditions:  46%|██████████████████████████████▉                                    | 950/2057 [05:36<05:07,  3.60item/s, Completed 950/2057]

Found 128 matched controls for ENSG00000204435
Getting matched controls for ENSG00000105364

Processing conditions:  46%|██████████████████████████████▉                                    | 951/2057 [05:37<04:57,  3.72item/s, Completed 951/2057]

Found 125 matched controls for ENSG00000105364
Getting matched controls for ENSG00000172269

Processing conditions:  46%|███████████████████████████████                                    | 952/2057 [05:37<05:13,  3.52item/s, Completed 952/2057]

Found 135 matched controls for ENSG00000172269
Getting matched controls for ENSG00000167986

Processing conditions:  46%|███████████████████████████████                                    | 953/2057 [05:37<05:28,  3.36item/s, Completed 953/2057]

Found 177 matched controls for ENSG00000167986
Getting matched controls for ENSG00000160294

Processing conditions:  46%|███████████████████████████████                                    | 954/2057 [05:37<05:03,  3.64item/s, Completed 954/2057]

Found 105 matched controls for ENSG00000160294
Getting matched controls for ENSG00000089737

Processing conditions:  46%|███████████████████████████████                                    | 955/2057 [05:38<06:16,  2.93item/s, Completed 955/2057]

Found 286 matched controls for ENSG00000089737
Getting matched controls for ENSG00000254415
Found 97 matched controls for ENSG00000254415

Processing conditions:  46%|███████████████████████████████▏                                   | 956/2057 [05:38<05:29,  3.34item/s, Completed 956/2057]

Getting matched controls for ENSG00000111481

Processing conditions:  47%|███████████████████████████████▏                                   | 957/2057 [05:39<05:54,  3.10item/s, Completed 957/2057]

Found 207 matched controls for ENSG00000111481
Getting matched controls for ENSG00000103168

Processing conditions:  47%|███████████████████████████████▏                                   | 959/2057 [05:39<04:53,  3.74item/s, Completed 959/2057]

Found 134 matched controls for ENSG00000103168
Getting matched controls for ENSG00000163950
Found 83 matched controls for ENSG00000163950
Getting matched controls for ENSG00000126814

Processing conditions:  47%|███████████████████████████████▎                                   | 960/2057 [05:39<04:31,  4.05item/s, Completed 960/2057]

Found 94 matched controls for ENSG00000126814
Getting matched controls for ENSG00000129197

Processing conditions:  47%|███████████████████████████████▎                                   | 962/2057 [05:40<04:09,  4.39item/s, Completed 962/2057]

Found 108 matched controls for ENSG00000129197
Getting matched controls for ENSG00000129968
Found 95 matched controls for ENSG00000129968
Getting matched controls for ENSG00000062716

Processing conditions:  47%|███████████████████████████████▍                                   | 964/2057 [05:40<03:48,  4.77item/s, Completed 964/2057]

Found 106 matched controls for ENSG00000062716
Getting matched controls for ENSG00000227057
Found 71 matched controls for ENSG00000227057
Getting matched controls for ENSG00000175054

Processing conditions:  47%|███████████████████████████████▍                                   | 965/2057 [05:40<04:25,  4.11item/s, Completed 965/2057]

Found 141 matched controls for ENSG00000175054
Getting matched controls for ENSG00000102978

Processing conditions:  47%|███████████████████████████████▍                                   | 966/2057 [05:41<04:58,  3.66item/s, Completed 966/2057]

Found 185 matched controls for ENSG00000102978
Getting matched controls for ENSG00000198670

Processing conditions:  47%|███████████████████████████████▍                                   | 967/2057 [05:41<04:46,  3.81item/s, Completed 967/2057]

Found 119 matched controls for ENSG00000198670
Getting matched controls for ENSG00000152904

Processing conditions:  47%|███████████████████████████████▌                                   | 969/2057 [05:41<04:31,  4.01item/s, Completed 969/2057]

Found 167 matched controls for ENSG00000152904
Getting matched controls for ENSG00000172586
Found 84 matched controls for ENSG00000172586
Getting matched controls for ENSG00000104142

Processing conditions:  47%|███████████████████████████████▋                                   | 971/2057 [05:42<03:59,  4.53item/s, Completed 971/2057]

Found 157 matched controls for ENSG00000104142
Getting matched controls for ENSG00000124635
Found 43 matched controls for ENSG00000124635
Getting matched controls for ENSG00000113048

Processing conditions:  47%|███████████████████████████████▋                                   | 972/2057 [05:42<03:46,  4.79item/s, Completed 972/2057]

Found 81 matched controls for ENSG00000113048
Getting matched controls for ENSG00000105185

Processing conditions:  47%|███████████████████████████████▋                                   | 974/2057 [05:43<04:07,  4.38item/s, Completed 974/2057]

Found 194 matched controls for ENSG00000105185
Getting matched controls for ENSG00000131051
Found 79 matched controls for ENSG00000131051
Getting matched controls for ENSG00000086200

Processing conditions:  47%|███████████████████████████████▊                                   | 975/2057 [05:43<03:48,  4.74item/s, Completed 975/2057]

Found 72 matched controls for ENSG00000086200
Getting matched controls for ENSG00000153989

Processing conditions:  47%|███████████████████████████████▊                                   | 976/2057 [05:43<04:01,  4.48item/s, Completed 976/2057]

Found 125 matched controls for ENSG00000153989
Getting matched controls for ENSG00000154781

Processing conditions:  47%|███████████████████████████████▊                                   | 977/2057 [05:43<03:58,  4.53item/s, Completed 977/2057]

Found 104 matched controls for ENSG00000154781
Getting matched controls for ENSG00000164758

Processing conditions:  48%|███████████████████████████████▊                                   | 978/2057 [05:44<05:26,  3.30item/s, Completed 978/2057]

Found 288 matched controls for ENSG00000164758
Getting matched controls for ENSG00000163466

Processing conditions:  48%|███████████████████████████████▉                                   | 979/2057 [05:44<05:58,  3.01item/s, Completed 979/2057]

Found 227 matched controls for ENSG00000163466
Getting matched controls for ENSG00000111711

Processing conditions:  48%|███████████████████████████████▉                                   | 980/2057 [05:45<06:46,  2.65item/s, Completed 980/2057]

Found 279 matched controls for ENSG00000111711
Getting matched controls for ENSG00000109971

Processing conditions:  48%|███████████████████████████████▉                                   | 981/2057 [05:45<07:07,  2.51item/s, Completed 981/2057]

Found 255 matched controls for ENSG00000109971
Getting matched controls for ENSG00000132382

Processing conditions:  48%|███████████████████████████████▉                                   | 982/2057 [05:45<06:15,  2.86item/s, Completed 982/2057]

Found 109 matched controls for ENSG00000132382
Getting matched controls for ENSG00000089195

Processing conditions:  48%|████████████████████████████████                                   | 983/2057 [05:45<05:36,  3.19item/s, Completed 983/2057]

Found 114 matched controls for ENSG00000089195
Getting matched controls for ENSG00000171453

Processing conditions:  48%|████████████████████████████████                                   | 984/2057 [05:46<05:43,  3.12item/s, Completed 984/2057]

Found 187 matched controls for ENSG00000171453
Getting matched controls for ENSG00000148296

Processing conditions:  48%|████████████████████████████████                                   | 986/2057 [05:46<04:39,  3.83item/s, Completed 986/2057]

Found 130 matched controls for ENSG00000148296
Getting matched controls for ENSG00000134453
Found 76 matched controls for ENSG00000134453
Getting matched controls for ENSG00000103274

Processing conditions:  48%|████████████████████████████████▏                                  | 987/2057 [05:47<05:14,  3.41item/s, Completed 987/2057]

Found 152 matched controls for ENSG00000103274
Getting matched controls for ENSG00000104957

Processing conditions:  48%|████████████████████████████████▏                                  | 988/2057 [05:47<05:06,  3.49item/s, Completed 988/2057]

Found 113 matched controls for ENSG00000104957
Getting matched controls for ENSG00000166441

Processing conditions:  48%|████████████████████████████████▏                                  | 989/2057 [05:47<05:42,  3.12item/s, Completed 989/2057]

Found 202 matched controls for ENSG00000166441
Getting matched controls for ENSG00000129559

Processing conditions:  48%|████████████████████████████████▏                                  | 990/2057 [05:48<05:52,  3.02item/s, Completed 990/2057]

Found 197 matched controls for ENSG00000129559
Getting matched controls for ENSG00000124193

Processing conditions:  48%|████████████████████████████████▎                                  | 991/2057 [05:48<06:16,  2.83item/s, Completed 991/2057]

Found 231 matched controls for ENSG00000124193
Getting matched controls for ENSG00000119285

Processing conditions:  48%|████████████████████████████████▎                                  | 993/2057 [05:49<05:11,  3.41item/s, Completed 993/2057]

Found 234 matched controls for ENSG00000119285
Getting matched controls for ENSG00000149428
Found 37 matched controls for ENSG00000149428
Getting matched controls for ENSG00000172977

Processing conditions:  48%|████████████████████████████████▍                                  | 995/2057 [05:49<04:25,  4.00item/s, Completed 995/2057]

Found 118 matched controls for ENSG00000172977
Getting matched controls for ENSG00000203812
Found 67 matched controls for ENSG00000203812
Getting matched controls for ENSG00000112739

Processing conditions:  48%|████████████████████████████████▍                                  | 996/2057 [05:49<05:03,  3.50item/s, Completed 996/2057]

Found 208 matched controls for ENSG00000112739
Getting matched controls for ENSG00000165269

Processing conditions:  48%|████████████████████████████████▍                                  | 997/2057 [05:50<04:41,  3.76item/s, Completed 997/2057]

Found 108 matched controls for ENSG00000165269
Getting matched controls for ENSG00000100413

Processing conditions:  49%|████████████████████████████████▌                                  | 998/2057 [05:50<04:26,  3.97item/s, Completed 998/2057]

Found 109 matched controls for ENSG00000100413
Getting matched controls for ENSG00000137054

Processing conditions:  49%|████████████████████████████████▌                                  | 999/2057 [05:50<05:04,  3.48item/s, Completed 999/2057]

Found 209 matched controls for ENSG00000137054
Getting matched controls for ENSG00000159720

Processing conditions:  49%|███████████████████████████████▌                                 | 1000/2057 [05:50<04:38,  3.80item/s, Completed 1000/2057]

Found 101 matched controls for ENSG00000159720
Getting matched controls for ENSG00000100319

Processing conditions:  49%|███████████████████████████████▋                                 | 1001/2057 [05:51<04:20,  4.06item/s, Completed 1001/2057]

Found 100 matched controls for ENSG00000100319
Getting matched controls for ENSG00000120800

Processing conditions:  49%|███████████████████████████████▋                                 | 1002/2057 [05:51<04:09,  4.23item/s, Completed 1002/2057]

Found 105 matched controls for ENSG00000120800
Getting matched controls for ENSG00000177302

Processing conditions:  49%|███████████████████████████████▋                                 | 1003/2057 [05:51<04:32,  3.87item/s, Completed 1003/2057]

Found 159 matched controls for ENSG00000177302
Getting matched controls for ENSG00000196230

Processing conditions:  49%|███████████████████████████████▊                                 | 1005/2057 [05:51<03:55,  4.46item/s, Completed 1005/2057]

Found 107 matched controls for ENSG00000196230
Getting matched controls for ENSG00000156502
Found 80 matched controls for ENSG00000156502
Getting matched controls for ENSG00000062582

Processing conditions:  49%|███████████████████████████████▊                                 | 1006/2057 [05:52<04:10,  4.19item/s, Completed 1006/2057]

Found 145 matched controls for ENSG00000062582
Getting matched controls for ENSG00000169750

Processing conditions:  49%|███████████████████████████████▊                                 | 1007/2057 [05:52<05:13,  3.35item/s, Completed 1007/2057]

Found 220 matched controls for ENSG00000169750
Getting matched controls for ENSG00000116670

Processing conditions:  49%|███████████████████████████████▊                                 | 1008/2057 [05:53<05:44,  3.05item/s, Completed 1008/2057]

Found 200 matched controls for ENSG00000116670
Getting matched controls for ENSG00000254726

Processing conditions:  49%|███████████████████████████████▉                                 | 1010/2057 [05:53<04:42,  3.71item/s, Completed 1010/2057]

Found 171 matched controls for ENSG00000254726
Getting matched controls for ENSG00000108848
Found 45 matched controls for ENSG00000108848
Getting matched controls for ENSG00000198498

Processing conditions:  49%|███████████████████████████████▉                                 | 1012/2057 [05:53<04:07,  4.22item/s, Completed 1012/2057]

Found 172 matched controls for ENSG00000198498
Getting matched controls for ENSG00000126216
Found 30 matched controls for ENSG00000126216
Getting matched controls for ENSG00000088205

Processing conditions:  49%|████████████████████████████████                                 | 1013/2057 [05:54<04:21,  3.99item/s, Completed 1013/2057]

Found 137 matched controls for ENSG00000088205
Getting matched controls for ENSG00000118655

Processing conditions:  49%|████████████████████████████████                                 | 1014/2057 [05:54<04:22,  3.98item/s, Completed 1014/2057]

Found 117 matched controls for ENSG00000118655
Getting matched controls for ENSG00000112473

Processing conditions:  49%|████████████████████████████████                                 | 1016/2057 [05:54<03:52,  4.47item/s, Completed 1016/2057]

Found 131 matched controls for ENSG00000112473
Getting matched controls for ENSG00000205609
Found 44 matched controls for ENSG00000205609
Getting matched controls for ENSG00000028203

Processing conditions:  49%|████████████████████████████████▏                                | 1017/2057 [05:55<04:41,  3.69item/s, Completed 1017/2057]

Found 204 matched controls for ENSG00000028203
Getting matched controls for ENSG00000273976

Processing conditions:  49%|████████████████████████████████▏                                | 1018/2057 [05:55<05:08,  3.37item/s, Completed 1018/2057]

Found 197 matched controls for ENSG00000273976
Getting matched controls for ENSG00000239900

Processing conditions:  50%|████████████████████████████████▏                                | 1019/2057 [05:55<04:54,  3.52item/s, Completed 1019/2057]

Found 133 matched controls for ENSG00000239900
Getting matched controls for ENSG00000173418

Processing conditions:  50%|████████████████████████████████▏                                | 1020/2057 [05:56<05:08,  3.36item/s, Completed 1020/2057]

Found 182 matched controls for ENSG00000173418
Getting matched controls for ENSG00000070785

Processing conditions:  50%|████████████████████████████████▎                                | 1022/2057 [05:56<03:59,  4.32item/s, Completed 1022/2057]

Found 104 matched controls for ENSG00000070785
Getting matched controls for ENSG00000166200
Found 47 matched controls for ENSG00000166200
Getting matched controls for ENSG00000173933

Processing conditions:  50%|████████████████████████████████▎                                | 1023/2057 [05:56<04:48,  3.58item/s, Completed 1023/2057]

Found 221 matched controls for ENSG00000173933
Getting matched controls for ENSG00000142507

Processing conditions:  50%|████████████████████████████████▎                                | 1024/2057 [05:57<05:19,  3.23item/s, Completed 1024/2057]

Found 200 matched controls for ENSG00000142507
Getting matched controls for ENSG00000183474

Processing conditions:  50%|████████████████████████████████▍                                | 1025/2057 [05:57<05:00,  3.44item/s, Completed 1025/2057]

Found 126 matched controls for ENSG00000183474
Getting matched controls for ENSG00000103510

Processing conditions:  50%|████████████████████████████████▍                                | 1026/2057 [05:58<06:14,  2.75item/s, Completed 1026/2057]

Found 287 matched controls for ENSG00000103510
Getting matched controls for ENSG00000188529

Processing conditions:  50%|████████████████████████████████▍                                | 1027/2057 [05:58<05:46,  2.97item/s, Completed 1027/2057]

Found 133 matched controls for ENSG00000188529
Getting matched controls for ENSG00000123473

Processing conditions:  50%|████████████████████████████████▍                                | 1028/2057 [05:58<05:39,  3.03item/s, Completed 1028/2057]

Found 171 matched controls for ENSG00000123473
Getting matched controls for ENSG00000139620

Processing conditions:  50%|████████████████████████████████▌                                | 1029/2057 [05:59<05:29,  3.12item/s, Completed 1029/2057]

Found 158 matched controls for ENSG00000139620
Getting matched controls for ENSG00000198736

Processing conditions:  50%|████████████████████████████████▌                                | 1030/2057 [05:59<05:56,  2.88item/s, Completed 1030/2057]

Found 205 matched controls for ENSG00000198736
Getting matched controls for ENSG00000180104

Processing conditions:  50%|████████████████████████████████▌                                | 1032/2057 [06:00<05:24,  3.16item/s, Completed 1032/2057]

Found 247 matched controls for ENSG00000180104
Getting matched controls for ENSG00000182446
Found 60 matched controls for ENSG00000182446
Getting matched controls for ENSG00000108506

Processing conditions:  50%|████████████████████████████████▋                                | 1033/2057 [06:00<07:02,  2.43item/s, Completed 1033/2057]

Found 354 matched controls for ENSG00000108506
Getting matched controls for ENSG00000122034

Processing conditions:  50%|████████████████████████████████▋                                | 1034/2057 [06:00<06:01,  2.83item/s, Completed 1034/2057]

Found 88 matched controls for ENSG00000122034
Getting matched controls for ENSG00000171314

Processing conditions:  50%|████████████████████████████████▋                                | 1035/2057 [06:01<05:44,  2.97item/s, Completed 1035/2057]

Found 160 matched controls for ENSG00000171314
Getting matched controls for ENSG00000077235

Processing conditions:  50%|████████████████████████████████▋                                | 1036/2057 [06:01<05:38,  3.02item/s, Completed 1036/2057]

Found 160 matched controls for ENSG00000077235
Getting matched controls for ENSG00000197734

Processing conditions:  50%|████████████████████████████████▊                                | 1038/2057 [06:01<04:33,  3.72item/s, Completed 1038/2057]

Found 143 matched controls for ENSG00000197734
Getting matched controls for ENSG00000164037
Found 74 matched controls for ENSG00000164037
Getting matched controls for ENSG00000122484

Processing conditions:  51%|████████████████████████████████▊                                | 1040/2057 [06:02<05:13,  3.25item/s, Completed 1040/2057]

Found 398 matched controls for ENSG00000122484
Getting matched controls for ENSG00000188566
Found 42 matched controls for ENSG00000188566
Getting matched controls for ENSG00000118181

Processing conditions:  51%|████████████████████████████████▉                                | 1042/2057 [06:03<03:42,  4.55item/s, Completed 1042/2057]

Found 40 matched controls for ENSG00000118181
Getting matched controls for ENSG00000177700
Found 62 matched controls for ENSG00000177700
Getting matched controls for ENSG00000198612

Processing conditions:  51%|████████████████████████████████▉                                | 1043/2057 [06:03<04:36,  3.67item/s, Completed 1043/2057]

Found 224 matched controls for ENSG00000198612
Getting matched controls for ENSG00000139618

Processing conditions:  51%|█████████████████████████████████                                | 1045/2057 [06:03<04:05,  4.12item/s, Completed 1045/2057]

Found 147 matched controls for ENSG00000139618
Getting matched controls for ENSG00000151304
Found 76 matched controls for ENSG00000151304
Getting matched controls for ENSG00000204542

Processing conditions:  51%|█████████████████████████████████                                | 1047/2057 [06:04<03:56,  4.26item/s, Completed 1047/2057]

Found 164 matched controls for ENSG00000204542
Getting matched controls for ENSG00000074582
Found 70 matched controls for ENSG00000074582
Getting matched controls for ENSG00000179950

Processing conditions:  51%|█████████████████████████████████                                | 1048/2057 [06:04<03:47,  4.43item/s, Completed 1048/2057]

Found 89 matched controls for ENSG00000179950
Getting matched controls for ENSG00000115091

Processing conditions:  51%|█████████████████████████████████▏                               | 1050/2057 [06:04<03:23,  4.95item/s, Completed 1050/2057]

Found 118 matched controls for ENSG00000115091
Getting matched controls for ENSG00000124228
Found 49 matched controls for ENSG00000124228
Getting matched controls for ENSG00000039650

Processing conditions:  51%|█████████████████████████████████▏                               | 1051/2057 [06:05<04:08,  4.04item/s, Completed 1051/2057]

Found 185 matched controls for ENSG00000039650
Getting matched controls for ENSG00000110871

Processing conditions:  51%|█████████████████████████████████▏                               | 1052/2057 [06:05<04:06,  4.08item/s, Completed 1052/2057]

Found 113 matched controls for ENSG00000110871
Getting matched controls for ENSG00000284906

Processing conditions:  51%|█████████████████████████████████▎                               | 1053/2057 [06:05<04:50,  3.46item/s, Completed 1053/2057]

Found 212 matched controls for ENSG00000284906
Getting matched controls for ENSG00000107185

Processing conditions:  51%|█████████████████████████████████▎                               | 1054/2057 [06:06<04:49,  3.47item/s, Completed 1054/2057]

Found 130 matched controls for ENSG00000107185
Getting matched controls for ENSG00000089159

Processing conditions:  51%|█████████████████████████████████▎                               | 1055/2057 [06:06<04:53,  3.41item/s, Completed 1055/2057]

Found 161 matched controls for ENSG00000089159
Getting matched controls for ENSG00000186468

Processing conditions:  51%|█████████████████████████████████▎                               | 1056/2057 [06:06<04:34,  3.64item/s, Completed 1056/2057]

Found 114 matched controls for ENSG00000186468
Getting matched controls for ENSG00000103226

Processing conditions:  51%|█████████████████████████████████▍                               | 1057/2057 [06:07<05:02,  3.30item/s, Completed 1057/2057]

Found 191 matched controls for ENSG00000103226
Getting matched controls for ENSG00000151657

Processing conditions:  51%|█████████████████████████████████▍                               | 1058/2057 [06:07<05:01,  3.32item/s, Completed 1058/2057]

Found 160 matched controls for ENSG00000151657
Getting matched controls for ENSG00000149809

Processing conditions:  52%|█████████████████████████████████▍                               | 1060/2057 [06:07<04:06,  4.05item/s, Completed 1060/2057]

Found 100 matched controls for ENSG00000149809
Getting matched controls for ENSG00000100941
Found 86 matched controls for ENSG00000100941
Getting matched controls for ENSG00000123415

Processing conditions:  52%|█████████████████████████████████▌                               | 1061/2057 [06:07<03:40,  4.52item/s, Completed 1061/2057]

Found 71 matched controls for ENSG00000123415
Getting matched controls for ENSG00000049541

Processing conditions:  52%|█████████████████████████████████▌                               | 1062/2057 [06:08<03:34,  4.63item/s, Completed 1062/2057]

Found 97 matched controls for ENSG00000049541
Getting matched controls for ENSG00000134684

Processing conditions:  52%|█████████████████████████████████▌                               | 1063/2057 [06:08<04:10,  3.97item/s, Completed 1063/2057]

Found 185 matched controls for ENSG00000134684
Getting matched controls for ENSG00000196262

Processing conditions:  52%|█████████████████████████████████▌                               | 1064/2057 [06:08<04:24,  3.75item/s, Completed 1064/2057]

Found 158 matched controls for ENSG00000196262
Getting matched controls for ENSG00000101407

Processing conditions:  52%|█████████████████████████████████▋                               | 1066/2057 [06:09<03:57,  4.17item/s, Completed 1066/2057]

Found 151 matched controls for ENSG00000101407
Getting matched controls for ENSG00000106459
Found 71 matched controls for ENSG00000106459
Getting matched controls for ENSG00000169371

Processing conditions:  52%|█████████████████████████████████▋                               | 1067/2057 [06:09<04:04,  4.04item/s, Completed 1067/2057]

Found 139 matched controls for ENSG00000169371
Getting matched controls for ENSG00000092108

Processing conditions:  52%|█████████████████████████████████▋                               | 1068/2057 [06:09<04:28,  3.68item/s, Completed 1068/2057]

Found 152 matched controls for ENSG00000092108
Getting matched controls for ENSG00000137818

Processing conditions:  52%|█████████████████████████████████▊                               | 1070/2057 [06:10<03:56,  4.17item/s, Completed 1070/2057]

Found 117 matched controls for ENSG00000137818
Getting matched controls for ENSG00000112159
Found 84 matched controls for ENSG00000112159
Getting matched controls for ENSG00000171357

Processing conditions:  52%|█████████████████████████████████▊                               | 1071/2057 [06:10<03:34,  4.60item/s, Completed 1071/2057]

Found 71 matched controls for ENSG00000171357
Getting matched controls for ENSG00000089009

Processing conditions:  52%|█████████████████████████████████▉                               | 1073/2057 [06:11<03:59,  4.12item/s, Completed 1073/2057]

Found 273 matched controls for ENSG00000089009
Getting matched controls for ENSG00000177971
Found 27 matched controls for ENSG00000177971
Getting matched controls for ENSG00000085872

Processing conditions:  52%|█████████████████████████████████▉                               | 1074/2057 [06:11<03:43,  4.39item/s, Completed 1074/2057]

Found 67 matched controls for ENSG00000085872
Getting matched controls for ENSG00000172922

Processing conditions:  52%|██████████████████████████████████                               | 1076/2057 [06:11<03:18,  4.94item/s, Completed 1076/2057]

Found 102 matched controls for ENSG00000172922
Getting matched controls for ENSG00000033011
Found 69 matched controls for ENSG00000033011
Getting matched controls for ENSG00000156970

Processing conditions:  52%|██████████████████████████████████                               | 1078/2057 [06:12<03:12,  5.09item/s, Completed 1078/2057]

Found 141 matched controls for ENSG00000156970
Getting matched controls for ENSG00000157106
Found 35 matched controls for ENSG00000157106
Getting matched controls for ENSG00000133226

Processing conditions:  52%|██████████████████████████████████                               | 1079/2057 [06:12<04:26,  3.67item/s, Completed 1079/2057]

Found 180 matched controls for ENSG00000133226
Getting matched controls for ENSG00000135956

Processing conditions:  53%|██████████████████████████████████▏                              | 1080/2057 [06:12<04:26,  3.67item/s, Completed 1080/2057]

Found 132 matched controls for ENSG00000135956
Getting matched controls for ENSG00000132664

Processing conditions:  53%|██████████████████████████████████▏                              | 1082/2057 [06:13<04:21,  3.72item/s, Completed 1082/2057]

Found 165 matched controls for ENSG00000132664
Getting matched controls for ENSG00000117877
Found 88 matched controls for ENSG00000117877
Getting matched controls for ENSG00000102900

Processing conditions:  53%|██████████████████████████████████▏                              | 1083/2057 [06:13<04:39,  3.49item/s, Completed 1083/2057]

Found 159 matched controls for ENSG00000102900
Getting matched controls for ENSG00000161920

Processing conditions:  53%|██████████████████████████████████▎                              | 1084/2057 [06:14<05:31,  2.94item/s, Completed 1084/2057]

Found 237 matched controls for ENSG00000161920
Getting matched controls for ENSG00000040275

Processing conditions:  53%|██████████████████████████████████▎                              | 1085/2057 [06:14<04:57,  3.27item/s, Completed 1085/2057]

Found 88 matched controls for ENSG00000040275
Getting matched controls for ENSG00000165898

Processing conditions:  53%|██████████████████████████████████▎                              | 1086/2057 [06:14<05:28,  2.96item/s, Completed 1086/2057]

Found 232 matched controls for ENSG00000165898
Getting matched controls for ENSG00000129055

Processing conditions:  53%|██████████████████████████████████▎                              | 1087/2057 [06:14<04:55,  3.29item/s, Completed 1087/2057]

Found 112 matched controls for ENSG00000129055
Getting matched controls for ENSG00000151239

Processing conditions:  53%|██████████████████████████████████▍                              | 1088/2057 [06:15<04:43,  3.41item/s, Completed 1088/2057]

Found 140 matched controls for ENSG00000151239
Getting matched controls for ENSG00000136897

Processing conditions:  53%|██████████████████████████████████▍                              | 1089/2057 [06:15<05:04,  3.18item/s, Completed 1089/2057]

Found 171 matched controls for ENSG00000136897
Getting matched controls for ENSG00000095906

Processing conditions:  53%|██████████████████████████████████▍                              | 1091/2057 [06:16<04:15,  3.78item/s, Completed 1091/2057]

Found 153 matched controls for ENSG00000095906
Getting matched controls for ENSG00000163684
Found 56 matched controls for ENSG00000163684
Getting matched controls for ENSG00000213638

Processing conditions:  53%|██████████████████████████████████▌                              | 1092/2057 [06:16<04:09,  3.87item/s, Completed 1092/2057]

Found 125 matched controls for ENSG00000213638
Getting matched controls for ENSG00000008324

Processing conditions:  53%|██████████████████████████████████▌                              | 1094/2057 [06:16<03:50,  4.18item/s, Completed 1094/2057]

Found 144 matched controls for ENSG00000008324
Getting matched controls for ENSG00000106803
Found 84 matched controls for ENSG00000106803
Getting matched controls for ENSG00000099956

Processing conditions:  53%|██████████████████████████████████▌                              | 1095/2057 [06:17<04:16,  3.75item/s, Completed 1095/2057]

Found 182 matched controls for ENSG00000099956
Getting matched controls for ENSG00000131966

Processing conditions:  53%|██████████████████████████████████▋                              | 1096/2057 [06:17<04:10,  3.83item/s, Completed 1096/2057]

Found 116 matched controls for ENSG00000131966
Getting matched controls for ENSG00000204843

Processing conditions:  53%|██████████████████████████████████▋                              | 1097/2057 [06:17<04:36,  3.47item/s, Completed 1097/2057]

Found 197 matched controls for ENSG00000204843
Getting matched controls for ENSG00000065978

Processing conditions:  53%|██████████████████████████████████▋                              | 1098/2057 [06:17<04:20,  3.68item/s, Completed 1098/2057]

Found 86 matched controls for ENSG00000065978
Getting matched controls for ENSG00000106976

Processing conditions:  53%|██████████████████████████████████▋                              | 1099/2057 [06:18<04:33,  3.50item/s, Completed 1099/2057]

Found 146 matched controls for ENSG00000106976
Getting matched controls for ENSG00000163682

Processing conditions:  53%|██████████████████████████████████▊                              | 1100/2057 [06:18<05:18,  3.01item/s, Completed 1100/2057]

Found 242 matched controls for ENSG00000163682
Getting matched controls for ENSG00000198700

Processing conditions:  54%|██████████████████████████████████▊                              | 1101/2057 [06:19<05:20,  2.98item/s, Completed 1101/2057]

Found 187 matched controls for ENSG00000198700
Getting matched controls for ENSG00000006634

Processing conditions:  54%|██████████████████████████████████▊                              | 1102/2057 [06:19<05:01,  3.16item/s, Completed 1102/2057]

Found 131 matched controls for ENSG00000006634
Getting matched controls for ENSG00000102786

Processing conditions:  54%|██████████████████████████████████▊                              | 1103/2057 [06:19<05:03,  3.15item/s, Completed 1103/2057]

Found 146 matched controls for ENSG00000102786
Getting matched controls for ENSG00000164024

Processing conditions:  54%|██████████████████████████████████▉                              | 1104/2057 [06:19<04:37,  3.44item/s, Completed 1104/2057]

Found 102 matched controls for ENSG00000164024
Getting matched controls for ENSG00000241343

Processing conditions:  54%|██████████████████████████████████▉                              | 1105/2057 [06:20<04:20,  3.66item/s, Completed 1105/2057]

Found 84 matched controls for ENSG00000241343
Getting matched controls for ENSG00000148840

Processing conditions:  54%|██████████████████████████████████▉                              | 1106/2057 [06:20<04:10,  3.80item/s, Completed 1106/2057]

Found 122 matched controls for ENSG00000148840
Getting matched controls for ENSG00000174231

Processing conditions:  54%|███████████████████████████████████                              | 1108/2057 [06:20<04:05,  3.87item/s, Completed 1108/2057]

Found 150 matched controls for ENSG00000174231
Getting matched controls for ENSG00000168818
Found 86 matched controls for ENSG00000168818
Getting matched controls for ENSG00000109920

Processing conditions:  54%|███████████████████████████████████                              | 1110/2057 [06:21<03:48,  4.14item/s, Completed 1110/2057]

Found 160 matched controls for ENSG00000109920
Getting matched controls for ENSG00000223496
Found 75 matched controls for ENSG00000223496
Getting matched controls for ENSG00000112592

Processing conditions:  54%|███████████████████████████████████                              | 1111/2057 [06:21<04:05,  3.86item/s, Completed 1111/2057]

Found 151 matched controls for ENSG00000112592
Getting matched controls for ENSG00000185651

Processing conditions:  54%|███████████████████████████████████▏                             | 1112/2057 [06:22<04:33,  3.46item/s, Completed 1113/2057]

Found 201 matched controls for ENSG00000185651
Getting matched controls for ENSG00000115541
Found 29 matched controls for ENSG00000115541
Getting matched controls for ENSG00000134690

Processing conditions:  54%|███████████████████████████████████▏                             | 1115/2057 [06:22<03:13,  4.88item/s, Completed 1115/2057]

Found 82 matched controls for ENSG00000134690
Getting matched controls for ENSG00000122882
Found 72 matched controls for ENSG00000122882
Getting matched controls for ENSG00000196943

Processing conditions:  54%|███████████████████████████████████▎                             | 1116/2057 [06:22<03:05,  5.09item/s, Completed 1116/2057]

Found 78 matched controls for ENSG00000196943
Getting matched controls for ENSG00000242950

Processing conditions:  54%|███████████████████████████████████▎                             | 1117/2057 [06:22<03:37,  4.32item/s, Completed 1117/2057]

Found 175 matched controls for ENSG00000242950
Getting matched controls for ENSG00000198176

Processing conditions:  54%|███████████████████████████████████▎                             | 1118/2057 [06:23<03:55,  3.98item/s, Completed 1118/2057]

Found 163 matched controls for ENSG00000198176
Getting matched controls for ENSG00000166272

Processing conditions:  54%|███████████████████████████████████▎                             | 1119/2057 [06:23<04:24,  3.54item/s, Completed 1119/2057]

Found 199 matched controls for ENSG00000166272
Getting matched controls for ENSG00000147403

Processing conditions:  54%|███████████████████████████████████▍                             | 1120/2057 [06:24<05:18,  2.95item/s, Completed 1120/2057]

Found 276 matched controls for ENSG00000147403
Getting matched controls for ENSG00000187514

Processing conditions:  54%|███████████████████████████████████▍                             | 1121/2057 [06:24<05:03,  3.09item/s, Completed 1121/2057]

Found 152 matched controls for ENSG00000187514
Getting matched controls for ENSG00000159210

Processing conditions:  55%|███████████████████████████████████▍                             | 1122/2057 [06:24<04:44,  3.29item/s, Completed 1122/2057]

Found 132 matched controls for ENSG00000159210
Getting matched controls for ENSG00000136908

Processing conditions:  55%|███████████████████████████████████▍                             | 1123/2057 [06:24<04:45,  3.27item/s, Completed 1123/2057]

Found 153 matched controls for ENSG00000136908
Getting matched controls for ENSG00000123485

Processing conditions:  55%|███████████████████████████████████▌                             | 1125/2057 [06:25<03:51,  4.03item/s, Completed 1125/2057]

Found 111 matched controls for ENSG00000123485
Getting matched controls for ENSG00000072274
Found 57 matched controls for ENSG00000072274
Getting matched controls for ENSG00000042753

Processing conditions:  55%|███████████████████████████████████▌                             | 1126/2057 [06:25<03:48,  4.07item/s, Completed 1126/2057]

Found 123 matched controls for ENSG00000042753
Getting matched controls for ENSG00000134697

Processing conditions:  55%|███████████████████████████████████▌                             | 1127/2057 [06:26<05:26,  2.84item/s, Completed 1127/2057]

Found 351 matched controls for ENSG00000134697
Getting matched controls for ENSG00000118705

Processing conditions:  55%|███████████████████████████████████▋                             | 1128/2057 [06:26<04:53,  3.17item/s, Completed 1129/2057]

Found 105 matched controls for ENSG00000118705
Getting matched controls for ENSG00000141543
Found 7 matched controls for ENSG00000141543
Getting matched controls for ENSG00000086065

Processing conditions:  55%|███████████████████████████████████▋                             | 1130/2057 [06:26<03:45,  4.12item/s, Completed 1130/2057]

Found 110 matched controls for ENSG00000086065
Getting matched controls for ENSG00000204574

Processing conditions:  55%|███████████████████████████████████▋                             | 1131/2057 [06:27<04:59,  3.10item/s, Completed 1131/2057]

Found 329 matched controls for ENSG00000204574
Getting matched controls for ENSG00000162521

Processing conditions:  55%|███████████████████████████████████▊                             | 1132/2057 [06:27<04:32,  3.39item/s, Completed 1132/2057]

Found 90 matched controls for ENSG00000162521
Getting matched controls for ENSG00000010292

Processing conditions:  55%|███████████████████████████████████▊                             | 1133/2057 [06:27<04:09,  3.70item/s, Completed 1133/2057]

Found 48 matched controls for ENSG00000010292
Getting matched controls for ENSG00000257949

Processing conditions:  55%|███████████████████████████████████▊                             | 1134/2057 [06:27<04:03,  3.79item/s, Completed 1134/2057]

Found 86 matched controls for ENSG00000257949
Getting matched controls for ENSG00000154743

Processing conditions:  55%|███████████████████████████████████▊                             | 1135/2057 [06:28<04:23,  3.49item/s, Completed 1135/2057]

Found 177 matched controls for ENSG00000154743
Getting matched controls for ENSG00000105229

Processing conditions:  55%|███████████████████████████████████▉                             | 1137/2057 [06:28<04:01,  3.82item/s, Completed 1137/2057]

Found 206 matched controls for ENSG00000105229
Getting matched controls for ENSG00000162517
Found 48 matched controls for ENSG00000162517
Getting matched controls for ENSG00000176915

Processing conditions:  55%|███████████████████████████████████▉                             | 1138/2057 [06:29<04:09,  3.69item/s, Completed 1138/2057]

Found 126 matched controls for ENSG00000176915
Getting matched controls for ENSG00000080819

Processing conditions:  55%|███████████████████████████████████▉                             | 1139/2057 [06:29<03:56,  3.88item/s, Completed 1139/2057]

Found 101 matched controls for ENSG00000080819
Getting matched controls for ENSG00000140990

Processing conditions:  55%|████████████████████████████████████                             | 1140/2057 [06:29<04:09,  3.68item/s, Completed 1140/2057]

Found 154 matched controls for ENSG00000140990
Getting matched controls for ENSG00000060237

Processing conditions:  56%|████████████████████████████████████                             | 1142/2057 [06:30<03:58,  3.83item/s, Completed 1142/2057]

Found 137 matched controls for ENSG00000060237
Getting matched controls for ENSG00000021776
Found 90 matched controls for ENSG00000021776
Getting matched controls for ENSG00000130985

Processing conditions:  56%|████████████████████████████████████                             | 1143/2057 [06:30<05:08,  2.96item/s, Completed 1143/2057]

Found 287 matched controls for ENSG00000130985
Getting matched controls for ENSG00000035928

Processing conditions:  56%|████████████████████████████████████▏                            | 1144/2057 [06:30<04:52,  3.12item/s, Completed 1144/2057]

Found 149 matched controls for ENSG00000035928
Getting matched controls for ENSG00000170889

Processing conditions:  56%|████████████████████████████████████▏                            | 1145/2057 [06:31<05:42,  2.66item/s, Completed 1145/2057]

Found 276 matched controls for ENSG00000170889
Getting matched controls for ENSG00000181991

Processing conditions:  56%|████████████████████████████████████▏                            | 1147/2057 [06:31<04:06,  3.70item/s, Completed 1147/2057]

Found 95 matched controls for ENSG00000181991
Getting matched controls for ENSG00000118194
Found 28 matched controls for ENSG00000118194
Getting matched controls for ENSG00000112578

Processing conditions:  56%|████████████████████████████████████▎                            | 1148/2057 [06:32<03:52,  3.92item/s, Completed 1148/2057]

Found 98 matched controls for ENSG00000112578
Getting matched controls for ENSG00000139168

Processing conditions:  56%|████████████████████████████████████▎                            | 1149/2057 [06:32<04:10,  3.62item/s, Completed 1149/2057]

Found 146 matched controls for ENSG00000139168
Getting matched controls for ENSG00000034510

Processing conditions:  56%|████████████████████████████████████▎                            | 1151/2057 [06:32<04:16,  3.53item/s, Completed 1151/2057]

Found 228 matched controls for ENSG00000034510
Getting matched controls for ENSG00000130119
Found 69 matched controls for ENSG00000130119
Getting matched controls for ENSG00000089048

Processing conditions:  56%|████████████████████████████████████▍                            | 1152/2057 [06:33<04:19,  3.49item/s, Completed 1152/2057]

Found 149 matched controls for ENSG00000089048
Getting matched controls for ENSG00000111596

Processing conditions:  56%|████████████████████████████████████▍                            | 1153/2057 [06:33<03:59,  3.78item/s, Completed 1153/2057]

Found 84 matched controls for ENSG00000111596
Getting matched controls for ENSG00000149823

Processing conditions:  56%|████████████████████████████████████▍                            | 1155/2057 [06:33<03:06,  4.84item/s, Completed 1155/2057]

Found 101 matched controls for ENSG00000149823
Getting matched controls for ENSG00000089053
Found 40 matched controls for ENSG00000089053
Getting matched controls for ENSG00000064419

Processing conditions:  56%|████████████████████████████████████▌                            | 1156/2057 [06:33<03:08,  4.79item/s, Completed 1156/2057]

Found 100 matched controls for ENSG00000064419
Getting matched controls for ENSG00000030066

Processing conditions:  56%|████████████████████████████████████▌                            | 1158/2057 [06:34<03:35,  4.18item/s, Completed 1158/2057]

Found 291 matched controls for ENSG00000030066
Getting matched controls for ENSG00000137947
Found 35 matched controls for ENSG00000137947
Getting matched controls for ENSG00000146109

Processing conditions:  56%|████████████████████████████████████▌                            | 1159/2057 [06:34<03:28,  4.30item/s, Completed 1159/2057]

Found 107 matched controls for ENSG00000146109
Getting matched controls for ENSG00000135624

Processing conditions:  56%|████████████████████████████████████▋                            | 1160/2057 [06:35<03:42,  4.03item/s, Completed 1160/2057]

Found 152 matched controls for ENSG00000135624
Getting matched controls for ENSG00000198034

Processing conditions:  56%|████████████████████████████████████▋                            | 1162/2057 [06:35<03:38,  4.09item/s, Completed 1162/2057]

Found 180 matched controls for ENSG00000198034
Getting matched controls for ENSG00000177990
Found 50 matched controls for ENSG00000177990
Getting matched controls for ENSG00000111361

Processing conditions:  57%|████████████████████████████████████▊                            | 1163/2057 [06:35<03:59,  3.74item/s, Completed 1163/2057]

Found 178 matched controls for ENSG00000111361
Getting matched controls for ENSG00000172809

Processing conditions:  57%|████████████████████████████████████▊                            | 1164/2057 [06:36<04:26,  3.36item/s, Completed 1164/2057]

Found 184 matched controls for ENSG00000172809
Getting matched controls for ENSG00000094880

Processing conditions:  57%|████████████████████████████████████▊                            | 1165/2057 [06:36<04:47,  3.10item/s, Completed 1165/2057]

Found 177 matched controls for ENSG00000094880
Getting matched controls for ENSG00000169446

Processing conditions:  57%|████████████████████████████████████▊                            | 1166/2057 [06:37<04:50,  3.06item/s, Completed 1166/2057]

Found 183 matched controls for ENSG00000169446
Getting matched controls for ENSG00000143476

Processing conditions:  57%|████████████████████████████████████▉                            | 1168/2057 [06:37<03:44,  3.96item/s, Completed 1168/2057]

Found 136 matched controls for ENSG00000143476
Getting matched controls for ENSG00000142731
Found 32 matched controls for ENSG00000142731
Getting matched controls for ENSG00000138231

Processing conditions:  57%|████████████████████████████████████▉                            | 1169/2057 [06:37<03:33,  4.17item/s, Completed 1169/2057]

Found 98 matched controls for ENSG00000138231
Getting matched controls for ENSG00000125691

Processing conditions:  57%|█████████████████████████████████████                            | 1171/2057 [06:38<04:52,  3.03item/s, Completed 1171/2057]

Found 398 matched controls for ENSG00000125691
Getting matched controls for ENSG00000108064
Found 82 matched controls for ENSG00000108064
Getting matched controls for ENSG00000106028

Processing conditions:  57%|█████████████████████████████████████                            | 1172/2057 [06:38<04:32,  3.24item/s, Completed 1172/2057]

Found 119 matched controls for ENSG00000106028
Getting matched controls for ENSG00000061794

Processing conditions:  57%|█████████████████████████████████████                            | 1173/2057 [06:39<04:47,  3.08item/s, Completed 1173/2057]

Found 201 matched controls for ENSG00000061794
Getting matched controls for ENSG00000172339

Processing conditions:  57%|█████████████████████████████████████▏                           | 1175/2057 [06:39<04:14,  3.46item/s, Completed 1175/2057]

Found 183 matched controls for ENSG00000172339
Getting matched controls for ENSG00000103932
Found 91 matched controls for ENSG00000103932
Getting matched controls for ENSG00000214517

Processing conditions:  57%|█████████████████████████████████████▏                           | 1177/2057 [06:40<04:03,  3.62item/s, Completed 1177/2057]

Found 222 matched controls for ENSG00000214517
Getting matched controls for ENSG00000100865
Found 78 matched controls for ENSG00000100865
Getting matched controls for ENSG00000115053

Processing conditions:  57%|█████████████████████████████████████▏                           | 1178/2057 [06:40<05:31,  2.65item/s, Completed 1178/2057]

Found 298 matched controls for ENSG00000115053
Getting matched controls for ENSG00000174748

Processing conditions:  57%|█████████████████████████████████████▎                           | 1180/2057 [06:41<04:20,  3.37item/s, Completed 1180/2057]

Found 168 matched controls for ENSG00000174748
Getting matched controls for ENSG00000116455
Found 42 matched controls for ENSG00000116455
Getting matched controls for ENSG00000174177

Processing conditions:  57%|█████████████████████████████████████▎                           | 1181/2057 [06:41<04:03,  3.60item/s, Completed 1181/2057]

Found 114 matched controls for ENSG00000174177
Getting matched controls for ENSG00000079785

Processing conditions:  58%|█████████████████████████████████████▍                           | 1183/2057 [06:41<03:21,  4.34item/s, Completed 1183/2057]

Found 101 matched controls for ENSG00000079785
Getting matched controls for ENSG00000170860
Found 74 matched controls for ENSG00000170860
Getting matched controls for ENSG00000188321

Processing conditions:  58%|█████████████████████████████████████▍                           | 1184/2057 [06:42<03:20,  4.36item/s, Completed 1184/2057]

Found 111 matched controls for ENSG00000188321
Getting matched controls for ENSG00000177370

Processing conditions:  58%|█████████████████████████████████████▍                           | 1185/2057 [06:42<03:18,  4.39item/s, Completed 1185/2057]

Found 78 matched controls for ENSG00000177370
Getting matched controls for ENSG00000174842

Processing conditions:  58%|█████████████████████████████████████▍                           | 1186/2057 [06:42<03:17,  4.42item/s, Completed 1186/2057]

Found 79 matched controls for ENSG00000174842
Getting matched controls for ENSG00000116688

Processing conditions:  58%|█████████████████████████████████████▌                           | 1188/2057 [06:43<03:02,  4.76item/s, Completed 1188/2057]

Found 135 matched controls for ENSG00000116688
Getting matched controls for ENSG00000198918
Found 37 matched controls for ENSG00000198918
Getting matched controls for ENSG00000163530

Processing conditions:  58%|█████████████████████████████████████▌                           | 1189/2057 [06:43<02:58,  4.87item/s, Completed 1189/2057]

Found 67 matched controls for ENSG00000163530
Getting matched controls for ENSG00000004779

Processing conditions:  58%|█████████████████████████████████████▌                           | 1190/2057 [06:43<03:22,  4.29item/s, Completed 1190/2057]

Found 160 matched controls for ENSG00000004779
Getting matched controls for ENSG00000132591

Processing conditions:  58%|█████████████████████████████████████▋                           | 1192/2057 [06:43<02:55,  4.92item/s, Completed 1192/2057]

Found 116 matched controls for ENSG00000132591
Getting matched controls for ENSG00000152240
Found 53 matched controls for ENSG00000152240
Getting matched controls for ENSG00000171720

Processing conditions:  58%|█████████████████████████████████████▋                           | 1193/2057 [06:44<02:40,  5.38item/s, Completed 1193/2057]

Found 60 matched controls for ENSG00000171720
Getting matched controls for ENSG00000063244

Processing conditions:  58%|█████████████████████████████████████▋                           | 1194/2057 [06:44<02:48,  5.11item/s, Completed 1194/2057]

Found 107 matched controls for ENSG00000063244
Getting matched controls for ENSG00000158615

Processing conditions:  58%|█████████████████████████████████████▊                           | 1195/2057 [06:44<03:05,  4.65item/s, Completed 1195/2057]

Found 135 matched controls for ENSG00000158615
Getting matched controls for ENSG00000164346

Processing conditions:  58%|█████████████████████████████████████▊                           | 1197/2057 [06:44<02:39,  5.40item/s, Completed 1197/2057]

Found 114 matched controls for ENSG00000164346
Getting matched controls for ENSG00000102144
Found 33 matched controls for ENSG00000102144
Getting matched controls for ENSG00000178966

Processing conditions:  58%|█████████████████████████████████████▉                           | 1199/2057 [06:45<02:56,  4.86item/s, Completed 1199/2057]

Found 203 matched controls for ENSG00000178966
Getting matched controls for ENSG00000103540
Found 47 matched controls for ENSG00000103540
Getting matched controls for ENSG00000167978

Processing conditions:  58%|█████████████████████████████████████▉                           | 1200/2057 [06:45<03:25,  4.18item/s, Completed 1200/2057]

Found 173 matched controls for ENSG00000167978
Getting matched controls for ENSG00000198730

Processing conditions:  58%|█████████████████████████████████████▉                           | 1202/2057 [06:46<03:37,  3.93item/s, Completed 1202/2057]

Found 212 matched controls for ENSG00000198730
Getting matched controls for ENSG00000180228
Found 78 matched controls for ENSG00000180228
Getting matched controls for ENSG00000197084

Processing conditions:  58%|██████████████████████████████████████                           | 1203/2057 [06:46<04:02,  3.52item/s, Completed 1203/2057]

Found 157 matched controls for ENSG00000197084
Getting matched controls for ENSG00000182993

Processing conditions:  59%|██████████████████████████████████████                           | 1204/2057 [06:46<03:55,  3.62item/s, Completed 1204/2057]

Found 110 matched controls for ENSG00000182993
Getting matched controls for ENSG00000110801

Processing conditions:  59%|██████████████████████████████████████                           | 1205/2057 [06:47<03:43,  3.82item/s, Completed 1205/2057]

Found 94 matched controls for ENSG00000110801
Getting matched controls for ENSG00000091140

Processing conditions:  59%|██████████████████████████████████████▏                          | 1207/2057 [06:47<04:00,  3.53item/s, Completed 1207/2057]

Found 311 matched controls for ENSG00000091140
Getting matched controls for ENSG00000108107
Found 50 matched controls for ENSG00000108107
Getting matched controls for ENSG00000181222

Processing conditions:  59%|██████████████████████████████████████▏                          | 1208/2057 [06:48<05:42,  2.48item/s, Completed 1208/2057]

Found 410 matched controls for ENSG00000181222
Getting matched controls for ENSG00000132676

Processing conditions:  59%|██████████████████████████████████████▏                          | 1209/2057 [06:48<05:15,  2.68item/s, Completed 1209/2057]

Found 162 matched controls for ENSG00000132676
Getting matched controls for ENSG00000131495

Processing conditions:  59%|██████████████████████████████████████▏                          | 1210/2057 [06:49<05:06,  2.76item/s, Completed 1210/2057]

Found 187 matched controls for ENSG00000131495
Getting matched controls for ENSG00000143379

Processing conditions:  59%|██████████████████████████████████████▎                          | 1211/2057 [06:49<04:35,  3.07item/s, Completed 1211/2057]

Found 124 matched controls for ENSG00000143379
Getting matched controls for ENSG00000108468

Processing conditions:  59%|██████████████████████████████████████▎                          | 1212/2057 [06:49<04:23,  3.20item/s, Completed 1212/2057]

Found 151 matched controls for ENSG00000108468
Getting matched controls for ENSG00000197756

Processing conditions:  59%|██████████████████████████████████████▎                          | 1214/2057 [06:50<04:43,  2.98item/s, Completed 1214/2057]

Found 386 matched controls for ENSG00000197756
Getting matched controls for ENSG00000106344
Found 68 matched controls for ENSG00000106344
Getting matched controls for ENSG00000134014

Processing conditions:  59%|██████████████████████████████████████▍                          | 1215/2057 [06:50<04:16,  3.28item/s, Completed 1215/2057]

Found 119 matched controls for ENSG00000134014
Getting matched controls for ENSG00000143624

Processing conditions:  59%|██████████████████████████████████████▍                          | 1216/2057 [06:50<03:53,  3.60item/s, Completed 1216/2057]

Found 106 matched controls for ENSG00000143624
Getting matched controls for ENSG00000242372

Processing conditions:  59%|██████████████████████████████████████▍                          | 1218/2057 [06:51<03:12,  4.37item/s, Completed 1218/2057]

Found 129 matched controls for ENSG00000242372
Getting matched controls for ENSG00000108055
Found 54 matched controls for ENSG00000108055
Getting matched controls for ENSG00000125148

Processing conditions:  59%|██████████████████████████████████████▌                          | 1219/2057 [06:51<03:10,  4.40item/s, Completed 1219/2057]

Found 112 matched controls for ENSG00000125148
Getting matched controls for ENSG00000125484

Processing conditions:  59%|██████████████████████████████████████▌                          | 1220/2057 [06:51<03:15,  4.29item/s, Completed 1220/2057]

Found 129 matched controls for ENSG00000125484
Getting matched controls for ENSG00000141867

Processing conditions:  59%|██████████████████████████████████████▌                          | 1221/2057 [06:51<03:14,  4.30item/s, Completed 1221/2057]

Found 116 matched controls for ENSG00000141867
Getting matched controls for ENSG00000131876

Processing conditions:  59%|██████████████████████████████████████▌                          | 1222/2057 [06:52<03:29,  3.98item/s, Completed 1223/2057]

Found 159 matched controls for ENSG00000131876
Getting matched controls for ENSG00000183431
Found 25 matched controls for ENSG00000183431
Getting matched controls for ENSG00000115274

Processing conditions:  60%|██████████████████████████████████████▋                          | 1224/2057 [06:52<02:54,  4.76item/s, Completed 1224/2057]

Found 116 matched controls for ENSG00000115274
Getting matched controls for ENSG00000244045

Processing conditions:  60%|██████████████████████████████████████▋                          | 1225/2057 [06:52<02:53,  4.80item/s, Completed 1225/2057]

Found 99 matched controls for ENSG00000244045
Getting matched controls for ENSG00000153037

Processing conditions:  60%|██████████████████████████████████████▊                          | 1227/2057 [06:53<02:56,  4.69item/s, Completed 1227/2057]

Found 124 matched controls for ENSG00000153037
Getting matched controls for ENSG00000093009
Found 92 matched controls for ENSG00000093009
Getting matched controls for ENSG00000136492

Processing conditions:  60%|██████████████████████████████████████▊                          | 1228/2057 [06:53<03:10,  4.35item/s, Completed 1228/2057]

Found 132 matched controls for ENSG00000136492
Getting matched controls for ENSG00000167914

Processing conditions:  60%|██████████████████████████████████████▊                          | 1229/2057 [06:53<03:07,  4.41item/s, Completed 1229/2057]

Found 110 matched controls for ENSG00000167914
Getting matched controls for ENSG00000160256

Processing conditions:  60%|██████████████████████████████████████▊                          | 1230/2057 [06:53<03:14,  4.25item/s, Completed 1230/2057]

Found 103 matched controls for ENSG00000160256
Getting matched controls for ENSG00000147416

Processing conditions:  60%|██████████████████████████████████████▉                          | 1232/2057 [06:54<04:11,  3.29item/s, Completed 1232/2057]

Found 442 matched controls for ENSG00000147416
Getting matched controls for ENSG00000276234
Found 39 matched controls for ENSG00000276234
Getting matched controls for ENSG00000041357

Processing conditions:  60%|██████████████████████████████████████▉                          | 1233/2057 [06:55<05:36,  2.45item/s, Completed 1233/2057]

Found 388 matched controls for ENSG00000041357
Getting matched controls for ENSG00000008018

Processing conditions:  60%|███████████████████████████████████████                          | 1235/2057 [06:55<04:07,  3.32item/s, Completed 1235/2057]

Found 143 matched controls for ENSG00000008018
Getting matched controls for ENSG00000266338
Found 62 matched controls for ENSG00000266338
Getting matched controls for ENSG00000163902

Processing conditions:  60%|███████████████████████████████████████                          | 1236/2057 [06:56<03:30,  3.90item/s, Completed 1236/2057]

Found 52 matched controls for ENSG00000163902
Getting matched controls for ENSG00000136710

Processing conditions:  60%|███████████████████████████████████████                          | 1237/2057 [06:56<04:35,  2.98item/s, Completed 1237/2057]

Found 211 matched controls for ENSG00000136710
Getting matched controls for ENSG00000197713

Processing conditions:  60%|███████████████████████████████████████▏                         | 1239/2057 [06:56<03:29,  3.90item/s, Completed 1239/2057]

Found 118 matched controls for ENSG00000197713
Getting matched controls for ENSG00000147536
Found 60 matched controls for ENSG00000147536
Getting matched controls for ENSG00000204394

Processing conditions:  60%|███████████████████████████████████████▏                         | 1240/2057 [06:57<04:02,  3.38item/s, Completed 1240/2057]

Found 220 matched controls for ENSG00000204394
Getting matched controls for ENSG00000108592

Processing conditions:  60%|███████████████████████████████████████▏                         | 1241/2057 [06:57<04:20,  3.13item/s, Completed 1241/2057]

Found 207 matched controls for ENSG00000108592
Getting matched controls for ENSG00000164091

Processing conditions:  60%|███████████████████████████████████████▏                         | 1242/2057 [06:57<03:51,  3.52item/s, Completed 1242/2057]

Found 99 matched controls for ENSG00000164091
Getting matched controls for ENSG00000132952

Processing conditions:  60%|███████████████████████████████████████▎                         | 1243/2057 [06:58<03:32,  3.83item/s, Completed 1243/2057]

Found 100 matched controls for ENSG00000132952
Getting matched controls for ENSG00000186141

Processing conditions:  61%|███████████████████████████████████████▎                         | 1245/2057 [06:58<03:26,  3.94item/s, Completed 1245/2057]

Found 175 matched controls for ENSG00000186141
Getting matched controls for ENSG00000092201
Found 93 matched controls for ENSG00000092201
Getting matched controls for ENSG00000025796

Processing conditions:  61%|███████████████████████████████████████▎                         | 1246/2057 [06:58<03:06,  4.36item/s, Completed 1246/2057]

Found 78 matched controls for ENSG00000025796
Getting matched controls for ENSG00000166986

Processing conditions:  61%|███████████████████████████████████████▍                         | 1247/2057 [06:59<03:05,  4.37item/s, Completed 1248/2057]

Found 89 matched controls for ENSG00000166986
Getting matched controls for ENSG00000110619
Found 19 matched controls for ENSG00000110619
Getting matched controls for ENSG00000144744

Processing conditions:  61%|███████████████████████████████████████▍                         | 1249/2057 [06:59<02:32,  5.29item/s, Completed 1249/2057]

Found 95 matched controls for ENSG00000144744
Getting matched controls for ENSG00000143368

Processing conditions:  61%|███████████████████████████████████████▌                         | 1251/2057 [06:59<03:03,  4.40item/s, Completed 1251/2057]

Found 238 matched controls for ENSG00000143368
Getting matched controls for ENSG00000178035
Found 77 matched controls for ENSG00000178035
Getting matched controls for ENSG00000118579

Processing conditions:  61%|███████████████████████████████████████▌                         | 1253/2057 [07:00<02:41,  4.97item/s, Completed 1253/2057]

Found 73 matched controls for ENSG00000118579
Getting matched controls for ENSG00000179409
Found 81 matched controls for ENSG00000179409
Getting matched controls for ENSG00000130741

Processing conditions:  61%|███████████████████████████████████████▋                         | 1254/2057 [07:00<02:28,  5.41item/s, Completed 1254/2057]

Found 57 matched controls for ENSG00000130741
Getting matched controls for ENSG00000150990

Processing conditions:  61%|███████████████████████████████████████▋                         | 1255/2057 [07:00<03:15,  4.10item/s, Completed 1255/2057]

Found 217 matched controls for ENSG00000150990
Getting matched controls for ENSG00000023734

Processing conditions:  61%|███████████████████████████████████████▋                         | 1256/2057 [07:01<03:08,  4.25item/s, Completed 1256/2057]

Found 106 matched controls for ENSG00000023734
Getting matched controls for ENSG00000101181

Processing conditions:  61%|███████████████████████████████████████▊                         | 1258/2057 [07:01<03:01,  4.41item/s, Completed 1258/2057]

Found 146 matched controls for ENSG00000101181
Getting matched controls for ENSG00000134809
Found 54 matched controls for ENSG00000134809
Getting matched controls for ENSG00000167508

Processing conditions:  61%|███████████████████████████████████████▊                         | 1259/2057 [07:01<03:07,  4.25item/s, Completed 1259/2057]

Found 104 matched controls for ENSG00000167508
Getting matched controls for ENSG00000089157

Processing conditions:  61%|███████████████████████████████████████▊                         | 1260/2057 [07:02<03:31,  3.76item/s, Completed 1260/2057]

Found 184 matched controls for ENSG00000089157
Getting matched controls for ENSG00000134371

Processing conditions:  61%|███████████████████████████████████████▊                         | 1261/2057 [07:02<03:51,  3.44item/s, Completed 1261/2057]

Found 171 matched controls for ENSG00000134371
Getting matched controls for ENSG00000160803

Processing conditions:  61%|███████████████████████████████████████▉                         | 1262/2057 [07:02<04:02,  3.27item/s, Completed 1262/2057]

Found 152 matched controls for ENSG00000160803
Getting matched controls for ENSG00000073050

Processing conditions:  61%|███████████████████████████████████████▉                         | 1264/2057 [07:03<04:08,  3.20item/s, Completed 1264/2057]

Found 254 matched controls for ENSG00000073050
Getting matched controls for ENSG00000103047
Found 95 matched controls for ENSG00000103047
Getting matched controls for ENSG00000150459

Processing conditions:  61%|███████████████████████████████████████▉                         | 1265/2057 [07:03<03:26,  3.83item/s, Completed 1265/2057]

Found 57 matched controls for ENSG00000150459
Getting matched controls for ENSG00000163041

Processing conditions:  62%|████████████████████████████████████████                         | 1266/2057 [07:04<04:12,  3.13item/s, Completed 1266/2057]

Found 237 matched controls for ENSG00000163041
Getting matched controls for ENSG00000072501

Processing conditions:  62%|████████████████████████████████████████                         | 1268/2057 [07:04<03:40,  3.58item/s, Completed 1268/2057]

Found 180 matched controls for ENSG00000072501
Getting matched controls for ENSG00000152464
Found 56 matched controls for ENSG00000152464
Getting matched controls for ENSG00000109606

Processing conditions:  62%|████████████████████████████████████████▏                        | 1270/2057 [07:05<04:03,  3.23item/s, Completed 1270/2057]

Found 359 matched controls for ENSG00000109606
Getting matched controls for ENSG00000163938
Found 38 matched controls for ENSG00000163938
Getting matched controls for ENSG00000078142

Processing conditions:  62%|████████████████████████████████████████▏                        | 1271/2057 [07:05<03:44,  3.51item/s, Completed 1271/2057]

Found 115 matched controls for ENSG00000078142
Getting matched controls for ENSG00000162923

Processing conditions:  62%|████████████████████████████████████████▏                        | 1272/2057 [07:05<04:11,  3.13item/s, Completed 1272/2057]

Found 226 matched controls for ENSG00000162923
Getting matched controls for ENSG00000239305

Processing conditions:  62%|████████████████████████████████████████▏                        | 1273/2057 [07:06<03:52,  3.37item/s, Completed 1273/2057]

Found 111 matched controls for ENSG00000239305
Getting matched controls for ENSG00000213066

Processing conditions:  62%|████████████████████████████████████████▎                        | 1274/2057 [07:06<03:58,  3.29item/s, Completed 1274/2057]

Found 119 matched controls for ENSG00000213066
Getting matched controls for ENSG00000080986

Processing conditions:  62%|████████████████████████████████████████▎                        | 1275/2057 [07:07<04:39,  2.80item/s, Completed 1275/2057]

Found 214 matched controls for ENSG00000080986
Getting matched controls for ENSG00000115947

Processing conditions:  62%|████████████████████████████████████████▎                        | 1276/2057 [07:07<04:11,  3.10item/s, Completed 1276/2057]

Found 95 matched controls for ENSG00000115947
Getting matched controls for ENSG00000051596

Processing conditions:  62%|████████████████████████████████████████▍                        | 1278/2057 [07:07<03:19,  3.90item/s, Completed 1278/2057]

Found 147 matched controls for ENSG00000051596
Getting matched controls for ENSG00000167553
Found 51 matched controls for ENSG00000167553
Getting matched controls for ENSG00000018699

Processing conditions:  62%|████████████████████████████████████████▍                        | 1279/2057 [07:07<03:15,  3.97item/s, Completed 1279/2057]

Found 89 matched controls for ENSG00000018699
Getting matched controls for ENSG00000130348

Processing conditions:  62%|████████████████████████████████████████▍                        | 1281/2057 [07:08<02:57,  4.37item/s, Completed 1281/2057]

Found 126 matched controls for ENSG00000130348
Getting matched controls for ENSG00000214113
Found 70 matched controls for ENSG00000214113
Getting matched controls for ENSG00000273611

Processing conditions:  62%|████████████████████████████████████████▌                        | 1282/2057 [07:08<02:51,  4.51item/s, Completed 1282/2057]

Found 72 matched controls for ENSG00000273611
Getting matched controls for ENSG00000065268

Processing conditions:  62%|████████████████████████████████████████▌                        | 1284/2057 [07:08<02:38,  4.87item/s, Completed 1284/2057]

Found 105 matched controls for ENSG00000065268
Getting matched controls for ENSG00000119707
Found 70 matched controls for ENSG00000119707
Getting matched controls for ENSG00000123349

Processing conditions:  62%|████████████████████████████████████████▌                        | 1285/2057 [07:09<02:42,  4.76item/s, Completed 1285/2057]

Found 110 matched controls for ENSG00000123349
Getting matched controls for ENSG00000140105

Processing conditions:  63%|████████████████████████████████████████▋                        | 1286/2057 [07:09<02:41,  4.77item/s, Completed 1286/2057]

Found 76 matched controls for ENSG00000140105
Getting matched controls for ENSG00000080603

Processing conditions:  63%|████████████████████████████████████████▋                        | 1287/2057 [07:09<03:13,  3.98item/s, Completed 1287/2057]

Found 194 matched controls for ENSG00000080603
Getting matched controls for ENSG00000154727

Processing conditions:  63%|████████████████████████████████████████▋                        | 1288/2057 [07:09<03:06,  4.11item/s, Completed 1288/2057]

Found 110 matched controls for ENSG00000154727
Getting matched controls for ENSG00000112306

Processing conditions:  63%|████████████████████████████████████████▋                        | 1289/2057 [07:10<05:26,  2.35item/s, Completed 1289/2057]

Found 485 matched controls for ENSG00000112306
Getting matched controls for ENSG00000184209

Processing conditions:  63%|████████████████████████████████████████▊                        | 1291/2057 [07:11<04:15,  3.00item/s, Completed 1291/2057]

Found 168 matched controls for ENSG00000184209
Getting matched controls for ENSG00000124789
Found 86 matched controls for ENSG00000124789
Getting matched controls for ENSG00000151465

Processing conditions:  63%|████████████████████████████████████████▊                        | 1292/2057 [07:11<03:49,  3.33item/s, Completed 1292/2057]

Found 112 matched controls for ENSG00000151465
Getting matched controls for ENSG00000155229

Processing conditions:  63%|████████████████████████████████████████▊                        | 1293/2057 [07:11<03:42,  3.43item/s, Completed 1293/2057]

Found 129 matched controls for ENSG00000155229
Getting matched controls for ENSG00000065183

Processing conditions:  63%|████████████████████████████████████████▉                        | 1295/2057 [07:12<04:20,  2.93item/s, Completed 1295/2057]

Found 365 matched controls for ENSG00000065183
Getting matched controls for ENSG00000163811
Found 86 matched controls for ENSG00000163811
Getting matched controls for ENSG00000182899

Processing conditions:  63%|████████████████████████████████████████▉                        | 1296/2057 [07:12<04:21,  2.91item/s, Completed 1296/2057]

Found 137 matched controls for ENSG00000182899
Getting matched controls for ENSG00000273749

Processing conditions:  63%|████████████████████████████████████████▉                        | 1297/2057 [07:13<04:02,  3.13item/s, Completed 1297/2057]

Found 111 matched controls for ENSG00000273749
Getting matched controls for ENSG00000231500

Processing conditions:  63%|█████████████████████████████████████████                        | 1298/2057 [07:13<03:54,  3.24item/s, Completed 1298/2057]

Found 122 matched controls for ENSG00000231500
Getting matched controls for ENSG00000254999

Processing conditions:  63%|█████████████████████████████████████████                        | 1299/2057 [07:13<04:06,  3.07item/s, Completed 1299/2057]

Found 180 matched controls for ENSG00000254999
Getting matched controls for ENSG00000120686

Processing conditions:  63%|█████████████████████████████████████████                        | 1300/2057 [07:14<04:01,  3.13item/s, Completed 1300/2057]

Found 130 matched controls for ENSG00000120686
Getting matched controls for ENSG00000131558

Processing conditions:  63%|█████████████████████████████████████████                        | 1301/2057 [07:14<03:52,  3.25item/s, Completed 1301/2057]

Found 108 matched controls for ENSG00000131558
Getting matched controls for ENSG00000102145

Processing conditions:  63%|█████████████████████████████████████████▏                       | 1302/2057 [07:14<03:34,  3.52item/s, Completed 1303/2057]

Found 108 matched controls for ENSG00000102145
Getting matched controls for ENSG00000112984
Found 96 matched controls for ENSG00000112984

Processing conditions:  63%|█████████████████████████████████████████▏                       | 1303/2057 [07:15<03:15,  3.86item/s, Completed 1304/2057]

Getting matched controls for ENSG00000116903
Found 18 matched controls for ENSG00000116903
Getting matched controls for ENSG00000115211

Processing conditions:  63%|█████████████████████████████████████████▏                       | 1305/2057 [07:15<03:38,  3.45item/s, Completed 1305/2057]

Found 324 matched controls for ENSG00000115211
Getting matched controls for ENSG00000169398

Processing conditions:  63%|█████████████████████████████████████████▎                       | 1306/2057 [07:15<03:34,  3.50item/s, Completed 1306/2057]

Found 144 matched controls for ENSG00000169398
Getting matched controls for ENSG00000203661

Processing conditions:  64%|█████████████████████████████████████████▎                       | 1307/2057 [07:16<03:20,  3.75item/s, Completed 1307/2057]

Found 106 matched controls for ENSG00000203661
Getting matched controls for ENSG00000147679

Processing conditions:  64%|█████████████████████████████████████████▎                       | 1308/2057 [07:16<03:31,  3.55item/s, Completed 1308/2057]

Found 163 matched controls for ENSG00000147679
Getting matched controls for ENSG00000197223

Processing conditions:  64%|█████████████████████████████████████████▎                       | 1309/2057 [07:16<03:34,  3.49item/s, Completed 1309/2057]

Found 160 matched controls for ENSG00000197223
Getting matched controls for ENSG00000125449

Processing conditions:  64%|█████████████████████████████████████████▍                       | 1311/2057 [07:17<02:51,  4.35item/s, Completed 1311/2057]

Found 110 matched controls for ENSG00000125449
Getting matched controls for ENSG00000128463
Found 55 matched controls for ENSG00000128463
Getting matched controls for ENSG00000270800

Processing conditions:  64%|█████████████████████████████████████████▍                       | 1312/2057 [07:17<03:12,  3.87item/s, Completed 1312/2057]

Found 164 matched controls for ENSG00000270800
Getting matched controls for ENSG00000081307

Processing conditions:  64%|█████████████████████████████████████████▌                       | 1314/2057 [07:17<02:37,  4.72item/s, Completed 1314/2057]

Found 102 matched controls for ENSG00000081307
Getting matched controls for ENSG00000107371
Found 53 matched controls for ENSG00000107371
Getting matched controls for ENSG00000088766

Processing conditions:  64%|█████████████████████████████████████████▌                       | 1316/2057 [07:18<02:25,  5.10item/s, Completed 1316/2057]

Found 111 matched controls for ENSG00000088766
Getting matched controls for ENSG00000172046
Found 65 matched controls for ENSG00000172046
Getting matched controls for ENSG00000165684

Processing conditions:  64%|█████████████████████████████████████████▋                       | 1318/2057 [07:18<02:24,  5.10item/s, Completed 1318/2057]

Found 104 matched controls for ENSG00000165684
Getting matched controls for ENSG00000184162
Found 86 matched controls for ENSG00000184162
Getting matched controls for ENSG00000123219

Processing conditions:  64%|█████████████████████████████████████████▋                       | 1319/2057 [07:18<02:25,  5.07item/s, Completed 1319/2057]

Found 97 matched controls for ENSG00000123219
Getting matched controls for ENSG00000119729

Processing conditions:  64%|█████████████████████████████████████████▋                       | 1320/2057 [07:19<02:56,  4.18item/s, Completed 1320/2057]

Found 185 matched controls for ENSG00000119729
Getting matched controls for ENSG00000075089

Processing conditions:  64%|█████████████████████████████████████████▊                       | 1322/2057 [07:19<02:38,  4.65item/s, Completed 1322/2057]

Found 108 matched controls for ENSG00000075089
Getting matched controls for ENSG00000185883
Found 53 matched controls for ENSG00000185883
Getting matched controls for ENSG00000125651

Processing conditions:  64%|█████████████████████████████████████████▊                       | 1324/2057 [07:19<02:21,  5.17item/s, Completed 1324/2057]

Found 41 matched controls for ENSG00000125651
Getting matched controls for ENSG00000102898
Found 67 matched controls for ENSG00000102898
Getting matched controls for ENSG00000181817

Processing conditions:  64%|█████████████████████████████████████████▊                       | 1325/2057 [07:20<02:36,  4.67item/s, Completed 1325/2057]

Found 135 matched controls for ENSG00000181817
Getting matched controls for ENSG00000173436

Processing conditions:  64%|█████████████████████████████████████████▉                       | 1326/2057 [07:20<02:35,  4.71item/s, Completed 1326/2057]

Found 87 matched controls for ENSG00000173436
Getting matched controls for ENSG00000159055

Processing conditions:  65%|█████████████████████████████████████████▉                       | 1327/2057 [07:20<03:00,  4.06item/s, Completed 1327/2057]

Found 129 matched controls for ENSG00000159055
Getting matched controls for ENSG00000092010

Processing conditions:  65%|█████████████████████████████████████████▉                       | 1329/2057 [07:20<02:44,  4.42item/s, Completed 1329/2057]

Found 121 matched controls for ENSG00000092010
Getting matched controls for ENSG00000140992
Found 80 matched controls for ENSG00000140992
Getting matched controls for ENSG00000105700

Processing conditions:  65%|██████████████████████████████████████████                       | 1330/2057 [07:21<02:40,  4.53item/s, Completed 1330/2057]

Found 101 matched controls for ENSG00000105700
Getting matched controls for ENSG00000080823

Processing conditions:  65%|██████████████████████████████████████████                       | 1331/2057 [07:21<02:44,  4.41item/s, Completed 1331/2057]

Found 123 matched controls for ENSG00000080823
Getting matched controls for ENSG00000109118

Processing conditions:  65%|██████████████████████████████████████████                       | 1332/2057 [07:21<02:43,  4.44item/s, Completed 1332/2057]

Found 110 matched controls for ENSG00000109118
Getting matched controls for ENSG00000145736

Processing conditions:  65%|██████████████████████████████████████████                       | 1333/2057 [07:21<02:57,  4.07item/s, Completed 1333/2057]

Found 156 matched controls for ENSG00000145736
Getting matched controls for ENSG00000074071

Processing conditions:  65%|██████████████████████████████████████████▏                      | 1335/2057 [07:22<02:34,  4.69item/s, Completed 1335/2057]

Found 141 matched controls for ENSG00000074071
Getting matched controls for ENSG00000163608
Found 42 matched controls for ENSG00000163608
Getting matched controls for ENSG00000136718

Processing conditions:  65%|██████████████████████████████████████████▏                      | 1336/2057 [07:22<02:53,  4.16item/s, Completed 1336/2057]

Found 164 matched controls for ENSG00000136718
Getting matched controls for ENSG00000266472

Processing conditions:  65%|██████████████████████████████████████████▎                      | 1338/2057 [07:23<02:49,  4.24item/s, Completed 1338/2057]

Found 146 matched controls for ENSG00000266472
Getting matched controls for ENSG00000143947
Found 97 matched controls for ENSG00000143947
Getting matched controls for ENSG00000183979

Processing conditions:  65%|██████████████████████████████████████████▎                      | 1339/2057 [07:23<03:14,  3.69item/s, Completed 1339/2057]

Found 196 matched controls for ENSG00000183979
Getting matched controls for ENSG00000165417

Processing conditions:  65%|██████████████████████████████████████████▎                      | 1341/2057 [07:23<02:42,  4.40item/s, Completed 1341/2057]

Found 113 matched controls for ENSG00000165417
Getting matched controls for ENSG00000145912
Found 66 matched controls for ENSG00000145912
Getting matched controls for ENSG00000029363

Processing conditions:  65%|██████████████████████████████████████████▍                      | 1342/2057 [07:24<02:30,  4.75item/s, Completed 1342/2057]

Found 51 matched controls for ENSG00000029363
Getting matched controls for ENSG00000010244

Processing conditions:  65%|██████████████████████████████████████████▍                      | 1343/2057 [07:24<03:29,  3.40item/s, Completed 1343/2057]

Found 283 matched controls for ENSG00000010244
Getting matched controls for ENSG00000112118

Processing conditions:  65%|██████████████████████████████████████████▌                      | 1345/2057 [07:24<02:55,  4.06item/s, Completed 1345/2057]

Found 124 matched controls for ENSG00000112118
Getting matched controls for ENSG00000196455
Found 77 matched controls for ENSG00000196455
Getting matched controls for ENSG00000188486

Processing conditions:  65%|██████████████████████████████████████████▌                      | 1347/2057 [07:25<02:42,  4.36item/s, Completed 1347/2057]

Found 139 matched controls for ENSG00000188486
Getting matched controls for ENSG00000151503
Found 81 matched controls for ENSG00000151503
Getting matched controls for ENSG00000117748

Processing conditions:  66%|██████████████████████████████████████████▌                      | 1348/2057 [07:25<03:18,  3.57item/s, Completed 1348/2057]

Found 225 matched controls for ENSG00000117748
Getting matched controls for ENSG00000177885

Processing conditions:  66%|██████████████████████████████████████████▋                      | 1350/2057 [07:26<02:58,  3.95item/s, Completed 1350/2057]

Found 169 matched controls for ENSG00000177885
Getting matched controls for ENSG00000154839
Found 68 matched controls for ENSG00000154839
Getting matched controls for ENSG00000182004

Processing conditions:  66%|██████████████████████████████████████████▋                      | 1352/2057 [07:26<02:38,  4.44item/s, Completed 1352/2057]

Found 184 matched controls for ENSG00000182004
Getting matched controls for ENSG00000240682
Found 30 matched controls for ENSG00000240682
Getting matched controls for ENSG00000168653

Processing conditions:  66%|██████████████████████████████████████████▊                      | 1354/2057 [07:27<02:40,  4.39item/s, Completed 1355/2057]

Found 195 matched controls for ENSG00000168653
Getting matched controls for ENSG00000100890
Found 42 matched controls for ENSG00000100890
Getting matched controls for ENSG00000105402
Found 12 matched controls for ENSG00000105402
Getting matched controls for ENSG00000203852

Processing conditions:  66%|██████████████████████████████████████████▊                      | 1356/2057 [07:27<02:05,  5.57item/s, Completed 1356/2057]

Found 79 matched controls for ENSG00000203852
Getting matched controls for ENSG00000172171

Processing conditions:  66%|██████████████████████████████████████████▉                      | 1357/2057 [07:27<02:38,  4.43item/s, Completed 1357/2057]

Found 203 matched controls for ENSG00000172171
Getting matched controls for ENSG00000171421

Processing conditions:  66%|██████████████████████████████████████████▉                      | 1358/2057 [07:28<03:03,  3.82item/s, Completed 1358/2057]

Found 189 matched controls for ENSG00000171421
Getting matched controls for ENSG00000112701

Processing conditions:  66%|██████████████████████████████████████████▉                      | 1360/2057 [07:28<02:39,  4.37item/s, Completed 1360/2057]

Found 94 matched controls for ENSG00000112701
Getting matched controls for ENSG00000176102
Found 66 matched controls for ENSG00000176102
Getting matched controls for ENSG00000139436

Processing conditions:  66%|███████████████████████████████████████████                      | 1361/2057 [07:28<02:46,  4.18item/s, Completed 1361/2057]

Found 107 matched controls for ENSG00000139436
Getting matched controls for ENSG00000125352

Processing conditions:  66%|███████████████████████████████████████████                      | 1362/2057 [07:29<03:10,  3.64item/s, Completed 1362/2057]

Found 176 matched controls for ENSG00000125352
Getting matched controls for ENSG00000123297

Processing conditions:  66%|███████████████████████████████████████████                      | 1363/2057 [07:29<03:01,  3.83item/s, Completed 1363/2057]

Found 98 matched controls for ENSG00000123297
Getting matched controls for ENSG00000075415

Processing conditions:  66%|███████████████████████████████████████████                      | 1364/2057 [07:29<03:04,  3.76item/s, Completed 1364/2057]

Found 114 matched controls for ENSG00000075415
Getting matched controls for ENSG00000139719

Processing conditions:  66%|███████████████████████████████████████████▏                     | 1365/2057 [07:30<03:23,  3.40item/s, Completed 1365/2057]

Found 182 matched controls for ENSG00000139719
Getting matched controls for ENSG00000160606

Processing conditions:  66%|███████████████████████████████████████████▏                     | 1367/2057 [07:30<03:06,  3.69item/s, Completed 1367/2057]

Found 155 matched controls for ENSG00000160606
Getting matched controls for ENSG00000196109
Found 89 matched controls for ENSG00000196109
Getting matched controls for ENSG00000120656

Processing conditions:  67%|███████████████████████████████████████████▏                     | 1368/2057 [07:30<02:47,  4.11item/s, Completed 1368/2057]

Found 67 matched controls for ENSG00000120656
Getting matched controls for ENSG00000135249

Processing conditions:  67%|███████████████████████████████████████████▎                     | 1369/2057 [07:31<03:02,  3.76item/s, Completed 1369/2057]

Found 145 matched controls for ENSG00000135249
Getting matched controls for ENSG00000180182

Processing conditions:  67%|███████████████████████████████████████████▎                     | 1370/2057 [07:31<03:03,  3.75item/s, Completed 1370/2057]

Found 117 matched controls for ENSG00000180182
Getting matched controls for ENSG00000124659

Processing conditions:  67%|███████████████████████████████████████████▎                     | 1371/2057 [07:31<03:03,  3.74item/s, Completed 1371/2057]

Found 141 matched controls for ENSG00000124659
Getting matched controls for ENSG00000168028

Processing conditions:  67%|███████████████████████████████████████████▍                     | 1373/2057 [07:32<02:54,  3.93item/s, Completed 1373/2057]

Found 224 matched controls for ENSG00000168028
Getting matched controls for ENSG00000126215
Found 53 matched controls for ENSG00000126215
Getting matched controls for ENSG00000152147

Processing conditions:  67%|███████████████████████████████████████████▍                     | 1374/2057 [07:32<02:41,  4.24item/s, Completed 1374/2057]

Found 84 matched controls for ENSG00000152147
Getting matched controls for ENSG00000115816

Processing conditions:  67%|███████████████████████████████████████████▍                     | 1376/2057 [07:32<02:29,  4.56item/s, Completed 1376/2057]

Found 113 matched controls for ENSG00000115816
Getting matched controls for ENSG00000119392
Found 57 matched controls for ENSG00000119392
Getting matched controls for ENSG00000162236

Processing conditions:  67%|███████████████████████████████████████████▌                     | 1378/2057 [07:33<02:12,  5.12item/s, Completed 1378/2057]

Found 51 matched controls for ENSG00000162236
Getting matched controls for ENSG00000066379
Found 81 matched controls for ENSG00000066379
Getting matched controls for ENSG00000086598

Processing conditions:  67%|███████████████████████████████████████████▌                     | 1380/2057 [07:33<02:23,  4.73item/s, Completed 1380/2057]

Found 137 matched controls for ENSG00000086598
Getting matched controls for ENSG00000025800
Found 78 matched controls for ENSG00000025800
Getting matched controls for ENSG00000165502

Processing conditions:  67%|███████████████████████████████████████████▋                     | 1381/2057 [07:33<02:42,  4.15item/s, Completed 1381/2057]

Found 152 matched controls for ENSG00000165502
Getting matched controls for ENSG00000115368

Processing conditions:  67%|███████████████████████████████████████████▋                     | 1382/2057 [07:34<02:56,  3.82item/s, Completed 1382/2057]

Found 158 matched controls for ENSG00000115368
Getting matched controls for ENSG00000064313

Processing conditions:  67%|███████████████████████████████████████████▋                     | 1383/2057 [07:34<02:58,  3.78item/s, Completed 1383/2057]

Found 144 matched controls for ENSG00000064313
Getting matched controls for ENSG00000129083

Processing conditions:  67%|███████████████████████████████████████████▋                     | 1384/2057 [07:34<02:53,  3.87item/s, Completed 1384/2057]

Found 91 matched controls for ENSG00000129083
Getting matched controls for ENSG00000173120

Processing conditions:  67%|███████████████████████████████████████████▊                     | 1385/2057 [07:34<02:59,  3.74item/s, Completed 1385/2057]

Found 117 matched controls for ENSG00000173120
Getting matched controls for ENSG00000139726

Processing conditions:  67%|███████████████████████████████████████████▊                     | 1386/2057 [07:35<03:38,  3.07item/s, Completed 1386/2057]

Found 251 matched controls for ENSG00000139726
Getting matched controls for ENSG00000185201

Processing conditions:  67%|███████████████████████████████████████████▊                     | 1387/2057 [07:35<03:35,  3.11item/s, Completed 1387/2057]

Found 150 matched controls for ENSG00000185201
Getting matched controls for ENSG00000145425

Processing conditions:  68%|███████████████████████████████████████████▉                     | 1389/2057 [07:36<03:12,  3.47item/s, Completed 1389/2057]

Found 160 matched controls for ENSG00000145425
Getting matched controls for ENSG00000196363
Found 78 matched controls for ENSG00000196363
Getting matched controls for ENSG00000163872

Processing conditions:  68%|███████████████████████████████████████████▉                     | 1390/2057 [07:36<03:45,  2.95item/s, Completed 1390/2057]

Found 240 matched controls for ENSG00000163872
Getting matched controls for ENSG00000250312

Processing conditions:  68%|███████████████████████████████████████████▉                     | 1392/2057 [07:37<03:40,  3.02item/s, Completed 1392/2057]

Found 330 matched controls for ENSG00000250312
Getting matched controls for ENSG00000106588
Found 64 matched controls for ENSG00000106588
Getting matched controls for ENSG00000009413

Processing conditions:  68%|████████████████████████████████████████████                     | 1393/2057 [07:37<03:16,  3.38item/s, Completed 1393/2057]

Found 101 matched controls for ENSG00000009413
Getting matched controls for ENSG00000132341

Processing conditions:  68%|████████████████████████████████████████████                     | 1394/2057 [07:38<03:27,  3.19item/s, Completed 1394/2057]

Found 193 matched controls for ENSG00000132341
Getting matched controls for ENSG00000138035

Processing conditions:  68%|████████████████████████████████████████████                     | 1395/2057 [07:38<03:15,  3.38item/s, Completed 1395/2057]

Found 131 matched controls for ENSG00000138035
Getting matched controls for ENSG00000253368

Processing conditions:  68%|████████████████████████████████████████████▏                    | 1397/2057 [07:38<02:49,  3.90item/s, Completed 1397/2057]

Found 156 matched controls for ENSG00000253368
Getting matched controls for ENSG00000187051
Found 54 matched controls for ENSG00000187051
Getting matched controls for ENSG00000108883

Processing conditions:  68%|████████████████████████████████████████████▏                    | 1399/2057 [07:39<02:25,  4.52item/s, Completed 1399/2057]

Found 127 matched controls for ENSG00000108883
Getting matched controls for ENSG00000121621
Found 47 matched controls for ENSG00000121621
Getting matched controls for ENSG00000180817

Processing conditions:  68%|████████████████████████████████████████████▏                    | 1400/2057 [07:39<02:35,  4.22item/s, Completed 1400/2057]

Found 143 matched controls for ENSG00000180817
Getting matched controls for ENSG00000100554

Processing conditions:  68%|████████████████████████████████████████████▎                    | 1401/2057 [07:39<03:06,  3.52item/s, Completed 1401/2057]

Found 139 matched controls for ENSG00000100554
Getting matched controls for ENSG00000156097

Processing conditions:  68%|████████████████████████████████████████████▎                    | 1402/2057 [07:40<02:54,  3.75item/s, Completed 1402/2057]

Found 112 matched controls for ENSG00000156097
Getting matched controls for ENSG00000006715

Processing conditions:  68%|████████████████████████████████████████████▎                    | 1404/2057 [07:40<03:13,  3.38item/s, Completed 1404/2057]

Found 332 matched controls for ENSG00000006715
Getting matched controls for ENSG00000175166
Found 63 matched controls for ENSG00000175166
Getting matched controls for ENSG00000242485

Processing conditions:  68%|████████████████████████████████████████████▍                    | 1406/2057 [07:41<02:27,  4.41item/s, Completed 1406/2057]

Found 120 matched controls for ENSG00000242485
Getting matched controls for ENSG00000114942
Found 32 matched controls for ENSG00000114942
Getting matched controls for ENSG00000197838

Processing conditions:  68%|████████████████████████████████████████████▍                    | 1407/2057 [07:41<02:35,  4.17item/s, Completed 1407/2057]

Found 140 matched controls for ENSG00000197838
Getting matched controls for ENSG00000012048

Processing conditions:  68%|████████████████████████████████████████████▍                    | 1408/2057 [07:41<02:31,  4.30item/s, Completed 1408/2057]

Found 104 matched controls for ENSG00000012048
Getting matched controls for ENSG00000161800

Processing conditions:  68%|████████████████████████████████████████████▌                    | 1409/2057 [07:41<02:50,  3.79item/s, Completed 1409/2057]

Found 175 matched controls for ENSG00000161800
Getting matched controls for ENSG00000105447

Processing conditions:  69%|████████████████████████████████████████████▌                    | 1411/2057 [07:42<02:31,  4.25item/s, Completed 1411/2057]

Found 189 matched controls for ENSG00000105447
Getting matched controls for ENSG00000158545
Found 32 matched controls for ENSG00000158545
Getting matched controls for ENSG00000137807

Processing conditions:  69%|████████████████████████████████████████████▌                    | 1412/2057 [07:42<02:23,  4.49item/s, Completed 1412/2057]

Found 87 matched controls for ENSG00000137807
Getting matched controls for ENSG00000188986

Processing conditions:  69%|████████████████████████████████████████████▋                    | 1413/2057 [07:42<02:33,  4.19item/s, Completed 1413/2057]

Found 140 matched controls for ENSG00000188986
Getting matched controls for ENSG00000099783

Processing conditions:  69%|████████████████████████████████████████████▋                    | 1414/2057 [07:43<03:15,  3.29item/s, Completed 1414/2057]

Found 258 matched controls for ENSG00000099783
Getting matched controls for ENSG00000162851

Processing conditions:  69%|████████████████████████████████████████████▋                    | 1416/2057 [07:43<02:43,  3.93item/s, Completed 1416/2057]

Found 162 matched controls for ENSG00000162851
Getting matched controls for ENSG00000105193
Found 57 matched controls for ENSG00000105193
Getting matched controls for ENSG00000257365

Processing conditions:  69%|████████████████████████████████████████████▊                    | 1418/2057 [07:44<02:24,  4.41item/s, Completed 1418/2057]

Found 102 matched controls for ENSG00000257365
Getting matched controls for ENSG00000100297
Found 90 matched controls for ENSG00000100297
Getting matched controls for ENSG00000135776

Processing conditions:  69%|████████████████████████████████████████████▊                    | 1419/2057 [07:44<02:06,  5.05item/s, Completed 1419/2057]

Found 51 matched controls for ENSG00000135776
Getting matched controls for ENSG00000142676

Processing conditions:  69%|████████████████████████████████████████████▊                    | 1420/2057 [07:44<03:32,  3.00item/s, Completed 1420/2057]

Found 387 matched controls for ENSG00000142676
Getting matched controls for ENSG00000181029

Processing conditions:  69%|████████████████████████████████████████████▉                    | 1422/2057 [07:45<02:46,  3.82item/s, Completed 1422/2057]

Found 132 matched controls for ENSG00000181029
Getting matched controls for ENSG00000108344
Found 64 matched controls for ENSG00000108344
Getting matched controls for ENSG00000100129

Processing conditions:  69%|████████████████████████████████████████████▉                    | 1423/2057 [07:45<02:22,  4.44item/s, Completed 1423/2057]

Found 57 matched controls for ENSG00000100129
Getting matched controls for ENSG00000173531

Processing conditions:  69%|████████████████████████████████████████████▉                    | 1424/2057 [07:45<02:29,  4.22item/s, Completed 1424/2057]

Found 134 matched controls for ENSG00000173531
Getting matched controls for ENSG00000147133

Processing conditions:  69%|█████████████████████████████████████████████                    | 1425/2057 [07:46<02:29,  4.23item/s, Completed 1425/2057]

Found 97 matched controls for ENSG00000147133
Getting matched controls for ENSG00000105085

Processing conditions:  69%|█████████████████████████████████████████████                    | 1426/2057 [07:46<02:27,  4.28item/s, Completed 1426/2057]

Found 105 matched controls for ENSG00000105085
Getting matched controls for ENSG00000117410

Processing conditions:  69%|█████████████████████████████████████████████                    | 1427/2057 [07:46<02:38,  3.97item/s, Completed 1427/2057]

Found 147 matched controls for ENSG00000117410
Getting matched controls for ENSG00000229676

Processing conditions:  69%|█████████████████████████████████████████████▏                   | 1429/2057 [07:46<02:15,  4.64item/s, Completed 1429/2057]

Found 157 matched controls for ENSG00000229676
Getting matched controls for ENSG00000198783
Found 15 matched controls for ENSG00000198783
Getting matched controls for ENSG00000121022

Processing conditions:  70%|█████████████████████████████████████████████▏                   | 1430/2057 [07:47<02:18,  4.54item/s, Completed 1430/2057]

Found 98 matched controls for ENSG00000121022
Getting matched controls for ENSG00000143105

Processing conditions:  70%|█████████████████████████████████████████████▎                   | 1432/2057 [07:47<02:11,  4.76item/s, Completed 1432/2057]

Found 147 matched controls for ENSG00000143105
Getting matched controls for ENSG00000071859
Found 38 matched controls for ENSG00000071859
Getting matched controls for ENSG00000145388

Processing conditions:  70%|█████████████████████████████████████████████▎                   | 1433/2057 [07:47<02:18,  4.50item/s, Completed 1433/2057]

Found 121 matched controls for ENSG00000145388
Getting matched controls for ENSG00000160179

Processing conditions:  70%|█████████████████████████████████████████████▎                   | 1434/2057 [07:48<02:31,  4.12item/s, Completed 1434/2057]

Found 144 matched controls for ENSG00000160179
Getting matched controls for ENSG00000167325

Processing conditions:  70%|█████████████████████████████████████████████▎                   | 1435/2057 [07:48<02:29,  4.16item/s, Completed 1435/2057]

Found 103 matched controls for ENSG00000167325
Getting matched controls for ENSG00000113810

Processing conditions:  70%|█████████████████████████████████████████████▍                   | 1436/2057 [07:48<03:35,  2.88item/s, Completed 1436/2057]

Found 340 matched controls for ENSG00000113810
Getting matched controls for ENSG00000163634

Processing conditions:  70%|█████████████████████████████████████████████▍                   | 1438/2057 [07:49<02:52,  3.60item/s, Completed 1438/2057]

Found 132 matched controls for ENSG00000163634
Getting matched controls for ENSG00000131013
Found 74 matched controls for ENSG00000131013
Getting matched controls for ENSG00000183054

Processing conditions:  70%|█████████████████████████████████████████████▍                   | 1439/2057 [07:49<03:06,  3.31item/s, Completed 1439/2057]

Found 202 matched controls for ENSG00000183054
Getting matched controls for ENSG00000163930

Processing conditions:  70%|█████████████████████████████████████████████▌                   | 1441/2057 [07:50<02:52,  3.58item/s, Completed 1441/2057]

Found 200 matched controls for ENSG00000163930
Getting matched controls for ENSG00000116830
Found 68 matched controls for ENSG00000116830
Getting matched controls for ENSG00000184166

Processing conditions:  70%|█████████████████████████████████████████████▌                   | 1443/2057 [07:50<02:24,  4.26item/s, Completed 1443/2057]

Found 125 matched controls for ENSG00000184166
Getting matched controls for ENSG00000175390
Found 67 matched controls for ENSG00000175390
Getting matched controls for ENSG00000149792

Processing conditions:  70%|█████████████████████████████████████████████▋                   | 1445/2057 [07:51<02:01,  5.05item/s, Completed 1445/2057]

Found 40 matched controls for ENSG00000149792
Getting matched controls for ENSG00000104131
Found 82 matched controls for ENSG00000104131
Getting matched controls for ENSG00000082516

Processing conditions:  70%|█████████████████████████████████████████████▋                   | 1446/2057 [07:51<02:14,  4.53item/s, Completed 1446/2057]

Found 133 matched controls for ENSG00000082516
Getting matched controls for ENSG00000116922

Processing conditions:  70%|█████████████████████████████████████████████▊                   | 1448/2057 [07:51<02:26,  4.15item/s, Completed 1448/2057]

Found 240 matched controls for ENSG00000116922
Getting matched controls for ENSG00000156709
Found 50 matched controls for ENSG00000156709
Getting matched controls for ENSG00000164654

Processing conditions:  70%|█████████████████████████████████████████████▊                   | 1449/2057 [07:52<02:37,  3.86item/s, Completed 1449/2057]

Found 163 matched controls for ENSG00000164654
Getting matched controls for ENSG00000159352

Processing conditions:  71%|█████████████████████████████████████████████▊                   | 1451/2057 [07:52<03:09,  3.20item/s, Completed 1451/2057]

Found 352 matched controls for ENSG00000159352
Getting matched controls for ENSG00000092330
Found 76 matched controls for ENSG00000092330
Getting matched controls for ENSG00000169217

Processing conditions:  71%|█████████████████████████████████████████████▉                   | 1452/2057 [07:53<03:01,  3.33item/s, Completed 1452/2057]

Found 132 matched controls for ENSG00000169217
Getting matched controls for ENSG00000129351

Processing conditions:  71%|█████████████████████████████████████████████▉                   | 1454/2057 [07:53<02:30,  4.00item/s, Completed 1454/2057]

Found 138 matched controls for ENSG00000129351
Getting matched controls for ENSG00000155097
Found 59 matched controls for ENSG00000155097
Getting matched controls for ENSG00000126461

Processing conditions:  71%|█████████████████████████████████████████████▉                   | 1455/2057 [07:53<02:44,  3.67item/s, Completed 1455/2057]

Found 174 matched controls for ENSG00000126461
Getting matched controls for ENSG00000100764

Processing conditions:  71%|██████████████████████████████████████████████                   | 1456/2057 [07:54<03:37,  2.76item/s, Completed 1457/2057]

Found 316 matched controls for ENSG00000100764
Getting matched controls for ENSG00000215301
Found 29 matched controls for ENSG00000215301
Getting matched controls for ENSG00000101654

Processing conditions:  71%|██████████████████████████████████████████████                   | 1459/2057 [07:55<02:31,  3.94item/s, Completed 1459/2057]

Found 114 matched controls for ENSG00000101654
Getting matched controls for ENSG00000116586
Found 66 matched controls for ENSG00000116586
Getting matched controls for ENSG00000171148

Processing conditions:  71%|██████████████████████████████████████████████▏                  | 1461/2057 [07:55<02:18,  4.30item/s, Completed 1461/2057]

Found 150 matched controls for ENSG00000171148
Getting matched controls for ENSG00000011523
Found 68 matched controls for ENSG00000011523
Getting matched controls for ENSG00000186226

Processing conditions:  71%|██████████████████████████████████████████████▏                  | 1462/2057 [07:55<02:19,  4.25item/s, Completed 1462/2057]

Found 123 matched controls for ENSG00000186226
Getting matched controls for ENSG00000274349

Processing conditions:  71%|██████████████████████████████████████████████▏                  | 1463/2057 [07:56<02:23,  4.15item/s, Completed 1463/2057]

Found 111 matched controls for ENSG00000274349
Getting matched controls for ENSG00000103051

Processing conditions:  71%|██████████████████████████████████████████████▎                  | 1464/2057 [07:56<02:28,  4.01item/s, Completed 1464/2057]

Found 129 matched controls for ENSG00000103051
Getting matched controls for ENSG00000113194

Processing conditions:  71%|██████████████████████████████████████████████▎                  | 1466/2057 [07:56<02:23,  4.12item/s, Completed 1466/2057]

Found 165 matched controls for ENSG00000113194
Getting matched controls for ENSG00000213465
Found 74 matched controls for ENSG00000213465
Getting matched controls for ENSG00000163605

Processing conditions:  71%|██████████████████████████████████████████████▎                  | 1467/2057 [07:57<02:42,  3.62item/s, Completed 1467/2057]

Found 187 matched controls for ENSG00000163605
Getting matched controls for ENSG00000241553

Processing conditions:  71%|██████████████████████████████████████████████▍                  | 1468/2057 [07:57<03:04,  3.19item/s, Completed 1468/2057]

Found 220 matched controls for ENSG00000241553
Getting matched controls for ENSG00000205795

Processing conditions:  71%|██████████████████████████████████████████████▍                  | 1469/2057 [07:57<03:07,  3.14item/s, Completed 1469/2057]

Found 170 matched controls for ENSG00000205795
Getting matched controls for ENSG00000154832

Processing conditions:  72%|██████████████████████████████████████████████▍                  | 1471/2057 [07:58<02:31,  3.87item/s, Completed 1471/2057]

Found 122 matched controls for ENSG00000154832
Getting matched controls for ENSG00000136942
Found 46 matched controls for ENSG00000136942
Getting matched controls for ENSG00000153207

Processing conditions:  72%|██████████████████████████████████████████████▌                  | 1473/2057 [07:59<02:48,  3.47item/s, Completed 1473/2057]

Found 290 matched controls for ENSG00000153207
Getting matched controls for ENSG00000180818
Found 83 matched controls for ENSG00000180818
Getting matched controls for ENSG00000071894

Processing conditions:  72%|██████████████████████████████████████████████▌                  | 1474/2057 [07:59<02:20,  4.14item/s, Completed 1474/2057]

Found 50 matched controls for ENSG00000071894
Getting matched controls for ENSG00000176444

Processing conditions:  72%|██████████████████████████████████████████████▋                  | 1476/2057 [07:59<01:55,  5.05item/s, Completed 1476/2057]

Found 88 matched controls for ENSG00000176444
Getting matched controls for ENSG00000145982
Found 40 matched controls for ENSG00000145982
Getting matched controls for ENSG00000173660

Processing conditions:  72%|██████████████████████████████████████████████▋                  | 1478/2057 [07:59<01:47,  5.41item/s, Completed 1478/2057]

Found 68 matched controls for ENSG00000173660
Getting matched controls for ENSG00000244038
Found 86 matched controls for ENSG00000244038
Getting matched controls for ENSG00000134480

Processing conditions:  72%|██████████████████████████████████████████████▊                  | 1480/2057 [08:00<01:44,  5.54item/s, Completed 1480/2057]

Found 79 matched controls for ENSG00000134480
Getting matched controls for ENSG00000105583
Found 83 matched controls for ENSG00000105583
Getting matched controls for ENSG00000180822

Processing conditions:  72%|██████████████████████████████████████████████▊                  | 1481/2057 [08:00<01:38,  5.83item/s, Completed 1481/2057]

Found 62 matched controls for ENSG00000180822
Getting matched controls for ENSG00000170122

Processing conditions:  72%|██████████████████████████████████████████████▊                  | 1482/2057 [08:00<01:50,  5.19item/s, Completed 1482/2057]

Found 94 matched controls for ENSG00000170122
Getting matched controls for ENSG00000105879

Processing conditions:  72%|██████████████████████████████████████████████▉                  | 1484/2057 [08:00<01:48,  5.30item/s, Completed 1484/2057]

Found 102 matched controls for ENSG00000105879
Getting matched controls for ENSG00000101189
Found 74 matched controls for ENSG00000101189
Getting matched controls for ENSG00000100564

Processing conditions:  72%|██████████████████████████████████████████████▉                  | 1485/2057 [08:01<01:46,  5.37item/s, Completed 1485/2057]

Found 85 matched controls for ENSG00000100564
Getting matched controls for ENSG00000166226

Processing conditions:  72%|██████████████████████████████████████████████▉                  | 1487/2057 [08:01<01:56,  4.90item/s, Completed 1487/2057]

Found 199 matched controls for ENSG00000166226
Getting matched controls for ENSG00000133112
Found 48 matched controls for ENSG00000133112
Getting matched controls for ENSG00000198231

Processing conditions:  72%|███████████████████████████████████████████████                  | 1489/2057 [08:01<01:37,  5.80item/s, Completed 1489/2057]

Found 44 matched controls for ENSG00000198231
Getting matched controls for ENSG00000106591
Found 67 matched controls for ENSG00000106591
Getting matched controls for ENSG00000115946

Processing conditions:  72%|███████████████████████████████████████████████                  | 1490/2057 [08:02<01:51,  5.07item/s, Completed 1490/2057]

Found 134 matched controls for ENSG00000115946
Getting matched controls for ENSG00000116580

Processing conditions:  72%|███████████████████████████████████████████████                  | 1491/2057 [08:02<02:28,  3.82item/s, Completed 1491/2057]

Found 237 matched controls for ENSG00000116580
Getting matched controls for ENSG00000172167

Processing conditions:  73%|███████████████████████████████████████████████▏                 | 1492/2057 [08:02<02:46,  3.39item/s, Completed 1492/2057]

Found 191 matched controls for ENSG00000172167
Getting matched controls for ENSG00000132424

Processing conditions:  73%|███████████████████████████████████████████████▏                 | 1493/2057 [08:03<02:56,  3.20item/s, Completed 1493/2057]

Found 196 matched controls for ENSG00000132424
Getting matched controls for ENSG00000253710

Processing conditions:  73%|███████████████████████████████████████████████▏                 | 1494/2057 [08:03<02:38,  3.55item/s, Completed 1494/2057]

Found 97 matched controls for ENSG00000253710
Getting matched controls for ENSG00000167113

Processing conditions:  73%|███████████████████████████████████████████████▏                 | 1495/2057 [08:03<02:51,  3.28item/s, Completed 1495/2057]

Found 162 matched controls for ENSG00000167113
Getting matched controls for ENSG00000115364

Processing conditions:  73%|███████████████████████████████████████████████▎                 | 1496/2057 [08:04<03:05,  3.03item/s, Completed 1496/2057]

Found 192 matched controls for ENSG00000115364
Getting matched controls for ENSG00000162526

Processing conditions:  73%|███████████████████████████████████████████████▎                 | 1497/2057 [08:04<03:22,  2.77item/s, Completed 1497/2057]

Found 212 matched controls for ENSG00000162526
Getting matched controls for ENSG00000132702

Processing conditions:  73%|███████████████████████████████████████████████▎                 | 1498/2057 [08:04<03:05,  3.01item/s, Completed 1498/2057]

Found 121 matched controls for ENSG00000132702
Getting matched controls for ENSG00000091157

Processing conditions:  73%|███████████████████████████████████████████████▎                 | 1499/2057 [08:05<02:49,  3.29item/s, Completed 1499/2057]

Found 103 matched controls for ENSG00000091157
Getting matched controls for ENSG00000212993

Processing conditions:  73%|███████████████████████████████████████████████▍                 | 1501/2057 [08:05<02:21,  3.93item/s, Completed 1501/2057]

Found 81 matched controls for ENSG00000212993
Getting matched controls for ENSG00000135829
Found 92 matched controls for ENSG00000135829
Getting matched controls for ENSG00000159202

Processing conditions:  73%|███████████████████████████████████████████████▍                 | 1502/2057 [08:05<02:07,  4.36item/s, Completed 1502/2057]

Found 64 matched controls for ENSG00000159202
Getting matched controls for ENSG00000103549

Processing conditions:  73%|███████████████████████████████████████████████▍                 | 1503/2057 [08:06<02:35,  3.56item/s, Completed 1503/2057]

Found 198 matched controls for ENSG00000103549
Getting matched controls for ENSG00000147274

Processing conditions:  73%|███████████████████████████████████████████████▌                 | 1505/2057 [08:06<02:13,  4.12item/s, Completed 1505/2057]

Found 147 matched controls for ENSG00000147274
Getting matched controls for ENSG00000172534
Found 55 matched controls for ENSG00000172534
Getting matched controls for ENSG00000014138

Processing conditions:  73%|███████████████████████████████████████████████▌                 | 1506/2057 [08:07<02:49,  3.25item/s, Completed 1507/2057]

Found 234 matched controls for ENSG00000014138
Getting matched controls for ENSG00000136448
Found 25 matched controls for ENSG00000136448
Getting matched controls for ENSG00000127463

Processing conditions:  73%|███████████████████████████████████████████████▋                 | 1509/2057 [08:07<01:51,  4.90item/s, Completed 1510/2057]

Found 83 matched controls for ENSG00000127463
Getting matched controls for ENSG00000182180
Found 41 matched controls for ENSG00000182180
Getting matched controls for ENSG00000183207
Found 14 matched controls for ENSG00000183207
Getting matched controls for ENSG00000062822

Processing conditions:  73%|███████████████████████████████████████████████▋                 | 1511/2057 [08:07<01:58,  4.62item/s, Completed 1511/2057]

Found 212 matched controls for ENSG00000062822
Getting matched controls for ENSG00000133858

Processing conditions:  74%|███████████████████████████████████████████████▊                 | 1512/2057 [08:08<02:01,  4.48item/s, Completed 1512/2057]

Found 117 matched controls for ENSG00000133858
Getting matched controls for ENSG00000268009

Processing conditions:  74%|███████████████████████████████████████████████▊                 | 1513/2057 [08:08<02:03,  4.42item/s, Completed 1513/2057]

Found 101 matched controls for ENSG00000268009
Getting matched controls for ENSG00000185627

Processing conditions:  74%|███████████████████████████████████████████████▊                 | 1514/2057 [08:08<02:06,  4.29item/s, Completed 1514/2057]

Found 122 matched controls for ENSG00000185627
Getting matched controls for ENSG00000130856

Processing conditions:  74%|███████████████████████████████████████████████▊                 | 1515/2057 [08:08<02:04,  4.35item/s, Completed 1515/2057]

Found 85 matched controls for ENSG00000130856
Getting matched controls for ENSG00000086827

Processing conditions:  74%|███████████████████████████████████████████████▉                 | 1516/2057 [08:09<02:23,  3.76item/s, Completed 1516/2057]

Found 200 matched controls for ENSG00000086827
Getting matched controls for ENSG00000115652

Processing conditions:  74%|███████████████████████████████████████████████▉                 | 1517/2057 [08:09<02:20,  3.85item/s, Completed 1517/2057]

Found 124 matched controls for ENSG00000115652
Getting matched controls for ENSG00000213639

Processing conditions:  74%|███████████████████████████████████████████████▉                 | 1518/2057 [08:09<02:26,  3.69item/s, Completed 1518/2057]

Found 160 matched controls for ENSG00000213639
Getting matched controls for ENSG00000101003

Processing conditions:  74%|███████████████████████████████████████████████▉                 | 1519/2057 [08:10<02:36,  3.44item/s, Completed 1519/2057]

Found 186 matched controls for ENSG00000101003
Getting matched controls for ENSG00000165264

Processing conditions:  74%|████████████████████████████████████████████████                 | 1521/2057 [08:10<02:19,  3.85item/s, Completed 1521/2057]

Found 190 matched controls for ENSG00000165264
Getting matched controls for ENSG00000101146
Found 59 matched controls for ENSG00000101146
Getting matched controls for ENSG00000133103

Processing conditions:  74%|████████████████████████████████████████████████                 | 1522/2057 [08:10<02:31,  3.54item/s, Completed 1522/2057]

Found 183 matched controls for ENSG00000133103
Getting matched controls for ENSG00000149084

Processing conditions:  74%|████████████████████████████████████████████████▏                | 1523/2057 [08:11<02:29,  3.57item/s, Completed 1523/2057]

Found 142 matched controls for ENSG00000149084
Getting matched controls for ENSG00000115207

Processing conditions:  74%|████████████████████████████████████████████████▏                | 1525/2057 [08:11<02:07,  4.16item/s, Completed 1525/2057]

Found 114 matched controls for ENSG00000115207
Getting matched controls for ENSG00000125995
Found 87 matched controls for ENSG00000125995
Getting matched controls for ENSG00000284024

Processing conditions:  74%|████████████████████████████████████████████████▏                | 1526/2057 [08:11<02:12,  4.02item/s, Completed 1526/2057]

Found 120 matched controls for ENSG00000284024
Getting matched controls for ENSG00000167182

Processing conditions:  74%|████████████████████████████████████████████████▎                | 1527/2057 [08:12<02:12,  4.00item/s, Completed 1527/2057]

Found 118 matched controls for ENSG00000167182
Getting matched controls for ENSG00000166012

Processing conditions:  74%|████████████████████████████████████████████████▎                | 1528/2057 [08:12<02:18,  3.81item/s, Completed 1528/2057]

Found 141 matched controls for ENSG00000166012
Getting matched controls for ENSG00000172115

Processing conditions:  74%|████████████████████████████████████████████████▎                | 1530/2057 [08:12<02:04,  4.22item/s, Completed 1530/2057]

Found 163 matched controls for ENSG00000172115
Getting matched controls for ENSG00000204525
Found 44 matched controls for ENSG00000204525
Getting matched controls for ENSG00000128524

Processing conditions:  74%|████████████████████████████████████████████████▍                | 1531/2057 [08:13<01:52,  4.66item/s, Completed 1532/2057]

Found 72 matched controls for ENSG00000128524
Getting matched controls for ENSG00000188976
Found 28 matched controls for ENSG00000188976
Getting matched controls for ENSG00000161513

Processing conditions:  75%|████████████████████████████████████████████████▍                | 1533/2057 [08:13<01:48,  4.84item/s, Completed 1533/2057]

Found 140 matched controls for ENSG00000161513
Getting matched controls for ENSG00000171960

Processing conditions:  75%|████████████████████████████████████████████████▍                | 1534/2057 [08:13<01:57,  4.46item/s, Completed 1534/2057]

Found 114 matched controls for ENSG00000171960
Getting matched controls for ENSG00000155959

Processing conditions:  75%|████████████████████████████████████████████████▌                | 1535/2057 [08:14<01:58,  4.40item/s, Completed 1535/2057]

Found 116 matched controls for ENSG00000155959
Getting matched controls for ENSG00000125835

Processing conditions:  75%|████████████████████████████████████████████████▌                | 1537/2057 [08:14<02:15,  3.85item/s, Completed 1537/2057]

Found 269 matched controls for ENSG00000125835
Getting matched controls for ENSG00000178057
Found 81 matched controls for ENSG00000178057
Getting matched controls for ENSG00000106263

Processing conditions:  75%|████████████████████████████████████████████████▋                | 1539/2057 [08:14<01:38,  5.26item/s, Completed 1539/2057]

Found 34 matched controls for ENSG00000106263
Getting matched controls for ENSG00000060339
Found 48 matched controls for ENSG00000060339
Getting matched controls for ENSG00000136122

Processing conditions:  75%|████████████████████████████████████████████████▋                | 1540/2057 [08:15<01:30,  5.70item/s, Completed 1540/2057]

Found 55 matched controls for ENSG00000136122
Getting matched controls for ENSG00000131351

Processing conditions:  75%|████████████████████████████████████████████████▋                | 1541/2057 [08:15<01:40,  5.15item/s, Completed 1541/2057]

Found 122 matched controls for ENSG00000131351
Getting matched controls for ENSG00000143093

Processing conditions:  75%|████████████████████████████████████████████████▊                | 1543/2057 [08:15<01:35,  5.36item/s, Completed 1543/2057]

Found 107 matched controls for ENSG00000143093
Getting matched controls for ENSG00000103275
Found 64 matched controls for ENSG00000103275
Getting matched controls for ENSG00000150753

Processing conditions:  75%|████████████████████████████████████████████████▊                | 1544/2057 [08:15<01:31,  5.62item/s, Completed 1544/2057]

Found 66 matched controls for ENSG00000150753
Getting matched controls for ENSG00000111640

Processing conditions:  75%|████████████████████████████████████████████████▊                | 1546/2057 [08:16<01:53,  4.51item/s, Completed 1546/2057]

Found 183 matched controls for ENSG00000111640
Getting matched controls for ENSG00000204568
Found 59 matched controls for ENSG00000204568
Getting matched controls for ENSG00000011260

Processing conditions:  75%|████████████████████████████████████████████████▉                | 1548/2057 [08:16<01:43,  4.92item/s, Completed 1548/2057]

Found 77 matched controls for ENSG00000011260
Getting matched controls for ENSG00000171824
Found 92 matched controls for ENSG00000171824
Getting matched controls for ENSG00000151461

Processing conditions:  75%|████████████████████████████████████████████████▉                | 1550/2057 [08:17<01:45,  4.82item/s, Completed 1550/2057]

Found 154 matched controls for ENSG00000151461
Getting matched controls for ENSG00000131747
Found 38 matched controls for ENSG00000131747
Getting matched controls for ENSG00000187778

Processing conditions:  75%|█████████████████████████████████████████████████                | 1551/2057 [08:17<01:45,  4.78item/s, Completed 1551/2057]

Found 71 matched controls for ENSG00000187778
Getting matched controls for ENSG00000161888

Processing conditions:  75%|█████████████████████████████████████████████████                | 1552/2057 [08:17<01:47,  4.68item/s, Completed 1552/2057]

Found 98 matched controls for ENSG00000161888
Getting matched controls for ENSG00000182117

Processing conditions:  76%|█████████████████████████████████████████████████                | 1554/2057 [08:18<01:45,  4.76item/s, Completed 1554/2057]

Found 147 matched controls for ENSG00000182117
Getting matched controls for ENSG00000160917
Found 59 matched controls for ENSG00000160917
Getting matched controls for ENSG00000006695

Processing conditions:  76%|█████████████████████████████████████████████████▏               | 1555/2057 [08:18<01:45,  4.74item/s, Completed 1555/2057]

Found 94 matched controls for ENSG00000006695
Getting matched controls for ENSG00000067225

Processing conditions:  76%|█████████████████████████████████████████████████▏               | 1556/2057 [08:18<01:56,  4.30item/s, Completed 1556/2057]

Found 149 matched controls for ENSG00000067225
Getting matched controls for ENSG00000197771

Processing conditions:  76%|█████████████████████████████████████████████████▏               | 1558/2057 [08:19<01:52,  4.43item/s, Completed 1558/2057]

Found 145 matched controls for ENSG00000197771
Getting matched controls for ENSG00000105640
Found 65 matched controls for ENSG00000105640
Getting matched controls for ENSG00000087263

Processing conditions:  76%|█████████████████████████████████████████████████▎               | 1559/2057 [08:19<01:53,  4.41item/s, Completed 1559/2057]

Found 114 matched controls for ENSG00000087263
Getting matched controls for ENSG00000063177

Processing conditions:  76%|█████████████████████████████████████████████████▎               | 1561/2057 [08:19<02:17,  3.62item/s, Completed 1561/2057]

Found 308 matched controls for ENSG00000063177
Getting matched controls for ENSG00000153044
Found 63 matched controls for ENSG00000153044
Getting matched controls for ENSG00000163882

Processing conditions:  76%|█████████████████████████████████████████████████▎               | 1562/2057 [08:20<02:11,  3.76item/s, Completed 1562/2057]

Found 102 matched controls for ENSG00000163882
Getting matched controls for ENSG00000112972

Processing conditions:  76%|█████████████████████████████████████████████████▍               | 1563/2057 [08:20<02:32,  3.25item/s, Completed 1563/2057]

Found 230 matched controls for ENSG00000112972
Getting matched controls for ENSG00000129128

Processing conditions:  76%|█████████████████████████████████████████████████▍               | 1565/2057 [08:21<02:16,  3.60item/s, Completed 1565/2057]

Found 167 matched controls for ENSG00000129128
Getting matched controls for ENSG00000102974
Found 68 matched controls for ENSG00000102974
Getting matched controls for ENSG00000153774

Processing conditions:  76%|█████████████████████████████████████████████████▍               | 1566/2057 [08:21<02:24,  3.39item/s, Completed 1566/2057]

Found 157 matched controls for ENSG00000153774
Getting matched controls for ENSG00000159479

Processing conditions:  76%|█████████████████████████████████████████████████▌               | 1568/2057 [08:21<01:56,  4.20item/s, Completed 1568/2057]

Found 112 matched controls for ENSG00000159479
Getting matched controls for ENSG00000173085
Found 67 matched controls for ENSG00000173085
Getting matched controls for ENSG00000128563

Processing conditions:  76%|█████████████████████████████████████████████████▌               | 1569/2057 [08:22<02:09,  3.77item/s, Completed 1569/2057]

Found 182 matched controls for ENSG00000128563
Getting matched controls for ENSG00000145604

Processing conditions:  76%|█████████████████████████████████████████████████▋               | 1571/2057 [08:22<02:00,  4.02item/s, Completed 1571/2057]

Found 202 matched controls for ENSG00000145604
Getting matched controls for ENSG00000131469
Found 38 matched controls for ENSG00000131469
Getting matched controls for ENSG00000184678

Processing conditions:  76%|█████████████████████████████████████████████████▋               | 1572/2057 [08:22<01:39,  4.87item/s, Completed 1572/2057]

Found 31 matched controls for ENSG00000184678
Getting matched controls for ENSG00000115875

Processing conditions:  77%|█████████████████████████████████████████████████▋               | 1574/2057 [08:23<01:26,  5.56item/s, Completed 1574/2057]

Found 118 matched controls for ENSG00000115875
Getting matched controls for ENSG00000082068
Found 30 matched controls for ENSG00000082068
Getting matched controls for ENSG00000189043

Processing conditions:  77%|█████████████████████████████████████████████████▊               | 1575/2057 [08:23<01:30,  5.33item/s, Completed 1575/2057]

Found 86 matched controls for ENSG00000189043
Getting matched controls for ENSG00000174437

Processing conditions:  77%|█████████████████████████████████████████████████▊               | 1576/2057 [08:23<02:06,  3.81item/s, Completed 1576/2057]

Found 158 matched controls for ENSG00000174437
Getting matched controls for ENSG00000175106

Processing conditions:  77%|█████████████████████████████████████████████████▊               | 1577/2057 [08:23<02:00,  3.97item/s, Completed 1577/2057]

Found 113 matched controls for ENSG00000175106
Getting matched controls for ENSG00000138376

Processing conditions:  77%|█████████████████████████████████████████████████▉               | 1579/2057 [08:24<01:59,  3.99item/s, Completed 1579/2057]

Found 140 matched controls for ENSG00000138376
Getting matched controls for ENSG00000141759
Found 85 matched controls for ENSG00000141759
Getting matched controls for ENSG00000204569

Processing conditions:  77%|█████████████████████████████████████████████████▉               | 1581/2057 [08:24<01:31,  5.21item/s, Completed 1581/2057]

Found 7 matched controls for ENSG00000204569
Getting matched controls for ENSG00000184260
Found 73 matched controls for ENSG00000184260
Getting matched controls for ENSG00000100479

Processing conditions:  77%|█████████████████████████████████████████████████▉               | 1582/2057 [08:24<01:24,  5.60item/s, Completed 1582/2057]

Found 56 matched controls for ENSG00000100479
Getting matched controls for ENSG00000196365

Processing conditions:  77%|██████████████████████████████████████████████████               | 1584/2057 [08:25<01:30,  5.20item/s, Completed 1584/2057]

Found 128 matched controls for ENSG00000196365
Getting matched controls for ENSG00000108433
Found 84 matched controls for ENSG00000108433
Getting matched controls for ENSG00000083093

Processing conditions:  77%|██████████████████████████████████████████████████               | 1585/2057 [08:25<01:32,  5.12item/s, Completed 1585/2057]

Found 97 matched controls for ENSG00000083093
Getting matched controls for ENSG00000105401

Processing conditions:  77%|██████████████████████████████████████████████████               | 1586/2057 [08:25<01:48,  4.33item/s, Completed 1586/2057]

Found 174 matched controls for ENSG00000105401
Getting matched controls for ENSG00000096401

Processing conditions:  77%|██████████████████████████████████████████████████▏              | 1587/2057 [08:26<01:44,  4.48item/s, Completed 1587/2057]

Found 99 matched controls for ENSG00000096401
Getting matched controls for ENSG00000204220

Processing conditions:  77%|██████████████████████████████████████████████████▏              | 1588/2057 [08:26<01:45,  4.45item/s, Completed 1588/2057]

Found 115 matched controls for ENSG00000204220
Getting matched controls for ENSG00000134825

Processing conditions:  77%|██████████████████████████████████████████████████▏              | 1590/2057 [08:26<01:51,  4.21item/s, Completed 1590/2057]

Found 193 matched controls for ENSG00000134825
Getting matched controls for ENSG00000162396
Found 66 matched controls for ENSG00000162396
Getting matched controls for ENSG00000130706

Processing conditions:  77%|██████████████████████████████████████████████████▎              | 1592/2057 [08:27<01:34,  4.95item/s, Completed 1592/2057]

Found 105 matched controls for ENSG00000130706
Getting matched controls for ENSG00000007923
Found 46 matched controls for ENSG00000007923
Getting matched controls for ENSG00000156990

Processing conditions:  77%|██████████████████████████████████████████████████▎              | 1593/2057 [08:27<01:47,  4.30item/s, Completed 1593/2057]

Found 164 matched controls for ENSG00000156990
Getting matched controls for ENSG00000169564

Processing conditions:  78%|██████████████████████████████████████████████████▍              | 1595/2057 [08:27<01:34,  4.90item/s, Completed 1595/2057]

Found 108 matched controls for ENSG00000169564
Getting matched controls for ENSG00000115216
Found 63 matched controls for ENSG00000115216
Getting matched controls for ENSG00000169230

Processing conditions:  78%|██████████████████████████████████████████████████▍              | 1597/2057 [08:28<01:29,  5.11item/s, Completed 1597/2057]

Found 152 matched controls for ENSG00000169230
Getting matched controls for ENSG00000184967
Found 34 matched controls for ENSG00000184967
Getting matched controls for ENSG00000053372

Processing conditions:  78%|██████████████████████████████████████████████████▍              | 1598/2057 [08:28<01:30,  5.09item/s, Completed 1598/2057]

Found 83 matched controls for ENSG00000053372
Getting matched controls for ENSG00000116120

Processing conditions:  78%|██████████████████████████████████████████████████▌              | 1600/2057 [08:28<01:26,  5.30item/s, Completed 1600/2057]

Found 97 matched controls for ENSG00000116120
Getting matched controls for ENSG00000169189
Found 61 matched controls for ENSG00000169189
Getting matched controls for ENSG00000188342

Processing conditions:  78%|██████████████████████████████████████████████████▌              | 1601/2057 [08:28<01:22,  5.50item/s, Completed 1601/2057]

Found 59 matched controls for ENSG00000188342
Getting matched controls for ENSG00000129932

Processing conditions:  78%|██████████████████████████████████████████████████▌              | 1602/2057 [08:29<01:42,  4.43item/s, Completed 1602/2057]

Found 155 matched controls for ENSG00000129932
Getting matched controls for ENSG00000103995

Processing conditions:  78%|██████████████████████████████████████████████████▋              | 1603/2057 [08:29<01:53,  3.99item/s, Completed 1603/2057]

Found 153 matched controls for ENSG00000103995
Getting matched controls for ENSG00000168566

Processing conditions:  78%|██████████████████████████████████████████████████▋              | 1604/2057 [08:30<02:11,  3.44item/s, Completed 1604/2057]

Found 191 matched controls for ENSG00000168566
Getting matched controls for ENSG00000100836

Processing conditions:  78%|██████████████████████████████████████████████████▋              | 1605/2057 [08:30<02:10,  3.47item/s, Completed 1605/2057]

Found 148 matched controls for ENSG00000100836
Getting matched controls for ENSG00000112041

Processing conditions:  78%|██████████████████████████████████████████████████▋              | 1606/2057 [08:30<02:03,  3.65item/s, Completed 1606/2057]

Found 123 matched controls for ENSG00000112041
Getting matched controls for ENSG00000185298

Processing conditions:  78%|██████████████████████████████████████████████████▊              | 1607/2057 [08:30<02:14,  3.34item/s, Completed 1607/2057]

Found 198 matched controls for ENSG00000185298
Getting matched controls for ENSG00000165630

Processing conditions:  78%|██████████████████████████████████████████████████▊              | 1609/2057 [08:31<02:14,  3.34item/s, Completed 1609/2057]

Found 268 matched controls for ENSG00000165630
Getting matched controls for ENSG00000105656
Found 83 matched controls for ENSG00000105656
Getting matched controls for ENSG00000106290

Processing conditions:  78%|██████████████████████████████████████████████████▉              | 1610/2057 [08:31<02:03,  3.61item/s, Completed 1610/2057]

Found 113 matched controls for ENSG00000106290
Getting matched controls for ENSG00000104221

Processing conditions:  78%|██████████████████████████████████████████████████▉              | 1611/2057 [08:32<02:09,  3.43item/s, Completed 1611/2057]

Found 174 matched controls for ENSG00000104221
Getting matched controls for ENSG00000119041

Processing conditions:  78%|██████████████████████████████████████████████████▉              | 1613/2057 [08:32<01:53,  3.90item/s, Completed 1613/2057]

Found 132 matched controls for ENSG00000119041
Getting matched controls for ENSG00000115750
Found 94 matched controls for ENSG00000115750
Getting matched controls for ENSG00000052749

Processing conditions:  78%|███████████████████████████████████████████████████              | 1614/2057 [08:32<02:07,  3.47item/s, Completed 1614/2057]

Found 204 matched controls for ENSG00000052749
Getting matched controls for ENSG00000113141

Processing conditions:  79%|███████████████████████████████████████████████████              | 1616/2057 [08:33<02:09,  3.41item/s, Completed 1616/2057]

Found 289 matched controls for ENSG00000113141
Getting matched controls for ENSG00000120438
Found 67 matched controls for ENSG00000120438
Getting matched controls for ENSG00000101361

Processing conditions:  79%|███████████████████████████████████████████████████▏             | 1618/2057 [08:33<01:48,  4.04item/s, Completed 1618/2057]

Found 99 matched controls for ENSG00000101361
Getting matched controls for ENSG00000143319
Found 73 matched controls for ENSG00000143319
Getting matched controls for ENSG00000180543

Processing conditions:  79%|███████████████████████████████████████████████████▏             | 1620/2057 [08:34<01:37,  4.47item/s, Completed 1620/2057]

Found 93 matched controls for ENSG00000180543
Getting matched controls for ENSG00000129696
Found 43 matched controls for ENSG00000129696
Getting matched controls for ENSG00000149503

Processing conditions:  79%|███████████████████████████████████████████████████▏             | 1621/2057 [08:34<01:31,  4.74item/s, Completed 1621/2057]

Found 59 matched controls for ENSG00000149503
Getting matched controls for ENSG00000076043

Processing conditions:  79%|███████████████████████████████████████████████████▎             | 1623/2057 [08:34<01:28,  4.89item/s, Completed 1623/2057]

Found 79 matched controls for ENSG00000076043
Getting matched controls for ENSG00000104356
Found 84 matched controls for ENSG00000104356
Getting matched controls for ENSG00000105829

Processing conditions:  79%|███████████████████████████████████████████████████▎             | 1625/2057 [08:35<01:27,  4.96item/s, Completed 1625/2057]

Found 131 matched controls for ENSG00000105829
Getting matched controls for ENSG00000128272
Found 72 matched controls for ENSG00000128272
Getting matched controls for ENSG00000104852

Processing conditions:  79%|███████████████████████████████████████████████████▍             | 1626/2057 [08:35<01:35,  4.51item/s, Completed 1626/2057]

Found 129 matched controls for ENSG00000104852
Getting matched controls for ENSG00000143748

Processing conditions:  79%|███████████████████████████████████████████████████▍             | 1627/2057 [08:35<01:40,  4.26item/s, Completed 1627/2057]

Found 110 matched controls for ENSG00000143748
Getting matched controls for ENSG00000061273

Processing conditions:  79%|███████████████████████████████████████████████████▍             | 1628/2057 [08:36<02:02,  3.52item/s, Completed 1628/2057]

Found 171 matched controls for ENSG00000061273
Getting matched controls for ENSG00000025770

Processing conditions:  79%|███████████████████████████████████████████████████▌             | 1630/2057 [08:36<01:50,  3.87item/s, Completed 1630/2057]

Found 143 matched controls for ENSG00000025770
Getting matched controls for ENSG00000204356
Found 74 matched controls for ENSG00000204356
Getting matched controls for ENSG00000071553

Processing conditions:  79%|███████████████████████████████████████████████████▌             | 1631/2057 [08:37<01:49,  3.89item/s, Completed 1631/2057]

Found 119 matched controls for ENSG00000071553
Getting matched controls for ENSG00000188846

Processing conditions:  79%|███████████████████████████████████████████████████▌             | 1633/2057 [08:37<01:51,  3.81item/s, Completed 1633/2057]

Found 220 matched controls for ENSG00000188846
Getting matched controls for ENSG00000136003
Found 58 matched controls for ENSG00000136003
Getting matched controls for ENSG00000158042

Processing conditions:  79%|███████████████████████████████████████████████████▋             | 1635/2057 [08:38<01:35,  4.42item/s, Completed 1635/2057]

Found 99 matched controls for ENSG00000158042
Getting matched controls for ENSG00000180596
Found 64 matched controls for ENSG00000180596
Getting matched controls for ENSG00000047410

Processing conditions:  80%|███████████████████████████████████████████████████▋             | 1636/2057 [08:38<01:28,  4.76item/s, Completed 1636/2057]

Found 77 matched controls for ENSG00000047410
Getting matched controls for ENSG00000131368

Processing conditions:  80%|███████████████████████████████████████████████████▊             | 1638/2057 [08:38<01:21,  5.13item/s, Completed 1638/2057]

Found 99 matched controls for ENSG00000131368
Getting matched controls for ENSG00000182154
Found 69 matched controls for ENSG00000182154
Getting matched controls for ENSG00000168056

Processing conditions:  80%|███████████████████████████████████████████████████▊             | 1639/2057 [08:38<01:37,  4.30item/s, Completed 1639/2057]

Found 157 matched controls for ENSG00000168056
Getting matched controls for ENSG00000105676

Processing conditions:  80%|███████████████████████████████████████████████████▊             | 1640/2057 [08:39<01:38,  4.25item/s, Completed 1640/2057]

Found 86 matched controls for ENSG00000105676
Getting matched controls for ENSG00000166847

Processing conditions:  80%|███████████████████████████████████████████████████▉             | 1642/2057 [08:39<01:31,  4.56item/s, Completed 1642/2057]

Found 141 matched controls for ENSG00000166847
Getting matched controls for ENSG00000108384
Found 65 matched controls for ENSG00000108384
Getting matched controls for ENSG00000075131

Processing conditions:  80%|███████████████████████████████████████████████████▉             | 1643/2057 [08:39<01:31,  4.53item/s, Completed 1643/2057]

Found 109 matched controls for ENSG00000075131
Getting matched controls for ENSG00000140319

Processing conditions:  80%|███████████████████████████████████████████████████▉             | 1644/2057 [08:40<01:35,  4.30item/s, Completed 1644/2057]

Found 132 matched controls for ENSG00000140319
Getting matched controls for ENSG00000001497

Processing conditions:  80%|███████████████████████████████████████████████████▉             | 1645/2057 [08:40<01:32,  4.45item/s, Completed 1645/2057]

Found 83 matched controls for ENSG00000001497
Getting matched controls for ENSG00000068120

Processing conditions:  80%|████████████████████████████████████████████████████             | 1647/2057 [08:40<01:41,  4.04item/s, Completed 1647/2057]

Found 247 matched controls for ENSG00000068120
Getting matched controls for ENSG00000217930
Found 56 matched controls for ENSG00000217930
Getting matched controls for ENSG00000221944

Processing conditions:  80%|████████████████████████████████████████████████████             | 1648/2057 [08:41<01:31,  4.48item/s, Completed 1648/2057]

Found 59 matched controls for ENSG00000221944
Getting matched controls for ENSG00000278053

Processing conditions:  80%|████████████████████████████████████████████████████▏            | 1650/2057 [08:41<01:22,  4.91item/s, Completed 1650/2057]

Found 117 matched controls for ENSG00000278053
Getting matched controls for ENSG00000066136
Found 23 matched controls for ENSG00000066136
Getting matched controls for ENSG00000144381

Processing conditions:  80%|████████████████████████████████████████████████████▏            | 1652/2057 [08:41<01:29,  4.52item/s, Completed 1652/2057]

Found 145 matched controls for ENSG00000144381
Getting matched controls for ENSG00000170855
Found 66 matched controls for ENSG00000170855
Getting matched controls for ENSG00000134153

Processing conditions:  80%|████████████████████████████████████████████████████▏            | 1653/2057 [08:42<01:46,  3.80item/s, Completed 1653/2057]

Found 193 matched controls for ENSG00000134153
Getting matched controls for ENSG00000161980

Processing conditions:  80%|████████████████████████████████████████████████████▎            | 1654/2057 [08:42<01:41,  3.98item/s, Completed 1654/2057]

Found 108 matched controls for ENSG00000161980
Getting matched controls for ENSG00000183495

Processing conditions:  80%|████████████████████████████████████████████████████▎            | 1655/2057 [08:42<01:41,  3.94item/s, Completed 1655/2057]

Found 82 matched controls for ENSG00000183495
Getting matched controls for ENSG00000182512

Processing conditions:  81%|████████████████████████████████████████████████████▎            | 1657/2057 [08:43<01:26,  4.61item/s, Completed 1657/2057]

Found 99 matched controls for ENSG00000182512
Getting matched controls for ENSG00000128626
Found 55 matched controls for ENSG00000128626
Getting matched controls for ENSG00000182872

Processing conditions:  81%|████████████████████████████████████████████████████▍            | 1658/2057 [08:43<01:30,  4.40item/s, Completed 1658/2057]

Found 130 matched controls for ENSG00000182872
Getting matched controls for ENSG00000169375

Processing conditions:  81%|████████████████████████████████████████████████████▍            | 1659/2057 [08:43<02:08,  3.09item/s, Completed 1659/2057]

Found 307 matched controls for ENSG00000169375
Getting matched controls for ENSG00000163029

Processing conditions:  81%|████████████████████████████████████████████████████▍            | 1660/2057 [08:44<01:59,  3.32item/s, Completed 1660/2057]

Found 125 matched controls for ENSG00000163029
Getting matched controls for ENSG00000163156

Processing conditions:  81%|████████████████████████████████████████████████████▍            | 1661/2057 [08:44<01:48,  3.65item/s, Completed 1661/2057]

Found 101 matched controls for ENSG00000163156
Getting matched controls for ENSG00000058262

Processing conditions:  81%|████████████████████████████████████████████████████▌            | 1662/2057 [08:44<01:54,  3.45item/s, Completed 1663/2057]

Found 180 matched controls for ENSG00000058262
Getting matched controls for ENSG00000099194
Found 24 matched controls for ENSG00000099194
Getting matched controls for ENSG00000129534

Processing conditions:  81%|████████████████████████████████████████████████████▌            | 1664/2057 [08:45<01:29,  4.40item/s, Completed 1664/2057]

Found 107 matched controls for ENSG00000129534
Getting matched controls for ENSG00000167987

Processing conditions:  81%|████████████████████████████████████████████████████▋            | 1666/2057 [08:45<01:28,  4.41item/s, Completed 1666/2057]

Found 177 matched controls for ENSG00000167987
Getting matched controls for ENSG00000095059
Found 66 matched controls for ENSG00000095059
Getting matched controls for ENSG00000112742

Processing conditions:  81%|████████████████████████████████████████████████████▋            | 1668/2057 [08:46<01:30,  4.29item/s, Completed 1668/2057]

Found 199 matched controls for ENSG00000112742
Getting matched controls for ENSG00000121152
Found 68 matched controls for ENSG00000121152
Getting matched controls for ENSG00000103194

Processing conditions:  81%|████████████████████████████████████████████████████▊            | 1670/2057 [08:46<01:23,  4.63item/s, Completed 1670/2057]

Found 92 matched controls for ENSG00000103194
Getting matched controls for ENSG00000107937
Found 71 matched controls for ENSG00000107937
Getting matched controls for ENSG00000168393

Processing conditions:  81%|████████████████████████████████████████████████████▊            | 1671/2057 [08:46<01:25,  4.51item/s, Completed 1671/2057]

Found 121 matched controls for ENSG00000168393
Getting matched controls for ENSG00000126261

Processing conditions:  81%|████████████████████████████████████████████████████▊            | 1672/2057 [08:46<01:38,  3.91item/s, Completed 1672/2057]

Found 172 matched controls for ENSG00000126261
Getting matched controls for ENSG00000225828

Processing conditions:  81%|████████████████████████████████████████████████████▊            | 1673/2057 [08:47<01:40,  3.80item/s, Completed 1673/2057]

Found 137 matched controls for ENSG00000225828
Getting matched controls for ENSG00000124571

Processing conditions:  81%|████████████████████████████████████████████████████▉            | 1674/2057 [08:47<01:59,  3.19item/s, Completed 1674/2057]

Found 221 matched controls for ENSG00000124571
Getting matched controls for ENSG00000140854

Processing conditions:  81%|████████████████████████████████████████████████████▉            | 1675/2057 [08:48<02:00,  3.16item/s, Completed 1675/2057]

Found 178 matched controls for ENSG00000140854
Getting matched controls for ENSG00000134146

Processing conditions:  82%|████████████████████████████████████████████████████▉            | 1677/2057 [08:48<01:36,  3.95item/s, Completed 1677/2057]

Found 101 matched controls for ENSG00000134146
Getting matched controls for ENSG00000077549
Found 83 matched controls for ENSG00000077549
Getting matched controls for ENSG00000204449

Processing conditions:  82%|█████████████████████████████████████████████████████            | 1679/2057 [08:48<01:21,  4.61item/s, Completed 1679/2057]

Found 85 matched controls for ENSG00000204449
Getting matched controls for ENSG00000189007
Found 85 matched controls for ENSG00000189007
Getting matched controls for ENSG00000071994

Processing conditions:  82%|█████████████████████████████████████████████████████            | 1680/2057 [08:48<01:19,  4.75item/s, Completed 1680/2057]

Found 74 matched controls for ENSG00000071994
Getting matched controls for ENSG00000113734

Processing conditions:  82%|█████████████████████████████████████████████████████            | 1681/2057 [08:49<01:20,  4.67item/s, Completed 1681/2057]

Found 111 matched controls for ENSG00000113734
Getting matched controls for ENSG00000139131

Processing conditions:  82%|█████████████████████████████████████████████████████▏           | 1682/2057 [08:49<01:35,  3.94item/s, Completed 1682/2057]

Found 190 matched controls for ENSG00000139131
Getting matched controls for ENSG00000143774

Processing conditions:  82%|█████████████████████████████████████████████████████▏           | 1684/2057 [08:49<01:23,  4.45item/s, Completed 1684/2057]

Found 118 matched controls for ENSG00000143774
Getting matched controls for ENSG00000112983
Found 77 matched controls for ENSG00000112983
Getting matched controls for ENSG00000107833

Processing conditions:  82%|█████████████████████████████████████████████████████▏           | 1685/2057 [08:50<01:17,  4.82item/s, Completed 1685/2057]

Found 62 matched controls for ENSG00000107833
Getting matched controls for ENSG00000182220

Processing conditions:  82%|█████████████████████████████████████████████████████▎           | 1687/2057 [08:50<01:23,  4.42item/s, Completed 1687/2057]

Found 175 matched controls for ENSG00000182220
Getting matched controls for ENSG00000099795
Found 74 matched controls for ENSG00000099795
Getting matched controls for ENSG00000256525

Processing conditions:  82%|█████████████████████████████████████████████████████▎           | 1689/2057 [08:51<01:22,  4.45item/s, Completed 1689/2057]

Found 156 matched controls for ENSG00000256525
Getting matched controls for ENSG00000213246
Found 74 matched controls for ENSG00000213246
Getting matched controls for ENSG00000152253

Processing conditions:  82%|█████████████████████████████████████████████████████▍           | 1690/2057 [08:51<01:40,  3.65item/s, Completed 1690/2057]

Found 199 matched controls for ENSG00000152253
Getting matched controls for ENSG00000012174

Processing conditions:  82%|█████████████████████████████████████████████████████▍           | 1691/2057 [08:51<01:55,  3.16item/s, Completed 1691/2057]

Found 214 matched controls for ENSG00000012174
Getting matched controls for ENSG00000221983

Processing conditions:  82%|█████████████████████████████████████████████████████▍           | 1692/2057 [08:52<01:43,  3.54item/s, Completed 1693/2057]

Found 58 matched controls for ENSG00000221983
Getting matched controls for ENSG00000006744
Found 85 matched controls for ENSG00000006744

Processing conditions:  82%|█████████████████████████████████████████████████████▌           | 1694/2057 [08:52<01:18,  4.61item/s, Completed 1694/2057]

Getting matched controls for ENSG00000105697
Found 33 matched controls for ENSG00000105697
Getting matched controls for ENSG00000111300

Processing conditions:  82%|█████████████████████████████████████████████████████▌           | 1696/2057 [08:52<01:27,  4.15item/s, Completed 1696/2057]

Found 176 matched controls for ENSG00000111300
Getting matched controls for ENSG00000126524
Found 95 matched controls for ENSG00000126524
Getting matched controls for ENSG00000137815

Processing conditions:  82%|█████████████████████████████████████████████████████▌           | 1697/2057 [08:53<01:18,  4.56item/s, Completed 1697/2057]

Found 62 matched controls for ENSG00000137815
Getting matched controls for ENSG00000132646

Processing conditions:  83%|█████████████████████████████████████████████████████▋           | 1698/2057 [08:53<01:24,  4.23item/s, Completed 1698/2057]

Found 132 matched controls for ENSG00000132646
Getting matched controls for ENSG00000071127

Processing conditions:  83%|█████████████████████████████████████████████████████▋           | 1700/2057 [08:53<01:16,  4.64item/s, Completed 1700/2057]

Found 102 matched controls for ENSG00000071127
Getting matched controls for ENSG00000143256
Found 86 matched controls for ENSG00000143256
Getting matched controls for ENSG00000136238

Processing conditions:  83%|█████████████████████████████████████████████████████▊           | 1702/2057 [08:54<01:23,  4.25item/s, Completed 1702/2057]

Found 194 matched controls for ENSG00000136238
Getting matched controls for ENSG00000159593
Found 88 matched controls for ENSG00000159593
Getting matched controls for ENSG00000196419

Processing conditions:  83%|█████████████████████████████████████████████████████▊           | 1703/2057 [08:54<01:12,  4.91item/s, Completed 1703/2057]

Found 28 matched controls for ENSG00000196419
Getting matched controls for ENSG00000112195

Processing conditions:  83%|█████████████████████████████████████████████████████▉           | 1705/2057 [08:54<01:04,  5.43item/s, Completed 1705/2057]

Found 58 matched controls for ENSG00000112195
Getting matched controls for ENSG00000101182
Found 41 matched controls for ENSG00000101182
Getting matched controls for ENSG00000114346

Processing conditions:  83%|█████████████████████████████████████████████████████▉           | 1707/2057 [08:55<01:01,  5.69item/s, Completed 1707/2057]

Found 55 matched controls for ENSG00000114346
Getting matched controls for ENSG00000168374
Found 89 matched controls for ENSG00000168374
Getting matched controls for ENSG00000015676

Processing conditions:  83%|██████████████████████████████████████████████████████           | 1709/2057 [08:55<01:01,  5.70item/s, Completed 1709/2057]

Found 112 matched controls for ENSG00000015676
Getting matched controls for ENSG00000229117
Found 47 matched controls for ENSG00000229117
Getting matched controls for ENSG00000142784

Processing conditions:  83%|██████████████████████████████████████████████████████           | 1710/2057 [08:55<01:07,  5.15item/s, Completed 1710/2057]

Found 112 matched controls for ENSG00000142784
Getting matched controls for ENSG00000183598

Processing conditions:  83%|██████████████████████████████████████████████████████           | 1711/2057 [08:56<01:23,  4.13item/s, Completed 1711/2057]

Found 185 matched controls for ENSG00000183598
Getting matched controls for ENSG00000153107

Processing conditions:  83%|██████████████████████████████████████████████████████           | 1712/2057 [08:56<01:25,  4.02item/s, Completed 1712/2057]

Found 124 matched controls for ENSG00000153107
Getting matched controls for ENSG00000066322

Processing conditions:  83%|██████████████████████████████████████████████████████▏          | 1713/2057 [08:56<01:36,  3.56item/s, Completed 1713/2057]

Found 176 matched controls for ENSG00000066322
Getting matched controls for ENSG00000172273

Processing conditions:  83%|██████████████████████████████████████████████████████▏          | 1714/2057 [08:57<01:40,  3.42item/s, Completed 1714/2057]

Found 160 matched controls for ENSG00000172273
Getting matched controls for ENSG00000101246

Processing conditions:  83%|██████████████████████████████████████████████████████▏          | 1716/2057 [08:57<01:18,  4.33item/s, Completed 1716/2057]

Found 138 matched controls for ENSG00000101246
Getting matched controls for ENSG00000144161
Found 21 matched controls for ENSG00000144161
Getting matched controls for ENSG00000178950

Processing conditions:  83%|██████████████████████████████████████████████████████▎          | 1717/2057 [08:57<01:27,  3.87item/s, Completed 1717/2057]

Found 167 matched controls for ENSG00000178950
Getting matched controls for ENSG00000160679

Processing conditions:  84%|██████████████████████████████████████████████████████▎          | 1719/2057 [08:58<01:19,  4.25item/s, Completed 1719/2057]

Found 149 matched controls for ENSG00000160679
Getting matched controls for ENSG00000135900
Found 73 matched controls for ENSG00000135900
Getting matched controls for ENSG00000120539

Processing conditions:  84%|██████████████████████████████████████████████████████▎          | 1720/2057 [08:58<01:20,  4.21item/s, Completed 1720/2057]

Found 112 matched controls for ENSG00000120539
Getting matched controls for ENSG00000173812

Processing conditions:  84%|██████████████████████████████████████████████████████▍          | 1722/2057 [08:58<01:13,  4.55item/s, Completed 1722/2057]

Found 95 matched controls for ENSG00000173812
Getting matched controls for ENSG00000153201
Found 85 matched controls for ENSG00000153201
Getting matched controls for ENSG00000086758

Processing conditions:  84%|██████████████████████████████████████████████████████▍          | 1723/2057 [08:59<01:12,  4.59item/s, Completed 1724/2057]

Found 94 matched controls for ENSG00000086758
Getting matched controls for ENSG00000127922
Found 88 matched controls for ENSG00000127922

Processing conditions:  84%|██████████████████████████████████████████████████████▌          | 1725/2057 [08:59<01:01,  5.39item/s, Completed 1725/2057]

Getting matched controls for ENSG00000111845
Found 21 matched controls for ENSG00000111845
Getting matched controls for ENSG00000185379

Processing conditions:  84%|██████████████████████████████████████████████████████▌          | 1726/2057 [08:59<01:11,  4.64item/s, Completed 1726/2057]

Found 142 matched controls for ENSG00000185379
Getting matched controls for ENSG00000174990

Processing conditions:  84%|██████████████████████████████████████████████████████▌          | 1727/2057 [09:00<01:26,  3.82item/s, Completed 1727/2057]

Found 190 matched controls for ENSG00000174990
Getting matched controls for ENSG00000036257

Processing conditions:  84%|██████████████████████████████████████████████████████▌          | 1728/2057 [09:00<01:25,  3.87item/s, Completed 1728/2057]

Found 120 matched controls for ENSG00000036257
Getting matched controls for ENSG00000163528

Processing conditions:  84%|██████████████████████████████████████████████████████▋          | 1730/2057 [09:00<01:17,  4.25item/s, Completed 1730/2057]

Found 140 matched controls for ENSG00000163528
Getting matched controls for ENSG00000156876
Found 68 matched controls for ENSG00000156876
Getting matched controls for ENSG00000073578

Processing conditions:  84%|██████████████████████████████████████████████████████▋          | 1731/2057 [09:00<01:11,  4.57item/s, Completed 1731/2057]

Found 62 matched controls for ENSG00000073578
Getting matched controls for ENSG00000104976

Processing conditions:  84%|██████████████████████████████████████████████████████▋          | 1732/2057 [09:01<01:09,  4.67item/s, Completed 1732/2057]

Found 72 matched controls for ENSG00000104976
Getting matched controls for ENSG00000130204

Processing conditions:  84%|██████████████████████████████████████████████████████▊          | 1734/2057 [09:01<01:01,  5.23item/s, Completed 1734/2057]

Found 117 matched controls for ENSG00000130204
Getting matched controls for ENSG00000100296
Found 32 matched controls for ENSG00000100296
Getting matched controls for ENSG00000205659

Processing conditions:  84%|██████████████████████████████████████████████████████▊          | 1735/2057 [09:01<00:55,  5.80item/s, Completed 1735/2057]

Found 13 matched controls for ENSG00000205659
Getting matched controls for ENSG00000132463

Processing conditions:  84%|██████████████████████████████████████████████████████▉          | 1737/2057 [09:02<01:09,  4.59item/s, Completed 1737/2057]

Found 172 matched controls for ENSG00000132463
Getting matched controls for ENSG00000100726
Found 74 matched controls for ENSG00000100726

Processing conditions:  84%|██████████████████████████████████████████████████████▉          | 1738/2057 [09:02<01:07,  4.74item/s, Completed 1738/2057]

Getting matched controls for ENSG00000163918
Found 72 matched controls for ENSG00000163918
Getting matched controls for ENSG00000175906

Processing conditions:  85%|██████████████████████████████████████████████████████▉          | 1739/2057 [09:02<01:14,  4.28item/s, Completed 1739/2057]

Found 120 matched controls for ENSG00000175906
Getting matched controls for ENSG00000164754

Processing conditions:  85%|███████████████████████████████████████████████████████          | 1741/2057 [09:03<01:08,  4.62item/s, Completed 1741/2057]

Found 117 matched controls for ENSG00000164754
Getting matched controls for ENSG00000109618
Found 82 matched controls for ENSG00000109618
Getting matched controls for ENSG00000141564

Processing conditions:  85%|███████████████████████████████████████████████████████          | 1742/2057 [09:03<01:06,  4.72item/s, Completed 1742/2057]

Found 82 matched controls for ENSG00000141564
Getting matched controls for ENSG00000156831

Processing conditions:  85%|███████████████████████████████████████████████████████          | 1743/2057 [09:03<01:08,  4.57item/s, Completed 1743/2057]

Found 118 matched controls for ENSG00000156831
Getting matched controls for ENSG00000143164

Processing conditions:  85%|███████████████████████████████████████████████████████▏         | 1745/2057 [09:03<01:09,  4.50item/s, Completed 1745/2057]

Found 137 matched controls for ENSG00000143164
Getting matched controls for ENSG00000204469
Found 89 matched controls for ENSG00000204469
Getting matched controls for ENSG00000131165

Processing conditions:  85%|███████████████████████████████████████████████████████▏         | 1746/2057 [09:04<01:07,  4.59item/s, Completed 1746/2057]

Found 78 matched controls for ENSG00000131165
Getting matched controls for ENSG00000146540

Processing conditions:  85%|███████████████████████████████████████████████████████▏         | 1748/2057 [09:04<01:03,  4.88item/s, Completed 1748/2057]

Found 93 matched controls for ENSG00000146540
Getting matched controls for ENSG00000143771
Found 67 matched controls for ENSG00000143771
Getting matched controls for ENSG00000121743

Processing conditions:  85%|███████████████████████████████████████████████████████▎         | 1749/2057 [09:04<00:59,  5.17item/s, Completed 1749/2057]

Found 73 matched controls for ENSG00000121743
Getting matched controls for ENSG00000156261

Processing conditions:  85%|███████████████████████████████████████████████████████▎         | 1750/2057 [09:04<01:03,  4.81item/s, Completed 1750/2057]

Found 111 matched controls for ENSG00000156261
Getting matched controls for ENSG00000100949

Processing conditions:  85%|███████████████████████████████████████████████████████▎         | 1752/2057 [09:05<01:04,  4.76item/s, Completed 1752/2057]

Found 116 matched controls for ENSG00000100949
Getting matched controls for ENSG00000075886
Found 69 matched controls for ENSG00000075886
Getting matched controls for ENSG00000111605

Processing conditions:  85%|███████████████████████████████████████████████████████▍         | 1753/2057 [09:05<00:58,  5.19item/s, Completed 1753/2057]

Found 50 matched controls for ENSG00000111605
Getting matched controls for ENSG00000249115

Processing conditions:  85%|███████████████████████████████████████████████████████▍         | 1754/2057 [09:05<01:09,  4.37item/s, Completed 1754/2057]

Found 160 matched controls for ENSG00000249115
Getting matched controls for ENSG00000168496

Processing conditions:  85%|███████████████████████████████████████████████████████▍         | 1755/2057 [09:06<01:15,  4.01item/s, Completed 1755/2057]

Found 141 matched controls for ENSG00000168496
Getting matched controls for ENSG00000166197

Processing conditions:  85%|███████████████████████████████████████████████████████▌         | 1757/2057 [09:06<01:08,  4.39item/s, Completed 1757/2057]

Found 119 matched controls for ENSG00000166197
Getting matched controls for ENSG00000128422
Found 85 matched controls for ENSG00000128422
Getting matched controls for ENSG00000161960

Processing conditions:  86%|███████████████████████████████████████████████████████▌         | 1759/2057 [09:06<00:57,  5.19item/s, Completed 1759/2057]

Found 46 matched controls for ENSG00000161960
Getting matched controls for ENSG00000127580
Found 82 matched controls for ENSG00000127580
Getting matched controls for ENSG00000165138

Processing conditions:  86%|███████████████████████████████████████████████████████▋         | 1761/2057 [09:07<00:52,  5.66item/s, Completed 1761/2057]

Found 95 matched controls for ENSG00000165138
Getting matched controls for ENSG00000055044
Found 55 matched controls for ENSG00000055044
Getting matched controls for ENSG00000149262

Processing conditions:  86%|███████████████████████████████████████████████████████▋         | 1763/2057 [09:07<00:50,  5.83item/s, Completed 1763/2057]

Found 48 matched controls for ENSG00000149262
Getting matched controls for ENSG00000086189
Found 94 matched controls for ENSG00000086189
Getting matched controls for ENSG00000148688

Processing conditions:  86%|███████████████████████████████████████████████████████▋         | 1764/2057 [09:07<00:53,  5.51item/s, Completed 1765/2057]

Found 101 matched controls for ENSG00000148688
Getting matched controls for ENSG00000100811
Found 82 matched controls for ENSG00000100811

Processing conditions:  86%|███████████████████████████████████████████████████████▊         | 1766/2057 [09:08<00:51,  5.69item/s, Completed 1766/2057]

Getting matched controls for ENSG00000188612
Found 63 matched controls for ENSG00000188612
Getting matched controls for ENSG00000110107

Processing conditions:  86%|███████████████████████████████████████████████████████▊         | 1768/2057 [09:08<00:56,  5.09item/s, Completed 1768/2057]

Found 112 matched controls for ENSG00000110107
Getting matched controls for ENSG00000136888
Found 67 matched controls for ENSG00000136888
Getting matched controls for ENSG00000276410

Processing conditions:  86%|███████████████████████████████████████████████████████▉         | 1770/2057 [09:09<00:58,  4.90item/s, Completed 1770/2057]

Found 135 matched controls for ENSG00000276410
Getting matched controls for ENSG00000091651
Found 81 matched controls for ENSG00000091651
Getting matched controls for ENSG00000126953

Processing conditions:  86%|███████████████████████████████████████████████████████▉         | 1772/2057 [09:09<01:03,  4.48item/s, Completed 1772/2057]

Found 162 matched controls for ENSG00000126953
Getting matched controls for ENSG00000125755
Found 89 matched controls for ENSG00000125755
Getting matched controls for ENSG00000198887

Processing conditions:  86%|████████████████████████████████████████████████████████         | 1774/2057 [09:09<01:01,  4.63item/s, Completed 1774/2057]

Found 121 matched controls for ENSG00000198887
Getting matched controls for ENSG00000115685
Found 63 matched controls for ENSG00000115685
Getting matched controls for ENSG00000117360

Processing conditions:  86%|████████████████████████████████████████████████████████         | 1776/2057 [09:10<01:07,  4.19item/s, Completed 1776/2057]

Found 143 matched controls for ENSG00000117360
Getting matched controls for ENSG00000182173
Found 52 matched controls for ENSG00000182173
Getting matched controls for ENSG00000140307

Processing conditions:  86%|████████████████████████████████████████████████████████▏        | 1778/2057 [09:10<01:01,  4.54item/s, Completed 1778/2057]

Found 173 matched controls for ENSG00000140307
Getting matched controls for ENSG00000134186
Found 29 matched controls for ENSG00000134186
Getting matched controls for ENSG00000160563

Processing conditions:  86%|████████████████████████████████████████████████████████▏        | 1779/2057 [09:11<00:51,  5.42item/s, Completed 1779/2057]

Found 19 matched controls for ENSG00000160563
Getting matched controls for ENSG00000165480

Processing conditions:  87%|████████████████████████████████████████████████████████▎        | 1781/2057 [09:11<00:55,  4.98item/s, Completed 1781/2057]

Found 116 matched controls for ENSG00000165480
Getting matched controls for ENSG00000165732
Found 90 matched controls for ENSG00000165732
Getting matched controls for ENSG00000163399

Processing conditions:  87%|████████████████████████████████████████████████████████▎        | 1782/2057 [09:11<00:53,  5.14item/s, Completed 1783/2057]

Found 84 matched controls for ENSG00000163399
Getting matched controls for ENSG00000142089
Found 20 matched controls for ENSG00000142089
Getting matched controls for ENSG00000167881

Processing conditions:  87%|████████████████████████████████████████████████████████▍        | 1785/2057 [09:12<00:49,  5.44item/s, Completed 1785/2057]

Found 171 matched controls for ENSG00000167881
Getting matched controls for ENSG00000074201
Found 53 matched controls for ENSG00000074201
Getting matched controls for ENSG00000166598

Processing conditions:  87%|████████████████████████████████████████████████████████▍        | 1786/2057 [09:12<00:52,  5.12item/s, Completed 1786/2057]

Found 114 matched controls for ENSG00000166598
Getting matched controls for ENSG00000162368

Processing conditions:  87%|████████████████████████████████████████████████████████▍        | 1787/2057 [09:12<01:01,  4.38item/s, Completed 1787/2057]

Found 173 matched controls for ENSG00000162368
Getting matched controls for ENSG00000163660

Processing conditions:  87%|████████████████████████████████████████████████████████▍        | 1788/2057 [09:13<01:10,  3.82item/s, Completed 1788/2057]

Found 177 matched controls for ENSG00000163660
Getting matched controls for ENSG00000103342

Processing conditions:  87%|████████████████████████████████████████████████████████▌        | 1789/2057 [09:13<01:07,  3.99item/s, Completed 1789/2057]

Found 108 matched controls for ENSG00000103342
Getting matched controls for ENSG00000157216

Processing conditions:  87%|████████████████████████████████████████████████████████▌        | 1790/2057 [09:13<01:04,  4.14item/s, Completed 1790/2057]

Found 107 matched controls for ENSG00000157216
Getting matched controls for ENSG00000186185

Processing conditions:  87%|████████████████████████████████████████████████████████▋        | 1793/2057 [09:13<00:45,  5.82item/s, Completed 1793/2057]

Found 122 matched controls for ENSG00000186185
Getting matched controls for ENSG00000170325
Found 14 matched controls for ENSG00000170325
Getting matched controls for ENSG00000162408
Found 33 matched controls for ENSG00000162408
Getting matched controls for ENSG00000119421

Processing conditions:  87%|████████████████████████████████████████████████████████▋        | 1794/2057 [09:14<00:48,  5.44item/s, Completed 1794/2057]

Found 109 matched controls for ENSG00000119421
Getting matched controls for ENSG00000118263

Processing conditions:  87%|████████████████████████████████████████████████████████▊        | 1796/2057 [09:14<00:54,  4.79item/s, Completed 1796/2057]

Found 173 matched controls for ENSG00000118263
Getting matched controls for ENSG00000232838
Found 83 matched controls for ENSG00000232838
Getting matched controls for ENSG00000163159

Processing conditions:  87%|████████████████████████████████████████████████████████▊        | 1798/2057 [09:15<00:49,  5.23item/s, Completed 1798/2057]

Found 98 matched controls for ENSG00000163159
Getting matched controls for ENSG00000110048
Found 65 matched controls for ENSG00000110048
Getting matched controls for ENSG00000155858

Processing conditions:  88%|████████████████████████████████████████████████████████▉        | 1800/2057 [09:15<00:48,  5.25item/s, Completed 1800/2057]

Found 130 matched controls for ENSG00000155858
Getting matched controls for ENSG00000083635
Found 63 matched controls for ENSG00000083635
Getting matched controls for ENSG00000156467

Processing conditions:  88%|████████████████████████████████████████████████████████▉        | 1802/2057 [09:15<00:42,  6.02item/s, Completed 1802/2057]

Found 96 matched controls for ENSG00000156467
Getting matched controls for ENSG00000104129
Found 31 matched controls for ENSG00000104129
Getting matched controls for ENSG00000122952

Processing conditions:  88%|█████████████████████████████████████████████████████████        | 1804/2057 [09:15<00:35,  7.19item/s, Completed 1804/2057]

Found 33 matched controls for ENSG00000122952
Getting matched controls for ENSG00000122965
Found 43 matched controls for ENSG00000122965
Getting matched controls for ENSG00000116221

Processing conditions:  88%|█████████████████████████████████████████████████████████        | 1805/2057 [09:16<00:42,  5.99item/s, Completed 1805/2057]

Found 116 matched controls for ENSG00000116221
Getting matched controls for ENSG00000170043

Processing conditions:  88%|█████████████████████████████████████████████████████████        | 1806/2057 [09:16<00:45,  5.51item/s, Completed 1806/2057]

Found 106 matched controls for ENSG00000170043
Getting matched controls for ENSG00000083845

Processing conditions:  88%|█████████████████████████████████████████████████████████▏       | 1808/2057 [09:16<00:46,  5.34item/s, Completed 1808/2057]

Found 144 matched controls for ENSG00000083845
Getting matched controls for ENSG00000141101
Found 53 matched controls for ENSG00000141101
Getting matched controls for ENSG00000117222

Processing conditions:  88%|█████████████████████████████████████████████████████████▏       | 1810/2057 [09:17<00:35,  6.96item/s, Completed 1810/2057]

Found 23 matched controls for ENSG00000117222
Getting matched controls for ENSG00000277203
Found 28 matched controls for ENSG00000277203
Getting matched controls for ENSG00000105669

Processing conditions:  88%|█████████████████████████████████████████████████████████▏       | 1811/2057 [09:17<00:43,  5.68item/s, Completed 1811/2057]

Found 143 matched controls for ENSG00000105669
Getting matched controls for ENSG00000115884

Processing conditions:  88%|█████████████████████████████████████████████████████████▎       | 1813/2057 [09:17<00:51,  4.75item/s, Completed 1813/2057]

Found 170 matched controls for ENSG00000115884
Getting matched controls for ENSG00000107951
Found 90 matched controls for ENSG00000107951
Getting matched controls for ENSG00000112339

Processing conditions:  88%|█████████████████████████████████████████████████████████▎       | 1814/2057 [09:18<00:56,  4.27item/s, Completed 1814/2057]

Found 143 matched controls for ENSG00000112339
Getting matched controls for ENSG00000171311

Processing conditions:  88%|█████████████████████████████████████████████████████████▍       | 1816/2057 [09:18<00:49,  4.86item/s, Completed 1816/2057]

Found 77 matched controls for ENSG00000171311
Getting matched controls for ENSG00000138777
Found 64 matched controls for ENSG00000138777
Getting matched controls for ENSG00000144426

Processing conditions:  88%|█████████████████████████████████████████████████████████▍       | 1818/2057 [09:18<00:46,  5.09item/s, Completed 1818/2057]

Found 99 matched controls for ENSG00000144426
Getting matched controls for ENSG00000274290
Found 55 matched controls for ENSG00000274290
Getting matched controls for ENSG00000044090

Processing conditions:  88%|█████████████████████████████████████████████████████████▍       | 1819/2057 [09:19<00:42,  5.56item/s, Completed 1819/2057]

Found 33 matched controls for ENSG00000044090
Getting matched controls for ENSG00000114650

Processing conditions:  88%|█████████████████████████████████████████████████████████▌       | 1820/2057 [09:19<00:51,  4.59item/s, Completed 1820/2057]

Found 140 matched controls for ENSG00000114650
Getting matched controls for ENSG00000172172

Processing conditions:  89%|█████████████████████████████████████████████████████████▌       | 1822/2057 [09:19<00:43,  5.43item/s, Completed 1822/2057]

Found 87 matched controls for ENSG00000172172
Getting matched controls for ENSG00000103061
Found 38 matched controls for ENSG00000103061
Getting matched controls for ENSG00000197345

Processing conditions:  89%|█████████████████████████████████████████████████████████▋       | 1824/2057 [09:19<00:36,  6.44item/s, Completed 1824/2057]

Found 14 matched controls for ENSG00000197345
Getting matched controls for ENSG00000166233
Found 59 matched controls for ENSG00000166233
Getting matched controls for ENSG00000144736

Processing conditions:  89%|█████████████████████████████████████████████████████████▋       | 1826/2057 [09:20<00:40,  5.76item/s, Completed 1826/2057]

Found 94 matched controls for ENSG00000144736
Getting matched controls for ENSG00000141456
Found 69 matched controls for ENSG00000141456
Getting matched controls for ENSG00000169249

Processing conditions:  89%|█████████████████████████████████████████████████████████▊       | 1828/2057 [09:20<00:42,  5.45item/s, Completed 1828/2057]

Found 113 matched controls for ENSG00000169249
Getting matched controls for ENSG00000182944
Found 48 matched controls for ENSG00000182944
Getting matched controls for ENSG00000225921

Processing conditions:  89%|█████████████████████████████████████████████████████████▊       | 1829/2057 [09:20<00:41,  5.55item/s, Completed 1829/2057]

Found 73 matched controls for ENSG00000225921
Getting matched controls for ENSG00000183258

Processing conditions:  89%|█████████████████████████████████████████████████████████▊       | 1831/2057 [09:21<00:53,  4.26item/s, Completed 1831/2057]

Found 292 matched controls for ENSG00000183258
Getting matched controls for ENSG00000089685
Found 46 matched controls for ENSG00000089685
Getting matched controls for ENSG00000092094

Processing conditions:  89%|█████████████████████████████████████████████████████████▉       | 1832/2057 [09:21<00:48,  4.60item/s, Completed 1832/2057]

Found 70 matched controls for ENSG00000092094
Getting matched controls for ENSG00000197958

Processing conditions:  89%|█████████████████████████████████████████████████████████▉       | 1834/2057 [09:22<00:56,  3.97item/s, Completed 1834/2057]

Found 255 matched controls for ENSG00000197958
Getting matched controls for ENSG00000113558
Found 66 matched controls for ENSG00000113558
Getting matched controls for ENSG00000069248

Processing conditions:  89%|██████████████████████████████████████████████████████████       | 1836/2057 [09:22<00:45,  4.90item/s, Completed 1836/2057]

Found 79 matched controls for ENSG00000069248
Getting matched controls for ENSG00000132485
Found 40 matched controls for ENSG00000132485
Getting matched controls for ENSG00000105849

Processing conditions:  89%|██████████████████████████████████████████████████████████       | 1838/2057 [09:23<00:48,  4.50item/s, Completed 1838/2057]

Found 169 matched controls for ENSG00000105849
Getting matched controls for ENSG00000136628
Found 79 matched controls for ENSG00000136628
Getting matched controls for ENSG00000065427

Processing conditions:  89%|██████████████████████████████████████████████████████████▏      | 1840/2057 [09:23<00:43,  5.03item/s, Completed 1840/2057]

Found 59 matched controls for ENSG00000065427
Getting matched controls for ENSG00000100209
Found 86 matched controls for ENSG00000100209
Getting matched controls for ENSG00000100029

Processing conditions:  89%|██████████████████████████████████████████████████████████▏      | 1841/2057 [09:23<00:40,  5.28item/s, Completed 1841/2057]

Found 65 matched controls for ENSG00000100029
Getting matched controls for ENSG00000153187

Processing conditions:  90%|██████████████████████████████████████████████████████████▏      | 1843/2057 [09:24<00:39,  5.46item/s, Completed 1843/2057]

Found 93 matched controls for ENSG00000153187
Getting matched controls for ENSG00000163961
Found 61 matched controls for ENSG00000163961
Getting matched controls for ENSG00000136715

Processing conditions:  90%|██████████████████████████████████████████████████████████▎      | 1845/2057 [09:24<00:39,  5.42item/s, Completed 1845/2057]

Found 113 matched controls for ENSG00000136715
Getting matched controls for ENSG00000148835
Found 35 matched controls for ENSG00000148835
Getting matched controls for ENSG00000108559

Processing conditions:  90%|██████████████████████████████████████████████████████████▎      | 1846/2057 [09:24<00:34,  6.18item/s, Completed 1846/2057]

Found 36 matched controls for ENSG00000108559
Getting matched controls for ENSG00000164919

Processing conditions:  90%|██████████████████████████████████████████████████████████▍      | 1848/2057 [09:24<00:34,  6.13item/s, Completed 1848/2057]

Found 117 matched controls for ENSG00000164919
Getting matched controls for ENSG00000161526
Found 40 matched controls for ENSG00000161526
Getting matched controls for ENSG00000129084

Processing conditions:  90%|██████████████████████████████████████████████████████████▍      | 1850/2057 [09:25<00:41,  5.03item/s, Completed 1850/2057]

Found 170 matched controls for ENSG00000129084
Getting matched controls for ENSG00000129562
Found 80 matched controls for ENSG00000129562
Getting matched controls for ENSG00000086504

Processing conditions:  90%|██████████████████████████████████████████████████████████▌      | 1852/2057 [09:25<00:31,  6.43item/s, Completed 1852/2057]

Found 52 matched controls for ENSG00000086504
Getting matched controls for ENSG00000116017
Found 31 matched controls for ENSG00000116017
Getting matched controls for ENSG00000023608

Processing conditions:  90%|██████████████████████████████████████████████████████████▌      | 1854/2057 [09:25<00:35,  5.73item/s, Completed 1854/2057]

Found 96 matched controls for ENSG00000023608
Getting matched controls for ENSG00000162244
Found 88 matched controls for ENSG00000162244
Getting matched controls for ENSG00000165525

Processing conditions:  90%|██████████████████████████████████████████████████████████▌      | 1855/2057 [09:26<00:33,  6.01item/s, Completed 1855/2057]

Found 63 matched controls for ENSG00000165525
Getting matched controls for ENSG00000096080

Processing conditions:  90%|██████████████████████████████████████████████████████████▋      | 1857/2057 [09:26<00:36,  5.45item/s, Completed 1857/2057]

Found 121 matched controls for ENSG00000096080
Getting matched controls for ENSG00000106628
Found 78 matched controls for ENSG00000106628
Getting matched controls for ENSG00000182783

Processing conditions:  90%|██████████████████████████████████████████████████████████▋      | 1859/2057 [09:26<00:38,  5.09item/s, Completed 1859/2057]

Found 103 matched controls for ENSG00000182783
Getting matched controls for ENSG00000104980
Found 45 matched controls for ENSG00000104980
Getting matched controls for ENSG00000099942

Processing conditions:  90%|██████████████████████████████████████████████████████████▊      | 1860/2057 [09:27<00:43,  4.56item/s, Completed 1860/2057]

Found 120 matched controls for ENSG00000099942
Getting matched controls for ENSG00000118197

Processing conditions:  90%|██████████████████████████████████████████████████████████▊      | 1861/2057 [09:27<00:47,  4.17item/s, Completed 1861/2057]

Found 154 matched controls for ENSG00000118197
Getting matched controls for ENSG00000092853

Processing conditions:  91%|██████████████████████████████████████████████████████████▊      | 1863/2057 [09:27<00:42,  4.52item/s, Completed 1863/2057]

Found 134 matched controls for ENSG00000092853
Getting matched controls for ENSG00000136146
Found 66 matched controls for ENSG00000136146
Getting matched controls for ENSG00000172757

Processing conditions:  91%|██████████████████████████████████████████████████████████▉      | 1864/2057 [09:28<00:36,  5.27item/s, Completed 1864/2057]

Found 23 matched controls for ENSG00000172757
Getting matched controls for ENSG00000182504

Processing conditions:  91%|██████████████████████████████████████████████████████████▉      | 1866/2057 [09:28<00:37,  5.03item/s, Completed 1866/2057]

Found 135 matched controls for ENSG00000182504
Getting matched controls for ENSG00000185838
Found 76 matched controls for ENSG00000185838
Getting matched controls for ENSG00000128908

Processing conditions:  91%|███████████████████████████████████████████████████████████      | 1868/2057 [09:28<00:36,  5.16item/s, Completed 1868/2057]

Found 151 matched controls for ENSG00000128908
Getting matched controls for ENSG00000204370
Found 45 matched controls for ENSG00000204370
Getting matched controls for ENSG00000185359

Processing conditions:  91%|███████████████████████████████████████████████████████████      | 1870/2057 [09:29<00:35,  5.23item/s, Completed 1870/2057]

Found 99 matched controls for ENSG00000185359
Getting matched controls for ENSG00000174886
Found 80 matched controls for ENSG00000174886
Getting matched controls for ENSG00000169021

Processing conditions:  91%|███████████████████████████████████████████████████████████      | 1871/2057 [09:29<00:37,  4.91item/s, Completed 1871/2057]

Found 119 matched controls for ENSG00000169021
Getting matched controls for ENSG00000090470

Processing conditions:  91%|███████████████████████████████████████████████████████████▏     | 1873/2057 [09:29<00:32,  5.66item/s, Completed 1873/2057]

Found 99 matched controls for ENSG00000090470
Getting matched controls for ENSG00000156508
Found 37 matched controls for ENSG00000156508
Getting matched controls for ENSG00000070367

Processing conditions:  91%|███████████████████████████████████████████████████████████▏     | 1874/2057 [09:30<00:35,  5.09item/s, Completed 1874/2057]

Found 110 matched controls for ENSG00000070367
Getting matched controls for ENSG00000143436

Processing conditions:  91%|███████████████████████████████████████████████████████████▎     | 1876/2057 [09:30<00:34,  5.23item/s, Completed 1876/2057]

Found 121 matched controls for ENSG00000143436
Getting matched controls for ENSG00000198841
Found 52 matched controls for ENSG00000198841
Getting matched controls for ENSG00000239779

Processing conditions:  91%|███████████████████████████████████████████████████████████▎     | 1877/2057 [09:30<00:37,  4.84item/s, Completed 1877/2057]

Found 99 matched controls for ENSG00000239779
Getting matched controls for ENSG00000138495

Processing conditions:  91%|███████████████████████████████████████████████████████████▍     | 1879/2057 [09:31<00:35,  5.03item/s, Completed 1879/2057]

Found 143 matched controls for ENSG00000138495
Getting matched controls for ENSG00000132467
Found 27 matched controls for ENSG00000132467
Getting matched controls for ENSG00000087269

Processing conditions:  91%|███████████████████████████████████████████████████████████▍     | 1880/2057 [09:31<00:31,  5.63item/s, Completed 1881/2057]

Found 47 matched controls for ENSG00000087269
Getting matched controls for ENSG00000149308
Found 21 matched controls for ENSG00000149308
Getting matched controls for ENSG00000244005

Processing conditions:  92%|███████████████████████████████████████████████████████████▌     | 1883/2057 [09:31<00:25,  6.87item/s, Completed 1883/2057]

Found 82 matched controls for ENSG00000244005
Getting matched controls for ENSG00000144741
Found 36 matched controls for ENSG00000144741
Getting matched controls for ENSG00000213516

Processing conditions:  92%|███████████████████████████████████████████████████████████▌     | 1885/2057 [09:31<00:26,  6.50item/s, Completed 1885/2057]

Found 60 matched controls for ENSG00000213516
Getting matched controls for ENSG00000061676
Found 70 matched controls for ENSG00000061676
Getting matched controls for ENSG00000151131

Processing conditions:  92%|███████████████████████████████████████████████████████████▌     | 1886/2057 [09:32<00:29,  5.77item/s, Completed 1886/2057]

Found 100 matched controls for ENSG00000151131
Getting matched controls for ENSG00000183513

Processing conditions:  92%|███████████████████████████████████████████████████████████▋     | 1888/2057 [09:32<00:35,  4.77item/s, Completed 1888/2057]

Found 175 matched controls for ENSG00000183513
Getting matched controls for ENSG00000143493
Found 79 matched controls for ENSG00000143493
Getting matched controls for ENSG00000063046

Processing conditions:  92%|███████████████████████████████████████████████████████████▋     | 1889/2057 [09:32<00:32,  5.13item/s, Completed 1890/2057]

Found 41 matched controls for ENSG00000063046
Getting matched controls for ENSG00000171793
Found 14 matched controls for ENSG00000171793
Getting matched controls for ENSG00000241973

Processing conditions:  92%|███████████████████████████████████████████████████████████▊     | 1891/2057 [09:33<00:30,  5.47item/s, Completed 1892/2057]

Found 109 matched controls for ENSG00000241973
Getting matched controls for ENSG00000079805
Found 12 matched controls for ENSG00000079805
Getting matched controls for ENSG00000143621

Processing conditions:  92%|███████████████████████████████████████████████████████████▊     | 1894/2057 [09:33<00:24,  6.61item/s, Completed 1894/2057]

Found 56 matched controls for ENSG00000143621
Getting matched controls for ENSG00000154813
Found 60 matched controls for ENSG00000154813
Getting matched controls for ENSG00000256771

Processing conditions:  92%|███████████████████████████████████████████████████████████▉     | 1896/2057 [09:34<00:28,  5.72item/s, Completed 1896/2057]

Found 118 matched controls for ENSG00000256771
Getting matched controls for ENSG00000079246
Found 88 matched controls for ENSG00000079246
Getting matched controls for ENSG00000005100

Processing conditions:  92%|███████████████████████████████████████████████████████████▉     | 1898/2057 [09:34<00:30,  5.22item/s, Completed 1898/2057]

Found 140 matched controls for ENSG00000005100
Getting matched controls for ENSG00000178028
Found 78 matched controls for ENSG00000178028
Getting matched controls for ENSG00000005007

Processing conditions:  92%|████████████████████████████████████████████████████████████     | 1899/2057 [09:34<00:33,  4.78item/s, Completed 1899/2057]

Found 131 matched controls for ENSG00000005007
Getting matched controls for ENSG00000243927

Processing conditions:  92%|████████████████████████████████████████████████████████████     | 1900/2057 [09:35<00:36,  4.29item/s, Completed 1901/2057]

Found 152 matched controls for ENSG00000243927
Getting matched controls for ENSG00000142937
Found 22 matched controls for ENSG00000142937
Getting matched controls for ENSG00000077348
Found 41 matched controls for ENSG00000077348

Processing conditions:  93%|████████████████████████████████████████████████████████████▏    | 1903/2057 [09:35<00:24,  6.31item/s, Completed 1904/2057]

Getting matched controls for ENSG00000134748
Found 19 matched controls for ENSG00000134748
Getting matched controls for ENSG00000115268
Found 26 matched controls for ENSG00000115268
Getting matched controls for ENSG00000141552

Processing conditions:  93%|████████████████████████████████████████████████████████████▏    | 1906/2057 [09:35<00:20,  7.21item/s, Completed 1906/2057]

Found 77 matched controls for ENSG00000141552
Getting matched controls for ENSG00000101132
Found 34 matched controls for ENSG00000101132
Getting matched controls for ENSG00000127481
Found 26 matched controls for ENSG00000127481

Processing conditions:  93%|████████████████████████████████████████████████████████████▎    | 1908/2057 [09:35<00:21,  6.99item/s, Completed 1908/2057]

Getting matched controls for ENSG00000111011
Found 98 matched controls for ENSG00000111011
Getting matched controls for ENSG00000163655

Processing conditions:  93%|████████████████████████████████████████████████████████████▎    | 1910/2057 [09:36<00:23,  6.14item/s, Completed 1910/2057]

Found 123 matched controls for ENSG00000163655
Getting matched controls for ENSG00000163002
Found 64 matched controls for ENSG00000163002
Getting matched controls for ENSG00000144029

Processing conditions:  93%|████████████████████████████████████████████████████████████▍    | 1911/2057 [09:36<00:24,  5.93item/s, Completed 1911/2057]

Found 73 matched controls for ENSG00000144029
Getting matched controls for ENSG00000145241

Processing conditions:  93%|████████████████████████████████████████████████████████████▍    | 1913/2057 [09:37<00:28,  5.07item/s, Completed 1913/2057]

Found 124 matched controls for ENSG00000145241
Getting matched controls for ENSG00000122257
Found 86 matched controls for ENSG00000122257
Getting matched controls for ENSG00000173726

Processing conditions:  93%|████████████████████████████████████████████████████████████▌    | 1915/2057 [09:37<00:27,  5.14item/s, Completed 1915/2057]

Found 111 matched controls for ENSG00000173726
Getting matched controls for ENSG00000166483
Found 41 matched controls for ENSG00000166483
Getting matched controls for ENSG00000147669

Processing conditions:  93%|████████████████████████████████████████████████████████████▌    | 1917/2057 [09:37<00:23,  5.99item/s, Completed 1917/2057]

Found 22 matched controls for ENSG00000147669
Getting matched controls for ENSG00000146909
Found 80 matched controls for ENSG00000146909
Getting matched controls for ENSG00000111445

Processing conditions:  93%|████████████████████████████████████████████████████████████▋    | 1919/2057 [09:38<00:23,  5.91item/s, Completed 1919/2057]

Found 111 matched controls for ENSG00000111445
Getting matched controls for ENSG00000189306
Found 46 matched controls for ENSG00000189306
Getting matched controls for ENSG00000256618

Processing conditions:  93%|████████████████████████████████████████████████████████████▋    | 1921/2057 [09:38<00:21,  6.38item/s, Completed 1921/2057]

Found 43 matched controls for ENSG00000256618
Getting matched controls for ENSG00000143442
Found 38 matched controls for ENSG00000143442
Getting matched controls for ENSG00000092439

Processing conditions:  93%|████████████████████████████████████████████████████████████▋    | 1922/2057 [09:38<00:27,  4.95item/s, Completed 1922/2057]

Found 128 matched controls for ENSG00000092439
Getting matched controls for ENSG00000185049

Processing conditions:  94%|████████████████████████████████████████████████████████████▊    | 1924/2057 [09:39<00:26,  5.10item/s, Completed 1924/2057]

Found 89 matched controls for ENSG00000185049
Getting matched controls for ENSG00000187922
Found 81 matched controls for ENSG00000187922
Getting matched controls for ENSG00000085721

Processing conditions:  94%|████████████████████████████████████████████████████████████▊    | 1926/2057 [09:39<00:24,  5.45item/s, Completed 1926/2057]

Found 39 matched controls for ENSG00000085721
Getting matched controls for ENSG00000115866
Found 70 matched controls for ENSG00000115866
Getting matched controls for ENSG00000127804

Processing conditions:  94%|████████████████████████████████████████████████████████████▉    | 1928/2057 [09:39<00:21,  6.08item/s, Completed 1928/2057]

Found 42 matched controls for ENSG00000127804
Getting matched controls for ENSG00000108651
Found 69 matched controls for ENSG00000108651
Getting matched controls for ENSG00000063322

Processing conditions:  94%|████████████████████████████████████████████████████████████▉    | 1929/2057 [09:39<00:23,  5.56item/s, Completed 1929/2057]

Found 93 matched controls for ENSG00000063322
Getting matched controls for ENSG00000179115

Processing conditions:  94%|█████████████████████████████████████████████████████████████    | 1931/2057 [09:40<00:25,  4.99item/s, Completed 1931/2057]

Found 138 matched controls for ENSG00000179115
Getting matched controls for ENSG00000198522
Found 86 matched controls for ENSG00000198522
Getting matched controls for ENSG00000273899

Processing conditions:  94%|█████████████████████████████████████████████████████████████    | 1932/2057 [09:40<00:25,  5.00item/s, Completed 1932/2057]

Found 93 matched controls for ENSG00000273899
Getting matched controls for ENSG00000121579

Processing conditions:  94%|█████████████████████████████████████████████████████████████    | 1934/2057 [09:40<00:23,  5.21item/s, Completed 1934/2057]

Found 108 matched controls for ENSG00000121579
Getting matched controls for ENSG00000127993
Found 55 matched controls for ENSG00000127993
Getting matched controls for ENSG00000100902

Processing conditions:  94%|█████████████████████████████████████████████████████████████▏   | 1935/2057 [09:41<00:20,  5.90item/s, Completed 1935/2057]

Found 40 matched controls for ENSG00000100902
Getting matched controls for ENSG00000011426
Found 96 matched controls for ENSG00000011426

Processing conditions:  94%|█████████████████████████████████████████████████████████████▏   | 1937/2057 [09:41<00:19,  6.03item/s, Completed 1937/2057]

Getting matched controls for ENSG00000163781
Found 52 matched controls for ENSG00000163781
Getting matched controls for ENSG00000150991

Processing conditions:  94%|█████████████████████████████████████████████████████████████▎   | 1939/2057 [09:41<00:18,  6.35item/s, Completed 1939/2057]

Found 107 matched controls for ENSG00000150991
Getting matched controls for ENSG00000160949
Found 28 matched controls for ENSG00000160949
Getting matched controls for ENSG00000108010

Processing conditions:  94%|█████████████████████████████████████████████████████████████▎   | 1941/2057 [09:42<00:18,  6.13item/s, Completed 1942/2057]

Found 136 matched controls for ENSG00000108010
Getting matched controls for ENSG00000112081
Found 29 matched controls for ENSG00000112081
Getting matched controls for ENSG00000119953
Found 15 matched controls for ENSG00000119953
Getting matched controls for ENSG00000147162

Processing conditions:  95%|█████████████████████████████████████████████████████████████▍   | 1944/2057 [09:42<00:15,  7.12item/s, Completed 1944/2057]

Found 31 matched controls for ENSG00000147162
Getting matched controls for ENSG00000111358
Found 76 matched controls for ENSG00000111358
Getting matched controls for ENSG00000115446

Processing conditions:  95%|█████████████████████████████████████████████████████████████▍   | 1946/2057 [09:42<00:16,  6.87item/s, Completed 1946/2057]

Found 83 matched controls for ENSG00000115446
Getting matched controls for ENSG00000149313
Found 49 matched controls for ENSG00000149313
Getting matched controls for ENSG00000104824

Processing conditions:  95%|█████████████████████████████████████████████████████████████▌   | 1948/2057 [09:43<00:18,  5.93item/s, Completed 1948/2057]

Found 80 matched controls for ENSG00000104824
Getting matched controls for ENSG00000185946
Found 74 matched controls for ENSG00000185946
Getting matched controls for ENSG00000164162

Processing conditions:  95%|█████████████████████████████████████████████████████████████▌   | 1950/2057 [09:43<00:14,  7.31item/s, Completed 1950/2057]

Found 29 matched controls for ENSG00000164162
Getting matched controls for ENSG00000120253
Found 29 matched controls for ENSG00000120253
Getting matched controls for ENSG00000241370

Processing conditions:  95%|█████████████████████████████████████████████████████████████▋   | 1953/2057 [09:43<00:12,  8.29item/s, Completed 1953/2057]

Found 60 matched controls for ENSG00000241370
Getting matched controls for ENSG00000008952
Found 5 matched controls for ENSG00000008952
Getting matched controls for ENSG00000128951
Found 49 matched controls for ENSG00000128951
Getting matched controls for ENSG00000144034

Processing conditions:  95%|█████████████████████████████████████████████████████████████▊   | 1955/2057 [09:43<00:13,  7.59item/s, Completed 1955/2057]

Found 40 matched controls for ENSG00000144034
Getting matched controls for ENSG00000183751
Found 75 matched controls for ENSG00000183751
Getting matched controls for ENSG00000146232

Processing conditions:  95%|█████████████████████████████████████████████████████████████▊   | 1956/2057 [09:44<00:13,  7.58item/s, Completed 1956/2057]

Found 51 matched controls for ENSG00000146232
Getting matched controls for ENSG00000146834

Processing conditions:  95%|█████████████████████████████████████████████████████████████▊   | 1958/2057 [09:44<00:16,  6.01item/s, Completed 1958/2057]

Found 127 matched controls for ENSG00000146834
Getting matched controls for ENSG00000186166
Found 79 matched controls for ENSG00000186166
Getting matched controls for ENSG00000175283

Processing conditions:  95%|█████████████████████████████████████████████████████████████▉   | 1960/2057 [09:44<00:18,  5.31item/s, Completed 1960/2057]

Found 146 matched controls for ENSG00000175283
Getting matched controls for ENSG00000129933
Found 66 matched controls for ENSG00000129933
Getting matched controls for ENSG00000163510

Processing conditions:  95%|█████████████████████████████████████████████████████████████▉   | 1962/2057 [09:45<00:16,  5.76item/s, Completed 1962/2057]

Found 34 matched controls for ENSG00000163510
Getting matched controls for ENSG00000105176
Found 82 matched controls for ENSG00000105176
Getting matched controls for ENSG00000121940

Processing conditions:  95%|██████████████████████████████████████████████████████████████   | 1964/2057 [09:45<00:14,  6.28item/s, Completed 1964/2057]

Found 47 matched controls for ENSG00000121940
Getting matched controls for ENSG00000132792
Found 69 matched controls for ENSG00000132792
Getting matched controls for ENSG00000119414

Processing conditions:  96%|██████████████████████████████████████████████████████████████   | 1965/2057 [09:45<00:16,  5.58item/s, Completed 1966/2057]

Found 114 matched controls for ENSG00000119414
Getting matched controls for ENSG00000087191
Found 17 matched controls for ENSG00000087191
Getting matched controls for ENSG00000181038

Processing conditions:  96%|██████████████████████████████████████████████████████████████▏  | 1968/2057 [09:46<00:15,  5.73item/s, Completed 1968/2057]

Found 114 matched controls for ENSG00000181038
Getting matched controls for ENSG00000160948
Found 59 matched controls for ENSG00000160948
Getting matched controls for ENSG00000196747

Processing conditions:  96%|██████████████████████████████████████████████████████████████▎  | 1970/2057 [09:46<00:13,  6.35item/s, Completed 1970/2057]

Found 56 matched controls for ENSG00000196747
Getting matched controls for ENSG00000143106
Found 25 matched controls for ENSG00000143106
Getting matched controls for ENSG00000145386

Processing conditions:  96%|██████████████████████████████████████████████████████████████▎  | 1971/2057 [09:46<00:13,  6.50item/s, Completed 1971/2057]

Found 24 matched controls for ENSG00000145386
Getting matched controls for ENSG00000064703

Processing conditions:  96%|██████████████████████████████████████████████████████████████▎  | 1973/2057 [09:47<00:13,  6.02item/s, Completed 1973/2057]

Found 114 matched controls for ENSG00000064703
Getting matched controls for ENSG00000204070
Found 59 matched controls for ENSG00000204070
Getting matched controls for ENSG00000106244

Processing conditions:  96%|██████████████████████████████████████████████████████████████▍  | 1975/2057 [09:47<00:12,  6.53item/s, Completed 1975/2057]

Found 50 matched controls for ENSG00000106244
Getting matched controls for ENSG00000166851
Found 60 matched controls for ENSG00000166851
Getting matched controls for ENSG00000137547

Processing conditions:  96%|██████████████████████████████████████████████████████████████▍  | 1977/2057 [09:47<00:11,  6.93item/s, Completed 1978/2057]

Found 46 matched controls for ENSG00000137547
Getting matched controls for ENSG00000111669
Found 40 matched controls for ENSG00000111669
Getting matched controls for ENSG00000070756
Found 19 matched controls for ENSG00000070756
Getting matched controls for ENSG00000125459

Processing conditions:  96%|██████████████████████████████████████████████████████████████▌  | 1980/2057 [09:48<00:10,  7.09item/s, Completed 1980/2057]

Found 100 matched controls for ENSG00000125459
Getting matched controls for ENSG00000069329
Found 43 matched controls for ENSG00000069329
Getting matched controls for ENSG00000089902

Processing conditions:  96%|██████████████████████████████████████████████████████████████▋  | 1982/2057 [09:48<00:10,  7.14item/s, Completed 1982/2057]

Found 35 matched controls for ENSG00000089902
Getting matched controls for ENSG00000241945
Found 51 matched controls for ENSG00000241945
Getting matched controls for ENSG00000063978

Processing conditions:  96%|██████████████████████████████████████████████████████████████▋  | 1984/2057 [09:48<00:09,  7.46item/s, Completed 1984/2057]

Found 32 matched controls for ENSG00000063978
Getting matched controls for ENSG00000167272
Found 56 matched controls for ENSG00000167272
Getting matched controls for ENSG00000165119

Processing conditions:  97%|██████████████████████████████████████████████████████████████▊  | 1986/2057 [09:48<00:08,  8.12item/s, Completed 1986/2057]

Found 25 matched controls for ENSG00000165119
Getting matched controls for ENSG00000168066
Found 47 matched controls for ENSG00000168066
Getting matched controls for ENSG00000165934

Processing conditions:  97%|██████████████████████████████████████████████████████████████▊  | 1988/2057 [09:49<00:08,  8.21item/s, Completed 1988/2057]

Found 20 matched controls for ENSG00000165934
Getting matched controls for ENSG00000088930
Found 66 matched controls for ENSG00000088930
Getting matched controls for ENSG00000168802

Processing conditions:  97%|██████████████████████████████████████████████████████████████▊  | 1989/2057 [09:49<00:08,  8.17item/s, Completed 1989/2057]

Found 45 matched controls for ENSG00000168802
Getting matched controls for ENSG00000132773

Processing conditions:  97%|██████████████████████████████████████████████████████████████▉  | 1991/2057 [09:49<00:10,  6.08item/s, Completed 1991/2057]

Found 146 matched controls for ENSG00000132773
Getting matched controls for ENSG00000186103
Found 84 matched controls for ENSG00000186103
Getting matched controls for ENSG00000197302

Processing conditions:  97%|██████████████████████████████████████████████████████████████▉  | 1993/2057 [09:49<00:09,  6.51item/s, Completed 1993/2057]

Found 73 matched controls for ENSG00000197302
Getting matched controls for ENSG00000176386
Found 45 matched controls for ENSG00000176386
Getting matched controls for ENSG00000104517

Processing conditions:  97%|███████████████████████████████████████████████████████████████  | 1995/2057 [09:50<00:08,  7.24item/s, Completed 1995/2057]

Found 46 matched controls for ENSG00000104517
Getting matched controls for ENSG00000137822
Found 42 matched controls for ENSG00000137822
Getting matched controls for ENSG00000241186

Processing conditions:  97%|███████████████████████████████████████████████████████████████▏ | 1998/2057 [09:50<00:07,  7.54item/s, Completed 1998/2057]

Found 106 matched controls for ENSG00000241186
Getting matched controls for ENSG00000181163
Found 27 matched controls for ENSG00000181163
Getting matched controls for ENSG00000175376
Found 33 matched controls for ENSG00000175376
Getting matched controls for ENSG00000090861

Processing conditions:  97%|███████████████████████████████████████████████████████████████▏ | 2001/2057 [09:50<00:06,  9.14item/s, Completed 2001/2057]

Found 40 matched controls for ENSG00000090861
Getting matched controls for ENSG00000114127
Found 10 matched controls for ENSG00000114127
Getting matched controls for ENSG00000105618
Found 27 matched controls for ENSG00000105618
Getting matched controls for ENSG00000134265

Processing conditions:  97%|███████████████████████████████████████████████████████████████▎ | 2003/2057 [09:51<00:06,  7.82item/s, Completed 2003/2057]

Found 62 matched controls for ENSG00000134265
Getting matched controls for ENSG00000130811
Found 67 matched controls for ENSG00000130811
Getting matched controls for ENSG00000163982

Processing conditions:  97%|███████████████████████████████████████████████████████████████▎ | 2005/2057 [09:51<00:07,  6.67item/s, Completed 2005/2057]

Found 105 matched controls for ENSG00000163982
Getting matched controls for ENSG00000165916
Found 41 matched controls for ENSG00000165916
Getting matched controls for ENSG00000130517

Processing conditions:  98%|███████████████████████████████████████████████████████████████▍ | 2007/2057 [09:51<00:07,  6.85item/s, Completed 2007/2057]

Found 52 matched controls for ENSG00000130517
Getting matched controls for ENSG00000196305
Found 58 matched controls for ENSG00000196305
Getting matched controls for ENSG00000109270

Processing conditions:  98%|███████████████████████████████████████████████████████████████▍ | 2009/2057 [09:52<00:07,  6.83item/s, Completed 2009/2057]

Found 40 matched controls for ENSG00000109270
Getting matched controls for ENSG00000205339
Found 75 matched controls for ENSG00000205339
Getting matched controls for ENSG00000198836

Processing conditions:  98%|███████████████████████████████████████████████████████████████▌ | 2011/2057 [09:52<00:06,  6.84item/s, Completed 2011/2057]

Found 60 matched controls for ENSG00000198836
Getting matched controls for ENSG00000213380
Found 47 matched controls for ENSG00000213380
Getting matched controls for ENSG00000072506

Processing conditions:  98%|███████████████████████████████████████████████████████████████▌ | 2013/2057 [09:52<00:05,  8.13item/s, Completed 2013/2057]

Found 26 matched controls for ENSG00000072506
Getting matched controls for ENSG00000146223
Found 30 matched controls for ENSG00000146223
Getting matched controls for ENSG00000163877

Processing conditions:  98%|███████████████████████████████████████████████████████████████▋ | 2014/2057 [09:52<00:05,  8.14item/s, Completed 2014/2057]

Found 45 matched controls for ENSG00000163877
Getting matched controls for ENSG00000124217

Processing conditions:  98%|███████████████████████████████████████████████████████████████▋ | 2017/2057 [09:53<00:05,  7.69item/s, Completed 2017/2057]

Found 118 matched controls for ENSG00000124217
Getting matched controls for ENSG00000031698
Found 28 matched controls for ENSG00000031698
Getting matched controls for ENSG00000182473
Found 32 matched controls for ENSG00000182473
Getting matched controls for ENSG00000178741

Processing conditions:  98%|███████████████████████████████████████████████████████████████▊ | 2019/2057 [09:53<00:05,  7.26item/s, Completed 2019/2057]

Found 85 matched controls for ENSG00000178741
Getting matched controls for ENSG00000147874
Found 33 matched controls for ENSG00000147874
Getting matched controls for ENSG00000101421

Processing conditions:  98%|███████████████████████████████████████████████████████████████▊ | 2021/2057 [09:53<00:05,  7.18item/s, Completed 2022/2057]

Found 71 matched controls for ENSG00000101421
Getting matched controls for ENSG00000149806
Found 48 matched controls for ENSG00000149806
Getting matched controls for ENSG00000108849
Found 10 matched controls for ENSG00000108849
Getting matched controls for ENSG00000147601

Processing conditions:  98%|███████████████████████████████████████████████████████████████▉ | 2025/2057 [09:54<00:03,  8.86item/s, Completed 2025/2057]

Found 83 matched controls for ENSG00000147601
Getting matched controls for ENSG00000115233
Found 10 matched controls for ENSG00000115233
Getting matched controls for ENSG00000137168
Found 24 matched controls for ENSG00000137168
Getting matched controls for ENSG00000167670

Processing conditions:  98%|████████████████████████████████████████████████████████████████ | 2026/2057 [09:54<00:03,  8.87item/s, Completed 2027/2057]

Found 38 matched controls for ENSG00000167670
Getting matched controls for ENSG00000125743
Found 19 matched controls for ENSG00000125743
Getting matched controls for ENSG00000142751

Processing conditions:  99%|████████████████████████████████████████████████████████████████ | 2029/2057 [09:54<00:03,  8.48item/s, Completed 2029/2057]

Found 44 matched controls for ENSG00000142751
Getting matched controls for ENSG00000168286
Found 63 matched controls for ENSG00000168286
Getting matched controls for ENSG00000117408

Processing conditions:  99%|████████████████████████████████████████████████████████████████▏| 2032/2057 [09:54<00:02,  8.97item/s, Completed 2032/2057]

Found 51 matched controls for ENSG00000117408
Getting matched controls for ENSG00000141385
Found 15 matched controls for ENSG00000141385
Getting matched controls for ENSG00000138073
Found 40 matched controls for ENSG00000138073
Getting matched controls for ENSG00000128513

Processing conditions:  99%|████████████████████████████████████████████████████████████████▎| 2034/2057 [09:55<00:02,  9.20item/s, Completed 2034/2057]

Found 5 matched controls for ENSG00000128513
Getting matched controls for ENSG00000105298
Found 60 matched controls for ENSG00000105298
Getting matched controls for ENSG00000130312

Processing conditions:  99%|████████████████████████████████████████████████████████████████▎| 2036/2057 [09:55<00:02,  9.90item/s, Completed 2037/2057]

Found 27 matched controls for ENSG00000130312
Getting matched controls for ENSG00000131462
Found 13 matched controls for ENSG00000131462
Getting matched controls for ENSG00000092871
Found 7 matched controls for ENSG00000092871
Getting matched controls for ENSG00000115761

Processing conditions:  99%|████████████████████████████████████████████████████████████████▍| 2039/2057 [09:55<00:02,  8.09item/s, Completed 2039/2057]

Found 25 matched controls for ENSG00000115761
Getting matched controls for ENSG00000140740
Found 68 matched controls for ENSG00000140740
Getting matched controls for ENSG00000126067

Processing conditions:  99%|████████████████████████████████████████████████████████████████▌| 2042/2057 [09:56<00:01,  9.16item/s, Completed 2042/2057]

Found 53 matched controls for ENSG00000126067
Getting matched controls for ENSG00000119335
Found 17 matched controls for ENSG00000119335
Getting matched controls for ENSG00000155249
Found 19 matched controls for ENSG00000155249
Getting matched controls for ENSG00000165733

Processing conditions:  99%|████████████████████████████████████████████████████████████████▌| 2044/2057 [09:56<00:01,  9.33item/s, Completed 2045/2057]

Found 28 matched controls for ENSG00000165733
Getting matched controls for ENSG00000106245
Found 37 matched controls for ENSG00000106245
Getting matched controls for ENSG00000005175
Found 18 matched controls for ENSG00000005175
Getting matched controls for ENSG00000134058

Processing conditions:  99%|████████████████████████████████████████████████████████████████▋| 2046/2057 [09:56<00:01, 10.11item/s, Completed 2047/2057]

Found 18 matched controls for ENSG00000134058
Getting matched controls for ENSG00000274611
Found 32 matched controls for ENSG00000274611
Getting matched controls for ENSG00000124562

Processing conditions: 100%|████████████████████████████████████████████████████████████████▋| 2049/2057 [09:56<00:00,  8.83item/s, Completed 2049/2057]

Found 34 matched controls for ENSG00000124562
Getting matched controls for ENSG00000140988
Found 53 matched controls for ENSG00000140988
Getting matched controls for ENSG00000003509

Processing conditions: 100%|████████████████████████████████████████████████████████████████▊| 2051/2057 [09:57<00:00,  8.95item/s, Completed 2051/2057]

Found 18 matched controls for ENSG00000003509
Getting matched controls for ENSG00000167513
Found 28 matched controls for ENSG00000167513
Getting matched controls for ENSG00000234545

Processing conditions: 100%|████████████████████████████████████████████████████████████████▉| 2054/2057 [09:57<00:00,  9.76item/s, Completed 2054/2057]

Found 25 matched controls for ENSG00000234545
Getting matched controls for ENSG00000148303
Found 10 matched controls for ENSG00000148303
Getting matched controls for ENSG00000113569
Found 7 matched controls for ENSG00000113569
Getting matched controls for ENSG00000160752

Processing conditions: 100%|█████████████████████████████████████████████████████████████████| 2057/2057 [09:57<00:00,  3.44item/s, Completed 2057/2057]

Found 10 matched controls for ENSG00000160752
Getting matched controls for ENSG00000086589
Found 5 matched controls for ENSG00000086589
Getting matched controls for ENSG00000148606
Found 6 matched controls for ENSG00000148606
Saving new control cells ids to json

## Load Comparison Data

In [7]:
adata_filtered_v1.shape

(310385, 8563)

In [13]:
v1_filtered_data_path = '/home/mgill/.cz-benchmarks/datasets/replogle_k562_essential_perturbpredict_de_results_control_cells_v1.h5ad'
adata_filtered_v1 = sc.read_h5ad(v1_filtered_data_path, backed=None)

control_cells_ids_v1 = adata_filtered_v1.uns['control_cells_ids']
control_cells_ids_v1.pop('non-targeting', None)

del adata_filtered_v1

In [ ]:
# with open("/data2/czbenchmarks/control_cells_ids_replogle_k562_essential_perturbpredict.json", "r") as f:
#     control_cells_ids_new = json.load(f) # filtered data

# with open("/data2/czbenchmarks/control_cells_ids_replogle_k562_essential_perturbpredict_validate.json", "r") as f:
#     control_cells_ids_validate = json.load(f) # cr4 data

## QC of Conditions

In [17]:
len(control_cells_ids_v1.keys()), len(control_cells_ids.keys())

(2057, 2057)

In [18]:
set(control_cells_ids_v1.keys()) == set(control_cells_ids.keys())

True

## QC of Matches

In [21]:
conditions = list(control_cells_ids.keys())

for condition in conditions:
    print(condition, len(control_cells_ids_v1[condition]), len(control_cells_ids[condition]))
    assert len(control_cells_ids_v1[condition]) == len(control_cells_ids[condition])
    matches = 0
    for pos, (val1, val2) in enumerate(zip(control_cells_ids_v1[condition], control_cells_ids[condition].values())):
        print(val1, val2)
        if val1 == val2:
            matches += 1
        if pos == 10:
            break
    # print(f"     matches {matches}, differences {len(control_cells_ids_v1[condition]) - matches}")

ENSG00000145414 94 94
GGGACCTGTGATACCT-15 GAGGGATTCGTGGACC-27
AGTGCCGGTCATGACT-17 AGTGCCGGTCATGACT-17
AGGACGATCCTCGCAT-17 TGCGGCAAGACAACTA-47
GCATGATTCACGATCA-45 AAATGGACAGAGTAAT-10
CAATCGATCGACATAC-45 CAACCTCAGGCACTAG-34
ATCACGAAGAGGACTC-45 TCACACCGTCCCACGA-13
TCGCTCATCGTTAGTG-33 GAGACCCTCCTAGAGT-40
AACCACAGTGCCGGTT-33 GTTGAACCAACAACAA-22
CTGGTCTGTGTGATGG-33 AGACACTAGCATTGAA-37
TTGAACGCAATTCTCT-33 TCCTCGAGTATTCCGA-9
TTACAGGTCCATTGTT-39 CGTGTCTAGAGTTCGG-13
ENSG00000169679 648 648
TCTGCCAGTTCAGCGC-15 CTTTCGGGTCTACGAT-31
AGCCAGCAGGATGAGA-15 CTGCATCGTTGTAGCT-10
CATGCTCCACCAAATC-15 CAACCAAAGGGTACAC-7
GTCTCACAGAGCCATG-15 GATCCCTTCCGGCTTT-33
AGACTCAGTGAGGATC-15 GTGGGAATCATGCCAA-36
TTTACCATCAACGTGT-15 CTGATCCCAACGTAAA-46
GCAGTTAAGGTTGGAC-15 AGCCAATCATAGACTC-8
CAAGACTTCTAGGAAA-15 GTAACCAGTCAAACGG-44
GGCACGTTCTCCAAGA-15 TCCCATGGTACGACTT-3
CCGGGTAGTTCGCGTG-15 TTGCGTCAGACAAGCC-33
GTCACTCGTGGCCACT-15 TGACAGTAGACGGAAA-29
ENSG00000198258 232 232
GGCACGTTCTCCAAGA-15 GGAGGTATCGGTCGGT-34
CACGGGTCATTCAGGT-15 CCACAAAGTGAACGGT-42
ATCGGCGAGTCGCTAT-15 AGTTCGAAGTTCCGTA-25
GAACACTAGGTTGAGC-15 TAGGAGGAGTATGAAC-35
GTGGAGAAGTTCCTGA-17 TGTCCTGAGCGATCGA-33
AGCGATTCAGTTCCAA-17 CTCCATGCAATCTCTT-5
TTTGTTGGTACCGGCT-17 TTCAGGACATCGATCA-6
TTCCTTCCATCTAGAC-17 GAACTGTAGTGAGTTA-24
TGTCCCAGTCACCGAC-17 GTCTCACCATCCAATG-5
CGAAGGAGTCCTTGTC-17 TGAGCATAGCTCCGAC-12
CGACAGCGTGCGAACA-17 TGTCAGACAGTAGAGC-40
ENSG00000171159 212 212
GAAGCGATCGGCGATC-15 GAACACTTCTGCATGA-43
CCACTTGCAACGTAAA-17 CCATAAGCAAATCCCA-23
CCCTCAATCTTCCTAA-20 TCGTGCTGTTCGGCCA-6
CTGTACCCAGCACGAA-20 CTGCCTATCGAGCCTG-37
GGGCCATCATGACTCA-45 AGGGTGAAGCAACAGC-16
CAGCAGCCACCCTTGT-45 TCCTCGAGTGGCAACA-7
AAAGTCCCAAATGGAT-45 CAACAGTAGCTAATCC-11
CATCCGTAGAATTGTG-45 CATGCAAAGTCTGCGC-4
TAAGCGTTCCACACCT-45 GTAACACAGTAAGCAT-33
GTAACACAGTAAGCAT-33 TAGGTTGGTCTTAGTG-13
CTGCTCAGTAGCACAG-33 CCGAACGCAGAATTCC-41
ENSG00000100575 201 201
CGTCAAAAGTGTCATC-15 GATTGGTGTGTTTGCA-28
TTCCACGAGCGATGGT-15 GTGCTGGTCCGGACGT-41
CGACAGCGTGCGAACA-17 TAACGACGTGAGTAGC-34
TTAGGCATCTATACTC-17 AAAGGTATCCATTCAT-14
CTGGCAGCAGGCAATG-17 GCAGCTGTCTCACGAA-30
TCAGTCCTCTCGGGAC-17 GGAGCAACAGTTAGGG-22
TTCTAGTAGTAGATCA-20 ATGCATGAGATCGACG-47
ACTTTGTCATAAGCAA-20 GGATCTATCTACGGGC-22
ATCCATTGTATGGTAA-20 GTTACCCAGCCTCATA-5
TTCATGTAGGGAGTTC-33 AGAGAGCAGGTTTGAA-40
GAGGCCTAGAGGGCGA-33 AGGGTTTGTAACCCGC-41
ENSG00000198952 83 83
TCTTTGAGTTCAGGTT-15 CGACAGCCATGCAGGA-10
TCAAGTGCAATAACCC-17 TTAGGGTTCAAGTCGT-46
GCCATGGTCTGCCTCA-17 AGGATCTTCACTACGA-2
GCCGATGAGTCGAGGT-17 GTGCGTGTCGCCCAGA-26
TATCTGTAGAGCTTTC-20 CAAGGGATCAGAGTGG-10
TGATCTTGTGTATACC-45 CATTGCCGTAACCCTA-29
CGAGGAAAGGGAACAA-45 TGATCTTGTGTATACC-45
TGCAGATAGCATATGA-45 ATGAAAGAGAGGCCAT-12
TCTCAGCGTACAAAGT-39 GCTCAAATCCAGTACA-24
TCCGATCCAGGGCTTC-39 TTACAGGTCTGCTAGA-12
GCCAGCAGTACTGAGG-13 AGTCACAGTTGCAACT-10
ENSG00000143373 205 205
GCCATGGTCGGTCTAA-15 TCGGATAAGCTAAACA-19
CTCCCAAAGATTGATG-15 TGATTTCTCACGGAGA-43
AATGGCTCAACTCGTA-15 CTCCCTCTCAAGCGTT-10
CACACAAGTCGGAACA-17 GGAGAACCAACTCGTA-26
TGGATCATCTCACCCA-17 CTTCTAAGTACGGATG-39
ATGCATGCAATGGCCC-17 CCCTAACTCGCTAATG-41
ACTGTCCCAGGCTCTG-17 GACCGTGAGGACTAAT-41
AGCATCAGTATCGTAC-20 AGCATCAGTATCGTAC-20
GGCTTTCAGCAACCAG-20 AGGAGGTTCGTTCGCT-24
CCCTCAAAGAATAGTC-20 CCTATCGGTCGCATCG-48
CGCCAGATCGCCTTTG-20 TCAATCTAGTCGGGAT-33
ENSG00000141026 119 119
CCGGGTAGTTCGCGTG-15 CCTCTAGTCGCAACAT-34
TCATCATAGTTGTCGT-15 GTCGTTCAGTTGTCGT-46
TACCCACTCCGAACGC-15 CTCTCGACAGCTGTCG-3
GACGTTATCGTTTACT-15 GCATCGGCAGAAGCGT-9
ATGAGTCGTATGAGCG-15 CCAATGACATAGGCGA-8
TGTCCCAGTCACCGAC-17 ATGCATGGTGCTGTCG-7
ATGAGGGTCGGAGTAG-17 AGTCACACAAGCCCAC-7
TGCCGAGTCCACTTTA-17 TCGTGCTTCGTACCTC-19
CCTCAGTTCTACCTTA-20 GCGATCGGTGGCATCC-7
GGAATCTAGTGGACTG-45 GTCTGTCTCACTGAAC-6
CTGAGCGAGTCTGGTT-45 TGACAGTCAAATCAAG-2
ENSG00000100316 1996 1996
TGTTCTACATGTGCCG-15 CCTCTCCCAACACTAC-11
CGTCAAAAGTGTCATC-15 AGTAGCTTCACATTGG-36
CACGGGTCATTCAGGT-15 ATTCCATAGCACTCCG-23
CATTCATTCACCGCTT-15 ATCGTAGTCTCCTACG-16
ACGATCAGTCTTAGTG-15 GGTGTTATCACATCAG-40
GGAGATGAGTTCCAGT-15 TGATGGTAGATAGCAT-27
GAACACTAGGTTGAGC-15 TCATTGTCAGGAAGTC-10
CAAGACTTCTAGGAAA-15 TCGTAGACATATAGCC-43
CTACTATCAGGTATGG-15 CTGCTCATCATGGAGG-10
GCCATGGTCGGTCTAA-15 TAGGGTTTCATCTATC-22
AAATGGACAGTCAGAG-15 TTGATGGGTATGAAAC-13
ENSG00000179988 379 379
ACATGCATCTTCCACG-15 TCACGCTCATGGACAG-19
TCTGCCAGTTCAGCGC-15 TACCGGGTCCTCTCGA-25
TCATGAGGTGGCTGCT-15 GTTGCTCCAATCAAGA-32
CCATAAGAGGGCAGGA-15 ACCACAATCTCATTAC-31
GAACACTAGAGTATAC-17 TTTACGTAGCTAATCC-6
TATCTTGGTCTGTCCT-17 AGATGAAGTAATACCC-32
GTAGCTAGTGTATCCA-20 AACCTGACACAACCGC-7
CATGCGGGTCAATCTG-20 TTAGGCACAAGGTCAG-40
CAGTTAGCATATGCGT-20 ATCCATTGTTCGTTCC-10
TCAAGCAAGTCCCGAC-20 GGCTTGGCATCGAAGG-8
AGCATCAGTATCGTAC-20 GCCCGAACACGACGTC-27
ENSG00000112130 176 176
GCAACCGGTTGAGGAC-15 TTAGGGTCATCAGCGC-32
TGTTCATCATCTCGTC-15 ATACTTCTCGATCCAA-48
GATGATCCAAGGAGTC-15 GTCTAGAGTCTCTCCA-25
GTTTACTCAGCAGTTT-17 GACCGTGTCTCAACGA-25
TTTGTTGGTACCGGCT-17 TGTAGACCAGCTAACT-46
TAAGCACCAACGACAG-17 TTGGGCGCAGCGACCT-20
TAGATCGTCACACGAT-17 ATACCTTCAGGACGAT-10
TTGGGCGCAGCGACCT-20 CGGGCATCAGCTGCCA-5
AGTCTCCCACGGTGTC-20 GCGAGAATCGCCAATA-7
GTGGAGAGTGCGGATA-20 TGGATCATCACTCGAA-28
CCTGTTGGTGTCCCTT-20 CTTCCGAGTGTTATCG-16
ENSG00000125686 254 254
GAAATGAAGGTAAGGA-15 AAGACAATCCATCAGA-11
GAAGCGATCGGCGATC-15 GAAATGAAGGTAAGGA-15
CCTTGTGCACTTCAGA-15 AGCGTCGAGAGGCTGT-12
GCAACCGGTTGAGGAC-15 GGTAACTGTACAGTCT-11
ATGAGGGTCGGAGTAG-17 CATAGACTCTCCATAT-12
GGAGGTAGTTAGAAGT-17 TCGGGACTCATTCACT-26
CCTCAGTTCTACCTTA-20 TAAGTCGGTCAGCGTC-37
ATAGAGATCGTCGCTT-20 ACTTAGGCATACCACA-45
ACTTAGGCATACCACA-45 TGGGCGTTCGGTAAGG-25
GGAATCTAGTGGACTG-45 TGTCAGACAGTAGAGC-40
ATTACCTAGTAAGCAT-45 TAAGTCGCACGTACAT-9
ENSG00000169045 160 160
GAGATGGGTCGCAGTC-15 CGGTCAGTCTTACCAT-31
ATTACCTGTATGGTAA-15 TCCACCAAGTAAGAGG-44
TACCCACTCCGAACGC-15 CAATTTCAGTGGCAGT-16
CTTCGGTTCTCAGAAC-15 ATGGATCAGCCTATCA-8
TCATGAGGTGGCTGCT-15 GAGATGGGTCGCAGTC-15
GCCCAGATCCTTCTAA-15 TTACAGGAGTCGCCCA-22
AGAGCAGTCAGAGCAG-15 GGAAGTGTCTAACGGT-43
AGTGCCGGTCATGACT-17 TAACACGAGCTTCGTA-14
TGAGTCAAGGAACATT-17 TATCTGTAGAGGTTTA-39
GAGTCATAGCTGAAGC-20 CACACAATCTCGTCGT-32
CTTGAGATCTTGAACG-45 TTTACGTTCCTGGCTT-7
ENSG00000198755 257 257
GAGATGGGTGCTGCAC-15 CTGTCGTCAATCTCTT-24
CGCAGGTCACCAGCCA-15 AACGTCACAGCCTACG-25
ATGGGAGCATACCACA-15 ATAGGCTAGGGCAGAG-33
CCTTTGGAGGACCCAA-17 GAAGAATAGGTAACTA-7
CGACAGCGTGCGAACA-17 AGGCCACAGGGTAGCT-6
GCATGATAGGGTAATT-17 TCCACCAGTAGACAGC-28
GCTGAATTCTCATGCC-17 GCACTAATCAGCTTGA-35
TGGATCATCTCACCCA-17 CCCTAACAGGTAGCAC-4
TGTCCCAGTCACCGAC-17 TGCATGAGTTGATGTC-9
ATGAGGGTCGGAGTAG-17 TCGATTTAGGGCCAAT-39
GTCTAGAAGGTTCCGC-17 TCCGATCCAGGGCTTC-39
ENSG00000121073 70 70
GTGGAAGCACAGACGA-17 GTGTAACCAATGGGTG-34
ATCGATGGTTTACCAG-20 AGGCATTCAACCGATT-21
AGCCACGGTACCGCGT-45 CGTGTCTAGCCACTCG-33
CAGCAGCCACCCTTGT-45 TGACGCGTCAAGGAGC-17
TTTACGTAGTAAATGC-45 AAAGGATCACTCTCGT-38
CGTGTCTAGCCACTCG-33 CTGTGAATCCCTGGTT-29
TATTGGGGTATGTCAC-33 GAGTTGTAGCAGGCTA-7
CTGAATGCAGCTATAC-13 AGCCACGGTACCGCGT-45
GTGGAGACAAAGACGC-44 TAACCAGGTTCGCGTG-19
TTGCATTGTTAGCTAC-36 GCAGCTGTCTCACGAA-30
GGTGAAGAGGGACAGG-36 GATTCTTAGAGGACTC-14
ENSG00000189308 306 306
TGCTGAAAGTGTTGAA-15 ATGATCGCAACAAGAT-42
AATGGCTCAACTCGTA-15 GTAATGCTCTATGCCC-14
CTGAGGCTCAAGGAGC-15 CTGTGAATCCCTGGTT-29
AAATGGACAGTCAGAG-15 AGACCATCATGAGTAA-1
ATGCCTCTCAGAACCT-17 ACCACAATCTCATTAC-31
ACTGATGTCGTTTACT-20 ACTATTCTCGAGCCAC-39
AATGACCCACGTAGAG-20 AACTTCTAGGTTGAGC-41
AGTGATCGTTCCATTT-20 ATACCTTCAAAGACTA-25
GTATTGGAGGAACGCT-45 CTGCAGGAGGCACTAG-7
AGGTTACTCTCATTGT-45 ACTTTCACAATCGCGC-48
TGGAGAGCAGCGTAGA-45 GCAGCCAGTGCGGATA-5
ENSG00000173674 134 134
TTCGGTCAGCCTCAAT-15 TGCACGGGTGGAACAC-40
GATGACTAGGTGGGTT-15 GGCTTTCAGTAGCTCT-35
TTGCATTCACAGTCCG-15 TTCGCTGGTGAATGTA-38
TTTGTTGGTACCGGCT-17 GTCGTAATCCTGGTCT-8
GATTTCTCAATTGCTG-17 TTTGTTGGTACCGGCT-17
GAACACTAGAGTATAC-17 CGTGATATCGCGGACT-47
TACAGGTCATGTTTGG-17 CTTCTCTAGCAGGCTA-32
CAACAGTCAAACTCGT-17 CTAACTTAGTCTCTGA-9
CCCGAAGGTAGTGATA-20 AACCTTTCAATACGAA-48
CTTCCGATCCACAAGT-20 GCAGGCTTCGAAGCAG-21
CAACGGCGTCTGTGGC-20 TTCGGTCAGAAGCCTG-18
ENSG00000185385 108 108
ACGTACACATAGAGGC-15 GGTGTTATCACATCAG-40
GAGATGGGTCGCAGTC-15 AGCGCTGCACAAATGA-27
AATGGAACACTTTATC-17 GGCTTGGCATCGAAGG-8
AAGACAACAAGGGCAT-17 TTCTAACTCAGCAATC-21
ACCTGAAAGCTACAAA-17 TGACAGTAGGCACAAC-18
GCCAGGTGTACAAGCG-20 AAAGGTACACAACCGC-9
ATCGATGGTTTACCAG-20 GATCGTACACCTCTGT-7
TCAAGACAGCCTTTCC-20 AGCTTCCGTTTGGGTT-27
CTTCCGACAGCGACCT-20 GAATAGAGTGATGGCA-31
TTGCATTAGTTGGGAC-20 GCCAGGTGTACAAGCG-20
ATATCCTTCGTGCACG-45 GTCACGGTCTACAGGT-28
ENSG00000110713 510 510
ATCACAGTCCTACCGT-15 TCTCCGATCAGCGGAA-44
GAGAGGTTCTTCTGTA-15 AGGAGGTTCCCTCAAC-10
GACTATGGTGTGTCGC-15 TCATGCCGTATGTCAC-22
CGCATAATCTACACAG-15 CGAAGGACACCAACAT-45
GAAATGAGTCTTCGAA-15 TGAGGGAGTTTGATCG-17
GATGACTAGGTGGGTT-15 TCATTCAGTCAGACTT-41
AAACGAAAGTAATTGG-15 GGGATCCCAAGATCCT-6
TAGGAGGGTTCTCGTC-15 CATGCCTGTTCAATCG-19
TTTACCATCAACGTGT-15 GTAAGTCAGCATTTCG-36
CATGCTCCACCAAATC-15 CCCTAACAGGCTTAAA-47
GTCGTTCGTCGGTGTC-15 CCACCATTCGTTCCTG-19
ENSG00000104147 137 137
AAACGAAAGTAATTGG-15 AACCATGAGTCTGCAT-38
AGCTACAGTACTAACC-15 ATCTTCATCCTCTAAT-46
CATGCTCCACCAAATC-15 CTGAATGCAGCTATAC-13
CAAGAGGTCAAACGTC-15 AACAAAGAGGGCAATC-48
TAGATCGGTTGACTAC-17 ACAGCCGTCTCGGCTT-2
GTCTAGATCGTGCAGC-20 AATGGAAGTGTGATGG-38
TATCGCCTCGCGGTAC-20 CTGCAGGCACAGGATG-47
TGGAGAGCAGCGTAGA-45 GCAGCTGCAGACAAGC-10
ATTACCTCACGGTGCT-45 TCAATTCAGGATATAC-24
ACGGTCGTCAAGCTTG-45 TACACCCCACAAATCC-6
TGGATCAAGGGTAATT-33 TCTCACGAGCAACCAG-4
ENSG00000110200 424 424
ATGGAGGAGTCGAAGC-15 ACTATGGGTTACACAC-10
TCCGGGACACTAAACC-15 CTGTGAATCACATACG-34
CTGGACGTCTCGTTTA-15 GCCCAGAAGAGGTTTA-37
ACATGCATCTTCCACG-15 AATGGCTCACTGCACG-33
GTCACTCCAGAAACCG-15 TGGTTAGAGATGCCGA-29
GTCCACTCAGTTCCAA-15 TGGGAAGGTTATGTCG-38
CACGGGTCATTCAGGT-15 CATGGTACAGAGCTAG-46
TGCTGAAAGTGTTGAA-15 CTGAATGTCATCACCC-30
AAAGAACGTGTTTGCA-17 TAAGCACCAACGATCT-2
CCTTTGGAGGACCCAA-17 AGTAACCAGATTGAGT-12
ACTGTCCCAGGCTCTG-17 AAATGGAAGACATGCG-41
ENSG00000171848 577 577
TGTTCATCATCTCGTC-15 TTGGGCGTCCACTGAA-34
GATGATCCAAGGAGTC-15 TGTTGAGCAGGAACCA-48
ATGGGAGCATACCACA-15 CTGAATGGTACGTGAG-24
TAGGAGGGTTCTCGTC-15 GGAATCTGTCACTACA-31
AGTGTTGAGTCGTCTA-15 GGTAGAGGTTCCTAAG-1
TGAGGAGGTTTATGCG-15 GAATCGTAGGAGGGTG-12
GACGTTATCGTTTACT-15 CACTTCGGTCTTGGTA-14
GCAGGCTGTCTTGTCC-15 CCTGTTGAGCTGACCC-23
TTCGGTCTCGTAACTG-17 ATATCCTTCGTGTTCC-10
AGCGATTTCCCTCAAC-17 GTAGGAGCAGGGCTTC-44
GCCGATGAGTCGAGGT-17 AGGGTCCTCATCCTGC-13
ENSG00000156239 138 138
GACCAATAGTCGAATA-15 CTCTCAGAGTATTAGG-12
CTTGATTGTGGGATTG-15 TCAAGCATCAAGGACG-30
ACCAAACAGATTGAGT-15 AGACACTTCAACACCA-42
TAAGCACCAACGACAG-17 TGAATGCTCGCAAGAG-9
ATGCATGCAATGGCCC-17 CGGGCATCAGCTGCCA-5
AGTCTCCCACGGTGTC-20 TAAGCACCAACGACAG-17
TCCTCGATCGCCTCTA-20 TCTACCGGTTGCTCAA-11
TGCAGTAGTCTACAAC-45 ATGAGGGAGGTATCTC-34
TACCCACTCATGGCCG-45 GATGCTACACTGTTCC-43
TGCAGATAGCATATGA-45 TAATCTCTCCGGCAAC-36
TGCAGTAAGGAAGTAG-45 TGCAGTAGTCTACAAC-45
ENSG00000008988 273 273
AGCCAGCAGGATGAGA-15 CTTGATTGTGTATTGC-7
CTCTGGTTCCGTGGGT-15 CCTGTTGGTGTCCCTT-20
CTCCCAAAGATTGATG-15 CTCACTGAGACTCTTG-34
CCACTTGCAACGTAAA-17 CCCTGATGTACTAACC-1
GATTGGTTCGCTAGCG-17 TCTAACTCACAGAAGC-28
AACAACCGTACGTGAG-17 GTGAGCCAGTAAGGGA-42
CCTGTTGGTGTCCCTT-20 CGCAGGTAGTAATACG-7
ATAGAGATCGTCGCTT-20 TCACTCGGTCGCATTA-10
CAATACGGTACGCTTA-20 AATTTCCCAATTGTGC-16
TCGGGACCACCTTCCA-45 CGAAGTTTCTTCTGGC-31
ATATCCTTCGTGCACG-45 GGTGTCGTCGTCCTCA-5
ENSG00000146457 165 165
TGAGGAGGTTTATGCG-15 GGAATCTGTACCCACG-20
GTCACTCGTGGCCACT-15 TTTGTTGGTACCTGTA-6
AGGAATAAGGATATAC-17 TCATGCCGTGGCTGAA-3
AGTGCCGGTCATGACT-17 TCATCATTCAGCTTGA-47
GGAATCTGTACCCACG-20 AGACCCGAGCCGATCC-41
GTGATGTAGGTCATCT-20 AGAAATGCACACTTAG-42
AAACCCAAGTACCCTA-20 CATTGTTCAGCGTAGA-2
AGAAGCGGTCTCGGGT-20 CGAAGTTTCGAGAGAC-28
ATAGAGATCGTCGCTT-20 GTGATGTAGGTCATCT-20
CACTGGGCATAAGCGG-20 GTTACAGCACCGTCGA-30
TGTCCTGGTATAGCTC-45 TTCCACGAGGCCACTC-24
ENSG00000058729 174 174
ACGATCAGTCTTAGTG-15 AGCTTCCTCGGCTCTT-14
TGCTTCGTCTATTTCG-15 AAGAACATCGAGTCCG-45
GATCAGTAGGGTACAC-15 ACACAGTTCTCCAATT-39
GCGATCGTCTTAGTTC-15 TCGCTTGAGTTGGGAC-5
TGAGGAGGTTTATGCG-15 CTTTCGGCAGGCGATA-20
GTTAGTGAGCTAATCC-17 AAGCCATCAGATCCAT-3
CTTTCGGCAGGCGATA-20 GACTCAACAAGTTGGG-43
CATTCATCACACGTGC-20 GGGACTCAGGATGTTA-37
ATCGATGGTTTACCAG-20 ATACTTCGTAGGATAT-16
ATCCATTGTATGGTAA-20 CAATGACAGGTTCAGG-36
GTAGCTAGTGTATCCA-20 GTGGAAGAGCTGACAG-32
ENSG00000144021 255 255
TAGACTGTCTAAACGC-15 TAATCTCAGCGGGTAT-5
ACGATCAGTCTTAGTG-15 TGTAACGTCAAACGAA-4
GGATCTATCGACGAGA-15 TACAACGGTTAGGACG-19
GTCACTCCAGAAACCG-15 TGCATGAGTAACACGG-37
CCTTGTGCACTTCAGA-15 GAGTTGTCAGTGGTGA-40
ACTATGGAGCACTAGG-17 CTACAGACAGGGACTA-26
TTAGGCATCTATACTC-17 CGTGATATCTGTAACG-24
GTTTACTTCTGAATGC-17 GCAGCTGTCTCACGAA-30
GTAGGTTAGGTAGACC-17 AGTTAGCTCTACTATC-25
TCAAGCATCATGCCGG-17 AACAGGGCAGGTCAAG-27
AAACCCACAGTATACC-20 ATATCCTCACATAGCT-26
ENSG00000172336 218 218
AATGCCAGTCCACTCT-15 ACATCGATCTACCCAC-22
TGGTAGTCAAGCTCTA-15 TCAGTGAGTTAAACAG-14
GTGGCGTGTCGTCAGC-17 AATGCCAGTCCACTCT-15
AGTGCCGGTCATGACT-17 GGTGATTGTATTGAGA-8
AATGCCAGTGCGTCGT-17 GTGTCCTGTGGGTTGA-16
TACCCGTAGTGAATAC-17 CCCTTAGTCTGCGGAC-32
TCGTCCAGTTCTGAGT-20 GCGATCGTCGAGTTGT-24
GAGTCATAGCTGAAGC-20 AACAACCGTCAATGGG-37
TCAAGACAGCCTTTCC-20 GGTGGCTTCGGCCAAC-44
TGTGATGTCTGTCCGT-20 GTGGCGTGTCGTCAGC-17
TTCCTCTGTTCCGCAG-45 ATCACGAGTAACAAGT-43
ENSG00000104408 232 232
AGTGATCAGAGGGTCT-15 CCGTTCAGTGTCCTAA-21
GTCACGGGTGAGGCAT-15 GGTGATTCAACGACAG-30
TATGTTCCAAGTGGCA-15 ACACGCGAGCCTATCA-5
GCCATGGTCGGTCTAA-15 ACAACCAGTTCTGACA-3
AGAGCCCAGGTTGACG-17 GACTCAACACATGGTT-11
AGTGCCGGTGTAACGG-17 TCTTAGTGTGGACAGT-9
TGCTGAAGTTTCGTTT-17 GAGTGAGAGGGTTAGC-34
GATGAGGTCGGCTTGG-17 TCGGGTGTCGGTCTGG-22
AGGAATAAGGATATAC-17 TCCCACAAGAGGCGTT-2
TTACCGCTCGAGAACG-17 GTGCTGGAGATTGGGC-30
GCATCTCAGCTGGCTC-20 ATTCTTGCAAACTAAG-9
ENSG00000120333 92 92
AGAGCAGTCAGAGCAG-15 CAATGACGTGGTAACG-23
GTCGCGATCAGGAAGC-15 TGCGGCAAGACAACTA-47
GCAGGCTGTCTTGTCC-15 ATAGAGAGTCTACACA-12
GCTACCTCATCATCCC-15 ATGAGGGGTAGTATAG-25
GTCCACTGTGCCTGCA-17 ACACCAACAGCCGTCA-2
ATCGTGAAGTCATCGT-20 GTTTGGACAAGGAGTC-2
CAATACGAGTTGCGCC-45 ACCAAACCACAAATCC-44
AAGAACATCGAGTCCG-45 TCAGTGAAGAGTATAC-43
TGTTCCGTCTACGGTA-45 ATTCTTGTCGCGAAGA-25
CATCCACAGATGCGAC-33 TAGTGCAGTCGCTGCA-35
TAGTGCACACAGCGCT-33 AGAGCAGTCAGAGCAG-15
ENSG00000174527 124 124
CCTTGTGCATAGGTAA-15 GTAATGCCACAATGTC-14
GACTATGGTGTGTCGC-15 GCCTGTTCAAGTGACG-2
GCCCGAACAAGTGGAC-17 TATTCCAAGGTTAGTA-35
TCTCACGGTATGAGAT-17 AACCTGAAGAATCTAG-16
TTGGGCGCAGCGACCT-20 CCCATTGTCCCAGGAC-29
ATAGAGATCGTCGCTT-20 TACGGTAGTTGTTTGG-39
GTGGAGAGTGCGGATA-20 AACGGGATCACATACG-28
TCCTGCATCAGCAGAG-45 TAACACGGTATCGCGC-3
AATCGACGTGGTTTGT-45 ATCCATTCAAAGCTCT-37
TCTTCCTTCAGCGCGT-45 AGGAGGTAGTCACGAG-4
ACACCAAGTGTCATCA-33 ACACCAAGTGTCATCA-33
ENSG00000112651 147 147
AGTGTTGAGTCGTCTA-15 AAGGAATGTGCCTATA-10
TGGTAGTCAAGCTCTA-15 TGAGGGACAGTGCGCT-10
GGCAGTCGTCGTGGTC-17 AATGGCTGTCACGCTG-23
AATGGAACACTTTATC-17 CCCTGATGTACTAACC-1
CTTGAGAGTTTCGTAG-20 AGAAATGAGCATGTTC-33
TCAAGCAAGTCCCGAC-20 GAATCGTCAGAGTCAG-39
AGCATCAGTATCGTAC-20 GTGTAACGTGCATACT-27
GGTGATTCAAGCAGGT-45 ACGGAAGGTGTCTTAG-11
AGAAATGAGCATGTTC-33 CTCAATTAGGCATGGT-33
CTCAATTAGGCATGGT-33 AGTGTTGAGTCGTCTA-15
TCATTGTCAACGTTAC-33 GGGCTCAGTCGAATTC-42
ENSG00000133398 516 516
CGCCAGATCGTCGCTT-15 CGTGTCTCAGCTGTGC-18
TCTGCCAGTTCAGCGC-15 TAGGTACTCTTCTAAC-6
GCCATGGTCGGTCTAA-15 AACAAGAAGTGCACTT-30
TGGTAGTCAAGCTCTA-15 ACCCTTGAGGTTCCGC-33
GCAGGCTGTCTTGTCC-15 AGATCGTCATCCAATG-31
GTCGCGATCAGGAAGC-15 AGGTGTTCATATTCGG-28
GTCTCACAGAGCCATG-15 CCGGTAGCATCACGGC-12
GTCGTTCGTCGGTGTC-15 CTAACCCTCCCGATCT-42
AAATGGACAGTCAGAG-15 TGCGATACAGACACAG-7
TCGAACAAGGTTCACT-15 CTGGCAGCACTTTATC-29
TACCCACTCCGAACGC-15 CATGCCTCATTGAGGG-4
ENSG00000136527 222 222
ACGATCAGTCTTAGTG-15 AGCGATTCAGTTCCAA-17
TAGACTGTCTAAACGC-15 TGGGTTACAATCTCGA-18
TTGGGTAGTCTATGAC-15 CATGAGTGTAGAGACC-27
TGCTGAAAGTGTTGAA-15 GAAGGACAGGATGCGT-25
GACTGATGTATCGATC-15 AAGCGTTGTTGACGGA-39
AGCGATTCAGTTCCAA-17 GATGGAGAGTCTTCCC-17
GATGGAGAGTCTTCCC-17 CTTCTAAAGTATGGCG-38
TGAATCGCACATTGTG-17 ACGATCAGTCTTAGTG-15
TGATGCAGTCTAGATC-17 ATACCTTCAGGACGAT-10
CGTGATAAGCTAGATA-17 TTTCGATGTGTAGGAC-45
CTCCCAACACCGTGAC-17 TAGACTGTCTAAACGC-15
ENSG00000013275 242 242
GAAGCGATCGGCGATC-15 TGCGACGCATTCTCCG-32
TCATGAGGTGGCTGCT-15 CACATGAGTCCGAAGA-25
TTCCACGAGCGATGGT-15 GATTCGACATGAGATA-41
CGGACACCATCCTATT-15 CAGGGCTAGACCATTC-24
GGCAGTCGTCGTGGTC-17 GCTACAACAGGAGGTT-42
GTTAGACCAGCATTGT-17 GACATCAGTACATTGC-24
ATGCATGCAATGGCCC-17 TTCCTCTAGGTTCACT-44
GTCTAGAAGGTTCCGC-17 TCTACATAGAAGTCCG-39
CAACGGCCAATCGCGC-17 ATTACCTAGTAAGCAT-45
TGAGGGAGTTTGATCG-17 ATCCCTGGTGTGTCCG-41
ATGAGGGTCGGAGTAG-17 GTCACTCCATATACCG-18
ENSG00000183011 368 368
TGCTGAAAGTGTTGAA-15 ACCCAAACAGGCGTTC-1
GCACATAGTTAGGCTT-15 TACGGTACATAGAGGC-23
TACAACGAGTTACTCG-17 GTGGGAATCTGTTCAT-34
AACCTTTGTCATAACC-17 ATGAAAGGTATACCTG-9
AATAGAGTCCTAGCTC-17 TACAACGAGTTACTCG-17
GGGATCCTCTTGGTGA-17 TCATTACAGGAACTCG-43
ACAACCAGTACGATCT-17 CAGCAATTCTAGATCG-40
CAGCCAGCAAGTTTGC-17 CCTAACCGTCCCGCAA-35
TGCATCCCAAGCGAAC-17 TGTCCTGCATATGGCT-18
TTCAGGATCCTACGGG-20 GATTTCTTCCCTCTAG-35
GAAGTAATCGCTTTAT-20 CTGCATCGTTGTAGCT-10
ENSG00000167615 121 121
GCAGGCTGTCTTGTCC-15 ACCTGTCAGTTAACAG-32
GTCATGACAGCAATTC-15 GCCTGTTAGCCGAATG-23
TGCACGGAGATAGCAT-17 GTGAGCCCACTCCCTA-29
ACTGTCCCAGGCTCTG-17 GTAGTACTCAGTGTCA-16
AGCATCAGTATCGTAC-20 TGGCGTGCAAGCCTGC-44
ATCACGATCTGATGGT-20 TAGACTGCAAGAATGT-32
CCCGAAGGTAGTGATA-20 AACCTTTTCAGCACCG-24
AGTGCCGTCTATGCCC-45 CCTTGTGTCTTGGCTC-14
TGGGCGTCACTCTCGT-45 TTCAGGATCGTGTCAA-14
TGGCGTGTCATTGTGG-33 CTTCAATTCCCGAACG-1
GAGGGATGTAAGGCCA-33 TCCATCGAGGAGGCAG-40
ENSG00000140326 137 137
GCTACCTCATCATCCC-15 ACGGGTCCAGGCGATA-27
GTGGCGTGTCGAGCTC-15 GTTGAACCACGCTGAC-14
TAGGTACAGCGTCAGA-15 GCTACCTCATCATCCC-15
TACCGAATCAGCTGTA-15 ACAGCCGGTTCAAGGG-47
AGTGTTGCAATTAGGA-17 GGAGGATGTGCCTACG-46
AACCTTTGTCATAACC-17 TGCTGAAAGGACGCAT-8
TGATCAGCATCATCCC-17 AGTGTTGCAATTAGGA-17
TGTCCCAGTCACCGAC-17 GGATCTAGTTAGAGTA-28
GTGATGTAGGTCATCT-20 GTAATGCCACTAAACC-21
GTTCGCTGTCACGTGC-20 AATCGTGTCCAACTAG-44
AGGAATATCTGCCCTA-20 GTCACGGTCACCATAG-31
ENSG00000174996 127 127
GTGCTTCGTCGAAACG-17 TTACAGGAGCCTGTCG-45
GAACACTAGAGTATAC-17 CATTCATCAATTGAGA-3
GTGGCGTGTCGTCAGC-17 TATCTTGAGATTGGGC-16
TCAAGCAAGTCCCGAC-20 AGGGAGTGTATGAAAC-43
TATCTGTAGAGCTTTC-20 TGCTCGTAGACCTGGA-48
AACAAAGTCAAGATAG-20 TCCTCCCGTAATTGGA-18
TTACAGGAGCCTGTCG-45 AACCTGACACAACCGC-7
TCTGTCGTCCCAATAG-45 CGACAGCCATGCAGCC-41
ATTCAGGCACCCAAGC-45 CAGGCCATCTCACGAA-8
GCCTGTTCATCGGCCA-45 GTGCTTCGTCGAAACG-17
GAGGCCTTCATGCAGT-33 ATGAGGGGTAGTATAG-25
ENSG00000110172 259 259
AGTCAACGTTCTCGTC-15 CGGGACTAGGCACCAA-25
ACGGTCGCAAGAGCTG-15 GGGCTACAGCTAATCC-32
AACAACCAGTGCCGAA-15 CTCATGCAGCTGTCCG-28
GAGAGGTTCTTCTGTA-15 TCAATTCTCTACGCAA-3
GTCATCCGTGATTCTG-15 GTCCACTGTGCGACAA-12
GTTAGTGAGCTAATCC-17 GGATCTATCACCTTGC-6
GATGAGGAGGTCGTAG-17 CCACCATTCGTTCCTG-19
CCTATCGCATCTTCGC-17 GTCGTTCGTGTAACGG-9
ATGCCTCTCAGAACCT-17 ATTGGGTGTGGAGGTT-28
GCCGATGGTCTAACTG-20 AGGTGTTCATAATCGC-30
ATATCCTGTGAGCTCC-20 TCGAAGTGTACTTGTG-33
ENSG00000149923 171 171
TGAATGCGTGGTCTAT-15 GTAGTACTCAGTGTCA-16
ACATGCATCTTCCACG-15 AGTACCAAGTCATGCT-11
GATTGGTTCGCTAGCG-17 ACCCTCAGTCATAACC-26
GTCATCCAGCCAAGGT-17 TGTTCATCAGAGACTG-20
TGTTCATCAGAGACTG-20 TGCACGGAGGAAAGTG-26
ATCCATTGTATGGTAA-20 ACATGCAAGTACCGGA-48
CCTGTTGGTGTCCCTT-20 TCTCTGGCATCACGGC-6
GTCACTCGTTTCCCAC-45 AAGCGAGGTTGGCTAT-42
TTAGTCTAGAACTTCC-45 GGGTCTGAGTGGAAGA-18
CCCTCAAAGCCATCCG-33 GATTGGTTCGCTAGCG-17
TGTTCATGTCCTCAGG-33 TTTAGTCTCACCTTGC-34
ENSG00000099246 43 43
TGAGGGATCTGATGGT-15 TTGCGTCAGACATGCG-33
GCAGGCTGTCTTGTCC-15 GATTCTTTCAAACTGC-40
ATGAGGGTCGGAGTAG-17 TTCACCGGTAGTGCGA-29
TATCGCCGTGGATGAC-20 AGGGCCTAGACAGCTG-45
AGGGCCTAGACAGCTG-45 AGGGAGTAGCTTTGTG-14
TTGCGTCAGACATGCG-33 CTTCCTTGTATCACCA-8
TGTAAGCGTCCAACGC-33 GTGCTGGAGATTGGGC-30
TCTACATAGAAGTCCG-39 TACGGTATCGAAGCAG-26
AAGTTCGAGGAGAGGC-36 AAATGGACATTGACTG-29
TACGGTATCGAAGCAG-26 ACGATCAGTGAGGCAT-38
AACCATGTCTTCGCTG-2 TACCGAAGTTCTCCAC-4
ENSG00000130640 238 238
AAGATAGAGGTGCTGA-15 TGGCGTGAGCTTGTGT-26
GCTTGGGGTATAGGGC-15 TCAGGTAAGCCTAGGA-24
CCAATTTGTGATATAG-15 ATCCTATTCGAAGTGG-34
GAGAGGTTCTTCTGTA-15 TCGACGGCAGACCCGT-46
GCCAGGTGTGTGTACT-17 CCACCATAGACTGAGC-11
AGTGCCGGTCATGACT-17 GGTAATCAGATGTTCC-48
TTCTAGTAGTAGATCA-20 CGATCGGCATCCGTTC-32
AATTCCTTCGCTCTAC-20 CGTAAGTTCGTGGGAA-35
CCTCATGTCGGAGATG-45 AAGATAGAGGTGCTGA-15
TGAACGTGTGATAGTA-45 TATACCTCAATAGGGC-32
GGGTAGAGTAAGTTAG-45 ATCCGTCTCTTGGTCC-32
ENSG00000149100 246 246
AGAGCAGTCAGAGCAG-15 AACCACATCGTCGATA-22
ACGTACACATAGAGGC-15 ACGTAGTCACATGTTG-25
TTCCACGAGCGATGGT-15 TCTAACTCACAGAAGC-28

## Unused Cells

In [ ]:
control_cells_used = set()
for condition in conditions:
    control_cells_used = control_cells_used.union(set(control_cells_ids[condition].keys()))
    control_cells_used = control_cells_used.union(set(control_cells_ids[condition].values()))

In [ ]:
all_cells = set(adata_filtered.obs_names)

In [ ]:
len(all_cells), len(control_cells_used)

In [ ]:
control_cells_used.issubset(all_cells)

In [ ]:
unused_cell_ids = all_cells.difference(control_cells_used)

In [51]:
unused_cells = adata_filtered.obs.loc[list(unused_cell_ids)]

In [54]:
unused_cells.condition.astype(str).unique()

array(['non-targeting'], dtype=object)

In [52]:
unused_cells

,gem_group,condition_name,condition,transcript,gene_transcript,sgID_AB,mitopercent,UMI_count,z_gemgroup_UMI,core_scale_factor,core_adjusted_UMI_count
cell_barcode,,,,,,,,,,,
GGGAAGTCAGCAGTTT-41,41,non-targeting,non-targeting,non-targeting,11267_non-targeting_non-targeting_non-targeting,non-targeting_03441|non-targeting_00663,0.099225,10965.0,-0.421027,0.943084,11626.750977
CAGTTAGAGATCACCT-30,30,non-targeting,non-targeting,non-targeting,11176_non-targeting_non-targeting_non-targeting,non-targeting_02774|non-targeting_00697,0.099290,14090.0,0.204779,0.949840,14834.083984
CGAAGGAGTACGAGCA-36,36,non-targeting,non-targeting,non-targeting,10866_non-targeting_non-targeting_non-targeting,non-targeting_00678|non-targeting_02387,0.092739,18881.0,0.978741,1.011235,18671.232422
CTGCATCAGTTACGTC-26,26,non-targeting,non-targeting,non-targeting,11290_non-targeting_non-targeting_non-targeting,non-targeting_03530|non-targeting_01407,0.101344,9897.0,-0.664785,0.901381,10979.821289
CTTCTCTAGGGTTGCA-20,20,non-targeting,non-targeting,non-targeting,10841_non-targeting_non-targeting_non-targeting,non-targeting_00531|non-targeting_01795,0.083502,16838.0,0.557413,1.030337,16342.218750
...,...,...,...,...,...,...,...,...,...,...,...
AGTGTTGCAGCCCACA-14,14,non-targeting,non-targeting,non-targeting,11305_non-targeting_non-targeting_non-targeting,non-targeting_03624|non-targeting_03589,0.127325,14137.0,-0.129345,1.050055,13463.107422
CACAACATCTTCACGC-9,9,non-targeting,non-targeting,non-targeting,10759_non-targeting_non-targeting_non-targeting,non-targeting_00081|non-targeting_03672,0.048635,17107.0,0.507703,1.036454,16505.314453
TAATTCCCATTCACAG-11,11,non-targeting,non-targeting,non-targeting,11251_non-targeting_non-targeting_non-targeting,non-targeting_03290|non-targeting_03021,0.100437,17842.0,0.629333,1.050188,16989.341797
GAATAGAAGTGGCGAT-7,7,non-targeting,non-targeting,non-targeting,11047_non-targeting_non-targeting_non-targeting,non-targeting_01946|non-targeting_02652,0.095708,16519.0,0.462924,1.017086,16241.493164
CAACAACGTATGGAGC-29,29,non-targeting,non-targeting,non-targeting,11248_non-targeting_non-targeting_non-targeting,non-targeting_03258|non-targeting_01564,0.099640,9996.0,-0.498045,0.866216,11539.841797

## Prototype Algorithm

In [62]:
n_nonzero_genes = (adata_filtered.X > 0).sum(axis=1)
if not isinstance(n_nonzero_genes, np.ndarray):
    n_nonzero_genes = n_nonzero_genes.toarray()

adata_filtered.obs['n_nonzero_genes'] = n_nonzero_genes

In [67]:
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.neighbors import NearestNeighbors

In [66]:
condition_key = ['condition']
grouper_keys = ['gem_group']
control_condition = "non-targeting"
# adata_filtered.obs['n_nonzero_genes'] = (adata_filtered.X > 0).sum(axis=1).A1

control_mask = obs.condition == control_condition
for condition, obs in adata_filtered.obs.groupby(grouper_keys, observed=True):
    
    control_cells = obs.loc[control_mask]
    condition_cells = obs.loc[~control_mask]
    print(condition, gem_group, obs.shape)
    
    break

ENSG00000001497 1 (4, 12)

In [69]:
condition_cells.head()

,gem_group,condition_name,condition,transcript,gene_transcript,sgID_AB,mitopercent,UMI_count,z_gemgroup_UMI,core_scale_factor,core_adjusted_UMI_count,n_nonzero_genes
cell_barcode,,,,,,,,,,,,
AGGCCACGTGGCGCTT-1,1,LAS1L,ENSG00000001497,P1P2,4523_LAS1L_P1P2_ENSG00000001497,LAS1L_+_64754550.23-P1P2|LAS1L_+_64754657.23-P1P2,0.093168,11753.0,0.165097,0.801973,14655.102539,3551
CGGTCAGTCATGGCCG-1,1,LAS1L,ENSG00000001497,P1P2,4523_LAS1L_P1P2_ENSG00000001497,LAS1L_+_64754550.23-P1P2|LAS1L_+_64754657.23-P1P2,0.085388,11477.0,0.086747,0.801973,14310.951172,3345
GCCGATGCAACTGCTA-1,1,LAS1L,ENSG00000001497,P1P2,4523_LAS1L_P1P2_ENSG00000001497,LAS1L_+_64754550.23-P1P2|LAS1L_+_64754657.23-P1P2,0.091399,11510.0,0.096115,0.801973,14352.100586,3432
GCTTCACGTAGACAAT-1,1,LAS1L,ENSG00000001497,P1P2,4523_LAS1L_P1P2_ENSG00000001497,LAS1L_+_64754550.23-P1P2|LAS1L_+_64754657.23-P1P2,0.081552,10153.0,-0.289109,0.801973,12660.023438,3090

In [59]:
adata_filtered.obs.condition.unique()

['ENSG00000145414', 'ENSG00000169679', 'ENSG00000198258', 'ENSG00000171159', 'ENSG00000100575', ..., 'ENSG00000148303', 'ENSG00000113569', 'ENSG00000160752', 'ENSG00000086589', 'ENSG00000148606']
Length: 2058
Categories (2058, object): ['ENSG00000001497', 'ENSG00000003509', 'ENSG00000004779', 'ENSG00000004897', ..., 'ENSG00000284024', 'ENSG00000284906', 'ENSG00000285053', 'non-targeting']