In [1]:
import os
import scanpy as sc
import pandas as pd
import anndata as ad
import numpy as np
import matplotlib.pyplot as plt
import json

## Load Data

In [2]:
filtered_data_path = f"{os.environ['HOME']}/.cz-benchmarks/datasets/replogle_k562_essential_perturbpredict_de_results_control_cells_v1.h5ad"
# filtered_data_path = "/data2/czbenchmarks/replogle2022/K562_essential_raw_singlecell_01.h5ad"

adata_filtered = ad.read_h5ad(filtered_data_path, backed=None)
adata_filtered.obs = adata_filtered.obs.rename(columns={'gene_id':'condition', 'gene':'condition_name'})
adata_filtered.var = adata_filtered.var.rename(columns={'gene_name':'gene'})
adata_filtered.obs['condition'] = adata_filtered.obs['condition'].astype(str)

control_cells_ids_cr4_orig = adata_filtered.uns["control_cells_ids"]
control_cells_ids_cr4_orig.pop("non-targeting", None)

array([], dtype=float64)

In [3]:
cr4_data_path = (
    "/data2/czbenchmarks/replogle2022/raw_h5ad_from_cr4/K562_essential_mtx.h5ad"
)
adata_cr4 = ad.read_h5ad(cr4_data_path, backed=None)
adata_cr4.var.index.name = "gene_id"
adata_cr4.var.rename(columns={"gene_name": "gene"}, inplace=True)
adata_cr4.obs.rename(columns={"gene_id": "condition"}, inplace=True)

In [4]:
with open("/data2/czbenchmarks/control_cells_ids_replogle_k562_essential_perturbpredict.json", "r") as f:
    control_cells_ids_filtered = json.load(f) # filtered data

with open("/data2/czbenchmarks/control_cells_ids_replogle_k562_essential_perturbpredict_validate.json", "r") as f:
    control_cells_ids_cr4_validate = json.load(f) # cr4 data

## QC of Conditions

In [5]:
len(control_cells_ids_cr4_orig.keys()), len(control_cells_ids_filtered.keys()), len(control_cells_ids_cr4_validate.keys())

(2057, 2057, 2057)

In [6]:
set(control_cells_ids_filtered.keys()) == set(control_cells_ids_cr4_orig.keys()) == set(control_cells_ids_cr4_validate.keys())

True

In [7]:
set(control_cells_ids_filtered.keys()).issubset(set(control_cells_ids_cr4_orig.keys()))

True

In [8]:
set(control_cells_ids_cr4_validate.keys()).issubset(set(control_cells_ids_cr4_orig.keys()))

True

## QC of Matches

In [11]:
# conditions = list(control_cells_ids_filtered.keys())
conditions = list(control_cells_ids_cr4_orig.keys())

# Old and new implementation fairly similar when both run on same dataset (cr4)
for condition in conditions:
    print(condition, len(control_cells_ids_cr4_orig[condition]), len(control_cells_ids_cr4_validate[condition]))
    assert len(control_cells_ids_cr4_orig[condition]) == len(control_cells_ids_cr4_validate[condition])
    
    matches = 0
    for pos, (val1, val2) in enumerate(zip(control_cells_ids_cr4_orig[condition], control_cells_ids_cr4_validate[condition].values())):
        if val1 == val2:
            matches += 1
    print(f"     matches {matches}, differences {len(control_cells_ids_cr4_orig[condition]) - matches}")

ENSG00000001497 83 83
     matches 83, differences 0
ENSG00000003509 18 18
     matches 18, differences 0
ENSG00000004779 160 160
     matches 159, differences 1
ENSG00000004897 366 366
     matches 364, differences 2
ENSG00000005007 131 131
     matches 131, differences 0
ENSG00000005100 140 140
     matches 140, differences 0
ENSG00000005175 18 18
     matches 18, differences 0
ENSG00000005194 151 151
     matches 151, differences 0
ENSG00000005448 208 208
     matches 206, differences 2
ENSG00000006634 131 131
     matches 130, differences 1
ENSG00000006695 94 94
     matches 94, differences 0
ENSG00000006712 238 238
     matches 235, differences 3
ENSG00000006715 332 332
     matches 331, differences 1
ENSG00000006744 85 85
     matches 85, differences 0
ENSG00000007168 126 126
     matches 123, differences 3
ENSG00000007866 267 267
     matches 265, differences 2
ENSG00000007923 46 46
     matches 46, differences 0
ENSG00000008018 143 143
     matches 141, differences 2
ENSG00000008128 269 269
     matches 263, differences 6
ENSG00000008324 144 144
     matches 144, differences 0
ENSG00000008952 5 5
     matches 5, differences 0
ENSG00000008988 273 273
     matches 273, differences 0
ENSG00000009413 101 101
     matches 100, differences 1
ENSG00000010072 139 139
     matches 136, differences 3
ENSG00000010244 283 283
     matches 280, differences 3
ENSG00000010256 316 316
     matches 312, differences 4
ENSG00000010292 48 48
     matches 48, differences 0
ENSG00000010322 144 144
     matches 143, differences 1
ENSG00000011260 77 77
     matches 77, differences 0
ENSG00000011304 152 152
     matches 152, differences 0
ENSG00000011376 149 149
     matches 149, differences 0
ENSG00000011426 96 96
     matches 96, differences 0
ENSG00000011523 68 68
     matches 67, differences 1
ENSG00000012048 104 104
     matches 103, differences 1
ENSG00000012174 214 214
     matches 210, differences 4
ENSG00000013275 242 242
     matches 242, differences 0
ENSG00000013503 113 113
     matches 113, differences 0
ENSG00000013561 240 240
     matches 239, differences 1
ENSG00000013573 128 128
     matches 127, differences 1
ENSG00000013810 132 132
     matches 132, differences 0
ENSG00000014123 162 162
     matches 159, differences 3
ENSG00000014138 234 234
     matches 234, differences 0
ENSG00000014919 103 103
     matches 102, differences 1
ENSG00000015676 112 112
     matches 111, differences 1
ENSG00000018699 89 89
     matches 89, differences 0
ENSG00000020426 85 85
     matches 84, differences 1
ENSG00000021776 90 90
     matches 90, differences 0
ENSG00000023608 96 96
     matches 96, differences 0
ENSG00000023734 106 106
     matches 105, differences 1
ENSG00000025770 143 143
     matches 142, differences 1
ENSG00000025796 78 78
     matches 78, differences 0
ENSG00000025800 78 78
     matches 78, differences 0
ENSG00000027001 90 90
     matches 89, differences 1
ENSG00000028203 204 204
     matches 204, differences 0
ENSG00000029363 51 51
     matches 50, differences 1
ENSG00000029364 752 752
     matches 741, differences 11
ENSG00000030066 291 291
     matches 290, differences 1
ENSG00000031698 28 28
     matches 28, differences 0
ENSG00000033011 69 69
     matches 68, differences 1
ENSG00000033327 674 674
     matches 670, differences 4
ENSG00000034510 228 228
     matches 228, differences 0
ENSG00000035141 50 50
     matches 50, differences 0
ENSG00000035928 149 149
     matches 147, differences 2
ENSG00000036257 120 120
     matches 118, differences 2
ENSG00000037241 148 148
     matches 147, differences 1
ENSG00000037897 208 208
     matches 208, differences 0
ENSG00000038358 166 166
     matches 166, differences 0
ENSG00000039650 185 185
     matches 182, differences 3
ENSG00000040275 88 88
     matches 88, differences 0
ENSG00000041357 388 388
     matches 382, differences 6
ENSG00000041802 116 116
     matches 116, differences 0
ENSG00000042429 151 151
     matches 151, differences 0
ENSG00000042753 123 123
     matches 121, differences 2
ENSG00000044090 33 33
     matches 33, differences 0
ENSG00000044574 438 438
     matches 436, differences 2
ENSG00000046647 86 86
     matches 85, differences 1
ENSG00000047249 84 84
     matches 83, differences 1
ENSG00000047315 320 320
     matches 319, differences 1
ENSG00000047410 77 77
     matches 76, differences 1
ENSG00000048162 149 149
     matches 149, differences 0
ENSG00000048544 121 121
     matches 121, differences 0
ENSG00000048707 140 140
     matches 140, differences 0
ENSG00000049541 97 97
     matches 97, differences 0
ENSG00000050820 246 246
     matches 243, differences 3
ENSG00000051180 241 241
     matches 240, differences 1
ENSG00000051596 147 147
     matches 145, differences 2
ENSG00000052749 204 204
     matches 202, differences 2
ENSG00000053372 83 83
     matches 82, differences 1
ENSG00000053900 63 63
     matches 61, differences 2
ENSG00000054116 163 163
     matches 161, differences 2
ENSG00000055044 55 55
     matches 55, differences 0
ENSG00000055130 223 223
     matches 222, differences 1
ENSG00000055483 174 174
     matches 169, differences 5
ENSG00000055950 95 95
     matches 95, differences 0
ENSG00000058262 180 180
     matches 180, differences 0
ENSG00000058272 179 179
     matches 176, differences 3
ENSG00000058600 221 221
     matches 221, differences 0
ENSG00000058729 174 174
     matches 173, differences 1
ENSG00000058804 39 39
     matches 39, differences 0
ENSG00000060069 117 117
     matches 115, differences 2
ENSG00000060237 137 137
     matches 136, differences 1
ENSG00000060339 48 48
     matches 46, differences 2
ENSG00000060688 210 210
     matches 209, differences 1
ENSG00000061273 171 171
     matches 169, differences 2
ENSG00000061676 70 70
     matches 68, differences 2
ENSG00000061794 201 201
     matches 201, differences 0
ENSG00000061936 172 172
     matches 172, differences 0
ENSG00000062485 222 222
     matches 219, differences 3
ENSG00000062582 145 145
     matches 144, differences 1
ENSG00000062716 106 106
     matches 103, differences 3
ENSG00000062822 212 212
     matches 211, differences 1
ENSG00000063046 41 41
     matches 40, differences 1
ENSG00000063177 308 308
     matches 306, differences 2
ENSG00000063244 107 107
     matches 107, differences 0
ENSG00000063322 93 93
     matches 93, differences 0
ENSG00000063978 32 32
     matches 32, differences 0
ENSG00000064313 144 144
     matches 144, differences 0
ENSG00000064419 100 100
     matches 99, differences 1
ENSG00000064666 197 197
     matches 196, differences 1
ENSG00000064703 114 114
     matches 113, differences 1
ENSG00000065183 365 365
     matches 364, differences 1
ENSG00000065268 105 105
     matches 103, differences 2
ENSG00000065328 219 219
     matches 217, differences 2
ENSG00000065427 59 59
     matches 59, differences 0
ENSG00000065518 166 166
     matches 166, differences 0
ENSG00000065978 86 86
     matches 85, differences 1
ENSG00000066136 23 23
     matches 23, differences 0
ENSG00000066322 176 176
     matches 174, differences 2
ENSG00000066379 81 81
     matches 81, differences 0
ENSG00000066422 146 146
     matches 146, differences 0
ENSG00000067225 149 149
     matches 148, differences 1
ENSG00000067334 264 264
     matches 260, differences 4
ENSG00000067533 32 32
     matches 32, differences 0
ENSG00000067596 115 115
     matches 115, differences 0
ENSG00000067704 216 216
     matches 215, differences 1
ENSG00000068120 247 247
     matches 247, differences 0
ENSG00000068394 107 107
     matches 105, differences 2
ENSG00000068654 127 127
     matches 127, differences 0
ENSG00000068784 150 150
     matches 150, differences 0
ENSG00000069248 79 79
     matches 79, differences 0
ENSG00000069329 43 43
     matches 43, differences 0
ENSG00000069764 202 202
     matches 200, differences 2
ENSG00000070366 54 54
     matches 54, differences 0
ENSG00000070367 110 110
     matches 109, differences 1
ENSG00000070495 193 193
     matches 191, differences 2
ENSG00000070756 19 19
     matches 19, differences 0
ENSG00000070785 104 104
     matches 104, differences 0
ENSG00000070814 97 97
     matches 97, differences 0
ENSG00000070831 70 70
     matches 70, differences 0
ENSG00000071082 294 294
     matches 290, differences 4
ENSG00000071127 102 102
     matches 102, differences 0
ENSG00000071243 65 65
     matches 64, differences 1
ENSG00000071553 119 119
     matches 118, differences 1
ENSG00000071859 38 38
     matches 38, differences 0
ENSG00000071894 50 50
     matches 49, differences 1
ENSG00000071994 74 74
     matches 74, differences 0
ENSG00000072274 57 57
     matches 57, differences 0
ENSG00000072501 180 180
     matches 178, differences 2
ENSG00000072506 26 26
     matches 26, differences 0
ENSG00000072756 203 203
     matches 200, differences 3
ENSG00000072849 124 124
     matches 122, differences 2
ENSG00000073050 254 254
     matches 253, differences 1
ENSG00000073111 123 123
     matches 120, differences 3
ENSG00000073536 413 413
     matches 411, differences 2
ENSG00000073578 62 62
     matches 62, differences 0
ENSG00000073584 31 31
     matches 31, differences 0
ENSG00000073969 165 165
     matches 165, differences 0
ENSG00000074071 141 141
     matches 139, differences 2
ENSG00000074201 53 53
     matches 52, differences 1
ENSG00000074319 87 87
     matches 86, differences 1
ENSG00000074582 70 70
     matches 70, differences 0
ENSG00000074800 70 70
     matches 70, differences 0
ENSG00000074935 134 134
     matches 132, differences 2
ENSG00000075089 108 108
     matches 108, differences 0
ENSG00000075131 109 109
     matches 109, differences 0
ENSG00000075415 114 114
     matches 113, differences 1
ENSG00000075624 168 168
     matches 165, differences 3
ENSG00000075856 154 154
     matches 151, differences 3
ENSG00000075886 69 69
     matches 69, differences 0
ENSG00000075914 113 113
     matches 113, differences 0
ENSG00000076003 102 102
     matches 101, differences 1
ENSG00000076043 79 79
     matches 78, differences 1
ENSG00000076201 140 140
     matches 140, differences 0
ENSG00000076924 153 153
     matches 153, differences 0
ENSG00000077235 160 160
     matches 160, differences 0
ENSG00000077348 41 41
     matches 40, differences 1
ENSG00000077380 300 300
     matches 299, differences 1
ENSG00000077514 68 68
     matches 68, differences 0
ENSG00000077549 83 83
     matches 81, differences 2
ENSG00000078142 115 115
     matches 115, differences 0
ENSG00000079134 38 38
     matches 38, differences 0
ENSG00000079246 88 88
     matches 88, differences 0
ENSG00000079785 101 101
     matches 99, differences 2
ENSG00000079805 12 12
     matches 11, differences 1
ENSG00000080603 194 194
     matches 192, differences 2
ENSG00000080819 101 101
     matches 99, differences 2
ENSG00000080823 123 123
     matches 122, differences 1
ENSG00000080986 214 214
     matches 213, differences 1
ENSG00000081307 102 102
     matches 102, differences 0
ENSG00000081665 177 177
     matches 175, differences 2
ENSG00000082068 30 30
     matches 30, differences 0
ENSG00000082515 96 96
     matches 95, differences 1
ENSG00000082516 133 133
     matches 133, differences 0
ENSG00000082898 207 207
     matches 204, differences 3
ENSG00000083093 97 97
     matches 95, differences 2
ENSG00000083520 43 43
     matches 43, differences 0
ENSG00000083635 63 63
     matches 63, differences 0
ENSG00000083845 144 144
     matches 141, differences 3
ENSG00000083896 237 237
     matches 236, differences 1
ENSG00000084072 46 46
     matches 46, differences 0
ENSG00000084090 117 117
     matches 117, differences 0
ENSG00000084463 312 312
     matches 309, differences 3
ENSG00000084623 61 61
     matches 61, differences 0
ENSG00000085415 60 60
     matches 60, differences 0
ENSG00000085721 39 39
     matches 39, differences 0
ENSG00000085840 530 530
     matches 528, differences 2
ENSG00000085872 67 67
     matches 67, differences 0
ENSG00000086061 292 292
     matches 289, differences 3
ENSG00000086065 110 110
     matches 109, differences 1
ENSG00000086189 94 94
     matches 94, differences 0
ENSG00000086200 72 72
     matches 72, differences 0
ENSG00000086504 52 52
     matches 52, differences 0
ENSG00000086589 5 5
     matches 5, differences 0
ENSG00000086598 137 137
     matches 131, differences 6
ENSG00000086758 94 94
     matches 94, differences 0
ENSG00000086827 200 200
     matches 198, differences 2
ENSG00000087087 307 307
     matches 303, differences 4
ENSG00000087157 104 104
     matches 102, differences 2
ENSG00000087191 17 17
     matches 17, differences 0
ENSG00000087263 114 114
     matches 112, differences 2
ENSG00000087269 47 47
     matches 47, differences 0
ENSG00000087365 500 500
     matches 497, differences 3
ENSG00000087470 168 168
     matches 167, differences 1
ENSG00000087586 58 58
     matches 57, differences 1
ENSG00000088038 332 332
     matches 332, differences 0
ENSG00000088205 137 137
     matches 135, differences 2
ENSG00000088325 361 361
     matches 357, differences 4
ENSG00000088356 116 116
     matches 115, differences 1
ENSG00000088766 111 111
     matches 108, differences 3
ENSG00000088930 66 66
     matches 65, differences 1
ENSG00000088986 71 71
     matches 71, differences 0
ENSG00000089009 273 273
     matches 271, differences 2
ENSG00000089048 149 149
     matches 148, differences 1
ENSG00000089053 40 40
     matches 39, differences 1
ENSG00000089157 184 184
     matches 184, differences 0
ENSG00000089159 161 161
     matches 160, differences 1
ENSG00000089195 114 114
     matches 112, differences 2
ENSG00000089289 281 281
     matches 281, differences 0
ENSG00000089685 46 46
     matches 46, differences 0
ENSG00000089737 286 286
     matches 280, differences 6
ENSG00000089902 35 35
     matches 35, differences 0
ENSG00000090054 28 28
     matches 28, differences 0
ENSG00000090061 327 327
     matches 323, differences 4
ENSG00000090273 117 117
     matches 116, differences 1
ENSG00000090470 99 99
     matches 99, differences 0
ENSG00000090861 40 40
     matches 40, differences 0
ENSG00000090889 129 129
     matches 127, differences 2
ENSG00000090989 182 182
     matches 180, differences 2
ENSG00000091140 311 311
     matches 307, differences 4
ENSG00000091157 103 103
     matches 101, differences 2
ENSG00000091651 81 81
     matches 81, differences 0
ENSG00000092010 121 121
     matches 121, differences 0
ENSG00000092020 52 52
     matches 50, differences 2
ENSG00000092036 189 189
     matches 187, differences 2
ENSG00000092094 70 70
     matches 69, differences 1
ENSG00000092108 152 152
     matches 149, differences 3
ENSG00000092148 130 130
     matches 127, differences 3
ENSG00000092199 334 334
     matches 332, differences 2
ENSG00000092201 93 93
     matches 93, differences 0
ENSG00000092330 76 76
     matches 76, differences 0
ENSG00000092439 128 128
     matches 127, differences 1
ENSG00000092853 134 134
     matches 132, differences 2
ENSG00000092871 7 7
     matches 7, differences 0
ENSG00000093009 92 92
     matches 92, differences 0
ENSG00000094804 192 192
     matches 190, differences 2
ENSG00000094880 177 177
     matches 176, differences 1
ENSG00000094914 212 212
     matches 212, differences 0
ENSG00000095059 66 66
     matches 66, differences 0
ENSG00000095139 333 333
     matches 328, differences 5
ENSG00000095787 162 162
     matches 161, differences 1
ENSG00000095906 153 153
     matches 153, differences 0
ENSG00000096080 121 121
     matches 120, differences 1
ENSG00000096401 99 99
     matches 99, differences 0
ENSG00000097046 95 95
     matches 95, differences 0
ENSG00000099194 24 24
     matches 24, differences 0
ENSG00000099246 43 43
     matches 42, differences 1
ENSG00000099326 128 128
     matches 128, differences 0
ENSG00000099341 22 22
     matches 21, differences 1
ENSG00000099381 69 69
     matches 69, differences 0
ENSG00000099783 258 258
     matches 255, differences 3
ENSG00000099795 74 74
     matches 73, differences 1
ENSG00000099800 178 178
     matches 173, differences 5
ENSG00000099817 225 225
     matches 224, differences 1
ENSG00000099821 214 214
     matches 212, differences 2
ENSG00000099942 120 120
     matches 120, differences 0
ENSG00000099956 182 182
     matches 182, differences 0
ENSG00000099995 332 332
     matches 328, differences 4
ENSG00000100023 130 130
     matches 130, differences 0
ENSG00000100027 72 72
     matches 70, differences 2
ENSG00000100028 182 182
     matches 182, differences 0
ENSG00000100029 65 65
     matches 64, differences 1
ENSG00000100033 379 379
     matches 376, differences 3
ENSG00000100084 341 341
     matches 340, differences 1
ENSG00000100109 61 61
     matches 61, differences 0
ENSG00000100129 57 57
     matches 57, differences 0
ENSG00000100142 337 337
     matches 336, differences 1
ENSG00000100209 86 86
     matches 85, differences 1
ENSG00000100216 104 104
     matches 104, differences 0
ENSG00000100220 171 171
     matches 170, differences 1
ENSG00000100296 32 32
     matches 32, differences 0
ENSG00000100297 90 90
     matches 88, differences 2
ENSG00000100316 1996 1996
     matches 1979, differences 17
ENSG00000100319 100 100
     matches 99, differences 1
ENSG00000100347 102 102
     matches 101, differences 1
ENSG00000100353 186 186
     matches 183, differences 3
ENSG00000100387 57 57
     matches 57, differences 0
ENSG00000100401 130 130
     matches 130, differences 0
ENSG00000100410 231 231
     matches 230, differences 1
ENSG00000100413 109 109
     matches 106, differences 3
ENSG00000100462 127 127
     matches 127, differences 0
ENSG00000100479 56 56
     matches 56, differences 0
ENSG00000100519 151 151
     matches 150, differences 1
ENSG00000100522 112 112
     matches 112, differences 0
ENSG00000100554 139 139
     matches 139, differences 0
ENSG00000100564 85 85
     matches 85, differences 0
ENSG00000100567 372 372
     matches 369, differences 3
ENSG00000100575 201 201
     matches 200, differences 1
ENSG00000100603 226 226
     matches 226, differences 0
ENSG00000100632 86 86
     matches 84, differences 2
ENSG00000100664 175 175
     matches 175, differences 0
ENSG00000100697 158 158
     matches 156, differences 2
ENSG00000100726 74 74
     matches 74, differences 0
ENSG00000100764 316 316
     matches 315, differences 1
ENSG00000100804 270 270
     matches 267, differences 3
ENSG00000100811 82 82
     matches 80, differences 2
ENSG00000100813 191 191
     matches 190, differences 1
ENSG00000100836 148 148
     matches 146, differences 2
ENSG00000100865 78 78
     matches 77, differences 1
ENSG00000100883 81 81
     matches 80, differences 1
ENSG00000100890 42 42
     matches 42, differences 0
ENSG00000100902 40 40
     matches 40, differences 0
ENSG00000100911 151 151
     matches 150, differences 1
ENSG00000100941 86 86
     matches 85, differences 1
ENSG00000100949 116 116
     matches 116, differences 0
ENSG00000101003 186 186
     matches 184, differences 2
ENSG00000101057 106 106
     matches 105, differences 1
ENSG00000101132 34 34
     matches 34, differences 0
ENSG00000101138 141 141
     matches 140, differences 1
ENSG00000101146 59 59
     matches 59, differences 0
ENSG00000101158 201 201
     matches 200, differences 1
ENSG00000101161 232 232
     matches 229, differences 3
ENSG00000101166 273 273
     matches 272, differences 1
ENSG00000101181 146 146
     matches 142, differences 4
ENSG00000101182 41 41
     matches 41, differences 0
ENSG00000101189 74 74
     matches 74, differences 0
ENSG00000101246 138 138
     matches 137, differences 1
ENSG00000101343 261 261
     matches 257, differences 4
ENSG00000101361 99 99
     matches 98, differences 1
ENSG00000101407 151 151
     matches 149, differences 2
ENSG00000101421 71 71
     matches 68, differences 3
ENSG00000101444 147 147
     matches 146, differences 1
ENSG00000101639 202 202
     matches 201, differences 1
ENSG00000101654 114 114
     matches 111, differences 3
ENSG00000101773 117 117
     matches 115, differences 2
ENSG00000101868 230 230

In [12]:
# Results are very different between old cr4 version and new filtered version
for condition in conditions:
    print(condition, len(control_cells_ids_cr4_orig[condition]), len(control_cells_ids_filtered[condition]))
    assert len(control_cells_ids_cr4_orig[condition]) == len(control_cells_ids_filtered[condition])
    
    matches = 0
    for pos, (val1, val2) in enumerate(zip(control_cells_ids_cr4_orig[condition], control_cells_ids_filtered[condition].values())):
        if val1 == val2:
            matches += 1
    print(f"     matches {matches}, differences {len(control_cells_ids_cr4_orig[condition]) - matches}")

ENSG00000001497 83 83
     matches 1, differences 82
ENSG00000003509 18 18
     matches 0, differences 18
ENSG00000004779 160 160
     matches 0, differences 160
ENSG00000004897 366 366
     matches 4, differences 362
ENSG00000005007 131 131
     matches 0, differences 131
ENSG00000005100 140 140
     matches 1, differences 139
ENSG00000005175 18 18
     matches 1, differences 17
ENSG00000005194 151 151
     matches 1, differences 150
ENSG00000005448 208 208
     matches 1, differences 207
ENSG00000006634 131 131
     matches 1, differences 130
ENSG00000006695 94 94
     matches 0, differences 94
ENSG00000006712 238 238
     matches 1, differences 237
ENSG00000006715 332 332
     matches 1, differences 331
ENSG00000006744 85 85
     matches 1, differences 84
ENSG00000007168 126 126
     matches 1, differences 125
ENSG00000007866 267 267
     matches 1, differences 266
ENSG00000007923 46 46
     matches 1, differences 45
ENSG00000008018 143 143
     matches 1, differences 142
ENSG00000008128 269 269
     matches 0, differences 269
ENSG00000008324 144 144
     matches 0, differences 144
ENSG00000008952 5 5
     matches 1, differences 4
ENSG00000008988 273 273
     matches 1, differences 272
ENSG00000009413 101 101
     matches 2, differences 99
ENSG00000010072 139 139
     matches 0, differences 139
ENSG00000010244 283 283
     matches 0, differences 283
ENSG00000010256 316 316
     matches 3, differences 313
ENSG00000010292 48 48
     matches 0, differences 48
ENSG00000010322 144 144
     matches 0, differences 144
ENSG00000011260 77 77
     matches 1, differences 76
ENSG00000011304 152 152
     matches 4, differences 148
ENSG00000011376 149 149
     matches 2, differences 147
ENSG00000011426 96 96
     matches 2, differences 94
ENSG00000011523 68 68
     matches 1, differences 67
ENSG00000012048 104 104
     matches 3, differences 101
ENSG00000012174 214 214
     matches 0, differences 214
ENSG00000013275 242 242
     matches 3, differences 239
ENSG00000013503 113 113
     matches 0, differences 113
ENSG00000013561 240 240
     matches 1, differences 239
ENSG00000013573 128 128
     matches 1, differences 127
ENSG00000013810 132 132
     matches 0, differences 132
ENSG00000014123 162 162
     matches 0, differences 162
ENSG00000014138 234 234
     matches 2, differences 232
ENSG00000014919 103 103
     matches 2, differences 101
ENSG00000015676 112 112
     matches 0, differences 112
ENSG00000018699 89 89
     matches 0, differences 89
ENSG00000020426 85 85
     matches 2, differences 83
ENSG00000021776 90 90
     matches 0, differences 90
ENSG00000023608 96 96
     matches 1, differences 95
ENSG00000023734 106 106
     matches 1, differences 105
ENSG00000025770 143 143
     matches 2, differences 141
ENSG00000025796 78 78
     matches 1, differences 77
ENSG00000025800 78 78
     matches 1, differences 77
ENSG00000027001 90 90
     matches 0, differences 90
ENSG00000028203 204 204
     matches 4, differences 200
ENSG00000029363 51 51
     matches 0, differences 51
ENSG00000029364 752 752
     matches 1, differences 751
ENSG00000030066 291 291
     matches 0, differences 291
ENSG00000031698 28 28
     matches 0, differences 28
ENSG00000033011 69 69
     matches 0, differences 69
ENSG00000033327 674 674
     matches 1, differences 673
ENSG00000034510 228 228
     matches 0, differences 228
ENSG00000035141 50 50
     matches 1, differences 49
ENSG00000035928 149 149
     matches 0, differences 149
ENSG00000036257 120 120
     matches 1, differences 119
ENSG00000037241 148 148
     matches 0, differences 148
ENSG00000037897 208 208
     matches 0, differences 208
ENSG00000038358 166 166
     matches 2, differences 164
ENSG00000039650 185 185
     matches 0, differences 185
ENSG00000040275 88 88
     matches 4, differences 84
ENSG00000041357 388 388
     matches 1, differences 387
ENSG00000041802 116 116
     matches 1, differences 115
ENSG00000042429 151 151
     matches 1, differences 150
ENSG00000042753 123 123
     matches 0, differences 123
ENSG00000044090 33 33
     matches 0, differences 33
ENSG00000044574 438 438
     matches 1, differences 437
ENSG00000046647 86 86
     matches 0, differences 86
ENSG00000047249 84 84
     matches 2, differences 82
ENSG00000047315 320 320
     matches 0, differences 320
ENSG00000047410 77 77
     matches 2, differences 75
ENSG00000048162 149 149
     matches 1, differences 148
ENSG00000048544 121 121
     matches 2, differences 119
ENSG00000048707 140 140
     matches 0, differences 140
ENSG00000049541 97 97
     matches 2, differences 95
ENSG00000050820 246 246
     matches 2, differences 244
ENSG00000051180 241 241
     matches 1, differences 240
ENSG00000051596 147 147
     matches 2, differences 145
ENSG00000052749 204 204
     matches 0, differences 204
ENSG00000053372 83 83
     matches 0, differences 83
ENSG00000053900 63 63
     matches 1, differences 62
ENSG00000054116 163 163
     matches 1, differences 162
ENSG00000055044 55 55
     matches 1, differences 54
ENSG00000055130 223 223
     matches 2, differences 221
ENSG00000055483 174 174
     matches 1, differences 173
ENSG00000055950 95 95
     matches 2, differences 93
ENSG00000058262 180 180
     matches 0, differences 180
ENSG00000058272 179 179
     matches 1, differences 178
ENSG00000058600 221 221
     matches 1, differences 220
ENSG00000058729 174 174
     matches 1, differences 173
ENSG00000058804 39 39
     matches 0, differences 39
ENSG00000060069 117 117
     matches 0, differences 117
ENSG00000060237 137 137
     matches 2, differences 135
ENSG00000060339 48 48
     matches 4, differences 44
ENSG00000060688 210 210
     matches 2, differences 208
ENSG00000061273 171 171
     matches 1, differences 170
ENSG00000061676 70 70
     matches 2, differences 68
ENSG00000061794 201 201
     matches 0, differences 201
ENSG00000061936 172 172
     matches 1, differences 171
ENSG00000062485 222 222
     matches 1, differences 221
ENSG00000062582 145 145
     matches 0, differences 145
ENSG00000062716 106 106
     matches 0, differences 106
ENSG00000062822 212 212
     matches 2, differences 210
ENSG00000063046 41 41
     matches 0, differences 41
ENSG00000063177 308 308
     matches 1, differences 307
ENSG00000063244 107 107
     matches 2, differences 105
ENSG00000063322 93 93
     matches 0, differences 93
ENSG00000063978 32 32
     matches 2, differences 30
ENSG00000064313 144 144
     matches 3, differences 141
ENSG00000064419 100 100
     matches 3, differences 97
ENSG00000064666 197 197
     matches 2, differences 195
ENSG00000064703 114 114
     matches 3, differences 111
ENSG00000065183 365 365
     matches 1, differences 364
ENSG00000065268 105 105
     matches 1, differences 104
ENSG00000065328 219 219
     matches 1, differences 218
ENSG00000065427 59 59
     matches 0, differences 59
ENSG00000065518 166 166
     matches 2, differences 164
ENSG00000065978 86 86
     matches 1, differences 85
ENSG00000066136 23 23
     matches 0, differences 23
ENSG00000066322 176 176
     matches 1, differences 175
ENSG00000066379 81 81
     matches 1, differences 80
ENSG00000066422 146 146
     matches 0, differences 146
ENSG00000067225 149 149
     matches 1, differences 148
ENSG00000067334 264 264
     matches 3, differences 261
ENSG00000067533 32 32
     matches 5, differences 27
ENSG00000067596 115 115
     matches 1, differences 114
ENSG00000067704 216 216
     matches 0, differences 216
ENSG00000068120 247 247
     matches 1, differences 246
ENSG00000068394 107 107
     matches 0, differences 107
ENSG00000068654 127 127
     matches 1, differences 126
ENSG00000068784 150 150
     matches 3, differences 147
ENSG00000069248 79 79
     matches 0, differences 79
ENSG00000069329 43 43
     matches 1, differences 42
ENSG00000069764 202 202
     matches 1, differences 201
ENSG00000070366 54 54
     matches 5, differences 49
ENSG00000070367 110 110
     matches 0, differences 110
ENSG00000070495 193 193
     matches 0, differences 193
ENSG00000070756 19 19
     matches 0, differences 19
ENSG00000070785 104 104
     matches 1, differences 103
ENSG00000070814 97 97
     matches 2, differences 95
ENSG00000070831 70 70
     matches 2, differences 68
ENSG00000071082 294 294
     matches 1, differences 293
ENSG00000071127 102 102
     matches 1, differences 101
ENSG00000071243 65 65
     matches 1, differences 64
ENSG00000071553 119 119
     matches 0, differences 119
ENSG00000071859 38 38
     matches 3, differences 35
ENSG00000071894 50 50
     matches 0, differences 50
ENSG00000071994 74 74
     matches 0, differences 74
ENSG00000072274 57 57
     matches 2, differences 55
ENSG00000072501 180 180
     matches 1, differences 179
ENSG00000072506 26 26
     matches 1, differences 25
ENSG00000072756 203 203
     matches 0, differences 203
ENSG00000072849 124 124
     matches 2, differences 122
ENSG00000073050 254 254
     matches 3, differences 251
ENSG00000073111 123 123
     matches 1, differences 122
ENSG00000073536 413 413
     matches 0, differences 413
ENSG00000073578 62 62
     matches 1, differences 61
ENSG00000073584 31 31
     matches 1, differences 30
ENSG00000073969 165 165
     matches 0, differences 165
ENSG00000074071 141 141
     matches 1, differences 140
ENSG00000074201 53 53
     matches 1, differences 52
ENSG00000074319 87 87
     matches 0, differences 87
ENSG00000074582 70 70
     matches 1, differences 69
ENSG00000074800 70 70
     matches 1, differences 69
ENSG00000074935 134 134
     matches 0, differences 134
ENSG00000075089 108 108
     matches 0, differences 108
ENSG00000075131 109 109
     matches 0, differences 109
ENSG00000075415 114 114
     matches 3, differences 111
ENSG00000075624 168 168
     matches 1, differences 167
ENSG00000075856 154 154
     matches 1, differences 153
ENSG00000075886 69 69
     matches 0, differences 69
ENSG00000075914 113 113
     matches 3, differences 110
ENSG00000076003 102 102
     matches 2, differences 100
ENSG00000076043 79 79
     matches 1, differences 78
ENSG00000076201 140 140
     matches 2, differences 138
ENSG00000076924 153 153
     matches 1, differences 152
ENSG00000077235 160 160
     matches 0, differences 160
ENSG00000077348 41 41
     matches 1, differences 40
ENSG00000077380 300 300
     matches 3, differences 297
ENSG00000077514 68 68
     matches 1, differences 67
ENSG00000077549 83 83
     matches 1, differences 82
ENSG00000078142 115 115
     matches 0, differences 115
ENSG00000079134 38 38
     matches 1, differences 37
ENSG00000079246 88 88
     matches 0, differences 88
ENSG00000079785 101 101
     matches 1, differences 100
ENSG00000079805 12 12
     matches 0, differences 12
ENSG00000080603 194 194
     matches 1, differences 193
ENSG00000080819 101 101
     matches 2, differences 99
ENSG00000080823 123 123
     matches 0, differences 123
ENSG00000080986 214 214
     matches 1, differences 213
ENSG00000081307 102 102
     matches 1, differences 101
ENSG00000081665 177 177
     matches 1, differences 176
ENSG00000082068 30 30
     matches 0, differences 30
ENSG00000082515 96 96
     matches 1, differences 95
ENSG00000082516 133 133
     matches 1, differences 132
ENSG00000082898 207 207
     matches 4, differences 203
ENSG00000083093 97 97
     matches 0, differences 97
ENSG00000083520 43 43
     matches 2, differences 41
ENSG00000083635 63 63
     matches 0, differences 63
ENSG00000083845 144 144
     matches 0, differences 144
ENSG00000083896 237 237
     matches 2, differences 235
ENSG00000084072 46 46
     matches 2, differences 44
ENSG00000084090 117 117
     matches 3, differences 114
ENSG00000084463 312 312
     matches 1, differences 311
ENSG00000084623 61 61
     matches 0, differences 61
ENSG00000085415 60 60
     matches 0, differences 60
ENSG00000085721 39 39
     matches 0, differences 39
ENSG00000085840 530 530
     matches 0, differences 530
ENSG00000085872 67 67
     matches 1, differences 66
ENSG00000086061 292 292
     matches 1, differences 291
ENSG00000086065 110 110
     matches 1, differences 109
ENSG00000086189 94 94
     matches 1, differences 93
ENSG00000086200 72 72
     matches 0, differences 72
ENSG00000086504 52 52
     matches 1, differences 51
ENSG00000086589 5 5
     matches 1, differences 4
ENSG00000086598 137 137
     matches 1, differences 136
ENSG00000086758 94 94
     matches 1, differences 93
ENSG00000086827 200 200
     matches 2, differences 198
ENSG00000087087 307 307
     matches 3, differences 304
ENSG00000087157 104 104
     matches 1, differences 103
ENSG00000087191 17 17
     matches 3, differences 14
ENSG00000087263 114 114
     matches 0, differences 114
ENSG00000087269 47 47
     matches 1, differences 46
ENSG00000087365 500 500
     matches 2, differences 498
ENSG00000087470 168 168
     matches 0, differences 168
ENSG00000087586 58 58
     matches 1, differences 57
ENSG00000088038 332 332
     matches 1, differences 331
ENSG00000088205 137 137
     matches 1, differences 136
ENSG00000088325 361 361
     matches 0, differences 361
ENSG00000088356 116 116
     matches 1, differences 115
ENSG00000088766 111 111
     matches 1, differences 110
ENSG00000088930 66 66
     matches 1, differences 65
ENSG00000088986 71 71
     matches 0, differences 71
ENSG00000089009 273 273
     matches 0, differences 273
ENSG00000089048 149 149
     matches 0, differences 149
ENSG00000089053 40 40
     matches 0, differences 40
ENSG00000089157 184 184
     matches 0, differences 184
ENSG00000089159 161 161
     matches 1, differences 160
ENSG00000089195 114 114
     matches 1, differences 113
ENSG00000089289 281 281
     matches 2, differences 279
ENSG00000089685 46 46
     matches 2, differences 44
ENSG00000089737 286 286
     matches 0, differences 286
ENSG00000089902 35 35
     matches 1, differences 34
ENSG00000090054 28 28
     matches 1, differences 27
ENSG00000090061 327 327
     matches 1, differences 326
ENSG00000090273 117 117
     matches 1, differences 116
ENSG00000090470 99 99
     matches 1, differences 98
ENSG00000090861 40 40
     matches 3, differences 37
ENSG00000090889 129 129
     matches 1, differences 128
ENSG00000090989 182 182
     matches 1, differences 181
ENSG00000091140 311 311
     matches 2, differences 309
ENSG00000091157 103 103
     matches 2, differences 101
ENSG00000091651 81 81
     matches 1, differences 80
ENSG00000092010 121 121
     matches 1, differences 120
ENSG00000092020 52 52
     matches 0, differences 52
ENSG00000092036 189 189
     matches 0, differences 189
ENSG00000092094 70 70
     matches 2, differences 68
ENSG00000092108 152 152
     matches 1, differences 151
ENSG00000092148 130 130
     matches 1, differences 129
ENSG00000092199 334 334
     matches 0, differences 334
ENSG00000092201 93 93
     matches 2, differences 91
ENSG00000092330 76 76
     matches 1, differences 75
ENSG00000092439 128 128
     matches 1, differences 127
ENSG00000092853 134 134
     matches 1, differences 133
ENSG00000092871 7 7
     matches 3, differences 4
ENSG00000093009 92 92
     matches 0, differences 92
ENSG00000094804 192 192
     matches 0, differences 192
ENSG00000094880 177 177
     matches 0, differences 177
ENSG00000094914 212 212
     matches 0, differences 212
ENSG00000095059 66 66
     matches 0, differences 66
ENSG00000095139 333 333
     matches 1, differences 332
ENSG00000095787 162 162
     matches 0, differences 162
ENSG00000095906 153 153
     matches 1, differences 152
ENSG00000096080 121 121
     matches 5, differences 116
ENSG00000096401 99 99
     matches 1, differences 98
ENSG00000097046 95 95
     matches 3, differences 92
ENSG00000099194 24 24
     matches 1, differences 23
ENSG00000099246 43 43
     matches 3, differences 40
ENSG00000099326 128 128
     matches 1, differences 127
ENSG00000099341 22 22
     matches 0, differences 22
ENSG00000099381 69 69
     matches 1, differences 68
ENSG00000099783 258 258
     matches 0, differences 258
ENSG00000099795 74 74
     matches 2, differences 72
ENSG00000099800 178 178
     matches 0, differences 178
ENSG00000099817 225 225
     matches 0, differences 225
ENSG00000099821 214 214
     matches 0, differences 214
ENSG00000099942 120 120
     matches 0, differences 120
ENSG00000099956 182 182
     matches 0, differences 182
ENSG00000099995 332 332
     matches 1, differences 331
ENSG00000100023 130 130
     matches 1, differences 129
ENSG00000100027 72 72
     matches 1, differences 71
ENSG00000100028 182 182
     matches 1, differences 181
ENSG00000100029 65 65
     matches 1, differences 64
ENSG00000100033 379 379
     matches 3, differences 376
ENSG00000100084 341 341
     matches 0, differences 341
ENSG00000100109 61 61
     matches 2, differences 59
ENSG00000100129 57 57
     matches 1, differences 56
ENSG00000100142 337 337
     matches 1, differences 336
ENSG00000100209 86 86
     matches 0, differences 86
ENSG00000100216 104 104
     matches 4, differences 100
ENSG00000100220 171 171
     matches 1, differences 170
ENSG00000100296 32 32
     matches 0, differences 32
ENSG00000100297 90 90
     matches 1, differences 89
ENSG00000100316 1996 1996
     matches 1, differences 1995
ENSG00000100319 100 100
     matches 2, differences 98
ENSG00000100347 102 102
     matches 0, differences 102
ENSG00000100353 186 186
     matches 0, differences 186
ENSG00000100387 57 57
     matches 2, differences 55
ENSG00000100401 130 130
     matches 2, differences 128
ENSG00000100410 231 231
     matches 1, differences 230
ENSG00000100413 109 109
     matches 0, differences 109
ENSG00000100462 127 127
     matches 0, differences 127
ENSG00000100479 56 56
     matches 1, differences 55
ENSG00000100519 151 151
     matches 0, differences 151
ENSG00000100522 112 112
     matches 0, differences 112
ENSG00000100554 139 139
     matches 1, differences 138
ENSG00000100564 85 85
     matches 3, differences 82
ENSG00000100567 372 372
     matches 0, differences 372
ENSG00000100575 201 201
     matches 1, differences 200
ENSG00000100603 226 226
     matches 1, differences 225
ENSG00000100632 86 86
     matches 1, differences 85
ENSG00000100664 175 175
     matches 0, differences 175
ENSG00000100697 158 158
     matches 0, differences 158
ENSG00000100726 74 74
     matches 0, differences 74
ENSG00000100764 316 316
     matches 0, differences 316
ENSG00000100804 270 270
     matches 2, differences 268
ENSG00000100811 82 82
     matches 0, differences 82
ENSG00000100813 191 191
     matches 0, differences 191
ENSG00000100836 148 148
     matches 1, differences 147
ENSG00000100865 78 78
     matches 2, differences 76
ENSG00000100883 81 81
     matches 0, differences 81
ENSG00000100890 42 42
     matches 0, differences 42
ENSG00000100902 40 40
     matches 0, differences 40
ENSG00000100911 151 151
     matches 0, differences 151
ENSG00000100941 86 86
     matches 1, differences 85
ENSG00000100949 116 116
     matches 1, differences 115
ENSG00000101003 186 186
     matches 2, differences 184
ENSG00000101057 106 106
     matches 0, differences 106
ENSG00000101132 34 34
     matches 0, differences 34
ENSG00000101138 141 141
     matches 1, differences 140
ENSG00000101146 59 59
     matches 1, differences 58
ENSG00000101158 201 201
     matches 3, differences 198
ENSG00000101161 232 232
     matches 2, differences 230
ENSG00000101166 273 273
     matches 0, differences 273
ENSG00000101181 146 146
     matches 0, differences 146
ENSG00000101182 41 41
     matches 1, differences 40
ENSG00000101189 74 74
     matches 2, differences 72
ENSG00000101246 138 138
     matches 2, differences 136
ENSG00000101343 261 261
     matches 1, differences 260
ENSG00000101361 99 99
     matches 0, differences 99
ENSG00000101407 151 151
     matches 0, differences 151
ENSG00000101421 71 71
     matches 1, differences 70
ENSG00000101444 147 147
     matches 1, differences 146
ENSG00000101639 202 202
     matches 0, differences 202
ENSG00000101654 114 114
     matches 0, differences 114
ENSG00000101773 117 117
     matches 0, differences 117
ENSG00000101868 230 230

In [23]:
# But the differences appear to be mostly because of sort order. There are still some unexplained issues with the original dictionary because differences of 1 can't be explained by sorting
for condition in conditions:
    print(condition, len(control_cells_ids_cr4_validate[condition]), len(control_cells_ids_filtered[condition]))
    assert len(control_cells_ids_cr4_validate[condition]) == len(control_cells_ids_filtered[condition])
    
    matches = 0
    num_pairs = len(control_cells_ids_cr4_validate[condition])
    for pos, key in enumerate(control_cells_ids_cr4_validate[condition].keys()):
        val1, val2 = control_cells_ids_cr4_validate[condition][key], control_cells_ids_filtered[condition][key]
        if val1 == val2:
            matches += 1
    print(f"     matches {matches}, differences {num_pairs - matches}")

ENSG00000001497 83 83
     matches 83, differences 0
ENSG00000003509 18 18
     matches 18, differences 0
ENSG00000004779 160 160
     matches 160, differences 0
ENSG00000004897 366 366
     matches 366, differences 0
ENSG00000005007 131 131
     matches 131, differences 0
ENSG00000005100 140 140
     matches 140, differences 0
ENSG00000005175 18 18
     matches 18, differences 0
ENSG00000005194 151 151
     matches 151, differences 0
ENSG00000005448 208 208
     matches 208, differences 0
ENSG00000006634 131 131
     matches 131, differences 0
ENSG00000006695 94 94
     matches 94, differences 0
ENSG00000006712 238 238
     matches 238, differences 0
ENSG00000006715 332 332
     matches 332, differences 0
ENSG00000006744 85 85
     matches 85, differences 0
ENSG00000007168 126 126
     matches 126, differences 0
ENSG00000007866 267 267
     matches 267, differences 0
ENSG00000007923 46 46
     matches 46, differences 0
ENSG00000008018 143 143
     matches 143, differences 0
ENSG00000008128 269 269
     matches 269, differences 0
ENSG00000008324 144 144
     matches 144, differences 0
ENSG00000008952 5 5
     matches 5, differences 0
ENSG00000008988 273 273
     matches 273, differences 0
ENSG00000009413 101 101
     matches 101, differences 0
ENSG00000010072 139 139
     matches 139, differences 0
ENSG00000010244 283 283
     matches 283, differences 0
ENSG00000010256 316 316
     matches 316, differences 0
ENSG00000010292 48 48
     matches 48, differences 0
ENSG00000010322 144 144
     matches 144, differences 0
ENSG00000011260 77 77
     matches 77, differences 0
ENSG00000011304 152 152
     matches 152, differences 0
ENSG00000011376 149 149
     matches 149, differences 0
ENSG00000011426 96 96
     matches 96, differences 0
ENSG00000011523 68 68
     matches 68, differences 0
ENSG00000012048 104 104
     matches 104, differences 0
ENSG00000012174 214 214
     matches 214, differences 0
ENSG00000013275 242 242
     matches 242, differences 0
ENSG00000013503 113 113
     matches 113, differences 0
ENSG00000013561 240 240
     matches 240, differences 0
ENSG00000013573 128 128
     matches 128, differences 0
ENSG00000013810 132 132
     matches 132, differences 0
ENSG00000014123 162 162
     matches 162, differences 0
ENSG00000014138 234 234
     matches 234, differences 0
ENSG00000014919 103 103
     matches 103, differences 0
ENSG00000015676 112 112
     matches 112, differences 0
ENSG00000018699 89 89
     matches 89, differences 0
ENSG00000020426 85 85
     matches 85, differences 0
ENSG00000021776 90 90
     matches 90, differences 0
ENSG00000023608 96 96
     matches 96, differences 0
ENSG00000023734 106 106
     matches 106, differences 0
ENSG00000025770 143 143
     matches 143, differences 0
ENSG00000025796 78 78
     matches 78, differences 0
ENSG00000025800 78 78
     matches 78, differences 0
ENSG00000027001 90 90
     matches 90, differences 0
ENSG00000028203 204 204
     matches 204, differences 0
ENSG00000029363 51 51
     matches 51, differences 0
ENSG00000029364 752 752
     matches 752, differences 0
ENSG00000030066 291 291
     matches 291, differences 0
ENSG00000031698 28 28
     matches 28, differences 0
ENSG00000033011 69 69
     matches 69, differences 0
ENSG00000033327 674 674
     matches 674, differences 0
ENSG00000034510 228 228
     matches 228, differences 0
ENSG00000035141 50 50
     matches 50, differences 0
ENSG00000035928 149 149
     matches 149, differences 0
ENSG00000036257 120 120
     matches 120, differences 0
ENSG00000037241 148 148
     matches 148, differences 0
ENSG00000037897 208 208
     matches 208, differences 0
ENSG00000038358 166 166
     matches 166, differences 0
ENSG00000039650 185 185
     matches 185, differences 0
ENSG00000040275 88 88
     matches 88, differences 0
ENSG00000041357 388 388
     matches 388, differences 0
ENSG00000041802 116 116
     matches 116, differences 0
ENSG00000042429 151 151
     matches 151, differences 0
ENSG00000042753 123 123
     matches 123, differences 0
ENSG00000044090 33 33
     matches 33, differences 0
ENSG00000044574 438 438
     matches 438, differences 0
ENSG00000046647 86 86
     matches 86, differences 0
ENSG00000047249 84 84
     matches 84, differences 0
ENSG00000047315 320 320
     matches 320, differences 0
ENSG00000047410 77 77
     matches 77, differences 0
ENSG00000048162 149 149
     matches 149, differences 0
ENSG00000048544 121 121
     matches 121, differences 0
ENSG00000048707 140 140
     matches 140, differences 0
ENSG00000049541 97 97
     matches 97, differences 0
ENSG00000050820 246 246
     matches 246, differences 0
ENSG00000051180 241 241
     matches 241, differences 0
ENSG00000051596 147 147
     matches 147, differences 0
ENSG00000052749 204 204
     matches 204, differences 0
ENSG00000053372 83 83
     matches 83, differences 0
ENSG00000053900 63 63
     matches 63, differences 0
ENSG00000054116 163 163
     matches 163, differences 0
ENSG00000055044 55 55
     matches 55, differences 0
ENSG00000055130 223 223
     matches 223, differences 0
ENSG00000055483 174 174
     matches 174, differences 0
ENSG00000055950 95 95
     matches 95, differences 0
ENSG00000058262 180 180
     matches 180, differences 0
ENSG00000058272 179 179
     matches 179, differences 0
ENSG00000058600 221 221
     matches 221, differences 0
ENSG00000058729 174 174
     matches 174, differences 0
ENSG00000058804 39 39
     matches 39, differences 0
ENSG00000060069 117 117
     matches 117, differences 0
ENSG00000060237 137 137
     matches 137, differences 0
ENSG00000060339 48 48
     matches 48, differences 0
ENSG00000060688 210 210
     matches 210, differences 0
ENSG00000061273 171 171
     matches 171, differences 0
ENSG00000061676 70 70
     matches 70, differences 0
ENSG00000061794 201 201
     matches 201, differences 0
ENSG00000061936 172 172
     matches 172, differences 0
ENSG00000062485 222 222
     matches 222, differences 0
ENSG00000062582 145 145
     matches 145, differences 0
ENSG00000062716 106 106
     matches 106, differences 0
ENSG00000062822 212 212
     matches 212, differences 0
ENSG00000063046 41 41
     matches 41, differences 0
ENSG00000063177 308 308
     matches 308, differences 0
ENSG00000063244 107 107
     matches 107, differences 0
ENSG00000063322 93 93
     matches 93, differences 0
ENSG00000063978 32 32
     matches 32, differences 0
ENSG00000064313 144 144
     matches 144, differences 0
ENSG00000064419 100 100
     matches 100, differences 0
ENSG00000064666 197 197
     matches 197, differences 0
ENSG00000064703 114 114
     matches 114, differences 0
ENSG00000065183 365 365
     matches 365, differences 0
ENSG00000065268 105 105
     matches 105, differences 0
ENSG00000065328 219 219
     matches 219, differences 0
ENSG00000065427 59 59
     matches 59, differences 0
ENSG00000065518 166 166
     matches 166, differences 0
ENSG00000065978 86 86
     matches 86, differences 0
ENSG00000066136 23 23
     matches 23, differences 0
ENSG00000066322 176 176
     matches 176, differences 0
ENSG00000066379 81 81
     matches 81, differences 0
ENSG00000066422 146 146
     matches 146, differences 0
ENSG00000067225 149 149
     matches 149, differences 0
ENSG00000067334 264 264
     matches 264, differences 0
ENSG00000067533 32 32
     matches 32, differences 0
ENSG00000067596 115 115
     matches 115, differences 0
ENSG00000067704 216 216
     matches 216, differences 0
ENSG00000068120 247 247
     matches 247, differences 0
ENSG00000068394 107 107
     matches 107, differences 0
ENSG00000068654 127 127
     matches 127, differences 0
ENSG00000068784 150 150
     matches 150, differences 0
ENSG00000069248 79 79
     matches 79, differences 0
ENSG00000069329 43 43
     matches 43, differences 0
ENSG00000069764 202 202
     matches 202, differences 0
ENSG00000070366 54 54
     matches 54, differences 0
ENSG00000070367 110 110
     matches 110, differences 0
ENSG00000070495 193 193
     matches 193, differences 0
ENSG00000070756 19 19
     matches 19, differences 0
ENSG00000070785 104 104
     matches 104, differences 0
ENSG00000070814 97 97
     matches 97, differences 0
ENSG00000070831 70 70
     matches 70, differences 0
ENSG00000071082 294 294
     matches 294, differences 0
ENSG00000071127 102 102
     matches 102, differences 0
ENSG00000071243 65 65
     matches 65, differences 0
ENSG00000071553 119 119
     matches 119, differences 0
ENSG00000071859 38 38
     matches 38, differences 0
ENSG00000071894 50 50
     matches 50, differences 0
ENSG00000071994 74 74
     matches 74, differences 0
ENSG00000072274 57 57
     matches 57, differences 0
ENSG00000072501 180 180
     matches 180, differences 0
ENSG00000072506 26 26
     matches 26, differences 0
ENSG00000072756 203 203
     matches 203, differences 0
ENSG00000072849 124 124
     matches 124, differences 0
ENSG00000073050 254 254
     matches 254, differences 0
ENSG00000073111 123 123
     matches 123, differences 0
ENSG00000073536 413 413
     matches 413, differences 0
ENSG00000073578 62 62
     matches 62, differences 0
ENSG00000073584 31 31
     matches 31, differences 0
ENSG00000073969 165 165
     matches 165, differences 0
ENSG00000074071 141 141
     matches 141, differences 0
ENSG00000074201 53 53
     matches 53, differences 0
ENSG00000074319 87 87
     matches 87, differences 0
ENSG00000074582 70 70
     matches 70, differences 0
ENSG00000074800 70 70
     matches 70, differences 0
ENSG00000074935 134 134
     matches 134, differences 0
ENSG00000075089 108 108
     matches 108, differences 0
ENSG00000075131 109 109
     matches 109, differences 0
ENSG00000075415 114 114
     matches 114, differences 0
ENSG00000075624 168 168
     matches 168, differences 0
ENSG00000075856 154 154
     matches 154, differences 0
ENSG00000075886 69 69
     matches 69, differences 0
ENSG00000075914 113 113
     matches 113, differences 0
ENSG00000076003 102 102
     matches 102, differences 0
ENSG00000076043 79 79
     matches 79, differences 0
ENSG00000076201 140 140
     matches 140, differences 0
ENSG00000076924 153 153
     matches 153, differences 0
ENSG00000077235 160 160
     matches 160, differences 0
ENSG00000077348 41 41
     matches 41, differences 0
ENSG00000077380 300 300
     matches 300, differences 0
ENSG00000077514 68 68
     matches 68, differences 0
ENSG00000077549 83 83
     matches 83, differences 0
ENSG00000078142 115 115
     matches 115, differences 0
ENSG00000079134 38 38
     matches 38, differences 0
ENSG00000079246 88 88
     matches 88, differences 0
ENSG00000079785 101 101
     matches 101, differences 0
ENSG00000079805 12 12
     matches 12, differences 0
ENSG00000080603 194 194
     matches 194, differences 0
ENSG00000080819 101 101
     matches 101, differences 0
ENSG00000080823 123 123
     matches 123, differences 0
ENSG00000080986 214 214
     matches 214, differences 0
ENSG00000081307 102 102
     matches 102, differences 0
ENSG00000081665 177 177
     matches 177, differences 0
ENSG00000082068 30 30
     matches 30, differences 0
ENSG00000082515 96 96
     matches 96, differences 0
ENSG00000082516 133 133
     matches 133, differences 0
ENSG00000082898 207 207
     matches 207, differences 0
ENSG00000083093 97 97
     matches 97, differences 0
ENSG00000083520 43 43
     matches 43, differences 0
ENSG00000083635 63 63
     matches 63, differences 0
ENSG00000083845 144 144
     matches 144, differences 0
ENSG00000083896 237 237
     matches 237, differences 0
ENSG00000084072 46 46
     matches 46, differences 0
ENSG00000084090 117 117
     matches 117, differences 0
ENSG00000084463 312 312
     matches 312, differences 0
ENSG00000084623 61 61
     matches 61, differences 0
ENSG00000085415 60 60
     matches 60, differences 0
ENSG00000085721 39 39
     matches 39, differences 0
ENSG00000085840 530 530
     matches 530, differences 0
ENSG00000085872 67 67
     matches 67, differences 0
ENSG00000086061 292 292
     matches 292, differences 0
ENSG00000086065 110 110
     matches 110, differences 0
ENSG00000086189 94 94
     matches 94, differences 0
ENSG00000086200 72 72
     matches 72, differences 0
ENSG00000086504 52 52
     matches 52, differences 0
ENSG00000086589 5 5
     matches 5, differences 0
ENSG00000086598 137 137
     matches 137, differences 0
ENSG00000086758 94 94
     matches 94, differences 0
ENSG00000086827 200 200
     matches 200, differences 0
ENSG00000087087 307 307
     matches 307, differences 0
ENSG00000087157 104 104
     matches 104, differences 0
ENSG00000087191 17 17
     matches 17, differences 0
ENSG00000087263 114 114
     matches 114, differences 0
ENSG00000087269 47 47
     matches 47, differences 0
ENSG00000087365 500 500
     matches 500, differences 0
ENSG00000087470 168 168
     matches 168, differences 0
ENSG00000087586 58 58
     matches 58, differences 0
ENSG00000088038 332 332
     matches 332, differences 0
ENSG00000088205 137 137
     matches 137, differences 0
ENSG00000088325 361 361
     matches 361, differences 0
ENSG00000088356 116 116
     matches 116, differences 0
ENSG00000088766 111 111
     matches 111, differences 0
ENSG00000088930 66 66
     matches 66, differences 0
ENSG00000088986 71 71
     matches 71, differences 0
ENSG00000089009 273 273
     matches 273, differences 0
ENSG00000089048 149 149
     matches 149, differences 0
ENSG00000089053 40 40
     matches 40, differences 0
ENSG00000089157 184 184
     matches 184, differences 0
ENSG00000089159 161 161
     matches 161, differences 0
ENSG00000089195 114 114
     matches 114, differences 0
ENSG00000089289 281 281
     matches 281, differences 0
ENSG00000089685 46 46
     matches 46, differences 0
ENSG00000089737 286 286
     matches 286, differences 0
ENSG00000089902 35 35
     matches 35, differences 0
ENSG00000090054 28 28
     matches 28, differences 0
ENSG00000090061 327 327
     matches 327, differences 0
ENSG00000090273 117 117
     matches 117, differences 0
ENSG00000090470 99 99
     matches 99, differences 0
ENSG00000090861 40 40
     matches 40, differences 0
ENSG00000090889 129 129
     matches 129, differences 0
ENSG00000090989 182 182
     matches 182, differences 0
ENSG00000091140 311 311
     matches 311, differences 0
ENSG00000091157 103 103
     matches 103, differences 0
ENSG00000091651 81 81
     matches 81, differences 0
ENSG00000092010 121 121
     matches 121, differences 0
ENSG00000092020 52 52
     matches 52, differences 0
ENSG00000092036 189 189
     matches 189, differences 0
ENSG00000092094 70 70
     matches 70, differences 0
ENSG00000092108 152 152
     matches 152, differences 0
ENSG00000092148 130 130
     matches 130, differences 0
ENSG00000092199 334 334
     matches 334, differences 0
ENSG00000092201 93 93
     matches 93, differences 0
ENSG00000092330 76 76
     matches 76, differences 0
ENSG00000092439 128 128
     matches 128, differences 0
ENSG00000092853 134 134
     matches 134, differences 0
ENSG00000092871 7 7
     matches 7, differences 0
ENSG00000093009 92 92
     matches 92, differences 0
ENSG00000094804 192 192
     matches 192, differences 0
ENSG00000094880 177 177
     matches 177, differences 0
ENSG00000094914 212 212
     matches 212, differences 0
ENSG00000095059 66 66
     matches 66, differences 0
ENSG00000095139 333 333
     matches 333, differences 0
ENSG00000095787 162 162
     matches 162, differences 0
ENSG00000095906 153 153
     matches 153, differences 0
ENSG00000096080 121 121
     matches 121, differences 0
ENSG00000096401 99 99
     matches 99, differences 0
ENSG00000097046 95 95
     matches 95, differences 0
ENSG00000099194 24 24
     matches 24, differences 0
ENSG00000099246 43 43
     matches 43, differences 0
ENSG00000099326 128 128
     matches 128, differences 0
ENSG00000099341 22 22
     matches 22, differences 0
ENSG00000099381 69 69
     matches 69, differences 0
ENSG00000099783 258 258
     matches 258, differences 0
ENSG00000099795 74 74
     matches 74, differences 0
ENSG00000099800 178 178
     matches 178, differences 0
ENSG00000099817 225 225
     matches 225, differences 0
ENSG00000099821 214 214
     matches 214, differences 0
ENSG00000099942 120 120
     matches 120, differences 0
ENSG00000099956 182 182
     matches 182, differences 0
ENSG00000099995 332 332
     matches 332, differences 0
ENSG00000100023 130 130
     matches 130, differences 0
ENSG00000100027 72 72
     matches 72, differences 0
ENSG00000100028 182 182
     matches 182, differences 0
ENSG00000100029 65 65
     matches 65, differences 0
ENSG00000100033 379 379
     matches 379, differences 0
ENSG00000100084 341 341
     matches 341, differences 0
ENSG00000100109 61 61
     matches 61, differences 0
ENSG00000100129 57 57
     matches 57, differences 0
ENSG00000100142 337 337
     matches 337, differences 0
ENSG00000100209 86 86
     matches 86, differences 0
ENSG00000100216 104 104
     matches 104, differences 0
ENSG00000100220 171 171
     matches 171, differences 0
ENSG00000100296 32 32
     matches 32, differences 0
ENSG00000100297 90 90
     matches 90, differences 0
ENSG00000100316 1996 1996
     matches 1996, differences 0
ENSG00000100319 100 100
     matches 100, differences 0
ENSG00000100347 102 102
     matches 102, differences 0
ENSG00000100353 186 186
     matches 186, differences 0
ENSG00000100387 57 57
     matches 57, differences 0
ENSG00000100401 130 130
     matches 130, differences 0
ENSG00000100410 231 231
     matches 231, differences 0
ENSG00000100413 109 109
     matches 109, differences 0
ENSG00000100462 127 127
     matches 127, differences 0
ENSG00000100479 56 56
     matches 56, differences 0
ENSG00000100519 151 151
     matches 151, differences 0
ENSG00000100522 112 112
     matches 112, differences 0
ENSG00000100554 139 139
     matches 139, differences 0
ENSG00000100564 85 85
     matches 85, differences 0
ENSG00000100567 372 372
     matches 372, differences 0
ENSG00000100575 201 201
     matches 201, differences 0
ENSG00000100603 226 226
     matches 226, differences 0
ENSG00000100632 86 86
     matches 86, differences 0
ENSG00000100664 175 175
     matches 175, differences 0
ENSG00000100697 158 158
     matches 158, differences 0
ENSG00000100726 74 74
     matches 74, differences 0
ENSG00000100764 316 316
     matches 316, differences 0
ENSG00000100804 270 270
     matches 270, differences 0
ENSG00000100811 82 82
     matches 82, differences 0
ENSG00000100813 191 191
     matches 191, differences 0
ENSG00000100836 148 148
     matches 148, differences 0
ENSG00000100865 78 78
     matches 78, differences 0
ENSG00000100883 81 81
     matches 81, differences 0
ENSG00000100890 42 42
     matches 42, differences 0
ENSG00000100902 40 40
     matches 40, differences 0
ENSG00000100911 151 151
     matches 151, differences 0
ENSG00000100941 86 86
     matches 86, differences 0
ENSG00000100949 116 116
     matches 116, differences 0
ENSG00000101003 186 186
     matches 186, differences 0
ENSG00000101057 106 106
     matches 106, differences 0
ENSG00000101132 34 34
     matches 34, differences 0
ENSG00000101138 141 141
     matches 141, differences 0
ENSG00000101146 59 59
     matches 59, differences 0
ENSG00000101158 201 201
     matches 201, differences 0
ENSG00000101161 232 232
     matches 232, differences 0
ENSG00000101166 273 273
     matches 273, differences 0
ENSG00000101181 146 146
     matches 146, differences 0
ENSG00000101182 41 41
     matches 41, differences 0
ENSG00000101189 74 74
     matches 74, differences 0
ENSG00000101246 138 138
     matches 138, differences 0
ENSG00000101343 261 261
     matches 261, differences 0
ENSG00000101361 99 99
     matches 99, differences 0
ENSG00000101407 151 151
     matches 151, differences 0
ENSG00000101421 71 71
     matches 71, differences 0
ENSG00000101444 147 147
     matches 147, differences 0
ENSG00000101639 202 202
     matches 202, differences 0
ENSG00000101654 114 114
     matches 114, differences 0
ENSG00000101773 117 117
     matches 117, differences 0
ENSG00000101868 230 230

## Unused Cells

In [13]:
control_cells_used = set()
for condition in conditions:
    control_cells_used = control_cells_used.union(set(control_cells_ids_filtered[condition].keys()))
    control_cells_used = control_cells_used.union(set(control_cells_ids_filtered[condition].values()))

In [14]:
all_cells = set(adata_filtered.obs_names)

In [15]:
len(all_cells), len(control_cells_used)

(310385, 310281)

In [16]:
control_cells_used.issubset(all_cells)

True

In [17]:
unused_cell_ids = all_cells.difference(control_cells_used)

In [18]:
unused_cells = adata_filtered.obs.loc[list(unused_cell_ids)]

In [19]:
unused_cells.condition.astype(str).unique()

array(['non-targeting'], dtype=object)

In [20]:
unused_cells

,gem_group,condition_name,condition,transcript,gene_transcript,sgID_AB,mitopercent,UMI_count,z_gemgroup_UMI,core_scale_factor,core_adjusted_UMI_count
cell_barcode,,,,,,,,,,,
TCCACGTGTCATCACA-26,26,non-targeting,non-targeting,non-targeting,11179_non-targeting_non-targeting_non-targeting,non-targeting_02787|non-targeting_01465,0.098578,18777.0,1.571038,0.901381,20831.373047
GGGACTCTCACCTCTG-25,25,non-targeting,non-targeting,non-targeting,10772_non-targeting_non-targeting_non-targeting,non-targeting_00166|non-targeting_02207,0.119748,12877.0,0.203468,0.855594,15050.363281
CCATAAGTCGACGACC-6,6,non-targeting,non-targeting,non-targeting,10822_non-targeting_non-targeting_non-targeting,non-targeting_00442|non-targeting_01312,0.078876,12995.0,-0.127853,0.954127,13619.778320
CCACGAGCATTCTCTA-19,19,non-targeting,non-targeting,non-targeting,10884_non-targeting_non-targeting_non-targeting,non-targeting_00807|non-targeting_02911,0.080580,17523.0,0.372891,1.123384,15598.401367
TTGAACGAGAGTATAC-8,8,non-targeting,non-targeting,non-targeting,10859_non-targeting_non-targeting_non-targeting,non-targeting_00652|non-targeting_02540,0.086616,18634.0,1.354366,0.950474,19604.958984
...,...,...,...,...,...,...,...,...,...,...,...
AATTTCCTCCGAAGGA-12,12,non-targeting,non-targeting,non-targeting,10882_non-targeting_non-targeting_non-targeting,non-targeting_00799|non-targeting_00833,0.093719,13978.0,-0.502728,1.232812,11338.302734
TACCGGGCATGTTCGA-34,34,non-targeting,non-targeting,non-targeting,10872_non-targeting_non-targeting_non-targeting,non-targeting_00702|non-targeting_02833,0.106195,15029.0,-0.047092,1.091537,13768.660156
CATCGTCTCGTTACCC-12,12,non-targeting,non-targeting,non-targeting,11023_non-targeting_non-targeting_non-targeting,non-targeting_01798|non-targeting_01119,0.114911,15525.0,-0.266281,1.232812,12593.157227
GCCAGGTGTAGCCCTG-43,43,non-targeting,non-targeting,non-targeting,11267_non-targeting_non-targeting_non-targeting,non-targeting_03441|non-targeting_00663,0.154688,10964.0,-0.570439,0.948277,11562.016602
CTTCAATAGTCGCCCA-31,31,non-targeting,non-targeting,non-targeting,11290_non-targeting_non-targeting_non-targeting,non-targeting_03530|non-targeting_01407,0.086622,12491.0,0.173189,0.844107,14797.893555

## Prototype Algorithm

In [32]:
n_nonzero_genes = (adata_filtered.X > 0).sum(axis=1)
if not isinstance(n_nonzero_genes, np.ndarray):
    n_nonzero_genes = n_nonzero_genes.toarray()

adata_filtered.obs['n_nonzero_genes'] = n_nonzero_genes
assert (adata_filtered.obs['UMI_count'] >= adata_filtered.obs['n_nonzero_genes']).all()

adata_filtered.obs[['UMI_count', 'n_nonzero_genes']].head()

                     UMI_count  n_nonzero_genes
cell_barcode
AAACCCAAGAAATCCA-27    11438.0             3332
AAACCCAAGAACTTCC-31     5342.0             2192
AAACCCAAGAAGCCAC-34    17305.0             4002
AAACCCAAGAATAGTC-43    30244.0             5358
AAACCCAAGACAGCGT-28     8407.0             2944

In [28]:
assert (adata_filtered.obs['UMI_count'] >= adata_filtered.obs['n_nonzero_genes']).all()

In [30]:
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.neighbors import NearestNeighbors

In [36]:
obs.gem_group.unique()

array([27, 31, 34, 43, 28, 10, 19, 11, 32, 24, 42, 40, 44, 38, 12,  7, 20,
       14,  5, 22, 21, 23, 47, 18, 17,  1, 45, 25, 16, 33, 26, 39,  6,  9,
        2, 30,  3, 48,  8, 29, 46,  4, 36, 15, 41, 37, 35, 13])

In [34]:
obs = adata_filtered.obs
# ['UMI_count', 'n_nonzero_genes', 'gem_group', 'condition']

                     UMI_count  n_nonzero_genes  gem_group        condition
cell_barcode
AAACCCAAGAAATCCA-27    11438.0             3332         27  ENSG00000145414
AAACCCAAGAACTTCC-31     5342.0             2192         31  ENSG00000169679
AAACCCAAGAAGCCAC-34    17305.0             4002         34  ENSG00000198258
AAACCCAAGAATAGTC-43    30244.0             5358         43  ENSG00000171159
AAACCCAAGACAGCGT-28     8407.0             2944         28  ENSG00000100575

In [49]:
# n_nonzero_genes = (adata_filtered.X > 0).sum(axis=1)
# if not isinstance(n_nonzero_genes, np.ndarray):
#     n_nonzero_genes = n_nonzero_genes.toarray()

# adata_filtered.obs['n_nonzero_genes'] = n_nonzero_genes
# assert (adata_filtered.obs['UMI_count'] >= adata_filtered.obs['n_nonzero_genes']).all()

obs = adata_filtered.obs
    
condition_key = 'condition'
control_condition = "non-targeting"
condition_list = [x for x in obs[condition_key].unique() if x != control_condition]

grouper_key = 'gem_group'

control_mask = obs.condition == control_condition
control_cells = obs.loc[control_mask]
condition_cells = obs.loc[~control_mask]

condition = conditions[0]

gem_group = 4
control_ = control_cells.loc[control_cells[grouper_key] == gem_group, ['UMI_count', 'n_nonzero_genes']]
condition_ = condition_cells.loc[(condition_cells[condition_key] == condition) & (condition_cells[grouper_key] == gem_group), 
    ['UMI_count', 'n_nonzero_genes']]

print(control_.shape, condition_.shape)

(120, 2) (4, 2)

In [72]:
dist_matrix = pairwise_distances(condition_, control_)
dist_matrix.shape

(4, 120)

In [73]:
dist_matrix.argmin(axis=1)

array([ 83, 109,  57,  31])

In [74]:
dist_matrix.argsort(axis=1)[:, :10]

array([[ 83, 104,  61, 100,  90,  30,   1,  88,  95,  75],
       [109,   3,  75,  76,  95,  88,  57,   1,  90, 100],
       [ 57,  71,  27, 117,   3,  76,  29, 109,  46,  75],
       [ 31,   5,  58, 114,  93,  52,  30,  61,  83,   9]])

In [80]:
dist_matrix[:, dist_matrix.argmin(axis=1)]

array([[  39.2173431 , 1080.82375992, 1911.94168321, 2280.66591153],
       [1293.00618715,  240.01041644,  657.00076103, 3526.25410315],
       [2138.18334106, 1031.6559504 ,  195.2562419 , 4360.83719027],
       [1871.1988136 , 2959.44065661, 3807.16640036,  370.74249824]])

In [75]:

rows, cols = linear_sum_assignment(dist_matrix)

In [76]:
rows

array([0, 1, 2, 3])

In [64]:
cols

array([ 83, 109,  57,  31])

In [81]:
dist_matrix[rows, cols]

array([ 39.2173431 , 240.01041644, 195.2562419 , 370.74249824])

In [100]:
columns

['condition', 'gem_group', ['UMI_count', 'n_nonzero_genes']]

In [117]:
from collections import defaultdict
from scipy.optimize import linear_sum_assignment

# # Calculate number of non-zero genes
# n_nonzero_genes = (adata_filtered.X > 0).sum(axis=1)
# if not isinstance(n_nonzero_genes, np.ndarray):
#     n_nonzero_genes = n_nonzero_genes.toarray()

# adata_filtered.obs['n_nonzero_genes'] = n_nonzero_genes
# assert (adata_filtered.obs['UMI_count'] >= adata_filtered.obs['n_nonzero_genes']).all()

condition_key = 'condition'
group_key = 'gem_group'
dist_keys = ['UMI_count', 'n_nonzero_genes'] 
columns = [condition_key, group_key] + dist_keys
control_condition = "non-targeting"

obs = adata_filtered.obs[columns]

control_mask = obs.condition == control_condition
control_cells = obs.loc[control_mask]
treatment_cells = obs.loc[~control_mask]

control_cells_gem = {gem_group:df for gem_group,df in control_cells.groupby(group_key)}
control_cells_ids = defaultdict(dict)

for condition, treatment_cells_cond in treatment_cells.groupby(condition_key):
    for gem_group, treatment_cells_cond_group in treatment_cells_cond.groupby(group_key):
        control_ = control_cells_gem[gem_group][dist_keys]
        treatment_ = treatment_cells_cond_group[dist_keys]
        # print(f"{condition} {gem_group} {len(treatment_)} {len(control_)}")
        
        dist_matrix = pairwise_distances(treatment_, control_)
        treatment_indices, control_indices = linear_sum_assignment(dist_matrix)

        assert np.allclose(control_indices[treatment_indices], dist_matrix.argmin(axis=1))
        
        treatment_ids = treatment_.index[treatment_indices]
        control_ids = control_.index[control_indices]
        control_cells_ids[condition].update(dict(zip(treatment_ids, control_ids)))

# Can probably accelerate by inverting loop order
# Will run fewer pairwise distance calculations, albeit with memory increase
for gem_group, treatment_gem_group in treatment_cells.groupby(group_key):
    control_ = control_cells_gem[gem_group][dist_keys]
    treatment_ = treatment_gem_group[dist_keys]
    dist_matrix = pairwise_distances(treatment_, control_)
    
    for condition, treatment_gem_condition in treatment_gem_group.groupby(condition_key):
        treatment_indices, control_indices = linear_sum_assignment(dist_matrix[treatment_gem_condition.indexes])

        treatment_ids = treatment_.index[treatment_indices]
        control_ids = control_.index[control_indices]
        control_cells_ids[condition].update(dict(zip(treatment_ids, control_ids)))

AssertionError:

In [118]:
control_indices[treatment_indices]

array([156, 101, 106,  12, 138])

In [119]:
dist_matrix.argmin(axis=1)

array([156, 101, 106,  12, 156])

In [120]:
condition, gem_group

('ENSG00000001497', 39)

In [123]:
dist_matrix[treatment_indices, control_indices]

array([13.92838828, 75.42545989, 39.01281841, 84.8763807 , 92.84934033])

In [124]:
dist_matrix[treatment_indices, dist_matrix.argmin(axis=1)]

array([13.92838828, 75.42545989, 39.01281841, 84.8763807 , 82.29216245])

In [109]:
control_cells_ids['ENSG00000001497']

{'CCTCTCCAGCGTATGG-48': 'GTTGAACAGCTGACAG-48'}

In [110]:
control_cells_ids = defaultdict(dict)
control_cells_ids['b'].update({'a':5})
control_cells_ids['b'].update({'c':7})
control_cells_ids

defaultdict(dict, {'b': {'a': 5, 'c': 7}})

In [114]:
control_indices[treatment_indices]

array([ 74,  25, 167, 140])

In [115]:
dist_matrix.argmin(axis=1)

array([ 74,  25, 167, 140])

In [116]:
treatment_indices

array([0, 1, 2, 3])