In [1]:
import os
import scanpy as sc
import pandas as pd
import anndata as ad
import numpy as np
import matplotlib.pyplot as plt
import json

## Load Data

In [2]:
# filtered_data_path = "/data2/czbenchmarks/replogle2022/K562_essential_raw_singlecell_01.h5ad"
filtered_data_path = f"{os.environ['HOME']}/.cz-benchmarks/datasets/replogle_k562_essential_perturbpredict_de_results_control_cells_v1.h5ad"

adata_filtered = ad.read_h5ad(filtered_data_path, backed=None)
adata_filtered.obs = adata_filtered.obs.rename(columns={'gene_id':'condition', 'gene':'condition_name'})
adata_filtered.var = adata_filtered.var.rename(columns={'gene_name':'gene'})
adata_filtered.obs['condition'] = adata_filtered.obs['condition'].astype(str)

control_cells_ids_cr4_orig = adata_filtered.uns["control_cells_ids"]
control_cells_ids_cr4_orig.pop("non-targeting", None)

array([], dtype=float64)

In [3]:
cr4_data_path = (
    "/data2/czbenchmarks/replogle2022/raw_h5ad_from_cr4/K562_essential_mtx.h5ad"
)
adata_cr4 = ad.read_h5ad(cr4_data_path, backed=None)
adata_cr4.var.index.name = "gene_id"
adata_cr4.var.rename(columns={"gene_name": "gene"}, inplace=True)
adata_cr4.obs.rename(columns={"gene_id": "condition"}, inplace=True)

In [4]:
with open("/data2/czbenchmarks/control_cells_ids_replogle_k562_essential_perturbpredict.json", "r") as f:
    control_cells_ids_filtered = json.load(f) # filtered data

with open("/data2/czbenchmarks/control_cells_ids_replogle_k562_essential_perturbpredict_validate.json", "r") as f:
    control_cells_ids_cr4_validate = json.load(f) # cr4 data

## QC of Conditions

In [5]:
len(control_cells_ids_cr4_orig.keys()), len(control_cells_ids_filtered.keys()), len(control_cells_ids_cr4_validate.keys())

(2057, 2057, 2057)

In [6]:
set(control_cells_ids_filtered.keys()) == set(control_cells_ids_cr4_orig.keys()) == set(control_cells_ids_cr4_validate.keys())

True

In [7]:
set(control_cells_ids_filtered.keys()).issubset(set(control_cells_ids_cr4_orig.keys()))

True

In [8]:
set(control_cells_ids_cr4_validate.keys()).issubset(set(control_cells_ids_cr4_orig.keys()))

True

## QC of Matches

In [153]:
# conditions = list(control_cells_ids_filtered.keys())
conditions = list(control_cells_ids_cr4_orig.keys())

# Old and new implementation fairly similar when both run on same dataset (cr4)
for condition in conditions:
    print(condition, len(control_cells_ids_cr4_orig[condition]), len(control_cells_ids_cr4_validate[condition]))
    assert len(control_cells_ids_cr4_orig[condition]) == len(control_cells_ids_cr4_validate[condition])
    
    matches = 0
    for pos, (val1, val2) in enumerate(zip(control_cells_ids_cr4_orig[condition], control_cells_ids_cr4_validate[condition].values())):
        if val1 == val2:
            matches += 1
    print(f"     matches {matches}, differences {len(control_cells_ids_cr4_orig[condition]) - matches}")

ENSG00000001497 83 83
     matches 83, differences 0
ENSG00000003509 18 18
     matches 18, differences 0
ENSG00000004779 160 160
     matches 159, differences 1
ENSG00000004897 366 366
     matches 364, differences 2
ENSG00000005007 131 131
     matches 131, differences 0
ENSG00000005100 140 140
     matches 140, differences 0
ENSG00000005175 18 18
     matches 18, differences 0
ENSG00000005194 151 151
     matches 151, differences 0
ENSG00000005448 208 208
     matches 206, differences 2
ENSG00000006634 131 131
     matches 130, differences 1
ENSG00000006695 94 94
     matches 94, differences 0
ENSG00000006712 238 238
     matches 235, differences 3
ENSG00000006715 332 332
     matches 331, differences 1
ENSG00000006744 85 85
     matches 85, differences 0
ENSG00000007168 126 126
     matches 123, differences 3
ENSG00000007866 267 267
     matches 265, differences 2
ENSG00000007923 46 46
     matches 46, differences 0
ENSG00000008018 143 143
     matches 141, differences 2
ENSG00000008128 269 269
     matches 263, differences 6
ENSG00000008324 144 144
     matches 144, differences 0
ENSG00000008952 5 5
     matches 5, differences 0
ENSG00000008988 273 273
     matches 273, differences 0
ENSG00000009413 101 101
     matches 100, differences 1
ENSG00000010072 139 139
     matches 136, differences 3
ENSG00000010244 283 283
     matches 280, differences 3
ENSG00000010256 316 316
     matches 312, differences 4
ENSG00000010292 48 48
     matches 48, differences 0
ENSG00000010322 144 144
     matches 143, differences 1
ENSG00000011260 77 77
     matches 77, differences 0
ENSG00000011304 152 152
     matches 152, differences 0
ENSG00000011376 149 149
     matches 149, differences 0
ENSG00000011426 96 96
     matches 96, differences 0
ENSG00000011523 68 68
     matches 67, differences 1
ENSG00000012048 104 104
     matches 103, differences 1
ENSG00000012174 214 214
     matches 210, differences 4
ENSG00000013275 242 242
     matches 242, differences 0
ENSG00000013503 113 113
     matches 113, differences 0
ENSG00000013561 240 240
     matches 239, differences 1
ENSG00000013573 128 128
     matches 127, differences 1
ENSG00000013810 132 132
     matches 132, differences 0
ENSG00000014123 162 162
     matches 159, differences 3
ENSG00000014138 234 234
     matches 234, differences 0
ENSG00000014919 103 103
     matches 102, differences 1
ENSG00000015676 112 112
     matches 111, differences 1
ENSG00000018699 89 89
     matches 89, differences 0
ENSG00000020426 85 85
     matches 84, differences 1
ENSG00000021776 90 90
     matches 90, differences 0
ENSG00000023608 96 96
     matches 96, differences 0
ENSG00000023734 106 106
     matches 105, differences 1
ENSG00000025770 143 143
     matches 142, differences 1
ENSG00000025796 78 78
     matches 78, differences 0
ENSG00000025800 78 78
     matches 78, differences 0
ENSG00000027001 90 90
     matches 89, differences 1
ENSG00000028203 204 204
     matches 204, differences 0
ENSG00000029363 51 51
     matches 50, differences 1
ENSG00000029364 752 752
     matches 741, differences 11
ENSG00000030066 291 291
     matches 290, differences 1
ENSG00000031698 28 28
     matches 28, differences 0
ENSG00000033011 69 69
     matches 68, differences 1
ENSG00000033327 674 674
     matches 670, differences 4
ENSG00000034510 228 228
     matches 228, differences 0
ENSG00000035141 50 50
     matches 50, differences 0
ENSG00000035928 149 149
     matches 147, differences 2
ENSG00000036257 120 120
     matches 118, differences 2
ENSG00000037241 148 148
     matches 147, differences 1
ENSG00000037897 208 208
     matches 208, differences 0
ENSG00000038358 166 166
     matches 166, differences 0
ENSG00000039650 185 185
     matches 182, differences 3
ENSG00000040275 88 88
     matches 88, differences 0
ENSG00000041357 388 388
     matches 382, differences 6
ENSG00000041802 116 116
     matches 116, differences 0
ENSG00000042429 151 151
     matches 151, differences 0
ENSG00000042753 123 123
     matches 121, differences 2
ENSG00000044090 33 33
     matches 33, differences 0
ENSG00000044574 438 438
     matches 436, differences 2
ENSG00000046647 86 86
     matches 85, differences 1
ENSG00000047249 84 84
     matches 83, differences 1
ENSG00000047315 320 320
     matches 319, differences 1
ENSG00000047410 77 77
     matches 76, differences 1
ENSG00000048162 149 149
     matches 149, differences 0
ENSG00000048544 121 121
     matches 121, differences 0
ENSG00000048707 140 140
     matches 140, differences 0
ENSG00000049541 97 97
     matches 97, differences 0
ENSG00000050820 246 246
     matches 243, differences 3
ENSG00000051180 241 241
     matches 240, differences 1
ENSG00000051596 147 147
     matches 145, differences 2
ENSG00000052749 204 204
     matches 202, differences 2
ENSG00000053372 83 83
     matches 82, differences 1
ENSG00000053900 63 63
     matches 61, differences 2
ENSG00000054116 163 163
     matches 161, differences 2
ENSG00000055044 55 55
     matches 55, differences 0
ENSG00000055130 223 223
     matches 222, differences 1
ENSG00000055483 174 174
     matches 169, differences 5
ENSG00000055950 95 95
     matches 95, differences 0
ENSG00000058262 180 180
     matches 180, differences 0
ENSG00000058272 179 179
     matches 176, differences 3
ENSG00000058600 221 221
     matches 221, differences 0
ENSG00000058729 174 174
     matches 173, differences 1
ENSG00000058804 39 39
     matches 39, differences 0
ENSG00000060069 117 117
     matches 115, differences 2
ENSG00000060237 137 137
     matches 136, differences 1
ENSG00000060339 48 48
     matches 46, differences 2
ENSG00000060688 210 210
     matches 209, differences 1
ENSG00000061273 171 171
     matches 169, differences 2
ENSG00000061676 70 70
     matches 68, differences 2
ENSG00000061794 201 201
     matches 201, differences 0
ENSG00000061936 172 172
     matches 172, differences 0
ENSG00000062485 222 222
     matches 219, differences 3
ENSG00000062582 145 145
     matches 144, differences 1
ENSG00000062716 106 106
     matches 103, differences 3
ENSG00000062822 212 212
     matches 211, differences 1
ENSG00000063046 41 41
     matches 40, differences 1
ENSG00000063177 308 308
     matches 306, differences 2
ENSG00000063244 107 107
     matches 107, differences 0
ENSG00000063322 93 93
     matches 93, differences 0
ENSG00000063978 32 32
     matches 32, differences 0
ENSG00000064313 144 144
     matches 144, differences 0
ENSG00000064419 100 100
     matches 99, differences 1
ENSG00000064666 197 197
     matches 196, differences 1
ENSG00000064703 114 114
     matches 113, differences 1
ENSG00000065183 365 365
     matches 364, differences 1
ENSG00000065268 105 105
     matches 103, differences 2
ENSG00000065328 219 219
     matches 217, differences 2
ENSG00000065427 59 59
     matches 59, differences 0
ENSG00000065518 166 166
     matches 166, differences 0
ENSG00000065978 86 86
     matches 85, differences 1
ENSG00000066136 23 23
     matches 23, differences 0
ENSG00000066322 176 176
     matches 174, differences 2
ENSG00000066379 81 81
     matches 81, differences 0
ENSG00000066422 146 146
     matches 146, differences 0
ENSG00000067225 149 149
     matches 148, differences 1
ENSG00000067334 264 264
     matches 260, differences 4
ENSG00000067533 32 32
     matches 32, differences 0
ENSG00000067596 115 115
     matches 115, differences 0
ENSG00000067704 216 216
     matches 215, differences 1
ENSG00000068120 247 247
     matches 247, differences 0
ENSG00000068394 107 107
     matches 105, differences 2
ENSG00000068654 127 127
     matches 127, differences 0
ENSG00000068784 150 150
     matches 150, differences 0
ENSG00000069248 79 79
     matches 79, differences 0
ENSG00000069329 43 43
     matches 43, differences 0
ENSG00000069764 202 202
     matches 200, differences 2
ENSG00000070366 54 54
     matches 54, differences 0
ENSG00000070367 110 110
     matches 109, differences 1
ENSG00000070495 193 193
     matches 191, differences 2
ENSG00000070756 19 19
     matches 19, differences 0
ENSG00000070785 104 104
     matches 104, differences 0
ENSG00000070814 97 97
     matches 97, differences 0
ENSG00000070831 70 70
     matches 70, differences 0
ENSG00000071082 294 294
     matches 290, differences 4
ENSG00000071127 102 102
     matches 102, differences 0
ENSG00000071243 65 65
     matches 64, differences 1
ENSG00000071553 119 119
     matches 118, differences 1
ENSG00000071859 38 38
     matches 38, differences 0
ENSG00000071894 50 50
     matches 49, differences 1
ENSG00000071994 74 74
     matches 74, differences 0
ENSG00000072274 57 57
     matches 57, differences 0
ENSG00000072501 180 180
     matches 178, differences 2
ENSG00000072506 26 26
     matches 26, differences 0
ENSG00000072756 203 203
     matches 200, differences 3
ENSG00000072849 124 124
     matches 122, differences 2
ENSG00000073050 254 254
     matches 253, differences 1
ENSG00000073111 123 123
     matches 120, differences 3
ENSG00000073536 413 413
     matches 411, differences 2
ENSG00000073578 62 62
     matches 62, differences 0
ENSG00000073584 31 31
     matches 31, differences 0
ENSG00000073969 165 165
     matches 165, differences 0
ENSG00000074071 141 141
     matches 139, differences 2
ENSG00000074201 53 53
     matches 52, differences 1
ENSG00000074319 87 87
     matches 86, differences 1
ENSG00000074582 70 70
     matches 70, differences 0
ENSG00000074800 70 70
     matches 70, differences 0
ENSG00000074935 134 134
     matches 132, differences 2
ENSG00000075089 108 108
     matches 108, differences 0
ENSG00000075131 109 109
     matches 109, differences 0
ENSG00000075415 114 114
     matches 113, differences 1
ENSG00000075624 168 168
     matches 165, differences 3
ENSG00000075856 154 154
     matches 151, differences 3
ENSG00000075886 69 69
     matches 69, differences 0
ENSG00000075914 113 113
     matches 113, differences 0
ENSG00000076003 102 102
     matches 101, differences 1
ENSG00000076043 79 79
     matches 78, differences 1
ENSG00000076201 140 140
     matches 140, differences 0
ENSG00000076924 153 153
     matches 153, differences 0
ENSG00000077235 160 160
     matches 160, differences 0
ENSG00000077348 41 41
     matches 40, differences 1
ENSG00000077380 300 300
     matches 299, differences 1
ENSG00000077514 68 68
     matches 68, differences 0
ENSG00000077549 83 83
     matches 81, differences 2
ENSG00000078142 115 115
     matches 115, differences 0
ENSG00000079134 38 38
     matches 38, differences 0
ENSG00000079246 88 88
     matches 88, differences 0
ENSG00000079785 101 101
     matches 99, differences 2
ENSG00000079805 12 12
     matches 11, differences 1
ENSG00000080603 194 194
     matches 192, differences 2
ENSG00000080819 101 101
     matches 99, differences 2
ENSG00000080823 123 123
     matches 122, differences 1
ENSG00000080986 214 214
     matches 213, differences 1
ENSG00000081307 102 102
     matches 102, differences 0
ENSG00000081665 177 177
     matches 175, differences 2
ENSG00000082068 30 30
     matches 30, differences 0
ENSG00000082515 96 96
     matches 95, differences 1
ENSG00000082516 133 133
     matches 133, differences 0
ENSG00000082898 207 207
     matches 204, differences 3
ENSG00000083093 97 97
     matches 95, differences 2
ENSG00000083520 43 43
     matches 43, differences 0
ENSG00000083635 63 63
     matches 63, differences 0
ENSG00000083845 144 144
     matches 141, differences 3
ENSG00000083896 237 237
     matches 236, differences 1
ENSG00000084072 46 46
     matches 46, differences 0
ENSG00000084090 117 117
     matches 117, differences 0
ENSG00000084463 312 312
     matches 309, differences 3
ENSG00000084623 61 61
     matches 61, differences 0
ENSG00000085415 60 60
     matches 60, differences 0
ENSG00000085721 39 39
     matches 39, differences 0
ENSG00000085840 530 530
     matches 528, differences 2
ENSG00000085872 67 67
     matches 67, differences 0
ENSG00000086061 292 292
     matches 289, differences 3
ENSG00000086065 110 110
     matches 109, differences 1
ENSG00000086189 94 94
     matches 94, differences 0
ENSG00000086200 72 72
     matches 72, differences 0
ENSG00000086504 52 52
     matches 52, differences 0
ENSG00000086589 5 5
     matches 5, differences 0
ENSG00000086598 137 137
     matches 131, differences 6
ENSG00000086758 94 94
     matches 94, differences 0
ENSG00000086827 200 200
     matches 198, differences 2
ENSG00000087087 307 307
     matches 303, differences 4
ENSG00000087157 104 104
     matches 102, differences 2
ENSG00000087191 17 17
     matches 17, differences 0
ENSG00000087263 114 114
     matches 112, differences 2
ENSG00000087269 47 47
     matches 47, differences 0
ENSG00000087365 500 500
     matches 497, differences 3
ENSG00000087470 168 168
     matches 167, differences 1
ENSG00000087586 58 58
     matches 57, differences 1
ENSG00000088038 332 332
     matches 332, differences 0
ENSG00000088205 137 137
     matches 135, differences 2
ENSG00000088325 361 361
     matches 357, differences 4
ENSG00000088356 116 116
     matches 115, differences 1
ENSG00000088766 111 111
     matches 108, differences 3
ENSG00000088930 66 66
     matches 65, differences 1
ENSG00000088986 71 71
     matches 71, differences 0
ENSG00000089009 273 273
     matches 271, differences 2
ENSG00000089048 149 149
     matches 148, differences 1
ENSG00000089053 40 40
     matches 39, differences 1
ENSG00000089157 184 184
     matches 184, differences 0
ENSG00000089159 161 161
     matches 160, differences 1
ENSG00000089195 114 114
     matches 112, differences 2
ENSG00000089289 281 281
     matches 281, differences 0
ENSG00000089685 46 46
     matches 46, differences 0
ENSG00000089737 286 286
     matches 280, differences 6
ENSG00000089902 35 35
     matches 35, differences 0
ENSG00000090054 28 28
     matches 28, differences 0
ENSG00000090061 327 327
     matches 323, differences 4
ENSG00000090273 117 117
     matches 116, differences 1
ENSG00000090470 99 99
     matches 99, differences 0
ENSG00000090861 40 40
     matches 40, differences 0
ENSG00000090889 129 129
     matches 127, differences 2
ENSG00000090989 182 182
     matches 180, differences 2
ENSG00000091140 311 311
     matches 307, differences 4
ENSG00000091157 103 103
     matches 101, differences 2
ENSG00000091651 81 81
     matches 81, differences 0
ENSG00000092010 121 121
     matches 121, differences 0
ENSG00000092020 52 52
     matches 50, differences 2
ENSG00000092036 189 189
     matches 187, differences 2
ENSG00000092094 70 70
     matches 69, differences 1
ENSG00000092108 152 152
     matches 149, differences 3
ENSG00000092148 130 130
     matches 127, differences 3
ENSG00000092199 334 334
     matches 332, differences 2
ENSG00000092201 93 93
     matches 93, differences 0
ENSG00000092330 76 76
     matches 76, differences 0
ENSG00000092439 128 128
     matches 127, differences 1
ENSG00000092853 134 134
     matches 132, differences 2
ENSG00000092871 7 7
     matches 7, differences 0
ENSG00000093009 92 92
     matches 92, differences 0
ENSG00000094804 192 192
     matches 190, differences 2
ENSG00000094880 177 177
     matches 176, differences 1
ENSG00000094914 212 212
     matches 212, differences 0
ENSG00000095059 66 66
     matches 66, differences 0
ENSG00000095139 333 333
     matches 328, differences 5
ENSG00000095787 162 162
     matches 161, differences 1
ENSG00000095906 153 153
     matches 153, differences 0
ENSG00000096080 121 121
     matches 120, differences 1
ENSG00000096401 99 99
     matches 99, differences 0
ENSG00000097046 95 95
     matches 95, differences 0
ENSG00000099194 24 24
     matches 24, differences 0
ENSG00000099246 43 43
     matches 42, differences 1
ENSG00000099326 128 128
     matches 128, differences 0
ENSG00000099341 22 22
     matches 21, differences 1
ENSG00000099381 69 69
     matches 69, differences 0
ENSG00000099783 258 258
     matches 255, differences 3
ENSG00000099795 74 74
     matches 73, differences 1
ENSG00000099800 178 178
     matches 173, differences 5
ENSG00000099817 225 225
     matches 224, differences 1
ENSG00000099821 214 214
     matches 212, differences 2
ENSG00000099942 120 120
     matches 120, differences 0
ENSG00000099956 182 182
     matches 182, differences 0
ENSG00000099995 332 332
     matches 328, differences 4
ENSG00000100023 130 130
     matches 130, differences 0
ENSG00000100027 72 72
     matches 70, differences 2
ENSG00000100028 182 182
     matches 182, differences 0
ENSG00000100029 65 65
     matches 64, differences 1
ENSG00000100033 379 379
     matches 376, differences 3
ENSG00000100084 341 341
     matches 340, differences 1
ENSG00000100109 61 61
     matches 61, differences 0
ENSG00000100129 57 57
     matches 57, differences 0
ENSG00000100142 337 337
     matches 336, differences 1
ENSG00000100209 86 86
     matches 85, differences 1
ENSG00000100216 104 104
     matches 104, differences 0
ENSG00000100220 171 171
     matches 170, differences 1
ENSG00000100296 32 32
     matches 32, differences 0
ENSG00000100297 90 90
     matches 88, differences 2
ENSG00000100316 1996 1996
     matches 1979, differences 17
ENSG00000100319 100 100
     matches 99, differences 1
ENSG00000100347 102 102
     matches 101, differences 1
ENSG00000100353 186 186
     matches 183, differences 3
ENSG00000100387 57 57
     matches 57, differences 0
ENSG00000100401 130 130
     matches 130, differences 0
ENSG00000100410 231 231
     matches 230, differences 1
ENSG00000100413 109 109
     matches 106, differences 3
ENSG00000100462 127 127
     matches 127, differences 0
ENSG00000100479 56 56
     matches 56, differences 0
ENSG00000100519 151 151
     matches 150, differences 1
ENSG00000100522 112 112
     matches 112, differences 0
ENSG00000100554 139 139
     matches 139, differences 0
ENSG00000100564 85 85
     matches 85, differences 0
ENSG00000100567 372 372
     matches 369, differences 3
ENSG00000100575 201 201
     matches 200, differences 1
ENSG00000100603 226 226
     matches 226, differences 0
ENSG00000100632 86 86
     matches 84, differences 2
ENSG00000100664 175 175
     matches 175, differences 0
ENSG00000100697 158 158
     matches 156, differences 2
ENSG00000100726 74 74
     matches 74, differences 0
ENSG00000100764 316 316
     matches 315, differences 1
ENSG00000100804 270 270
     matches 267, differences 3
ENSG00000100811 82 82
     matches 80, differences 2
ENSG00000100813 191 191
     matches 190, differences 1
ENSG00000100836 148 148
     matches 146, differences 2
ENSG00000100865 78 78
     matches 77, differences 1
ENSG00000100883 81 81
     matches 80, differences 1
ENSG00000100890 42 42
     matches 42, differences 0
ENSG00000100902 40 40
     matches 40, differences 0
ENSG00000100911 151 151
     matches 150, differences 1
ENSG00000100941 86 86
     matches 85, differences 1
ENSG00000100949 116 116
     matches 116, differences 0
ENSG00000101003 186 186
     matches 184, differences 2
ENSG00000101057 106 106
     matches 105, differences 1
ENSG00000101132 34 34
     matches 34, differences 0
ENSG00000101138 141 141
     matches 140, differences 1
ENSG00000101146 59 59
     matches 59, differences 0
ENSG00000101158 201 201
     matches 200, differences 1
ENSG00000101161 232 232
     matches 229, differences 3
ENSG00000101166 273 273
     matches 272, differences 1
ENSG00000101181 146 146
     matches 142, differences 4
ENSG00000101182 41 41
     matches 41, differences 0
ENSG00000101189 74 74
     matches 74, differences 0
ENSG00000101246 138 138
     matches 137, differences 1
ENSG00000101343 261 261
     matches 257, differences 4
ENSG00000101361 99 99
     matches 98, differences 1
ENSG00000101407 151 151
     matches 149, differences 2
ENSG00000101421 71 71
     matches 68, differences 3
ENSG00000101444 147 147
     matches 146, differences 1
ENSG00000101639 202 202
     matches 201, differences 1
ENSG00000101654 114 114
     matches 111, differences 3
ENSG00000101773 117 117
     matches 115, differences 2
ENSG00000101868 230 230

In [155]:
# Results are very different between old cr4 version and new filtered version
for condition in conditions:
    print(condition, len(control_cells_ids_cr4_orig[condition]), len(control_cells_ids_filtered[condition]))
    assert len(control_cells_ids_cr4_orig[condition]) == len(control_cells_ids_filtered[condition])
    
    matches = 0
    for pos, (val1, val2) in enumerate(zip(control_cells_ids_cr4_orig[condition], control_cells_ids_filtered[condition].values())):
        if val1 == val2:
            matches += 1
    print(f"     matches {matches}, differences {len(control_cells_ids_cr4_orig[condition]) - matches}")

ENSG00000001497 83 83
     matches 1, differences 82
ENSG00000003509 18 18
     matches 0, differences 18
ENSG00000004779 160 160
     matches 0, differences 160
ENSG00000004897 366 366
     matches 4, differences 362
ENSG00000005007 131 131
     matches 0, differences 131
ENSG00000005100 140 140
     matches 1, differences 139
ENSG00000005175 18 18
     matches 1, differences 17
ENSG00000005194 151 151
     matches 1, differences 150
ENSG00000005448 208 208
     matches 1, differences 207
ENSG00000006634 131 131
     matches 1, differences 130
ENSG00000006695 94 94
     matches 0, differences 94
ENSG00000006712 238 238
     matches 1, differences 237
ENSG00000006715 332 332
     matches 1, differences 331
ENSG00000006744 85 85
     matches 1, differences 84
ENSG00000007168 126 126
     matches 1, differences 125
ENSG00000007866 267 267
     matches 1, differences 266
ENSG00000007923 46 46
     matches 1, differences 45
ENSG00000008018 143 143
     matches 1, differences 142
ENSG00000008128 269 269
     matches 0, differences 269
ENSG00000008324 144 144
     matches 0, differences 144
ENSG00000008952 5 5
     matches 1, differences 4
ENSG00000008988 273 273
     matches 1, differences 272
ENSG00000009413 101 101
     matches 2, differences 99
ENSG00000010072 139 139
     matches 0, differences 139
ENSG00000010244 283 283
     matches 0, differences 283
ENSG00000010256 316 316
     matches 3, differences 313
ENSG00000010292 48 48
     matches 0, differences 48
ENSG00000010322 144 144
     matches 0, differences 144
ENSG00000011260 77 77
     matches 1, differences 76
ENSG00000011304 152 152
     matches 4, differences 148
ENSG00000011376 149 149
     matches 2, differences 147
ENSG00000011426 96 96
     matches 2, differences 94
ENSG00000011523 68 68
     matches 1, differences 67
ENSG00000012048 104 104
     matches 3, differences 101
ENSG00000012174 214 214
     matches 0, differences 214
ENSG00000013275 242 242
     matches 3, differences 239
ENSG00000013503 113 113
     matches 0, differences 113
ENSG00000013561 240 240
     matches 1, differences 239
ENSG00000013573 128 128
     matches 1, differences 127
ENSG00000013810 132 132
     matches 0, differences 132
ENSG00000014123 162 162
     matches 0, differences 162
ENSG00000014138 234 234
     matches 2, differences 232
ENSG00000014919 103 103
     matches 2, differences 101
ENSG00000015676 112 112
     matches 0, differences 112
ENSG00000018699 89 89
     matches 0, differences 89
ENSG00000020426 85 85
     matches 2, differences 83
ENSG00000021776 90 90
     matches 0, differences 90
ENSG00000023608 96 96
     matches 1, differences 95
ENSG00000023734 106 106
     matches 1, differences 105
ENSG00000025770 143 143
     matches 2, differences 141
ENSG00000025796 78 78
     matches 1, differences 77
ENSG00000025800 78 78
     matches 1, differences 77
ENSG00000027001 90 90
     matches 0, differences 90
ENSG00000028203 204 204
     matches 4, differences 200
ENSG00000029363 51 51
     matches 0, differences 51
ENSG00000029364 752 752
     matches 1, differences 751
ENSG00000030066 291 291
     matches 0, differences 291
ENSG00000031698 28 28
     matches 0, differences 28
ENSG00000033011 69 69
     matches 0, differences 69
ENSG00000033327 674 674
     matches 1, differences 673
ENSG00000034510 228 228
     matches 0, differences 228
ENSG00000035141 50 50
     matches 1, differences 49
ENSG00000035928 149 149
     matches 0, differences 149
ENSG00000036257 120 120
     matches 1, differences 119
ENSG00000037241 148 148
     matches 0, differences 148
ENSG00000037897 208 208
     matches 0, differences 208
ENSG00000038358 166 166
     matches 2, differences 164
ENSG00000039650 185 185
     matches 0, differences 185
ENSG00000040275 88 88
     matches 4, differences 84
ENSG00000041357 388 388
     matches 1, differences 387
ENSG00000041802 116 116
     matches 1, differences 115
ENSG00000042429 151 151
     matches 1, differences 150
ENSG00000042753 123 123
     matches 0, differences 123
ENSG00000044090 33 33
     matches 0, differences 33
ENSG00000044574 438 438
     matches 1, differences 437
ENSG00000046647 86 86
     matches 0, differences 86
ENSG00000047249 84 84
     matches 2, differences 82
ENSG00000047315 320 320
     matches 0, differences 320
ENSG00000047410 77 77
     matches 2, differences 75
ENSG00000048162 149 149
     matches 1, differences 148
ENSG00000048544 121 121
     matches 2, differences 119
ENSG00000048707 140 140
     matches 0, differences 140
ENSG00000049541 97 97
     matches 2, differences 95
ENSG00000050820 246 246
     matches 2, differences 244
ENSG00000051180 241 241
     matches 1, differences 240
ENSG00000051596 147 147
     matches 2, differences 145
ENSG00000052749 204 204
     matches 0, differences 204
ENSG00000053372 83 83
     matches 0, differences 83
ENSG00000053900 63 63
     matches 1, differences 62
ENSG00000054116 163 163
     matches 1, differences 162
ENSG00000055044 55 55
     matches 1, differences 54
ENSG00000055130 223 223
     matches 2, differences 221
ENSG00000055483 174 174
     matches 1, differences 173
ENSG00000055950 95 95
     matches 2, differences 93
ENSG00000058262 180 180
     matches 0, differences 180
ENSG00000058272 179 179
     matches 1, differences 178
ENSG00000058600 221 221
     matches 1, differences 220
ENSG00000058729 174 174
     matches 1, differences 173
ENSG00000058804 39 39
     matches 0, differences 39
ENSG00000060069 117 117
     matches 0, differences 117
ENSG00000060237 137 137
     matches 2, differences 135
ENSG00000060339 48 48
     matches 4, differences 44
ENSG00000060688 210 210
     matches 2, differences 208
ENSG00000061273 171 171
     matches 1, differences 170
ENSG00000061676 70 70
     matches 2, differences 68
ENSG00000061794 201 201
     matches 0, differences 201
ENSG00000061936 172 172
     matches 1, differences 171
ENSG00000062485 222 222
     matches 1, differences 221
ENSG00000062582 145 145
     matches 0, differences 145
ENSG00000062716 106 106
     matches 0, differences 106
ENSG00000062822 212 212
     matches 2, differences 210
ENSG00000063046 41 41
     matches 0, differences 41
ENSG00000063177 308 308
     matches 1, differences 307
ENSG00000063244 107 107
     matches 2, differences 105
ENSG00000063322 93 93
     matches 0, differences 93
ENSG00000063978 32 32
     matches 2, differences 30
ENSG00000064313 144 144
     matches 3, differences 141
ENSG00000064419 100 100
     matches 3, differences 97
ENSG00000064666 197 197
     matches 2, differences 195
ENSG00000064703 114 114
     matches 3, differences 111
ENSG00000065183 365 365
     matches 1, differences 364
ENSG00000065268 105 105
     matches 1, differences 104
ENSG00000065328 219 219
     matches 1, differences 218
ENSG00000065427 59 59
     matches 0, differences 59
ENSG00000065518 166 166
     matches 2, differences 164
ENSG00000065978 86 86
     matches 1, differences 85
ENSG00000066136 23 23
     matches 0, differences 23
ENSG00000066322 176 176
     matches 1, differences 175
ENSG00000066379 81 81
     matches 1, differences 80
ENSG00000066422 146 146
     matches 0, differences 146
ENSG00000067225 149 149
     matches 1, differences 148
ENSG00000067334 264 264
     matches 3, differences 261
ENSG00000067533 32 32
     matches 5, differences 27
ENSG00000067596 115 115
     matches 1, differences 114
ENSG00000067704 216 216
     matches 0, differences 216
ENSG00000068120 247 247
     matches 1, differences 246
ENSG00000068394 107 107
     matches 0, differences 107
ENSG00000068654 127 127
     matches 1, differences 126
ENSG00000068784 150 150
     matches 3, differences 147
ENSG00000069248 79 79
     matches 0, differences 79
ENSG00000069329 43 43
     matches 1, differences 42
ENSG00000069764 202 202
     matches 1, differences 201
ENSG00000070366 54 54
     matches 5, differences 49
ENSG00000070367 110 110
     matches 0, differences 110
ENSG00000070495 193 193
     matches 0, differences 193
ENSG00000070756 19 19
     matches 0, differences 19
ENSG00000070785 104 104
     matches 1, differences 103
ENSG00000070814 97 97
     matches 2, differences 95
ENSG00000070831 70 70
     matches 2, differences 68
ENSG00000071082 294 294
     matches 1, differences 293
ENSG00000071127 102 102
     matches 1, differences 101
ENSG00000071243 65 65
     matches 1, differences 64
ENSG00000071553 119 119
     matches 0, differences 119
ENSG00000071859 38 38
     matches 3, differences 35
ENSG00000071894 50 50
     matches 0, differences 50
ENSG00000071994 74 74
     matches 0, differences 74
ENSG00000072274 57 57
     matches 2, differences 55
ENSG00000072501 180 180
     matches 1, differences 179
ENSG00000072506 26 26
     matches 1, differences 25
ENSG00000072756 203 203
     matches 0, differences 203
ENSG00000072849 124 124
     matches 2, differences 122
ENSG00000073050 254 254
     matches 3, differences 251
ENSG00000073111 123 123
     matches 1, differences 122
ENSG00000073536 413 413
     matches 0, differences 413
ENSG00000073578 62 62
     matches 1, differences 61
ENSG00000073584 31 31
     matches 1, differences 30
ENSG00000073969 165 165
     matches 0, differences 165
ENSG00000074071 141 141
     matches 1, differences 140
ENSG00000074201 53 53
     matches 1, differences 52
ENSG00000074319 87 87
     matches 0, differences 87
ENSG00000074582 70 70
     matches 1, differences 69
ENSG00000074800 70 70
     matches 1, differences 69
ENSG00000074935 134 134
     matches 0, differences 134
ENSG00000075089 108 108
     matches 0, differences 108
ENSG00000075131 109 109
     matches 0, differences 109
ENSG00000075415 114 114
     matches 3, differences 111
ENSG00000075624 168 168
     matches 1, differences 167
ENSG00000075856 154 154
     matches 1, differences 153
ENSG00000075886 69 69
     matches 0, differences 69
ENSG00000075914 113 113
     matches 3, differences 110
ENSG00000076003 102 102
     matches 2, differences 100
ENSG00000076043 79 79
     matches 1, differences 78
ENSG00000076201 140 140
     matches 2, differences 138
ENSG00000076924 153 153
     matches 1, differences 152
ENSG00000077235 160 160
     matches 0, differences 160
ENSG00000077348 41 41
     matches 1, differences 40
ENSG00000077380 300 300
     matches 3, differences 297
ENSG00000077514 68 68
     matches 1, differences 67
ENSG00000077549 83 83
     matches 1, differences 82
ENSG00000078142 115 115
     matches 0, differences 115
ENSG00000079134 38 38
     matches 1, differences 37
ENSG00000079246 88 88
     matches 0, differences 88
ENSG00000079785 101 101
     matches 1, differences 100
ENSG00000079805 12 12
     matches 0, differences 12
ENSG00000080603 194 194
     matches 1, differences 193
ENSG00000080819 101 101
     matches 2, differences 99
ENSG00000080823 123 123
     matches 0, differences 123
ENSG00000080986 214 214
     matches 1, differences 213
ENSG00000081307 102 102
     matches 1, differences 101
ENSG00000081665 177 177
     matches 1, differences 176
ENSG00000082068 30 30
     matches 0, differences 30
ENSG00000082515 96 96
     matches 1, differences 95
ENSG00000082516 133 133
     matches 1, differences 132
ENSG00000082898 207 207
     matches 4, differences 203
ENSG00000083093 97 97
     matches 0, differences 97
ENSG00000083520 43 43
     matches 2, differences 41
ENSG00000083635 63 63
     matches 0, differences 63
ENSG00000083845 144 144
     matches 0, differences 144
ENSG00000083896 237 237
     matches 2, differences 235
ENSG00000084072 46 46
     matches 2, differences 44
ENSG00000084090 117 117
     matches 3, differences 114
ENSG00000084463 312 312
     matches 1, differences 311
ENSG00000084623 61 61
     matches 0, differences 61
ENSG00000085415 60 60
     matches 0, differences 60
ENSG00000085721 39 39
     matches 0, differences 39
ENSG00000085840 530 530
     matches 0, differences 530
ENSG00000085872 67 67
     matches 1, differences 66
ENSG00000086061 292 292
     matches 1, differences 291
ENSG00000086065 110 110
     matches 1, differences 109
ENSG00000086189 94 94
     matches 1, differences 93
ENSG00000086200 72 72
     matches 0, differences 72
ENSG00000086504 52 52
     matches 1, differences 51
ENSG00000086589 5 5
     matches 1, differences 4
ENSG00000086598 137 137
     matches 1, differences 136
ENSG00000086758 94 94
     matches 1, differences 93
ENSG00000086827 200 200
     matches 2, differences 198
ENSG00000087087 307 307
     matches 3, differences 304
ENSG00000087157 104 104
     matches 1, differences 103
ENSG00000087191 17 17
     matches 3, differences 14
ENSG00000087263 114 114
     matches 0, differences 114
ENSG00000087269 47 47
     matches 1, differences 46
ENSG00000087365 500 500
     matches 2, differences 498
ENSG00000087470 168 168
     matches 0, differences 168
ENSG00000087586 58 58
     matches 1, differences 57
ENSG00000088038 332 332
     matches 1, differences 331
ENSG00000088205 137 137
     matches 1, differences 136
ENSG00000088325 361 361
     matches 0, differences 361
ENSG00000088356 116 116
     matches 1, differences 115
ENSG00000088766 111 111
     matches 1, differences 110
ENSG00000088930 66 66
     matches 1, differences 65
ENSG00000088986 71 71
     matches 0, differences 71
ENSG00000089009 273 273
     matches 0, differences 273
ENSG00000089048 149 149
     matches 0, differences 149
ENSG00000089053 40 40
     matches 0, differences 40
ENSG00000089157 184 184
     matches 0, differences 184
ENSG00000089159 161 161
     matches 1, differences 160
ENSG00000089195 114 114
     matches 1, differences 113
ENSG00000089289 281 281
     matches 2, differences 279
ENSG00000089685 46 46
     matches 2, differences 44
ENSG00000089737 286 286
     matches 0, differences 286
ENSG00000089902 35 35
     matches 1, differences 34
ENSG00000090054 28 28
     matches 1, differences 27
ENSG00000090061 327 327
     matches 1, differences 326
ENSG00000090273 117 117
     matches 1, differences 116
ENSG00000090470 99 99
     matches 1, differences 98
ENSG00000090861 40 40
     matches 3, differences 37
ENSG00000090889 129 129
     matches 1, differences 128
ENSG00000090989 182 182
     matches 1, differences 181
ENSG00000091140 311 311
     matches 2, differences 309
ENSG00000091157 103 103
     matches 2, differences 101
ENSG00000091651 81 81
     matches 1, differences 80
ENSG00000092010 121 121
     matches 1, differences 120
ENSG00000092020 52 52
     matches 0, differences 52
ENSG00000092036 189 189
     matches 0, differences 189
ENSG00000092094 70 70
     matches 2, differences 68
ENSG00000092108 152 152
     matches 1, differences 151
ENSG00000092148 130 130
     matches 1, differences 129
ENSG00000092199 334 334
     matches 0, differences 334
ENSG00000092201 93 93
     matches 2, differences 91
ENSG00000092330 76 76
     matches 1, differences 75
ENSG00000092439 128 128
     matches 1, differences 127
ENSG00000092853 134 134
     matches 1, differences 133
ENSG00000092871 7 7
     matches 3, differences 4
ENSG00000093009 92 92
     matches 0, differences 92
ENSG00000094804 192 192
     matches 0, differences 192
ENSG00000094880 177 177
     matches 0, differences 177
ENSG00000094914 212 212
     matches 0, differences 212
ENSG00000095059 66 66
     matches 0, differences 66
ENSG00000095139 333 333
     matches 1, differences 332
ENSG00000095787 162 162
     matches 0, differences 162
ENSG00000095906 153 153
     matches 1, differences 152
ENSG00000096080 121 121
     matches 5, differences 116
ENSG00000096401 99 99
     matches 1, differences 98
ENSG00000097046 95 95
     matches 3, differences 92
ENSG00000099194 24 24
     matches 1, differences 23
ENSG00000099246 43 43
     matches 3, differences 40
ENSG00000099326 128 128
     matches 1, differences 127
ENSG00000099341 22 22
     matches 0, differences 22
ENSG00000099381 69 69
     matches 1, differences 68
ENSG00000099783 258 258
     matches 0, differences 258
ENSG00000099795 74 74
     matches 2, differences 72
ENSG00000099800 178 178
     matches 0, differences 178
ENSG00000099817 225 225
     matches 0, differences 225
ENSG00000099821 214 214
     matches 0, differences 214
ENSG00000099942 120 120
     matches 0, differences 120
ENSG00000099956 182 182
     matches 0, differences 182
ENSG00000099995 332 332
     matches 1, differences 331
ENSG00000100023 130 130
     matches 1, differences 129
ENSG00000100027 72 72
     matches 1, differences 71
ENSG00000100028 182 182
     matches 1, differences 181
ENSG00000100029 65 65
     matches 1, differences 64
ENSG00000100033 379 379
     matches 3, differences 376
ENSG00000100084 341 341
     matches 0, differences 341
ENSG00000100109 61 61
     matches 2, differences 59
ENSG00000100129 57 57
     matches 1, differences 56
ENSG00000100142 337 337
     matches 1, differences 336
ENSG00000100209 86 86
     matches 0, differences 86
ENSG00000100216 104 104
     matches 4, differences 100
ENSG00000100220 171 171
     matches 1, differences 170
ENSG00000100296 32 32
     matches 0, differences 32
ENSG00000100297 90 90
     matches 1, differences 89
ENSG00000100316 1996 1996
     matches 1, differences 1995
ENSG00000100319 100 100
     matches 2, differences 98
ENSG00000100347 102 102
     matches 0, differences 102
ENSG00000100353 186 186
     matches 0, differences 186
ENSG00000100387 57 57
     matches 2, differences 55
ENSG00000100401 130 130
     matches 2, differences 128
ENSG00000100410 231 231
     matches 1, differences 230
ENSG00000100413 109 109
     matches 0, differences 109
ENSG00000100462 127 127
     matches 0, differences 127
ENSG00000100479 56 56
     matches 1, differences 55
ENSG00000100519 151 151
     matches 0, differences 151
ENSG00000100522 112 112
     matches 0, differences 112
ENSG00000100554 139 139
     matches 1, differences 138
ENSG00000100564 85 85
     matches 3, differences 82
ENSG00000100567 372 372
     matches 0, differences 372
ENSG00000100575 201 201
     matches 1, differences 200
ENSG00000100603 226 226
     matches 1, differences 225
ENSG00000100632 86 86
     matches 1, differences 85
ENSG00000100664 175 175
     matches 0, differences 175
ENSG00000100697 158 158
     matches 0, differences 158
ENSG00000100726 74 74
     matches 0, differences 74
ENSG00000100764 316 316
     matches 0, differences 316
ENSG00000100804 270 270
     matches 2, differences 268
ENSG00000100811 82 82
     matches 0, differences 82
ENSG00000100813 191 191
     matches 0, differences 191
ENSG00000100836 148 148
     matches 1, differences 147
ENSG00000100865 78 78
     matches 2, differences 76
ENSG00000100883 81 81
     matches 0, differences 81
ENSG00000100890 42 42
     matches 0, differences 42
ENSG00000100902 40 40
     matches 0, differences 40
ENSG00000100911 151 151
     matches 0, differences 151
ENSG00000100941 86 86
     matches 1, differences 85
ENSG00000100949 116 116
     matches 1, differences 115
ENSG00000101003 186 186
     matches 2, differences 184
ENSG00000101057 106 106
     matches 0, differences 106
ENSG00000101132 34 34
     matches 0, differences 34
ENSG00000101138 141 141
     matches 1, differences 140
ENSG00000101146 59 59
     matches 1, differences 58
ENSG00000101158 201 201
     matches 3, differences 198
ENSG00000101161 232 232
     matches 2, differences 230
ENSG00000101166 273 273
     matches 0, differences 273
ENSG00000101181 146 146
     matches 0, differences 146
ENSG00000101182 41 41
     matches 1, differences 40
ENSG00000101189 74 74
     matches 2, differences 72
ENSG00000101246 138 138
     matches 2, differences 136
ENSG00000101343 261 261
     matches 1, differences 260
ENSG00000101361 99 99
     matches 0, differences 99
ENSG00000101407 151 151
     matches 0, differences 151
ENSG00000101421 71 71
     matches 1, differences 70
ENSG00000101444 147 147
     matches 1, differences 146
ENSG00000101639 202 202
     matches 0, differences 202
ENSG00000101654 114 114
     matches 0, differences 114
ENSG00000101773 117 117
     matches 0, differences 117
ENSG00000101868 230 230

In [23]:
# But the differences appear to be mostly because of sort order. There are still some unexplained issues with the original dictionary because differences of 1 can't be explained by sorting
for condition in conditions:
    print(condition, len(control_cells_ids_cr4_validate[condition]), len(control_cells_ids_filtered[condition]))
    assert len(control_cells_ids_cr4_validate[condition]) == len(control_cells_ids_filtered[condition])
    
    matches = 0
    num_pairs = len(control_cells_ids_cr4_validate[condition])
    for pos, key in enumerate(control_cells_ids_cr4_validate[condition].keys()):
        val1, val2 = control_cells_ids_cr4_validate[condition][key], control_cells_ids_filtered[condition][key]
        if val1 == val2:
            matches += 1
    print(f"     matches {matches}, differences {num_pairs - matches}")

ENSG00000001497 83 83
     matches 83, differences 0
ENSG00000003509 18 18
     matches 18, differences 0
ENSG00000004779 160 160
     matches 160, differences 0
ENSG00000004897 366 366
     matches 366, differences 0
ENSG00000005007 131 131
     matches 131, differences 0
ENSG00000005100 140 140
     matches 140, differences 0
ENSG00000005175 18 18
     matches 18, differences 0
ENSG00000005194 151 151
     matches 151, differences 0
ENSG00000005448 208 208
     matches 208, differences 0
ENSG00000006634 131 131
     matches 131, differences 0
ENSG00000006695 94 94
     matches 94, differences 0
ENSG00000006712 238 238
     matches 238, differences 0
ENSG00000006715 332 332
     matches 332, differences 0
ENSG00000006744 85 85
     matches 85, differences 0
ENSG00000007168 126 126
     matches 126, differences 0
ENSG00000007866 267 267
     matches 267, differences 0
ENSG00000007923 46 46
     matches 46, differences 0
ENSG00000008018 143 143
     matches 143, differences 0
ENSG00000008128 269 269
     matches 269, differences 0
ENSG00000008324 144 144
     matches 144, differences 0
ENSG00000008952 5 5
     matches 5, differences 0
ENSG00000008988 273 273
     matches 273, differences 0
ENSG00000009413 101 101
     matches 101, differences 0
ENSG00000010072 139 139
     matches 139, differences 0
ENSG00000010244 283 283
     matches 283, differences 0
ENSG00000010256 316 316
     matches 316, differences 0
ENSG00000010292 48 48
     matches 48, differences 0
ENSG00000010322 144 144
     matches 144, differences 0
ENSG00000011260 77 77
     matches 77, differences 0
ENSG00000011304 152 152
     matches 152, differences 0
ENSG00000011376 149 149
     matches 149, differences 0
ENSG00000011426 96 96
     matches 96, differences 0
ENSG00000011523 68 68
     matches 68, differences 0
ENSG00000012048 104 104
     matches 104, differences 0
ENSG00000012174 214 214
     matches 214, differences 0
ENSG00000013275 242 242
     matches 242, differences 0
ENSG00000013503 113 113
     matches 113, differences 0
ENSG00000013561 240 240
     matches 240, differences 0
ENSG00000013573 128 128
     matches 128, differences 0
ENSG00000013810 132 132
     matches 132, differences 0
ENSG00000014123 162 162
     matches 162, differences 0
ENSG00000014138 234 234
     matches 234, differences 0
ENSG00000014919 103 103
     matches 103, differences 0
ENSG00000015676 112 112
     matches 112, differences 0
ENSG00000018699 89 89
     matches 89, differences 0
ENSG00000020426 85 85
     matches 85, differences 0
ENSG00000021776 90 90
     matches 90, differences 0
ENSG00000023608 96 96
     matches 96, differences 0
ENSG00000023734 106 106
     matches 106, differences 0
ENSG00000025770 143 143
     matches 143, differences 0
ENSG00000025796 78 78
     matches 78, differences 0
ENSG00000025800 78 78
     matches 78, differences 0
ENSG00000027001 90 90
     matches 90, differences 0
ENSG00000028203 204 204
     matches 204, differences 0
ENSG00000029363 51 51
     matches 51, differences 0
ENSG00000029364 752 752
     matches 752, differences 0
ENSG00000030066 291 291
     matches 291, differences 0
ENSG00000031698 28 28
     matches 28, differences 0
ENSG00000033011 69 69
     matches 69, differences 0
ENSG00000033327 674 674
     matches 674, differences 0
ENSG00000034510 228 228
     matches 228, differences 0
ENSG00000035141 50 50
     matches 50, differences 0
ENSG00000035928 149 149
     matches 149, differences 0
ENSG00000036257 120 120
     matches 120, differences 0
ENSG00000037241 148 148
     matches 148, differences 0
ENSG00000037897 208 208
     matches 208, differences 0
ENSG00000038358 166 166
     matches 166, differences 0
ENSG00000039650 185 185
     matches 185, differences 0
ENSG00000040275 88 88
     matches 88, differences 0
ENSG00000041357 388 388
     matches 388, differences 0
ENSG00000041802 116 116
     matches 116, differences 0
ENSG00000042429 151 151
     matches 151, differences 0
ENSG00000042753 123 123
     matches 123, differences 0
ENSG00000044090 33 33
     matches 33, differences 0
ENSG00000044574 438 438
     matches 438, differences 0
ENSG00000046647 86 86
     matches 86, differences 0
ENSG00000047249 84 84
     matches 84, differences 0
ENSG00000047315 320 320
     matches 320, differences 0
ENSG00000047410 77 77
     matches 77, differences 0
ENSG00000048162 149 149
     matches 149, differences 0
ENSG00000048544 121 121
     matches 121, differences 0
ENSG00000048707 140 140
     matches 140, differences 0
ENSG00000049541 97 97
     matches 97, differences 0
ENSG00000050820 246 246
     matches 246, differences 0
ENSG00000051180 241 241
     matches 241, differences 0
ENSG00000051596 147 147
     matches 147, differences 0
ENSG00000052749 204 204
     matches 204, differences 0
ENSG00000053372 83 83
     matches 83, differences 0
ENSG00000053900 63 63
     matches 63, differences 0
ENSG00000054116 163 163
     matches 163, differences 0
ENSG00000055044 55 55
     matches 55, differences 0
ENSG00000055130 223 223
     matches 223, differences 0
ENSG00000055483 174 174
     matches 174, differences 0
ENSG00000055950 95 95
     matches 95, differences 0
ENSG00000058262 180 180
     matches 180, differences 0
ENSG00000058272 179 179
     matches 179, differences 0
ENSG00000058600 221 221
     matches 221, differences 0
ENSG00000058729 174 174
     matches 174, differences 0
ENSG00000058804 39 39
     matches 39, differences 0
ENSG00000060069 117 117
     matches 117, differences 0
ENSG00000060237 137 137
     matches 137, differences 0
ENSG00000060339 48 48
     matches 48, differences 0
ENSG00000060688 210 210
     matches 210, differences 0
ENSG00000061273 171 171
     matches 171, differences 0
ENSG00000061676 70 70
     matches 70, differences 0
ENSG00000061794 201 201
     matches 201, differences 0
ENSG00000061936 172 172
     matches 172, differences 0
ENSG00000062485 222 222
     matches 222, differences 0
ENSG00000062582 145 145
     matches 145, differences 0
ENSG00000062716 106 106
     matches 106, differences 0
ENSG00000062822 212 212
     matches 212, differences 0
ENSG00000063046 41 41
     matches 41, differences 0
ENSG00000063177 308 308
     matches 308, differences 0
ENSG00000063244 107 107
     matches 107, differences 0
ENSG00000063322 93 93
     matches 93, differences 0
ENSG00000063978 32 32
     matches 32, differences 0
ENSG00000064313 144 144
     matches 144, differences 0
ENSG00000064419 100 100
     matches 100, differences 0
ENSG00000064666 197 197
     matches 197, differences 0
ENSG00000064703 114 114
     matches 114, differences 0
ENSG00000065183 365 365
     matches 365, differences 0
ENSG00000065268 105 105
     matches 105, differences 0
ENSG00000065328 219 219
     matches 219, differences 0
ENSG00000065427 59 59
     matches 59, differences 0
ENSG00000065518 166 166
     matches 166, differences 0
ENSG00000065978 86 86
     matches 86, differences 0
ENSG00000066136 23 23
     matches 23, differences 0
ENSG00000066322 176 176
     matches 176, differences 0
ENSG00000066379 81 81
     matches 81, differences 0
ENSG00000066422 146 146
     matches 146, differences 0
ENSG00000067225 149 149
     matches 149, differences 0
ENSG00000067334 264 264
     matches 264, differences 0
ENSG00000067533 32 32
     matches 32, differences 0
ENSG00000067596 115 115
     matches 115, differences 0
ENSG00000067704 216 216
     matches 216, differences 0
ENSG00000068120 247 247
     matches 247, differences 0
ENSG00000068394 107 107
     matches 107, differences 0
ENSG00000068654 127 127
     matches 127, differences 0
ENSG00000068784 150 150
     matches 150, differences 0
ENSG00000069248 79 79
     matches 79, differences 0
ENSG00000069329 43 43
     matches 43, differences 0
ENSG00000069764 202 202
     matches 202, differences 0
ENSG00000070366 54 54
     matches 54, differences 0
ENSG00000070367 110 110
     matches 110, differences 0
ENSG00000070495 193 193
     matches 193, differences 0
ENSG00000070756 19 19
     matches 19, differences 0
ENSG00000070785 104 104
     matches 104, differences 0
ENSG00000070814 97 97
     matches 97, differences 0
ENSG00000070831 70 70
     matches 70, differences 0
ENSG00000071082 294 294
     matches 294, differences 0
ENSG00000071127 102 102
     matches 102, differences 0
ENSG00000071243 65 65
     matches 65, differences 0
ENSG00000071553 119 119
     matches 119, differences 0
ENSG00000071859 38 38
     matches 38, differences 0
ENSG00000071894 50 50
     matches 50, differences 0
ENSG00000071994 74 74
     matches 74, differences 0
ENSG00000072274 57 57
     matches 57, differences 0
ENSG00000072501 180 180
     matches 180, differences 0
ENSG00000072506 26 26
     matches 26, differences 0
ENSG00000072756 203 203
     matches 203, differences 0
ENSG00000072849 124 124
     matches 124, differences 0
ENSG00000073050 254 254
     matches 254, differences 0
ENSG00000073111 123 123
     matches 123, differences 0
ENSG00000073536 413 413
     matches 413, differences 0
ENSG00000073578 62 62
     matches 62, differences 0
ENSG00000073584 31 31
     matches 31, differences 0
ENSG00000073969 165 165
     matches 165, differences 0
ENSG00000074071 141 141
     matches 141, differences 0
ENSG00000074201 53 53
     matches 53, differences 0
ENSG00000074319 87 87
     matches 87, differences 0
ENSG00000074582 70 70
     matches 70, differences 0
ENSG00000074800 70 70
     matches 70, differences 0
ENSG00000074935 134 134
     matches 134, differences 0
ENSG00000075089 108 108
     matches 108, differences 0
ENSG00000075131 109 109
     matches 109, differences 0
ENSG00000075415 114 114
     matches 114, differences 0
ENSG00000075624 168 168
     matches 168, differences 0
ENSG00000075856 154 154
     matches 154, differences 0
ENSG00000075886 69 69
     matches 69, differences 0
ENSG00000075914 113 113
     matches 113, differences 0
ENSG00000076003 102 102
     matches 102, differences 0
ENSG00000076043 79 79
     matches 79, differences 0
ENSG00000076201 140 140
     matches 140, differences 0
ENSG00000076924 153 153
     matches 153, differences 0
ENSG00000077235 160 160
     matches 160, differences 0
ENSG00000077348 41 41
     matches 41, differences 0
ENSG00000077380 300 300
     matches 300, differences 0
ENSG00000077514 68 68
     matches 68, differences 0
ENSG00000077549 83 83
     matches 83, differences 0
ENSG00000078142 115 115
     matches 115, differences 0
ENSG00000079134 38 38
     matches 38, differences 0
ENSG00000079246 88 88
     matches 88, differences 0
ENSG00000079785 101 101
     matches 101, differences 0
ENSG00000079805 12 12
     matches 12, differences 0
ENSG00000080603 194 194
     matches 194, differences 0
ENSG00000080819 101 101
     matches 101, differences 0
ENSG00000080823 123 123
     matches 123, differences 0
ENSG00000080986 214 214
     matches 214, differences 0
ENSG00000081307 102 102
     matches 102, differences 0
ENSG00000081665 177 177
     matches 177, differences 0
ENSG00000082068 30 30
     matches 30, differences 0
ENSG00000082515 96 96
     matches 96, differences 0
ENSG00000082516 133 133
     matches 133, differences 0
ENSG00000082898 207 207
     matches 207, differences 0
ENSG00000083093 97 97
     matches 97, differences 0
ENSG00000083520 43 43
     matches 43, differences 0
ENSG00000083635 63 63
     matches 63, differences 0
ENSG00000083845 144 144
     matches 144, differences 0
ENSG00000083896 237 237
     matches 237, differences 0
ENSG00000084072 46 46
     matches 46, differences 0
ENSG00000084090 117 117
     matches 117, differences 0
ENSG00000084463 312 312
     matches 312, differences 0
ENSG00000084623 61 61
     matches 61, differences 0
ENSG00000085415 60 60
     matches 60, differences 0
ENSG00000085721 39 39
     matches 39, differences 0
ENSG00000085840 530 530
     matches 530, differences 0
ENSG00000085872 67 67
     matches 67, differences 0
ENSG00000086061 292 292
     matches 292, differences 0
ENSG00000086065 110 110
     matches 110, differences 0
ENSG00000086189 94 94
     matches 94, differences 0
ENSG00000086200 72 72
     matches 72, differences 0
ENSG00000086504 52 52
     matches 52, differences 0
ENSG00000086589 5 5
     matches 5, differences 0
ENSG00000086598 137 137
     matches 137, differences 0
ENSG00000086758 94 94
     matches 94, differences 0
ENSG00000086827 200 200
     matches 200, differences 0
ENSG00000087087 307 307
     matches 307, differences 0
ENSG00000087157 104 104
     matches 104, differences 0
ENSG00000087191 17 17
     matches 17, differences 0
ENSG00000087263 114 114
     matches 114, differences 0
ENSG00000087269 47 47
     matches 47, differences 0
ENSG00000087365 500 500
     matches 500, differences 0
ENSG00000087470 168 168
     matches 168, differences 0
ENSG00000087586 58 58
     matches 58, differences 0
ENSG00000088038 332 332
     matches 332, differences 0
ENSG00000088205 137 137
     matches 137, differences 0
ENSG00000088325 361 361
     matches 361, differences 0
ENSG00000088356 116 116
     matches 116, differences 0
ENSG00000088766 111 111
     matches 111, differences 0
ENSG00000088930 66 66
     matches 66, differences 0
ENSG00000088986 71 71
     matches 71, differences 0
ENSG00000089009 273 273
     matches 273, differences 0
ENSG00000089048 149 149
     matches 149, differences 0
ENSG00000089053 40 40
     matches 40, differences 0
ENSG00000089157 184 184
     matches 184, differences 0
ENSG00000089159 161 161
     matches 161, differences 0
ENSG00000089195 114 114
     matches 114, differences 0
ENSG00000089289 281 281
     matches 281, differences 0
ENSG00000089685 46 46
     matches 46, differences 0
ENSG00000089737 286 286
     matches 286, differences 0
ENSG00000089902 35 35
     matches 35, differences 0
ENSG00000090054 28 28
     matches 28, differences 0
ENSG00000090061 327 327
     matches 327, differences 0
ENSG00000090273 117 117
     matches 117, differences 0
ENSG00000090470 99 99
     matches 99, differences 0
ENSG00000090861 40 40
     matches 40, differences 0
ENSG00000090889 129 129
     matches 129, differences 0
ENSG00000090989 182 182
     matches 182, differences 0
ENSG00000091140 311 311
     matches 311, differences 0
ENSG00000091157 103 103
     matches 103, differences 0
ENSG00000091651 81 81
     matches 81, differences 0
ENSG00000092010 121 121
     matches 121, differences 0
ENSG00000092020 52 52
     matches 52, differences 0
ENSG00000092036 189 189
     matches 189, differences 0
ENSG00000092094 70 70
     matches 70, differences 0
ENSG00000092108 152 152
     matches 152, differences 0
ENSG00000092148 130 130
     matches 130, differences 0
ENSG00000092199 334 334
     matches 334, differences 0
ENSG00000092201 93 93
     matches 93, differences 0
ENSG00000092330 76 76
     matches 76, differences 0
ENSG00000092439 128 128
     matches 128, differences 0
ENSG00000092853 134 134
     matches 134, differences 0
ENSG00000092871 7 7
     matches 7, differences 0
ENSG00000093009 92 92
     matches 92, differences 0
ENSG00000094804 192 192
     matches 192, differences 0
ENSG00000094880 177 177
     matches 177, differences 0
ENSG00000094914 212 212
     matches 212, differences 0
ENSG00000095059 66 66
     matches 66, differences 0
ENSG00000095139 333 333
     matches 333, differences 0
ENSG00000095787 162 162
     matches 162, differences 0
ENSG00000095906 153 153
     matches 153, differences 0
ENSG00000096080 121 121
     matches 121, differences 0
ENSG00000096401 99 99
     matches 99, differences 0
ENSG00000097046 95 95
     matches 95, differences 0
ENSG00000099194 24 24
     matches 24, differences 0
ENSG00000099246 43 43
     matches 43, differences 0
ENSG00000099326 128 128
     matches 128, differences 0
ENSG00000099341 22 22
     matches 22, differences 0
ENSG00000099381 69 69
     matches 69, differences 0
ENSG00000099783 258 258
     matches 258, differences 0
ENSG00000099795 74 74
     matches 74, differences 0
ENSG00000099800 178 178
     matches 178, differences 0
ENSG00000099817 225 225
     matches 225, differences 0
ENSG00000099821 214 214
     matches 214, differences 0
ENSG00000099942 120 120
     matches 120, differences 0
ENSG00000099956 182 182
     matches 182, differences 0
ENSG00000099995 332 332
     matches 332, differences 0
ENSG00000100023 130 130
     matches 130, differences 0
ENSG00000100027 72 72
     matches 72, differences 0
ENSG00000100028 182 182
     matches 182, differences 0
ENSG00000100029 65 65
     matches 65, differences 0
ENSG00000100033 379 379
     matches 379, differences 0
ENSG00000100084 341 341
     matches 341, differences 0
ENSG00000100109 61 61
     matches 61, differences 0
ENSG00000100129 57 57
     matches 57, differences 0
ENSG00000100142 337 337
     matches 337, differences 0
ENSG00000100209 86 86
     matches 86, differences 0
ENSG00000100216 104 104
     matches 104, differences 0
ENSG00000100220 171 171
     matches 171, differences 0
ENSG00000100296 32 32
     matches 32, differences 0
ENSG00000100297 90 90
     matches 90, differences 0
ENSG00000100316 1996 1996
     matches 1996, differences 0
ENSG00000100319 100 100
     matches 100, differences 0
ENSG00000100347 102 102
     matches 102, differences 0
ENSG00000100353 186 186
     matches 186, differences 0
ENSG00000100387 57 57
     matches 57, differences 0
ENSG00000100401 130 130
     matches 130, differences 0
ENSG00000100410 231 231
     matches 231, differences 0
ENSG00000100413 109 109
     matches 109, differences 0
ENSG00000100462 127 127
     matches 127, differences 0
ENSG00000100479 56 56
     matches 56, differences 0
ENSG00000100519 151 151
     matches 151, differences 0
ENSG00000100522 112 112
     matches 112, differences 0
ENSG00000100554 139 139
     matches 139, differences 0
ENSG00000100564 85 85
     matches 85, differences 0
ENSG00000100567 372 372
     matches 372, differences 0
ENSG00000100575 201 201
     matches 201, differences 0
ENSG00000100603 226 226
     matches 226, differences 0
ENSG00000100632 86 86
     matches 86, differences 0
ENSG00000100664 175 175
     matches 175, differences 0
ENSG00000100697 158 158
     matches 158, differences 0
ENSG00000100726 74 74
     matches 74, differences 0
ENSG00000100764 316 316
     matches 316, differences 0
ENSG00000100804 270 270
     matches 270, differences 0
ENSG00000100811 82 82
     matches 82, differences 0
ENSG00000100813 191 191
     matches 191, differences 0
ENSG00000100836 148 148
     matches 148, differences 0
ENSG00000100865 78 78
     matches 78, differences 0
ENSG00000100883 81 81
     matches 81, differences 0
ENSG00000100890 42 42
     matches 42, differences 0
ENSG00000100902 40 40
     matches 40, differences 0
ENSG00000100911 151 151
     matches 151, differences 0
ENSG00000100941 86 86
     matches 86, differences 0
ENSG00000100949 116 116
     matches 116, differences 0
ENSG00000101003 186 186
     matches 186, differences 0
ENSG00000101057 106 106
     matches 106, differences 0
ENSG00000101132 34 34
     matches 34, differences 0
ENSG00000101138 141 141
     matches 141, differences 0
ENSG00000101146 59 59
     matches 59, differences 0
ENSG00000101158 201 201
     matches 201, differences 0
ENSG00000101161 232 232
     matches 232, differences 0
ENSG00000101166 273 273
     matches 273, differences 0
ENSG00000101181 146 146
     matches 146, differences 0
ENSG00000101182 41 41
     matches 41, differences 0
ENSG00000101189 74 74
     matches 74, differences 0
ENSG00000101246 138 138
     matches 138, differences 0
ENSG00000101343 261 261
     matches 261, differences 0
ENSG00000101361 99 99
     matches 99, differences 0
ENSG00000101407 151 151
     matches 151, differences 0
ENSG00000101421 71 71
     matches 71, differences 0
ENSG00000101444 147 147
     matches 147, differences 0
ENSG00000101639 202 202
     matches 202, differences 0
ENSG00000101654 114 114
     matches 114, differences 0
ENSG00000101773 117 117
     matches 117, differences 0
ENSG00000101868 230 230

## Unused Cells

In [13]:
control_cells_used = set()
for condition in conditions:
    control_cells_used = control_cells_used.union(set(control_cells_ids_filtered[condition].keys()))
    control_cells_used = control_cells_used.union(set(control_cells_ids_filtered[condition].values()))

In [14]:
all_cells = set(adata_filtered.obs_names)

In [15]:
len(all_cells), len(control_cells_used)

(310385, 310281)

In [16]:
control_cells_used.issubset(all_cells)

True

In [17]:
unused_cell_ids = all_cells.difference(control_cells_used)

In [18]:
unused_cells = adata_filtered.obs.loc[list(unused_cell_ids)]

In [19]:
unused_cells.condition.astype(str).unique()

array(['non-targeting'], dtype=object)

In [20]:
unused_cells

,gem_group,condition_name,condition,transcript,gene_transcript,sgID_AB,mitopercent,UMI_count,z_gemgroup_UMI,core_scale_factor,core_adjusted_UMI_count
cell_barcode,,,,,,,,,,,
TCCACGTGTCATCACA-26,26,non-targeting,non-targeting,non-targeting,11179_non-targeting_non-targeting_non-targeting,non-targeting_02787|non-targeting_01465,0.098578,18777.0,1.571038,0.901381,20831.373047
GGGACTCTCACCTCTG-25,25,non-targeting,non-targeting,non-targeting,10772_non-targeting_non-targeting_non-targeting,non-targeting_00166|non-targeting_02207,0.119748,12877.0,0.203468,0.855594,15050.363281
CCATAAGTCGACGACC-6,6,non-targeting,non-targeting,non-targeting,10822_non-targeting_non-targeting_non-targeting,non-targeting_00442|non-targeting_01312,0.078876,12995.0,-0.127853,0.954127,13619.778320
CCACGAGCATTCTCTA-19,19,non-targeting,non-targeting,non-targeting,10884_non-targeting_non-targeting_non-targeting,non-targeting_00807|non-targeting_02911,0.080580,17523.0,0.372891,1.123384,15598.401367
TTGAACGAGAGTATAC-8,8,non-targeting,non-targeting,non-targeting,10859_non-targeting_non-targeting_non-targeting,non-targeting_00652|non-targeting_02540,0.086616,18634.0,1.354366,0.950474,19604.958984
...,...,...,...,...,...,...,...,...,...,...,...
AATTTCCTCCGAAGGA-12,12,non-targeting,non-targeting,non-targeting,10882_non-targeting_non-targeting_non-targeting,non-targeting_00799|non-targeting_00833,0.093719,13978.0,-0.502728,1.232812,11338.302734
TACCGGGCATGTTCGA-34,34,non-targeting,non-targeting,non-targeting,10872_non-targeting_non-targeting_non-targeting,non-targeting_00702|non-targeting_02833,0.106195,15029.0,-0.047092,1.091537,13768.660156
CATCGTCTCGTTACCC-12,12,non-targeting,non-targeting,non-targeting,11023_non-targeting_non-targeting_non-targeting,non-targeting_01798|non-targeting_01119,0.114911,15525.0,-0.266281,1.232812,12593.157227
GCCAGGTGTAGCCCTG-43,43,non-targeting,non-targeting,non-targeting,11267_non-targeting_non-targeting_non-targeting,non-targeting_03441|non-targeting_00663,0.154688,10964.0,-0.570439,0.948277,11562.016602
CTTCAATAGTCGCCCA-31,31,non-targeting,non-targeting,non-targeting,11290_non-targeting_non-targeting_non-targeting,non-targeting_03530|non-targeting_01407,0.086622,12491.0,0.173189,0.844107,14797.893555

## Prototype Algorithm

In [147]:
from collections import defaultdict
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.neighbors import NearestNeighbors
from scipy.optimize import linear_sum_assignment

precision = 3
np.set_printoptions(precision=precision)

# # PREPROCESSING: Calculate number of non-zero genes
# n_nonzero_genes = (adata_filtered.X > 0).sum(axis=1)
# if not isinstance(n_nonzero_genes, np.ndarray):
#     n_nonzero_genes = n_nonzero_genes.toarray()

# adata_filtered.obs['n_nonzero_genes'] = n_nonzero_genes
# assert (adata_filtered.obs['UMI_count'] >= adata_filtered.obs['n_nonzero_genes']).all()

# Function inputs -- and obs
condition_key = 'condition'
group_key = 'gem_group'
dist_keys = ['UMI_count', 'n_nonzero_genes'] 
control_condition = "non-targeting"

def get_matched_controls_2(obs_metadata: pd.Dataframe, 
                           dist_keys: List[str], 
                           condition_key: str = 'condition', 
                           control_condition: str = 'non-targeting', 
                           group_key='gem_group') -> List[Dict[dict]]:

    
    df_columns = [condition_key, group_key] + dist_keys
    obs_metadata = obs_metadata[df_columns]
    
    control_mask = obs_metadata[condition_key] == control_condition
    control_cells = obs_metadata.loc[control_mask]
    treatment_cells = obs_metadata.loc[~control_mask]
    
    control_cells_gem = {gem_group:df for gem_group,df in control_cells.groupby(group_key)}
    control_cells_ids_filtered_lsum = defaultdict(dict)
    control_cells_ids_filtered_argm = defaultdict(dict)
    
    for condition, treatment_cells_cond in treatment_cells.groupby(condition_key):
        for gem_group, treatment_cells_cond_group in treatment_cells_cond.groupby(group_key):
            control_ = control_cells_gem[gem_group][dist_keys]
            treatment_ = treatment_cells_cond_group[dist_keys]
            if len(treatment_) > len(control_):
                print(f"Warning: {condition}, {gem_group} num treatment cells exceeds num control cells. {len(treatment_)} > {len(control_)}")
            elif len(treatment_) == len(control_):
                print(f"Info: {condition}, {gem_group} num treatment cells equals num control cells. {len(treatment_)} = {len(control_)}")
            
            dist_matrix = pairwise_distances(treatment_, control_)
            treatment_indices, control_indices = linear_sum_assignment(dist_matrix)
            if max(treatment_indices) >= len(treatment_): 
                AssertionError("Treatment indices out of range")
            if max(control_indices) >= len(control_): 
                AssertionError("Control indices out of range")

            control_indices_arg = dist_matrix.argmin(axis=1)
    
            if not np.allclose(control_indices[treatment_indices], control_indices_arg):
                lsum_dist_values = dist_matrix[treatment_indices, control_indices]
                # arg1_dist_values = dist_matrix[treatment_indices, control_indices_arg]
                arg1_dist_values = dist_matrix[list(range(dist_matrix.shape[0])), control_indices_arg]
                print(
                    f'Condition {condition}, gem_group {gem_group} :\n'
                    f'     lsum indices {control_indices[treatment_indices]} distances {lsum_dist_values} {sum(lsum_dist_values):.{precision}f}\n'
                    f'     arg1 indices {control_indices_arg} distances {arg1_dist_values} {sum(arg1_dist_values):.{precision}f}\n'
                )
            
            treatment_ids = treatment_.index[treatment_indices]
            control_ids = control_.index[control_indices]
            control_ids_arg = control_.index[control_indices_arg]
            control_cells_ids_filtered_lsum[condition].update(dict(zip(treatment_ids, control_ids)))
            control_cells_ids_filtered_argm[condition].update(dict(zip(treatment_.index, control_ids_arg)))

Condition ENSG00000001497, gem_group 39 :
     lsum indices [156 101 106  12 138] distances [13.928 75.425 39.013 84.876 92.849] 306.092
     arg1 indices [156 101 106  12 156] distances [13.928 75.425 39.013 84.876 82.292] 295.535

Condition ENSG00000004779, gem_group 9 :
     lsum indices [188  32 104  63] distances [106.85  257.391  65.803 155.544] 585.588
     arg1 indices [188  32 104 104] distances [106.85  257.391  65.803  26.571] 456.615

Condition ENSG00000004779, gem_group 33 :
     lsum indices [169 221  13  67  92 238  41 249  60] distances [128.413  48.836 110.476 103.586 168.814  82.735  64.815  35.057  30.61 ] 773.343
     arg1 indices [ 92 221  13  67  92 238  41 249  60] distances [ 82.492  48.836 110.476 103.586 168.814  82.735  64.815  35.057  30.61 ] 727.422

Condition ENSG00000004897, gem_group 12 :
     lsum indices [ 84  20 183 192  78  40 163  70] distances [  7.071  49.98   42.012  72.028 299.868 203.226 112.579  83.522] 870.287
     arg1 indices [ 84  20 183 192  78  78 163  70] distances [  7.071  49.98   42.012  72.028 299.868 147.801 112.579  83.522] 814.861

Condition ENSG00000004897, gem_group 17 :
     lsum indices [209 141 116  42  33 174 138  86 147 132] distances [ 41.881  92.027 208.087  80.505 150.712  65.215  77.201 176.366  76.42
  64.382] 1032.795
     arg1 indices [209 141 116 209  33 174 138  86 147 132] distances [ 41.881  92.027 208.087  68.622 150.712  65.215  77.201 176.366  76.42
  64.382] 1020.912

Condition ENSG00000004897, gem_group 20 :
     lsum indices [157 105  78 106  66 176  56  22  82 110  73] distances [  333.473    73.007  2385.942  2765.31    161.059   129.85    106.231
  1727.014 15744.902    84.172   209.122] 23720.080
     arg1 indices [157 105  22  82  66 176  56  22  82 110  73] distances [  333.473    73.007  1849.766   827.647   161.059   129.85    106.231
  1727.014 15744.902    84.172   209.122] 21246.243

Condition ENSG00000004897, gem_group 28 :
     lsum indices [227   2 193  89  30 189  16  74  64 229] distances [ 219.791   13.928   22.804  254.804   27.857  254.908   41.976 1812.226
  508.567 1055.917] 4212.777
     arg1 indices [227   2 193  89  30 189  16 189  64  74] distances [219.791  13.928  22.804 254.804  27.857 254.908  41.976 153.942 508.567
 910.838] 2409.413

Condition ENSG00000004897, gem_group 37 :
     lsum indices [ 72  22  38  53  69  37 103  84  44 176] distances [139.176 178.194  64.537 277.157 137.674 139.431 202.002  75.604 243.082
 230.868] 1687.725
     arg1 indices [ 72  22  38  53  69  37 103  84  44  38] distances [139.176 178.194  64.537 277.157 137.674 139.431 202.002  75.604 243.082
 102.903] 1559.760

Condition ENSG00000004897, gem_group 40 :
     lsum indices [ 49  20   4  96 102 129 198 103] distances [149.857  75.717  56.639 331.024  91.285  17.088 167.287 169.003] 1057.900
     arg1 indices [ 49  20   4  96 102 129 198 198] distances [149.857  75.717  56.639 331.024  91.285  17.088 167.287 140.631] 1029.528

Condition ENSG00000004897, gem_group 43 :
     lsum indices [ 98  45 126 168 118  97  36  74 170  62   6 166 214 150] distances [ 41.4   265.932 367.491  44.721  11.402  99.81  101.592 302.399  13.038
 183.657  58.    129.877  55.758  55.946] 1731.026
     arg1 indices [ 98  36 126 168 118  97  36  74 170  62   6 166 214 150] distances [ 41.4   209.093 367.491  44.721  11.402  99.81  101.592 302.399  13.038
 183.657  58.    129.877  55.758  55.946] 1674.187

Condition ENSG00000004897, gem_group 47 :
     lsum indices [192 189 172  64  72  99  20 223  44 149] distances [ 75.802  67.779 366.531 118.878 109.385  87.281  36.674  90.802  79.259
 131.32 ] 1163.712
     arg1 indices [192 189 172  64  20  99  20 223  44 149] distances [ 75.802  67.779 366.531 118.878  50.961  87.281  36.674  90.802  79.259
 131.32 ] 1105.288

Condition ENSG00000005007, gem_group 14 :
     lsum indices [ 65 147  98] distances [ 24.331 126.811 240.801] 391.943
     arg1 indices [ 65 147 147] distances [ 24.331 126.811 240.308] 391.450

Condition ENSG00000005100, gem_group 5 :
     lsum indices [ 22  31   4 116  33] distances [550.967 824.151 976.783 631.922 157.848] 3141.672
     arg1 indices [22 22 22  4 33] distances [550.967 245.41  749.805 275.036 157.848] 1979.067

Condition ENSG00000005100, gem_group 7 :
     lsum indices [ 95 207 212] distances [246.108 132.189  72.835] 451.132
     arg1 indices [ 95 212 212] distances [246.108  80.156  72.835] 399.099

Condition ENSG00000005100, gem_group 17 :
     lsum indices [  2  69  57  45  24 195] distances [  31.623   31.064   74.25   832.034  196.352 2145.106] 3310.429
     arg1 indices [ 2 69 57 45 24 45] distances [ 31.623  31.064  74.25  832.034 196.352 319.401] 1484.724

Condition ENSG00000005100, gem_group 47 :
     lsum indices [ 16 181 138 162] distances [83.361 51.478 77.885 72.56 ] 285.284
     arg1 indices [ 16 181 138  16] distances [83.361 51.478 77.885 62.514] 275.237

Condition ENSG00000005194, gem_group 11 :
     lsum indices [ 52  67 200  73] distances [189.694  66.068  60.926 322.219] 638.908
     arg1 indices [200  67 200  73] distances [169.921  66.068  60.926 322.219] 619.134

Condition ENSG00000005448, gem_group 5 :
     lsum indices [141  61 112 130  18 132] distances [160.449  55.66    8.485 328.661  70.859  34.132] 658.246
     arg1 indices [130  61 112 130  18 132] distances [156.952  55.66    8.485 328.661  70.859  34.132] 654.749

Condition ENSG00000005448, gem_group 23 :
     lsum indices [ 93 100  56 155] distances [104.809  47.011  42.202 196.469] 390.491
     arg1 indices [100 100  56 100] distances [ 87.824  47.011  42.202 131.518] 308.554

Condition ENSG00000005448, gem_group 24 :
     lsum indices [ 66 120 168 187 135] distances [171.735 137.441 101.39   79.649  83.169] 573.384
     arg1 indices [ 66 120 168 187 187] distances [171.735 137.441 101.39   79.649  75.584] 565.800

Condition ENSG00000005448, gem_group 27 :
     lsum indices [165 159  15 223  45 180   5] distances [ 70.214   6.708 207.82   71.868  14.866  60.539  73.355] 505.370
     arg1 indices [165 159 159 223  45 180 223] distances [ 70.214   6.708 206.495  71.868  14.866  60.539  39.408] 470.098

Condition ENSG00000005448, gem_group 29 :
     lsum indices [ 32 158  37 133 104  86  53  42 155] distances [478.173 107.912 192.512 208.483  16.155 647.105  17.088  94.26  738.968] 2500.657
     arg1 indices [133 158  37 133 104  86  53  42  37] distances [ 48.508 107.912 192.512 208.483  16.155 647.105  17.088  94.26  334.073] 1666.097

Condition ENSG00000005448, gem_group 34 :
     lsum indices [ 30  14 131 160 105] distances [ 82.855 351.011  76.942  90.736 126.657] 728.201
     arg1 indices [ 30  14  30 160 105] distances [ 82.855 351.011  73.43   90.736 126.657] 724.690

Condition ENSG00000005448, gem_group 37 :
     lsum indices [ 60  62  25 139  19] distances [789.704 278.297  50.249 316.661 184.391] 1619.301
     arg1 indices [19 62 25 60 19] distances [599.803 278.297  50.249 231.147 184.391] 1343.887

Condition ENSG00000006634, gem_group 15 :
     lsum indices [ 14 124  49  76  57] distances [184.177 335.622  54.406  47.381 128.035] 749.621
     arg1 indices [ 14 124  49  76  49] distances [184.177 335.622  54.406  47.381  67.119] 688.705

Condition ENSG00000006634, gem_group 39 :
     lsum indices [194 176 199] distances [101.966 100.     98.087] 300.052
     arg1 indices [194 199 199] distances [101.966  98.005  98.087] 298.057

Condition ENSG00000006695, gem_group 30 :
     lsum indices [ 20  32 116 192  33] distances [ 91.214  69.836  44.721 329.134  35.609] 570.514
     arg1 indices [ 33  32 116 192  33] distances [ 85.475  69.836  44.721 329.134  35.609] 564.775

Condition ENSG00000006712, gem_group 3 :
     lsum indices [139  30  22  55 107 128] distances [731.109 144.9    12.     71.701 831.79  774.407] 2565.907
     arg1 indices [128  30  22  55 107 128] distances [422.303 144.9    12.     71.701 831.79  774.407] 2257.100

Condition ENSG00000006712, gem_group 4 :
     lsum indices [89 19 80 48] distances [4369.347  454.829  974.159 2897.47 ] 8695.804
     arg1 indices [19 19 80 80] distances [ 982.008  454.829  974.159 1471.564] 3882.559

Condition ENSG00000006712, gem_group 5 :
     lsum indices [ 21   4  22  89  81 126  73 148  70 121] distances [  41.976 2386.778  699.909  173.22   239.209  738.329  182.332  104.738
  233.452  134.332] 4934.274
     arg1 indices [ 21  73  22  89  81 126  73 148  70 121] distances [ 41.976 389.032 699.909 173.22  239.209 738.329 182.332 104.738 233.452
 134.332] 2936.529

Condition ENSG00000006712, gem_group 6 :
     lsum indices [224  87   8 253 245 120 214 187 172] distances [1105.882   90.139  284.459  395.506   78.313  165.653  207.663 1268.393
 2309.585] 5905.594
     arg1 indices [187  87   8 214 245 120 214 187 187] distances [ 377.041   90.139  284.459  362.713   78.313  165.653  207.663 1268.393
  130.   ] 2964.375

Condition ENSG00000006712, gem_group 9 :
     lsum indices [136 137 119   4 147] distances [184.201 726.319 855.593 110.635 836.158] 2712.907
     arg1 indices [136 136 136   4 137] distances [184.201 492.184 147.221 110.635 701.031] 1635.271

Condition ENSG00000006712, gem_group 10 :
     lsum indices [ 72 114 165  98  24] distances [642.012 796.645 111.83  181.207 658.827] 2390.522
     arg1 indices [114  24 165  98  24] distances [508.842 604.448 111.83  181.207 658.827] 2065.154

Condition ENSG00000006712, gem_group 11 :
     lsum indices [ 76 174 149 109  57] distances [ 65.803 563.604 304.844 329.548 207.48 ] 1471.280
     arg1 indices [ 76  76 149 109  57] distances [ 65.803 409.121 304.844 329.548 207.48 ] 1316.796

Condition ENSG00000006712, gem_group 13 :
     lsum indices [ 96 165 144 129  40] distances [122.381 106.888 327.116 246.002 131.973] 934.360
     arg1 indices [ 96 165 144 129 165] distances [122.381 106.888 327.116 246.002 101.02 ] 903.406

Condition ENSG00000006712, gem_group 17 :
     lsum indices [ 45 137 195  60 108  75 149] distances [ 298.967  313.141 1491.546  155.184  957.975  136.473  314.07 ] 3667.355
     arg1 indices [ 45 137  45  60 195  75 149] distances [298.967 313.141 744.13  155.184 659.473 136.473 314.07 ] 2621.438

Condition ENSG00000006712, gem_group 22 :
     lsum indices [ 93 170 183 159  65] distances [1510.192  187.481  519.678 1242.131   43.417] 3502.899
     arg1 indices [183 170 183  93  65] distances [997.305 187.481 519.678 972.981  43.417] 2720.861

Condition ENSG00000006712, gem_group 24 :
     lsum indices [ 18  80   2 121 185] distances [ 651.089 2488.807 3885.174 1136.945 2987.197] 11149.213
     arg1 indices [ 18 121  18  18 121] distances [651.089 188.096 745.618 473.714 670.759] 2729.275

Condition ENSG00000006712, gem_group 26 :
     lsum indices [ 92 116   0  69  87 153] distances [ 447.42  2102.297 2011.855   25.495 2110.568  896.222] 7593.858
     arg1 indices [153  87  87  69  87  87] distances [ 180.544 1564.129 1809.604   25.495 2110.568  385.41 ] 6075.749

Condition ENSG00000006712, gem_group 28 :
     lsum indices [218 189  50  74 135 187 229] distances [  69.34  1353.101  120.507 1668.112   10.05   178.197 1715.428] 5114.734
     arg1 indices [218 189  50 189 135 187 189] distances [  69.34  1353.101  120.507  321.006   10.05   178.197  482.872] 2535.072

Condition ENSG00000006712, gem_group 29 :
     lsum indices [ 84  96 159 150] distances [238.891  67.119  89.022 431.419] 826.452
     arg1 indices [ 84  96 159  84] distances [238.891  67.119  89.022 257.031] 652.064

Condition ENSG00000006712, gem_group 31 :
     lsum indices [196 213 112 233 221 154 122 119 192  41 178] distances [420.058 379.111 406.964 161.555  68.731 702.906 475.825 332.415 306.217
 249.    252.858] 3755.641
     arg1 indices [196 213 119 233 221 119 122 119 196  41 178] distances [420.058 379.111 342.001 161.555  68.731 403.15  475.825 332.415 288.517
 249.    252.858] 3373.222

Condition ENSG00000006712, gem_group 34 :
     lsum indices [ 66  79  83 185 120  35 106 201] distances [707.195  60.033 365.    588.317 442.666 753.042 710.862 136.132] 3763.248
     arg1 indices [ 66  79  83 106  66 120 106 201] distances [707.195  60.033 365.    183.098 386.122 294.532 710.862 136.132] 2842.975

Condition ENSG00000006712, gem_group 35 :
     lsum indices [177  33 182 163 108  59] distances [ 146.294  454.271  299.456  132.91   590.003 1363.786] 2986.720
     arg1 indices [177  33 182 163  33 108] distances [146.294 454.271 299.456 132.91  370.115 322.555] 1725.601

Condition ENSG00000006712, gem_group 36 :
     lsum indices [ 35 225  99 125 127 223 147] distances [1926.235 4130.438  603.255 1166.382 2614.312  600.244  492.631] 11533.497
     arg1 indices [147 147 223 147 147 127 147] distances [1276.102 1229.433  417.767  844.967  539.633  500.658  492.631] 5301.190

Condition ENSG00000006712, gem_group 39 :
     lsum indices [ 43  67 194 176 162 111  91] distances [434.902 285.16   43.417 560.616 237.008 534.72  184.556] 2280.378
     arg1 indices [ 43  67 194  43 162 111  91] distances [434.902 285.16   43.417 529.718 237.008 534.72  184.556] 2249.481

Condition ENSG00000006712, gem_group 40 :
     lsum indices [  9  14 174 202   2  62] distances [478.754 352.026 292.657 445.112  11.045 287.689] 1867.283
     arg1 indices [  9  14 174   9   2  62] distances [478.754 352.026 292.657 410.222  11.045 287.689] 1832.392

Condition ENSG00000006712, gem_group 41 :
     lsum indices [116 200 128  98 115  95] distances [ 110.91   252.446   29.428 1286.101   85.165  371.618] 2135.668
     arg1 indices [116 200 128  95 115  95] distances [110.91  252.446  29.428 461.213  85.165 371.618] 1310.779

Condition ENSG00000006712, gem_group 43 :
     lsum indices [ 31 156 199 193 221] distances [ 260.192 1050.566  215.372 1882.556  765.823] 4174.509
     arg1 indices [ 31 156 199 156 199] distances [ 260.192 1050.566  215.372 1248.785  323.155] 3098.070

Condition ENSG00000006712, gem_group 45 :
     lsum indices [ 75 142 212  41  19 114] distances [ 342.072 2114.969  401.698  463.625  747.909  621.805] 4692.076
     arg1 indices [ 75 142 212  41 142 114] distances [ 342.072 2114.969  401.698  463.625  355.692  621.805] 4299.860

Condition ENSG00000006712, gem_group 47 :
     lsum indices [192 185 180 183  78] distances [ 87.321 514.328 288.503 169.293 304.105] 1363.550
     arg1 indices [192 180 180 183  78] distances [ 87.321 281.007 288.503 169.293 304.105] 1130.229

Condition ENSG00000006715, gem_group 3 :
     lsum indices [164  31   8  66 226 149 151 103 129] distances [ 19.799  60.008 154.081 291.318  78.518 146.014  65.123 111.826 233.214] 1159.901
     arg1 indices [164  31   8 151 226 149 151 103 129] distances [ 19.799  60.008 154.081 281.455  78.518 146.014  65.123 111.826 233.214] 1150.038

Condition ENSG00000006715, gem_group 12 :
     lsum indices [159  71  52 101 149  57 183 110 164 188] distances [ 79.63   55.009 478.533 641.543  67.417 216.474  17.117 321.255 162.807
 378.312] 2418.097
     arg1 indices [159  71 101 110 149  57 183 110 164 188] distances [ 79.63   55.009 155.081 337.511  67.417 216.474  17.117 321.255 162.807
 378.312] 1790.613

Condition ENSG00000006715, gem_group 22 :
     lsum indices [ 34 193  84 137  15 116   7 139 183  33] distances [176.649  61.27   26.571 267.576 347.311  71.113  61.741  51.923 357.241
 147.411] 1568.806
     arg1 indices [ 34 193  84 137  15 116   7 139 183 139] distances [176.649  61.27   26.571 267.576 347.311  71.113  61.741  51.923 357.241
  98.838] 1520.233

Condition ENSG00000006715, gem_group 28 :
     lsum indices [212  95 166 133  87   1 185  80  67  51] distances [ 94.594 113.842  95.901  40.05   76.551  31.321  52.086  15.133 118.962
 212.455] 850.894
     arg1 indices [212  95 166 133  87   1 185  80  95  51] distances [ 94.594 113.842  95.901  40.05   76.551  31.321  52.086  15.133 115.109
 212.455] 847.041

Condition ENSG00000006744, gem_group 31 :
     lsum indices [ 21 181 161 137] distances [ 84.77   14.213 350.184  98.717] 547.884
     arg1 indices [ 21 181  21 137] distances [ 84.77   14.213 310.01   98.717] 507.709

Condition ENSG00000007168, gem_group 13 :
     lsum indices [155 221  22  67 103] distances [475.341  84.077  24.083 126.716  34.54 ] 744.758
     arg1 indices [103 221  22  67 103] distances [406.69   84.077  24.083 126.716  34.54 ] 676.107

Condition ENSG00000007866, gem_group 7 :
     lsum indices [ 60  96  47 220 165 190  92] distances [34.    76.485 22.091 60.407 42.426 60.108 95.755] 391.273
     arg1 indices [ 60  96  47 220 165  47  92] distances [34.    76.485 22.091 60.407 42.426 45.277 95.755] 376.441

Condition ENSG00000007866, gem_group 27 :
     lsum indices [ 55  18 179 250 172  11] distances [ 48.27   70.228  49.82  120.814 232.166  78.186] 599.483
     arg1 indices [ 55  18 179 172 172  11] distances [ 48.27   70.228  49.82  111.252 232.166  78.186] 589.921

Condition ENSG00000007866, gem_group 30 :
     lsum indices [ 69  38 147  76  66 244 146 171  39] distances [720.367  20.616  38.601 145.578 124.201 121.037 104.005  87.664  29.069] 1391.138
     arg1 indices [ 69  38 147  76  66 146 146 171  39] distances [720.367  20.616  38.601 145.578 124.201  26.    104.005  87.664  29.069] 1296.101

Condition ENSG00000007866, gem_group 43 :
     lsum indices [ 93  90 202  40  98 190  13  78] distances [ 34.886  95.273 181.959  60.166 125.706  69.354  57.801 158.146] 783.291
     arg1 indices [ 93  90  90  40  98 190  13  78] distances [ 34.886  95.273 155.116  60.166 125.706  69.354  57.801 158.146] 756.448

Condition ENSG00000008018, gem_group 7 :
     lsum indices [86 70  7] distances [ 63.977 112.805 146.513] 323.294
     arg1 indices [86 86  7] distances [ 63.977  72.835 146.513] 283.325

Condition ENSG00000008018, gem_group 13 :
     lsum indices [168 169 204 213] distances [ 55.172  27.659 200.562 124.101] 407.494
     arg1 indices [168 169 213 213] distances [ 55.172  27.659 153.029 124.101] 359.961

Condition ENSG00000008018, gem_group 20 :
     lsum indices [41 89 43] distances [312.57   74.847 857.775] 1245.192
     arg1 indices [41 89 41] distances [312.57   74.847 455.281] 842.698

Condition ENSG00000008128, gem_group 1 :
     lsum indices [ 50 194  79  99 155 167 106  25] distances [ 12.042 120.83  109.836  32.388  42.802  62.817  42.379 155.824] 578.918
     arg1 indices [ 50 167  79  99 155 167 106  25] distances [ 12.042  93.536 109.836  32.388  42.802  62.817  42.379 155.824] 551.624

Condition ENSG00000008128, gem_group 6 :
     lsum indices [217 174 236 208  70 122  85] distances [78.409 81.271 82.608 30.265 38.21  99.363 50.961] 461.087
     arg1 indices [217 174 236 208 122 122  85] distances [78.409 81.271 82.608 30.265 36.62  99.363 50.961] 459.497

Condition ENSG00000008128, gem_group 11 :
     lsum indices [210  77  82 126  45  52 188   4] distances [163.368   8.062  48.27   51.352  33.838  28.284  64.537  42.521] 440.231
     arg1 indices [210  77  82 126 188  52 188   4] distances [163.368   8.062  48.27   51.352  24.839  28.284  64.537  42.521] 431.233

Condition ENSG00000008128, gem_group 15 :
     lsum indices [  3  76 123  74 191 212 114  52   7] distances [ 39.051 309.944   9.849  69.893 120.441 175.841  61.392  87.966 649.98 ] 1524.356
     arg1 indices [  3  76 123  74  74 212 114  52   7] distances [ 39.051 309.944   9.849  69.893 117.712 175.841  61.392  87.966 649.98 ] 1521.627

Condition ENSG00000008128, gem_group 20 :
     lsum indices [ 42 175  51  82 123   8  15 184] distances [  77.987   93.193   23.087 2240.889   31.016   44.102   42.521  205.883] 2758.679
     arg1 indices [ 42 175  51  82 123   8  15   8] distances [  77.987   93.193   23.087 2240.889   31.016   44.102   42.521  191.588] 2744.383

Condition ENSG00000008128, gem_group 25 :
     lsum indices [208 119 240 232 145 247] distances [ 28.284 254.049  36.139  55.317  64.351  51.971] 490.111
     arg1 indices [208 119 240 232 145 240] distances [ 28.284 254.049  36.139  55.317  64.351  49.649] 487.789

Condition ENSG00000008128, gem_group 37 :

In [127]:
# # Can probably accelerate by inverting loop order
# # Will run fewer pairwise distance calculations, albeit with memory increase
# for gem_group, treatment_gem_group in treatment_cells.groupby(group_key):
#     control_ = control_cells_gem[gem_group][dist_keys]
#     treatment_ = treatment_gem_group[dist_keys]
#     dist_matrix = pairwise_distances(treatment_, control_)
    
#     for condition, treatment_gem_condition in treatment_gem_group.groupby(condition_key):
#         treatment_indices, control_indices = linear_sum_assignment(dist_matrix[treatment_gem_condition.indexes])

#         treatment_ids = treatment_.index[treatment_indices]
#         control_ids = control_.index[control_indices]
#         control_cells_ids[condition].update(dict(zip(treatment_ids, control_ids)))

In [157]:
for condition in conditions:
    print(condition, len(control_cells_ids_filtered[condition]), len(control_cells_ids_filtered_lsum[condition]))
    assert len(control_cells_ids_filtered[condition]) == len(control_cells_ids_filtered_lsum[condition])
    
    matches = 0
    num_pairs = len(control_cells_ids_filtered[condition])
    for pos, key in enumerate(control_cells_ids_filtered[condition].keys()):
        val1, val2 = control_cells_ids_filtered[condition][key], control_cells_ids_filtered_lsum[condition][key]
        if val1 == val2:
            matches += 1
    print(f"     matches {matches}, differences {num_pairs - matches}")

ENSG00000001497 83 83
     matches 45, differences 38
ENSG00000003509 18 18
     matches 9, differences 9
ENSG00000004779 160 160
     matches 63, differences 97
ENSG00000004897 366 366
     matches 174, differences 192
ENSG00000005007 131 131
     matches 58, differences 73
ENSG00000005100 140 140
     matches 55, differences 85
ENSG00000005175 18 18
     matches 8, differences 10
ENSG00000005194 151 151
     matches 59, differences 92
ENSG00000005448 208 208
     matches 82, differences 126
ENSG00000006634 131 131
     matches 50, differences 81
ENSG00000006695 94 94
     matches 41, differences 53
ENSG00000006712 238 238
     matches 140, differences 98
ENSG00000006715 332 332
     matches 148, differences 184
ENSG00000006744 85 85
     matches 43, differences 42
ENSG00000007168 126 126
     matches 71, differences 55
ENSG00000007866 267 267
     matches 117, differences 150
ENSG00000007923 46 46
     matches 20, differences 26
ENSG00000008018 143 143
     matches 56, differences 87
ENSG00000008128 269 269
     matches 114, differences 155
ENSG00000008324 144 144
     matches 79, differences 65
ENSG00000008952 5 5
     matches 2, differences 3
ENSG00000008988 273 273
     matches 117, differences 156
ENSG00000009413 101 101
     matches 45, differences 56
ENSG00000010072 139 139
     matches 59, differences 80
ENSG00000010244 283 283
     matches 146, differences 137
ENSG00000010256 316 316
     matches 131, differences 185
ENSG00000010292 48 48
     matches 20, differences 28
ENSG00000010322 144 144
     matches 56, differences 88
ENSG00000011260 77 77
     matches 33, differences 44
ENSG00000011304 152 152
     matches 77, differences 75
ENSG00000011376 149 149
     matches 67, differences 82
ENSG00000011426 96 96
     matches 50, differences 46
ENSG00000011523 68 68
     matches 28, differences 40
ENSG00000012048 104 104
     matches 47, differences 57
ENSG00000012174 214 214
     matches 103, differences 111
ENSG00000013275 242 242
     matches 131, differences 111
ENSG00000013503 113 113
     matches 55, differences 58
ENSG00000013561 240 240
     matches 107, differences 133
ENSG00000013573 128 128
     matches 59, differences 69
ENSG00000013810 132 132
     matches 61, differences 71
ENSG00000014123 162 162
     matches 74, differences 88
ENSG00000014138 234 234
     matches 120, differences 114
ENSG00000014919 103 103
     matches 52, differences 51
ENSG00000015676 112 112
     matches 51, differences 61
ENSG00000018699 89 89
     matches 43, differences 46
ENSG00000020426 85 85
     matches 36, differences 49
ENSG00000021776 90 90
     matches 48, differences 42
ENSG00000023608 96 96
     matches 38, differences 58
ENSG00000023734 106 106
     matches 55, differences 51
ENSG00000025770 143 143
     matches 74, differences 69
ENSG00000025796 78 78
     matches 34, differences 44
ENSG00000025800 78 78
     matches 35, differences 43
ENSG00000027001 90 90
     matches 46, differences 44
ENSG00000028203 204 204
     matches 91, differences 113
ENSG00000029363 51 51
     matches 22, differences 29
ENSG00000029364 752 752
     matches 350, differences 402
ENSG00000030066 291 291
     matches 133, differences 158
ENSG00000031698 28 28
     matches 12, differences 16
ENSG00000033011 69 69
     matches 28, differences 41
ENSG00000033327 674 674
     matches 308, differences 366
ENSG00000034510 228 228
     matches 91, differences 137
ENSG00000035141 50 50
     matches 29, differences 21
ENSG00000035928 149 149
     matches 77, differences 72
ENSG00000036257 120 120
     matches 47, differences 73
ENSG00000037241 148 148
     matches 69, differences 79
ENSG00000037897 208 208
     matches 89, differences 119
ENSG00000038358 166 166
     matches 69, differences 97
ENSG00000039650 185 185
     matches 91, differences 94
ENSG00000040275 88 88
     matches 48, differences 40
ENSG00000041357 388 388
     matches 184, differences 204
ENSG00000041802 116 116
     matches 58, differences 58
ENSG00000042429 151 151
     matches 95, differences 56
ENSG00000042753 123 123
     matches 56, differences 67
ENSG00000044090 33 33
     matches 18, differences 15
ENSG00000044574 438 438
     matches 215, differences 223
ENSG00000046647 86 86
     matches 38, differences 48
ENSG00000047249 84 84
     matches 36, differences 48
ENSG00000047315 320 320
     matches 172, differences 148
ENSG00000047410 77 77
     matches 31, differences 46
ENSG00000048162 149 149
     matches 62, differences 87
ENSG00000048544 121 121
     matches 45, differences 76
ENSG00000048707 140 140
     matches 64, differences 76
ENSG00000049541 97 97
     matches 52, differences 45
ENSG00000050820 246 246
     matches 113, differences 133
ENSG00000051180 241 241
     matches 126, differences 115
ENSG00000051596 147 147
     matches 62, differences 85
ENSG00000052749 204 204
     matches 65, differences 139
ENSG00000053372 83 83
     matches 39, differences 44
ENSG00000053900 63 63
     matches 35, differences 28
ENSG00000054116 163 163
     matches 76, differences 87
ENSG00000055044 55 55
     matches 23, differences 32
ENSG00000055130 223 223
     matches 109, differences 114
ENSG00000055483 174 174
     matches 76, differences 98
ENSG00000055950 95 95
     matches 44, differences 51
ENSG00000058262 180 180
     matches 64, differences 116
ENSG00000058272 179 179
     matches 81, differences 98
ENSG00000058600 221 221
     matches 105, differences 116
ENSG00000058729 174 174
     matches 59, differences 115
ENSG00000058804 39 39
     matches 16, differences 23
ENSG00000060069 117 117
     matches 60, differences 57
ENSG00000060237 137 137
     matches 61, differences 76
ENSG00000060339 48 48
     matches 24, differences 24
ENSG00000060688 210 210
     matches 91, differences 119
ENSG00000061273 171 171
     matches 84, differences 87
ENSG00000061676 70 70
     matches 30, differences 40
ENSG00000061794 201 201
     matches 97, differences 104
ENSG00000061936 172 172
     matches 81, differences 91
ENSG00000062485 222 222
     matches 97, differences 125
ENSG00000062582 145 145
     matches 67, differences 78
ENSG00000062716 106 106
     matches 52, differences 54
ENSG00000062822 212 212
     matches 113, differences 99
ENSG00000063046 41 41
     matches 15, differences 26
ENSG00000063177 308 308
     matches 122, differences 186
ENSG00000063244 107 107
     matches 39, differences 68
ENSG00000063322 93 93
     matches 54, differences 39
ENSG00000063978 32 32
     matches 15, differences 17
ENSG00000064313 144 144
     matches 89, differences 55
ENSG00000064419 100 100
     matches 48, differences 52
ENSG00000064666 197 197
     matches 96, differences 101
ENSG00000064703 114 114
     matches 49, differences 65
ENSG00000065183 365 365
     matches 137, differences 228
ENSG00000065268 105 105
     matches 49, differences 56
ENSG00000065328 219 219
     matches 118, differences 101
ENSG00000065427 59 59
     matches 31, differences 28
ENSG00000065518 166 166
     matches 86, differences 80
ENSG00000065978 86 86
     matches 35, differences 51
ENSG00000066136 23 23
     matches 14, differences 9
ENSG00000066322 176 176
     matches 79, differences 97
ENSG00000066379 81 81
     matches 31, differences 50
ENSG00000066422 146 146
     matches 70, differences 76
ENSG00000067225 149 149
     matches 71, differences 78
ENSG00000067334 264 264
     matches 89, differences 175
ENSG00000067533 32 32
     matches 15, differences 17
ENSG00000067596 115 115
     matches 60, differences 55
ENSG00000067704 216 216
     matches 96, differences 120
ENSG00000068120 247 247
     matches 110, differences 137
ENSG00000068394 107 107
     matches 45, differences 62
ENSG00000068654 127 127
     matches 51, differences 76
ENSG00000068784 150 150
     matches 75, differences 75
ENSG00000069248 79 79
     matches 37, differences 42
ENSG00000069329 43 43
     matches 27, differences 16
ENSG00000069764 202 202
     matches 89, differences 113
ENSG00000070366 54 54
     matches 23, differences 31
ENSG00000070367 110 110
     matches 54, differences 56
ENSG00000070495 193 193
     matches 96, differences 97
ENSG00000070756 19 19
     matches 9, differences 10
ENSG00000070785 104 104
     matches 51, differences 53
ENSG00000070814 97 97
     matches 41, differences 56
ENSG00000070831 70 70
     matches 34, differences 36
ENSG00000071082 294 294
     matches 124, differences 170
ENSG00000071127 102 102
     matches 43, differences 59
ENSG00000071243 65 65
     matches 32, differences 33
ENSG00000071553 119 119
     matches 52, differences 67
ENSG00000071859 38 38
     matches 14, differences 24
ENSG00000071894 50 50
     matches 26, differences 24
ENSG00000071994 74 74
     matches 24, differences 50
ENSG00000072274 57 57
     matches 19, differences 38
ENSG00000072501 180 180
     matches 74, differences 106
ENSG00000072506 26 26
     matches 13, differences 13
ENSG00000072756 203 203
     matches 95, differences 108
ENSG00000072849 124 124
     matches 56, differences 68
ENSG00000073050 254 254
     matches 110, differences 144
ENSG00000073111 123 123
     matches 69, differences 54
ENSG00000073536 413 413
     matches 191, differences 222
ENSG00000073578 62 62
     matches 31, differences 31
ENSG00000073584 31 31
     matches 18, differences 13
ENSG00000073969 165 165
     matches 73, differences 92
ENSG00000074071 141 141
     matches 64, differences 77
ENSG00000074201 53 53
     matches 21, differences 32
ENSG00000074319 87 87
     matches 42, differences 45
ENSG00000074582 70 70
     matches 38, differences 32
ENSG00000074800 70 70
     matches 32, differences 38
ENSG00000074935 134 134
     matches 62, differences 72
ENSG00000075089 108 108
     matches 53, differences 55
ENSG00000075131 109 109
     matches 56, differences 53
ENSG00000075415 114 114
     matches 53, differences 61
ENSG00000075624 168 168
     matches 74, differences 94
ENSG00000075856 154 154
     matches 71, differences 83
ENSG00000075886 69 69
     matches 40, differences 29
ENSG00000075914 113 113
     matches 52, differences 61
ENSG00000076003 102 102
     matches 45, differences 57
ENSG00000076043 79 79
     matches 34, differences 45
ENSG00000076201 140 140
     matches 68, differences 72
ENSG00000076924 153 153
     matches 75, differences 78
ENSG00000077235 160 160
     matches 72, differences 88
ENSG00000077348 41 41
     matches 19, differences 22
ENSG00000077380 300 300
     matches 155, differences 145
ENSG00000077514 68 68
     matches 42, differences 26
ENSG00000077549 83 83
     matches 43, differences 40
ENSG00000078142 115 115
     matches 60, differences 55
ENSG00000079134 38 38
     matches 13, differences 25
ENSG00000079246 88 88
     matches 37, differences 51
ENSG00000079785 101 101
     matches 48, differences 53
ENSG00000079805 12 12
     matches 5, differences 7
ENSG00000080603 194 194
     matches 95, differences 99
ENSG00000080819 101 101
     matches 50, differences 51
ENSG00000080823 123 123
     matches 60, differences 63
ENSG00000080986 214 214
     matches 100, differences 114
ENSG00000081307 102 102
     matches 46, differences 56
ENSG00000081665 177 177
     matches 82, differences 95
ENSG00000082068 30 30
     matches 9, differences 21
ENSG00000082515 96 96
     matches 43, differences 53
ENSG00000082516 133 133
     matches 63, differences 70
ENSG00000082898 207 207
     matches 95, differences 112
ENSG00000083093 97 97
     matches 41, differences 56
ENSG00000083520 43 43
     matches 25, differences 18
ENSG00000083635 63 63
     matches 25, differences 38
ENSG00000083845 144 144
     matches 56, differences 88
ENSG00000083896 237 237
     matches 100, differences 137
ENSG00000084072 46 46
     matches 10, differences 36
ENSG00000084090 117 117
     matches 59, differences 58
ENSG00000084463 312 312
     matches 139, differences 173
ENSG00000084623 61 61
     matches 32, differences 29
ENSG00000085415 60 60
     matches 33, differences 27
ENSG00000085721 39 39
     matches 11, differences 28
ENSG00000085840 530 530
     matches 273, differences 257
ENSG00000085872 67 67
     matches 31, differences 36
ENSG00000086061 292 292
     matches 130, differences 162
ENSG00000086065 110 110
     matches 46, differences 64
ENSG00000086189 94 94
     matches 35, differences 59
ENSG00000086200 72 72
     matches 34, differences 38
ENSG00000086504 52 52
     matches 23, differences 29
ENSG00000086589 5 5
     matches 2, differences 3
ENSG00000086598 137 137
     matches 69, differences 68
ENSG00000086758 94 94
     matches 45, differences 49
ENSG00000086827 200 200
     matches 92, differences 108
ENSG00000087087 307 307
     matches 161, differences 146
ENSG00000087157 104 104
     matches 45, differences 59
ENSG00000087191 17 17
     matches 8, differences 9
ENSG00000087263 114 114
     matches 49, differences 65
ENSG00000087269 47 47
     matches 11, differences 36
ENSG00000087365 500 500
     matches 252, differences 248
ENSG00000087470 168 168
     matches 78, differences 90
ENSG00000087586 58 58
     matches 32, differences 26
ENSG00000088038 332 332
     matches 149, differences 183
ENSG00000088205 137 137
     matches 49, differences 88
ENSG00000088325 361 361
     matches 189, differences 172
ENSG00000088356 116 116
     matches 47, differences 69
ENSG00000088766 111 111
     matches 58, differences 53
ENSG00000088930 66 66
     matches 27, differences 39
ENSG00000088986 71 71
     matches 33, differences 38
ENSG00000089009 273 273
     matches 101, differences 172
ENSG00000089048 149 149
     matches 69, differences 80
ENSG00000089053 40 40
     matches 19, differences 21
ENSG00000089157 184 184
     matches 93, differences 91
ENSG00000089159 161 161
     matches 77, differences 84
ENSG00000089195 114 114
     matches 53, differences 61
ENSG00000089289 281 281
     matches 131, differences 150
ENSG00000089685 46 46
     matches 27, differences 19
ENSG00000089737 286 286
     matches 139, differences 147
ENSG00000089902 35 35
     matches 24, differences 11
ENSG00000090054 28 28
     matches 17, differences 11
ENSG00000090061 327 327
     matches 146, differences 181
ENSG00000090273 117 117
     matches 51, differences 66
ENSG00000090470 99 99
     matches 39, differences 60
ENSG00000090861 40 40
     matches 27, differences 13
ENSG00000090889 129 129
     matches 60, differences 69
ENSG00000090989 182 182
     matches 84, differences 98
ENSG00000091140 311 311
     matches 139, differences 172
ENSG00000091157 103 103
     matches 43, differences 60
ENSG00000091651 81 81
     matches 35, differences 46
ENSG00000092010 121 121
     matches 51, differences 70
ENSG00000092020 52 52
     matches 28, differences 24
ENSG00000092036 189 189
     matches 107, differences 82
ENSG00000092094 70 70
     matches 29, differences 41
ENSG00000092108 152 152
     matches 70, differences 82
ENSG00000092148 130 130
     matches 61, differences 69
ENSG00000092199 334 334
     matches 154, differences 180
ENSG00000092201 93 93
     matches 50, differences 43
ENSG00000092330 76 76
     matches 42, differences 34
ENSG00000092439 128 128
     matches 54, differences 74
ENSG00000092853 134 134
     matches 65, differences 69
ENSG00000092871 7 7
     matches 3, differences 4
ENSG00000093009 92 92
     matches 35, differences 57
ENSG00000094804 192 192
     matches 101, differences 91
ENSG00000094880 177 177
     matches 96, differences 81
ENSG00000094914 212 212
     matches 104, differences 108
ENSG00000095059 66 66
     matches 22, differences 44
ENSG00000095139 333 333
     matches 159, differences 174
ENSG00000095787 162 162
     matches 70, differences 92
ENSG00000095906 153 153
     matches 63, differences 90
ENSG00000096080 121 121
     matches 63, differences 58
ENSG00000096401 99 99
     matches 49, differences 50
ENSG00000097046 95 95
     matches 45, differences 50
ENSG00000099194 24 24
     matches 16, differences 8
ENSG00000099246 43 43
     matches 22, differences 21
ENSG00000099326 128 128
     matches 58, differences 70
ENSG00000099341 22 22
     matches 10, differences 12
ENSG00000099381 69 69
     matches 39, differences 30
ENSG00000099783 258 258
     matches 119, differences 139
ENSG00000099795 74 74
     matches 41, differences 33
ENSG00000099800 178 178
     matches 80, differences 98
ENSG00000099817 225 225
     matches 114, differences 111
ENSG00000099821 214 214
     matches 103, differences 111
ENSG00000099942 120 120
     matches 56, differences 64
ENSG00000099956 182 182
     matches 87, differences 95
ENSG00000099995 332 332
     matches 161, differences 171
ENSG00000100023 130 130
     matches 65, differences 65
ENSG00000100027 72 72
     matches 30, differences 42
ENSG00000100028 182 182
     matches 83, differences 99
ENSG00000100029 65 65
     matches 37, differences 28
ENSG00000100033 379 379
     matches 191, differences 188
ENSG00000100084 341 341
     matches 169, differences 172
ENSG00000100109 61 61
     matches 24, differences 37
ENSG00000100129 57 57
     matches 28, differences 29
ENSG00000100142 337 337
     matches 171, differences 166
ENSG00000100209 86 86
     matches 37, differences 49
ENSG00000100216 104 104
     matches 47, differences 57
ENSG00000100220 171 171
     matches 81, differences 90
ENSG00000100296 32 32
     matches 16, differences 16
ENSG00000100297 90 90
     matches 46, differences 44
ENSG00000100316 1996 1996
     matches 822, differences 1174
ENSG00000100319 100 100
     matches 46, differences 54
ENSG00000100347 102 102
     matches 51, differences 51
ENSG00000100353 186 186
     matches 80, differences 106
ENSG00000100387 57 57
     matches 31, differences 26
ENSG00000100401 130 130
     matches 60, differences 70
ENSG00000100410 231 231
     matches 91, differences 140
ENSG00000100413 109 109
     matches 43, differences 66
ENSG00000100462 127 127
     matches 49, differences 78
ENSG00000100479 56 56
     matches 26, differences 30
ENSG00000100519 151 151
     matches 70, differences 81
ENSG00000100522 112 112
     matches 45, differences 67
ENSG00000100554 139 139
     matches 58, differences 81
ENSG00000100564 85 85
     matches 39, differences 46
ENSG00000100567 372 372
     matches 170, differences 202
ENSG00000100575 201 201
     matches 90, differences 111
ENSG00000100603 226 226
     matches 103, differences 123
ENSG00000100632 86 86
     matches 47, differences 39
ENSG00000100664 175 175
     matches 86, differences 89
ENSG00000100697 158 158
     matches 71, differences 87
ENSG00000100726 74 74
     matches 38, differences 36
ENSG00000100764 316 316
     matches 171, differences 145
ENSG00000100804 270 270
     matches 112, differences 158
ENSG00000100811 82 82
     matches 40, differences 42
ENSG00000100813 191 191
     matches 89, differences 102
ENSG00000100836 148 148
     matches 69, differences 79
ENSG00000100865 78 78
     matches 40, differences 38
ENSG00000100883 81 81
     matches 36, differences 45
ENSG00000100890 42 42
     matches 23, differences 19
ENSG00000100902 40 40
     matches 18, differences 22
ENSG00000100911 151 151
     matches 67, differences 84
ENSG00000100941 86 86
     matches 37, differences 49
ENSG00000100949 116 116
     matches 63, differences 53
ENSG00000101003 186 186
     matches 107, differences 79
ENSG00000101057 106 106
     matches 63, differences 43
ENSG00000101132 34 34
     matches 16, differences 18
ENSG00000101138 141 141
     matches 63, differences 78
ENSG00000101146 59 59
     matches 33, differences 26
ENSG00000101158 201 201
     matches 101, differences 100
ENSG00000101161 232 232
     matches 95, differences 137
ENSG00000101166 273 273
     matches 152, differences 121
ENSG00000101181 146 146
     matches 70, differences 76
ENSG00000101182 41 41
     matches 16, differences 25
ENSG00000101189 74 74
     matches 27, differences 47
ENSG00000101246 138 138
     matches 59, differences 79
ENSG00000101343 261 261
     matches 123, differences 138
ENSG00000101361 99 99
     matches 55, differences 44
ENSG00000101407 151 151
     matches 58, differences 93
ENSG00000101421 71 71

In [149]:
for condition in conditions:
    print(condition, len(control_cells_ids_filtered[condition]), len(control_cells_ids_filtered_argm[condition]))
    assert len(control_cells_ids_filtered[condition]) == len(control_cells_ids_filtered_argm[condition])
    
    matches = 0
    num_pairs = len(control_cells_ids_filtered[condition])
    for pos, key in enumerate(control_cells_ids_filtered[condition].keys()):
        val1, val2 = control_cells_ids_filtered[condition][key], control_cells_ids_filtered_argm[condition][key]
        if val1 == val2:
            matches += 1
    print(f"     matches {matches}, differences {num_pairs - matches}")

ENSG00000001497 83 83
     matches 46, differences 37
ENSG00000003509 18 18
     matches 9, differences 9
ENSG00000004779 160 160
     matches 64, differences 96
ENSG00000004897 366 366
     matches 175, differences 191
ENSG00000005007 131 131
     matches 58, differences 73
ENSG00000005100 140 140
     matches 55, differences 85
ENSG00000005175 18 18
     matches 8, differences 10
ENSG00000005194 151 151
     matches 59, differences 92
ENSG00000005448 208 208
     matches 83, differences 125
ENSG00000006634 131 131
     matches 51, differences 80
ENSG00000006695 94 94
     matches 41, differences 53
ENSG00000006712 238 238
     matches 120, differences 118
ENSG00000006715 332 332
     matches 147, differences 185
ENSG00000006744 85 85
     matches 42, differences 43
ENSG00000007168 126 126
     matches 71, differences 55
ENSG00000007866 267 267
     matches 118, differences 149
ENSG00000007923 46 46
     matches 20, differences 26
ENSG00000008018 143 143
     matches 58, differences 85
ENSG00000008128 269 269
     matches 116, differences 153
ENSG00000008324 144 144
     matches 78, differences 66
ENSG00000008952 5 5
     matches 2, differences 3
ENSG00000008988 273 273
     matches 116, differences 157
ENSG00000009413 101 101
     matches 45, differences 56
ENSG00000010072 139 139
     matches 60, differences 79
ENSG00000010244 283 283
     matches 147, differences 136
ENSG00000010256 316 316
     matches 130, differences 186
ENSG00000010292 48 48
     matches 20, differences 28
ENSG00000010322 144 144
     matches 57, differences 87
ENSG00000011260 77 77
     matches 33, differences 44
ENSG00000011304 152 152
     matches 77, differences 75
ENSG00000011376 149 149
     matches 66, differences 83
ENSG00000011426 96 96
     matches 50, differences 46
ENSG00000011523 68 68
     matches 28, differences 40
ENSG00000012048 104 104
     matches 47, differences 57
ENSG00000012174 214 214
     matches 103, differences 111
ENSG00000013275 242 242
     matches 126, differences 116
ENSG00000013503 113 113
     matches 54, differences 59
ENSG00000013561 240 240
     matches 109, differences 131
ENSG00000013573 128 128
     matches 60, differences 68
ENSG00000013810 132 132
     matches 60, differences 72
ENSG00000014123 162 162
     matches 72, differences 90
ENSG00000014138 234 234
     matches 121, differences 113
ENSG00000014919 103 103
     matches 52, differences 51
ENSG00000015676 112 112
     matches 51, differences 61
ENSG00000018699 89 89
     matches 44, differences 45
ENSG00000020426 85 85
     matches 37, differences 48
ENSG00000021776 90 90
     matches 48, differences 42
ENSG00000023608 96 96
     matches 38, differences 58
ENSG00000023734 106 106
     matches 55, differences 51
ENSG00000025770 143 143
     matches 75, differences 68
ENSG00000025796 78 78
     matches 34, differences 44
ENSG00000025800 78 78
     matches 35, differences 43
ENSG00000027001 90 90
     matches 47, differences 43
ENSG00000028203 204 204
     matches 93, differences 111
ENSG00000029363 51 51
     matches 23, differences 28
ENSG00000029364 752 752
     matches 352, differences 400
ENSG00000030066 291 291
     matches 133, differences 158
ENSG00000031698 28 28
     matches 12, differences 16
ENSG00000033011 69 69
     matches 28, differences 41
ENSG00000033327 674 674
     matches 300, differences 374
ENSG00000034510 228 228
     matches 92, differences 136
ENSG00000035141 50 50
     matches 29, differences 21
ENSG00000035928 149 149
     matches 79, differences 70
ENSG00000036257 120 120
     matches 48, differences 72
ENSG00000037241 148 148
     matches 68, differences 80
ENSG00000037897 208 208
     matches 91, differences 117
ENSG00000038358 166 166
     matches 70, differences 96
ENSG00000039650 185 185
     matches 92, differences 93
ENSG00000040275 88 88
     matches 48, differences 40
ENSG00000041357 388 388
     matches 182, differences 206
ENSG00000041802 116 116
     matches 58, differences 58
ENSG00000042429 151 151
     matches 91, differences 60
ENSG00000042753 123 123
     matches 56, differences 67
ENSG00000044090 33 33
     matches 18, differences 15
ENSG00000044574 438 438
     matches 216, differences 222
ENSG00000046647 86 86
     matches 39, differences 47
ENSG00000047249 84 84
     matches 35, differences 49
ENSG00000047315 320 320
     matches 166, differences 154
ENSG00000047410 77 77
     matches 31, differences 46
ENSG00000048162 149 149
     matches 63, differences 86
ENSG00000048544 121 121
     matches 45, differences 76
ENSG00000048707 140 140
     matches 64, differences 76
ENSG00000049541 97 97
     matches 52, differences 45
ENSG00000050820 246 246
     matches 114, differences 132
ENSG00000051180 241 241
     matches 129, differences 112
ENSG00000051596 147 147
     matches 64, differences 83
ENSG00000052749 204 204
     matches 68, differences 136
ENSG00000053372 83 83
     matches 37, differences 46
ENSG00000053900 63 63
     matches 35, differences 28
ENSG00000054116 163 163
     matches 76, differences 87
ENSG00000055044 55 55
     matches 23, differences 32
ENSG00000055130 223 223
     matches 109, differences 114
ENSG00000055483 174 174
     matches 77, differences 97
ENSG00000055950 95 95
     matches 44, differences 51
ENSG00000058262 180 180
     matches 67, differences 113
ENSG00000058272 179 179
     matches 81, differences 98
ENSG00000058600 221 221
     matches 106, differences 115
ENSG00000058729 174 174
     matches 59, differences 115
ENSG00000058804 39 39
     matches 16, differences 23
ENSG00000060069 117 117
     matches 60, differences 57
ENSG00000060237 137 137
     matches 61, differences 76
ENSG00000060339 48 48
     matches 24, differences 24
ENSG00000060688 210 210
     matches 91, differences 119
ENSG00000061273 171 171
     matches 86, differences 85
ENSG00000061676 70 70
     matches 30, differences 40
ENSG00000061794 201 201
     matches 97, differences 104
ENSG00000061936 172 172
     matches 81, differences 91
ENSG00000062485 222 222
     matches 99, differences 123
ENSG00000062582 145 145
     matches 68, differences 77
ENSG00000062716 106 106
     matches 51, differences 55
ENSG00000062822 212 212
     matches 112, differences 100
ENSG00000063046 41 41
     matches 15, differences 26
ENSG00000063177 308 308
     matches 122, differences 186
ENSG00000063244 107 107
     matches 39, differences 68
ENSG00000063322 93 93
     matches 52, differences 41
ENSG00000063978 32 32
     matches 15, differences 17
ENSG00000064313 144 144
     matches 90, differences 54
ENSG00000064419 100 100
     matches 48, differences 52
ENSG00000064666 197 197
     matches 97, differences 100
ENSG00000064703 114 114
     matches 49, differences 65
ENSG00000065183 365 365
     matches 135, differences 230
ENSG00000065268 105 105
     matches 49, differences 56
ENSG00000065328 219 219
     matches 120, differences 99
ENSG00000065427 59 59
     matches 31, differences 28
ENSG00000065518 166 166
     matches 88, differences 78
ENSG00000065978 86 86
     matches 35, differences 51
ENSG00000066136 23 23
     matches 14, differences 9
ENSG00000066322 176 176
     matches 79, differences 97
ENSG00000066379 81 81
     matches 28, differences 53
ENSG00000066422 146 146
     matches 69, differences 77
ENSG00000067225 149 149
     matches 72, differences 77
ENSG00000067334 264 264
     matches 87, differences 177
ENSG00000067533 32 32
     matches 15, differences 17
ENSG00000067596 115 115
     matches 59, differences 56
ENSG00000067704 216 216
     matches 96, differences 120
ENSG00000068120 247 247
     matches 111, differences 136
ENSG00000068394 107 107
     matches 47, differences 60
ENSG00000068654 127 127
     matches 51, differences 76
ENSG00000068784 150 150
     matches 77, differences 73
ENSG00000069248 79 79
     matches 37, differences 42
ENSG00000069329 43 43
     matches 27, differences 16
ENSG00000069764 202 202
     matches 91, differences 111
ENSG00000070366 54 54
     matches 23, differences 31
ENSG00000070367 110 110
     matches 54, differences 56
ENSG00000070495 193 193
     matches 96, differences 97
ENSG00000070756 19 19
     matches 9, differences 10
ENSG00000070785 104 104
     matches 51, differences 53
ENSG00000070814 97 97
     matches 40, differences 57
ENSG00000070831 70 70
     matches 34, differences 36
ENSG00000071082 294 294
     matches 125, differences 169
ENSG00000071127 102 102
     matches 43, differences 59
ENSG00000071243 65 65
     matches 32, differences 33
ENSG00000071553 119 119
     matches 52, differences 67
ENSG00000071859 38 38
     matches 14, differences 24
ENSG00000071894 50 50
     matches 26, differences 24
ENSG00000071994 74 74
     matches 23, differences 51
ENSG00000072274 57 57
     matches 19, differences 38
ENSG00000072501 180 180
     matches 75, differences 105
ENSG00000072506 26 26
     matches 13, differences 13
ENSG00000072756 203 203
     matches 96, differences 107
ENSG00000072849 124 124
     matches 57, differences 67
ENSG00000073050 254 254
     matches 110, differences 144
ENSG00000073111 123 123
     matches 68, differences 55
ENSG00000073536 413 413
     matches 190, differences 223
ENSG00000073578 62 62
     matches 32, differences 30
ENSG00000073584 31 31
     matches 18, differences 13
ENSG00000073969 165 165
     matches 74, differences 91
ENSG00000074071 141 141
     matches 66, differences 75
ENSG00000074201 53 53
     matches 21, differences 32
ENSG00000074319 87 87
     matches 42, differences 45
ENSG00000074582 70 70
     matches 38, differences 32
ENSG00000074800 70 70
     matches 32, differences 38
ENSG00000074935 134 134
     matches 62, differences 72
ENSG00000075089 108 108
     matches 53, differences 55
ENSG00000075131 109 109
     matches 56, differences 53
ENSG00000075415 114 114
     matches 53, differences 61
ENSG00000075624 168 168
     matches 74, differences 94
ENSG00000075856 154 154
     matches 69, differences 85
ENSG00000075886 69 69
     matches 40, differences 29
ENSG00000075914 113 113
     matches 51, differences 62
ENSG00000076003 102 102
     matches 44, differences 58
ENSG00000076043 79 79
     matches 33, differences 46
ENSG00000076201 140 140
     matches 68, differences 72
ENSG00000076924 153 153
     matches 76, differences 77
ENSG00000077235 160 160
     matches 70, differences 90
ENSG00000077348 41 41
     matches 19, differences 22
ENSG00000077380 300 300
     matches 155, differences 145
ENSG00000077514 68 68
     matches 42, differences 26
ENSG00000077549 83 83
     matches 43, differences 40
ENSG00000078142 115 115
     matches 60, differences 55
ENSG00000079134 38 38
     matches 13, differences 25
ENSG00000079246 88 88
     matches 37, differences 51
ENSG00000079785 101 101
     matches 48, differences 53
ENSG00000079805 12 12
     matches 5, differences 7
ENSG00000080603 194 194
     matches 95, differences 99
ENSG00000080819 101 101
     matches 50, differences 51
ENSG00000080823 123 123
     matches 61, differences 62
ENSG00000080986 214 214
     matches 99, differences 115
ENSG00000081307 102 102
     matches 46, differences 56
ENSG00000081665 177 177
     matches 83, differences 94
ENSG00000082068 30 30
     matches 9, differences 21
ENSG00000082515 96 96
     matches 43, differences 53
ENSG00000082516 133 133
     matches 63, differences 70
ENSG00000082898 207 207
     matches 99, differences 108
ENSG00000083093 97 97
     matches 41, differences 56
ENSG00000083520 43 43
     matches 25, differences 18
ENSG00000083635 63 63
     matches 25, differences 38
ENSG00000083845 144 144
     matches 56, differences 88
ENSG00000083896 237 237
     matches 102, differences 135
ENSG00000084072 46 46
     matches 10, differences 36
ENSG00000084090 117 117
     matches 59, differences 58
ENSG00000084463 312 312
     matches 140, differences 172
ENSG00000084623 61 61
     matches 33, differences 28
ENSG00000085415 60 60
     matches 32, differences 28
ENSG00000085721 39 39
     matches 10, differences 29
ENSG00000085840 530 530
     matches 269, differences 261
ENSG00000085872 67 67
     matches 31, differences 36
ENSG00000086061 292 292
     matches 134, differences 158
ENSG00000086065 110 110
     matches 46, differences 64
ENSG00000086189 94 94
     matches 34, differences 60
ENSG00000086200 72 72
     matches 34, differences 38
ENSG00000086504 52 52
     matches 23, differences 29
ENSG00000086589 5 5
     matches 2, differences 3
ENSG00000086598 137 137
     matches 69, differences 68
ENSG00000086758 94 94
     matches 45, differences 49
ENSG00000086827 200 200
     matches 91, differences 109
ENSG00000087087 307 307
     matches 157, differences 150
ENSG00000087157 104 104
     matches 45, differences 59
ENSG00000087191 17 17
     matches 8, differences 9
ENSG00000087263 114 114
     matches 51, differences 63
ENSG00000087269 47 47
     matches 11, differences 36
ENSG00000087365 500 500
     matches 255, differences 245
ENSG00000087470 168 168
     matches 79, differences 89
ENSG00000087586 58 58
     matches 32, differences 26
ENSG00000088038 332 332
     matches 146, differences 186
ENSG00000088205 137 137
     matches 49, differences 88
ENSG00000088325 361 361
     matches 193, differences 168
ENSG00000088356 116 116
     matches 48, differences 68
ENSG00000088766 111 111
     matches 58, differences 53
ENSG00000088930 66 66
     matches 27, differences 39
ENSG00000088986 71 71
     matches 33, differences 38
ENSG00000089009 273 273
     matches 101, differences 172
ENSG00000089048 149 149
     matches 69, differences 80
ENSG00000089053 40 40
     matches 19, differences 21
ENSG00000089157 184 184
     matches 93, differences 91
ENSG00000089159 161 161
     matches 76, differences 85
ENSG00000089195 114 114
     matches 53, differences 61
ENSG00000089289 281 281
     matches 130, differences 151
ENSG00000089685 46 46
     matches 27, differences 19
ENSG00000089737 286 286
     matches 139, differences 147
ENSG00000089902 35 35
     matches 24, differences 11
ENSG00000090054 28 28
     matches 17, differences 11
ENSG00000090061 327 327
     matches 145, differences 182
ENSG00000090273 117 117
     matches 52, differences 65
ENSG00000090470 99 99
     matches 39, differences 60
ENSG00000090861 40 40
     matches 27, differences 13
ENSG00000090889 129 129
     matches 60, differences 69
ENSG00000090989 182 182
     matches 84, differences 98
ENSG00000091140 311 311
     matches 140, differences 171
ENSG00000091157 103 103
     matches 43, differences 60
ENSG00000091651 81 81
     matches 35, differences 46
ENSG00000092010 121 121
     matches 51, differences 70
ENSG00000092020 52 52
     matches 28, differences 24
ENSG00000092036 189 189
     matches 102, differences 87
ENSG00000092094 70 70
     matches 29, differences 41
ENSG00000092108 152 152
     matches 70, differences 82
ENSG00000092148 130 130
     matches 60, differences 70
ENSG00000092199 334 334
     matches 153, differences 181
ENSG00000092201 93 93
     matches 51, differences 42
ENSG00000092330 76 76
     matches 43, differences 33
ENSG00000092439 128 128
     matches 53, differences 75
ENSG00000092853 134 134
     matches 66, differences 68
ENSG00000092871 7 7
     matches 3, differences 4
ENSG00000093009 92 92
     matches 35, differences 57
ENSG00000094804 192 192
     matches 101, differences 91
ENSG00000094880 177 177
     matches 97, differences 80
ENSG00000094914 212 212
     matches 105, differences 107
ENSG00000095059 66 66
     matches 22, differences 44
ENSG00000095139 333 333
     matches 156, differences 177
ENSG00000095787 162 162
     matches 69, differences 93
ENSG00000095906 153 153
     matches 63, differences 90
ENSG00000096080 121 121
     matches 63, differences 58
ENSG00000096401 99 99
     matches 48, differences 51
ENSG00000097046 95 95
     matches 45, differences 50
ENSG00000099194 24 24
     matches 16, differences 8
ENSG00000099246 43 43
     matches 22, differences 21
ENSG00000099326 128 128
     matches 58, differences 70
ENSG00000099341 22 22
     matches 10, differences 12
ENSG00000099381 69 69
     matches 39, differences 30
ENSG00000099783 258 258
     matches 118, differences 140
ENSG00000099795 74 74
     matches 40, differences 34
ENSG00000099800 178 178
     matches 78, differences 100
ENSG00000099817 225 225
     matches 112, differences 113
ENSG00000099821 214 214
     matches 101, differences 113
ENSG00000099942 120 120
     matches 56, differences 64
ENSG00000099956 182 182
     matches 87, differences 95
ENSG00000099995 332 332
     matches 157, differences 175
ENSG00000100023 130 130
     matches 65, differences 65
ENSG00000100027 72 72
     matches 30, differences 42
ENSG00000100028 182 182
     matches 82, differences 100
ENSG00000100029 65 65
     matches 37, differences 28
ENSG00000100033 379 379
     matches 191, differences 188
ENSG00000100084 341 341
     matches 171, differences 170
ENSG00000100109 61 61
     matches 24, differences 37
ENSG00000100129 57 57
     matches 28, differences 29
ENSG00000100142 337 337
     matches 172, differences 165
ENSG00000100209 86 86
     matches 37, differences 49
ENSG00000100216 104 104
     matches 46, differences 58
ENSG00000100220 171 171
     matches 80, differences 91
ENSG00000100296 32 32
     matches 16, differences 16
ENSG00000100297 90 90
     matches 46, differences 44
ENSG00000100316 1996 1996
     matches 835, differences 1161
ENSG00000100319 100 100
     matches 46, differences 54
ENSG00000100347 102 102
     matches 51, differences 51
ENSG00000100353 186 186
     matches 81, differences 105
ENSG00000100387 57 57
     matches 31, differences 26
ENSG00000100401 130 130
     matches 61, differences 69
ENSG00000100410 231 231
     matches 90, differences 141
ENSG00000100413 109 109
     matches 43, differences 66
ENSG00000100462 127 127
     matches 49, differences 78
ENSG00000100479 56 56
     matches 26, differences 30
ENSG00000100519 151 151
     matches 68, differences 83
ENSG00000100522 112 112
     matches 45, differences 67
ENSG00000100554 139 139
     matches 56, differences 83
ENSG00000100564 85 85
     matches 39, differences 46
ENSG00000100567 372 372
     matches 170, differences 202
ENSG00000100575 201 201
     matches 92, differences 109
ENSG00000100603 226 226
     matches 102, differences 124
ENSG00000100632 86 86
     matches 48, differences 38
ENSG00000100664 175 175
     matches 87, differences 88
ENSG00000100697 158 158
     matches 71, differences 87
ENSG00000100726 74 74
     matches 38, differences 36
ENSG00000100764 316 316
     matches 166, differences 150
ENSG00000100804 270 270
     matches 114, differences 156
ENSG00000100811 82 82
     matches 40, differences 42
ENSG00000100813 191 191
     matches 89, differences 102
ENSG00000100836 148 148
     matches 69, differences 79
ENSG00000100865 78 78
     matches 39, differences 39
ENSG00000100883 81 81
     matches 36, differences 45
ENSG00000100890 42 42
     matches 23, differences 19
ENSG00000100902 40 40
     matches 18, differences 22
ENSG00000100911 151 151
     matches 67, differences 84
ENSG00000100941 86 86
     matches 37, differences 49
ENSG00000100949 116 116
     matches 63, differences 53
ENSG00000101003 186 186
     matches 110, differences 76
ENSG00000101057 106 106
     matches 63, differences 43
ENSG00000101132 34 34
     matches 16, differences 18
ENSG00000101138 141 141
     matches 64, differences 77
ENSG00000101146 59 59
     matches 33, differences 26
ENSG00000101158 201 201
     matches 100, differences 101
ENSG00000101161 232 232
     matches 94, differences 138
ENSG00000101166 273 273
     matches 146, differences 127
ENSG00000101181 146 146
     matches 69, differences 77
ENSG00000101182 41 41
     matches 16, differences 25
ENSG00000101189 74 74
     matches 27, differences 47
ENSG00000101246 138 138
     matches 60, differences 78
ENSG00000101343 261 261
     matches 121, differences 140
ENSG00000101361 99 99
     matches 55, differences 44
ENSG00000101407 151 151
     matches 54, differences 97
ENSG00000101421 71 71

In [150]:
for condition in conditions:
    print(condition, len(control_cells_ids_filtered_lsum[condition]), len(control_cells_ids_filtered_argm[condition]))
    assert len(control_cells_ids_filtered_lsum[condition]) == len(control_cells_ids_filtered_argm[condition])
    
    matches = 0
    num_pairs = len(control_cells_ids_filtered_lsum[condition])
    for pos, key in enumerate(control_cells_ids_filtered_lsum[condition].keys()):
        val1, val2 = control_cells_ids_filtered_lsum[condition][key], control_cells_ids_filtered_argm[condition][key]
        if val1 == val2:
            matches += 1
    print(f"     matches {matches}, differences {num_pairs - matches}")

ENSG00000001497 83 83
     matches 82, differences 1
ENSG00000003509 18 18
     matches 18, differences 0
ENSG00000004779 160 160
     matches 158, differences 2
ENSG00000004897 366 366
     matches 356, differences 10
ENSG00000005007 131 131
     matches 130, differences 1
ENSG00000005100 140 140
     matches 134, differences 6
ENSG00000005175 18 18
     matches 18, differences 0
ENSG00000005194 151 151
     matches 150, differences 1
ENSG00000005448 208 208
     matches 197, differences 11
ENSG00000006634 131 131
     matches 129, differences 2
ENSG00000006695 94 94
     matches 93, differences 1
ENSG00000006712 238 238
     matches 188, differences 50
ENSG00000006715 332 332
     matches 327, differences 5
ENSG00000006744 85 85
     matches 84, differences 1
ENSG00000007168 126 126
     matches 125, differences 1
ENSG00000007866 267 267
     matches 263, differences 4
ENSG00000007923 46 46
     matches 46, differences 0
ENSG00000008018 143 143
     matches 140, differences 3
ENSG00000008128 269 269
     matches 262, differences 7
ENSG00000008324 144 144
     matches 143, differences 1
ENSG00000008952 5 5
     matches 5, differences 0
ENSG00000008988 273 273
     matches 270, differences 3
ENSG00000009413 101 101
     matches 101, differences 0
ENSG00000010072 139 139
     matches 138, differences 1
ENSG00000010244 283 283
     matches 278, differences 5
ENSG00000010256 316 316
     matches 311, differences 5
ENSG00000010292 48 48
     matches 48, differences 0
ENSG00000010322 144 144
     matches 143, differences 1
ENSG00000011260 77 77
     matches 77, differences 0
ENSG00000011304 152 152
     matches 144, differences 8
ENSG00000011376 149 149
     matches 148, differences 1
ENSG00000011426 96 96
     matches 96, differences 0
ENSG00000011523 68 68
     matches 68, differences 0
ENSG00000012048 104 104
     matches 104, differences 0
ENSG00000012174 214 214
     matches 212, differences 2
ENSG00000013275 242 242
     matches 231, differences 11
ENSG00000013503 113 113
     matches 112, differences 1
ENSG00000013561 240 240
     matches 237, differences 3
ENSG00000013573 128 128
     matches 127, differences 1
ENSG00000013810 132 132
     matches 131, differences 1
ENSG00000014123 162 162
     matches 160, differences 2
ENSG00000014138 234 234
     matches 229, differences 5
ENSG00000014919 103 103
     matches 103, differences 0
ENSG00000015676 112 112
     matches 111, differences 1
ENSG00000018699 89 89
     matches 86, differences 3
ENSG00000020426 85 85
     matches 84, differences 1
ENSG00000021776 90 90
     matches 90, differences 0
ENSG00000023608 96 96
     matches 96, differences 0
ENSG00000023734 106 106
     matches 106, differences 0
ENSG00000025770 143 143
     matches 141, differences 2
ENSG00000025796 78 78
     matches 78, differences 0
ENSG00000025800 78 78
     matches 78, differences 0
ENSG00000027001 90 90
     matches 89, differences 1
ENSG00000028203 204 204
     matches 201, differences 3
ENSG00000029363 51 51
     matches 50, differences 1
ENSG00000029364 752 752
     matches 718, differences 34
ENSG00000030066 291 291
     matches 285, differences 6
ENSG00000031698 28 28
     matches 28, differences 0
ENSG00000033011 69 69
     matches 67, differences 2
ENSG00000033327 674 674
     matches 600, differences 74
ENSG00000034510 228 228
     matches 227, differences 1
ENSG00000035141 50 50
     matches 50, differences 0
ENSG00000035928 149 149
     matches 143, differences 6
ENSG00000036257 120 120
     matches 119, differences 1
ENSG00000037241 148 148
     matches 147, differences 1
ENSG00000037897 208 208
     matches 204, differences 4
ENSG00000038358 166 166
     matches 165, differences 1
ENSG00000039650 185 185
     matches 184, differences 1
ENSG00000040275 88 88
     matches 87, differences 1
ENSG00000041357 388 388
     matches 374, differences 14
ENSG00000041802 116 116
     matches 115, differences 1
ENSG00000042429 151 151
     matches 129, differences 22
ENSG00000042753 123 123
     matches 123, differences 0
ENSG00000044090 33 33
     matches 33, differences 0
ENSG00000044574 438 438
     matches 393, differences 45
ENSG00000046647 86 86
     matches 85, differences 1
ENSG00000047249 84 84
     matches 83, differences 1
ENSG00000047315 320 320
     matches 290, differences 30
ENSG00000047410 77 77
     matches 74, differences 3
ENSG00000048162 149 149
     matches 148, differences 1
ENSG00000048544 121 121
     matches 119, differences 2
ENSG00000048707 140 140
     matches 138, differences 2
ENSG00000049541 97 97
     matches 97, differences 0
ENSG00000050820 246 246
     matches 238, differences 8
ENSG00000051180 241 241
     matches 226, differences 15
ENSG00000051596 147 147
     matches 145, differences 2
ENSG00000052749 204 204
     matches 193, differences 11
ENSG00000053372 83 83
     matches 81, differences 2
ENSG00000053900 63 63
     matches 63, differences 0
ENSG00000054116 163 163
     matches 163, differences 0
ENSG00000055044 55 55
     matches 55, differences 0
ENSG00000055130 223 223
     matches 221, differences 2
ENSG00000055483 174 174
     matches 170, differences 4
ENSG00000055950 95 95
     matches 95, differences 0
ENSG00000058262 180 180
     matches 174, differences 6
ENSG00000058272 179 179
     matches 176, differences 3
ENSG00000058600 221 221
     matches 220, differences 1
ENSG00000058729 174 174
     matches 170, differences 4
ENSG00000058804 39 39
     matches 39, differences 0
ENSG00000060069 117 117
     matches 117, differences 0
ENSG00000060237 137 137
     matches 135, differences 2
ENSG00000060339 48 48
     matches 48, differences 0
ENSG00000060688 210 210
     matches 207, differences 3
ENSG00000061273 171 171
     matches 169, differences 2
ENSG00000061676 70 70
     matches 70, differences 0
ENSG00000061794 201 201
     matches 198, differences 3
ENSG00000061936 172 172
     matches 172, differences 0
ENSG00000062485 222 222
     matches 220, differences 2
ENSG00000062582 145 145
     matches 144, differences 1
ENSG00000062716 106 106
     matches 105, differences 1
ENSG00000062822 212 212
     matches 204, differences 8
ENSG00000063046 41 41
     matches 41, differences 0
ENSG00000063177 308 308
     matches 298, differences 10
ENSG00000063244 107 107
     matches 107, differences 0
ENSG00000063322 93 93
     matches 89, differences 4
ENSG00000063978 32 32
     matches 32, differences 0
ENSG00000064313 144 144
     matches 138, differences 6
ENSG00000064419 100 100
     matches 100, differences 0
ENSG00000064666 197 197
     matches 192, differences 5
ENSG00000064703 114 114
     matches 113, differences 1
ENSG00000065183 365 365
     matches 341, differences 24
ENSG00000065268 105 105
     matches 105, differences 0
ENSG00000065328 219 219
     matches 217, differences 2
ENSG00000065427 59 59
     matches 59, differences 0
ENSG00000065518 166 166
     matches 162, differences 4
ENSG00000065978 86 86
     matches 86, differences 0
ENSG00000066136 23 23
     matches 23, differences 0
ENSG00000066322 176 176
     matches 174, differences 2
ENSG00000066379 81 81
     matches 78, differences 3
ENSG00000066422 146 146
     matches 144, differences 2
ENSG00000067225 149 149
     matches 147, differences 2
ENSG00000067334 264 264
     matches 253, differences 11
ENSG00000067533 32 32
     matches 32, differences 0
ENSG00000067596 115 115
     matches 113, differences 2
ENSG00000067704 216 216
     matches 213, differences 3
ENSG00000068120 247 247
     matches 242, differences 5
ENSG00000068394 107 107
     matches 105, differences 2
ENSG00000068654 127 127
     matches 126, differences 1
ENSG00000068784 150 150
     matches 146, differences 4
ENSG00000069248 79 79
     matches 79, differences 0
ENSG00000069329 43 43
     matches 43, differences 0
ENSG00000069764 202 202
     matches 197, differences 5
ENSG00000070366 54 54
     matches 54, differences 0
ENSG00000070367 110 110
     matches 110, differences 0
ENSG00000070495 193 193
     matches 189, differences 4
ENSG00000070756 19 19
     matches 19, differences 0
ENSG00000070785 104 104
     matches 103, differences 1
ENSG00000070814 97 97
     matches 96, differences 1
ENSG00000070831 70 70
     matches 70, differences 0
ENSG00000071082 294 294
     matches 285, differences 9
ENSG00000071127 102 102
     matches 102, differences 0
ENSG00000071243 65 65
     matches 65, differences 0
ENSG00000071553 119 119
     matches 119, differences 0
ENSG00000071859 38 38
     matches 38, differences 0
ENSG00000071894 50 50
     matches 50, differences 0
ENSG00000071994 74 74
     matches 73, differences 1
ENSG00000072274 57 57
     matches 57, differences 0
ENSG00000072501 180 180
     matches 173, differences 7
ENSG00000072506 26 26
     matches 26, differences 0
ENSG00000072756 203 203
     matches 200, differences 3
ENSG00000072849 124 124
     matches 123, differences 1
ENSG00000073050 254 254
     matches 250, differences 4
ENSG00000073111 123 123
     matches 122, differences 1
ENSG00000073536 413 413
     matches 397, differences 16
ENSG00000073578 62 62
     matches 61, differences 1
ENSG00000073584 31 31
     matches 31, differences 0
ENSG00000073969 165 165
     matches 162, differences 3
ENSG00000074071 141 141
     matches 139, differences 2
ENSG00000074201 53 53
     matches 53, differences 0
ENSG00000074319 87 87
     matches 87, differences 0
ENSG00000074582 70 70
     matches 70, differences 0
ENSG00000074800 70 70
     matches 70, differences 0
ENSG00000074935 134 134
     matches 134, differences 0
ENSG00000075089 108 108
     matches 108, differences 0
ENSG00000075131 109 109
     matches 109, differences 0
ENSG00000075415 114 114
     matches 114, differences 0
ENSG00000075624 168 168
     matches 167, differences 1
ENSG00000075856 154 154
     matches 151, differences 3
ENSG00000075886 69 69
     matches 68, differences 1
ENSG00000075914 113 113
     matches 112, differences 1
ENSG00000076003 102 102
     matches 101, differences 1
ENSG00000076043 79 79
     matches 78, differences 1
ENSG00000076201 140 140
     matches 140, differences 0
ENSG00000076924 153 153
     matches 150, differences 3
ENSG00000077235 160 160
     matches 157, differences 3
ENSG00000077348 41 41
     matches 40, differences 1
ENSG00000077380 300 300
     matches 291, differences 9
ENSG00000077514 68 68
     matches 68, differences 0
ENSG00000077549 83 83
     matches 83, differences 0
ENSG00000078142 115 115
     matches 114, differences 1
ENSG00000079134 38 38
     matches 38, differences 0
ENSG00000079246 88 88
     matches 88, differences 0
ENSG00000079785 101 101
     matches 101, differences 0
ENSG00000079805 12 12
     matches 12, differences 0
ENSG00000080603 194 194
     matches 193, differences 1
ENSG00000080819 101 101
     matches 101, differences 0
ENSG00000080823 123 123
     matches 122, differences 1
ENSG00000080986 214 214
     matches 206, differences 8
ENSG00000081307 102 102
     matches 102, differences 0
ENSG00000081665 177 177
     matches 176, differences 1
ENSG00000082068 30 30
     matches 30, differences 0
ENSG00000082515 96 96
     matches 96, differences 0
ENSG00000082516 133 133
     matches 133, differences 0
ENSG00000082898 207 207
     matches 199, differences 8
ENSG00000083093 97 97
     matches 97, differences 0
ENSG00000083520 43 43
     matches 43, differences 0
ENSG00000083635 63 63
     matches 63, differences 0
ENSG00000083845 144 144
     matches 141, differences 3
ENSG00000083896 237 237
     matches 233, differences 4
ENSG00000084072 46 46
     matches 45, differences 1
ENSG00000084090 117 117
     matches 117, differences 0
ENSG00000084463 312 312
     matches 310, differences 2
ENSG00000084623 61 61
     matches 60, differences 1
ENSG00000085415 60 60
     matches 59, differences 1
ENSG00000085721 39 39
     matches 38, differences 1
ENSG00000085840 530 530
     matches 507, differences 23
ENSG00000085872 67 67
     matches 67, differences 0
ENSG00000086061 292 292
     matches 283, differences 9
ENSG00000086065 110 110
     matches 109, differences 1
ENSG00000086189 94 94
     matches 93, differences 1
ENSG00000086200 72 72
     matches 72, differences 0
ENSG00000086504 52 52
     matches 52, differences 0
ENSG00000086589 5 5
     matches 5, differences 0
ENSG00000086598 137 137
     matches 132, differences 5
ENSG00000086758 94 94
     matches 94, differences 0
ENSG00000086827 200 200
     matches 199, differences 1
ENSG00000087087 307 307
     matches 274, differences 33
ENSG00000087157 104 104
     matches 104, differences 0
ENSG00000087191 17 17
     matches 17, differences 0
ENSG00000087263 114 114
     matches 110, differences 4
ENSG00000087269 47 47
     matches 47, differences 0
ENSG00000087365 500 500
     matches 476, differences 24
ENSG00000087470 168 168
     matches 167, differences 1
ENSG00000087586 58 58
     matches 58, differences 0
ENSG00000088038 332 332
     matches 324, differences 8
ENSG00000088205 137 137
     matches 133, differences 4
ENSG00000088325 361 361
     matches 345, differences 16
ENSG00000088356 116 116
     matches 115, differences 1
ENSG00000088766 111 111
     matches 111, differences 0
ENSG00000088930 66 66
     matches 66, differences 0
ENSG00000088986 71 71
     matches 69, differences 2
ENSG00000089009 273 273
     matches 269, differences 4
ENSG00000089048 149 149
     matches 148, differences 1
ENSG00000089053 40 40
     matches 40, differences 0
ENSG00000089157 184 184
     matches 180, differences 4
ENSG00000089159 161 161
     matches 159, differences 2
ENSG00000089195 114 114
     matches 114, differences 0
ENSG00000089289 281 281
     matches 276, differences 5
ENSG00000089685 46 46
     matches 46, differences 0
ENSG00000089737 286 286
     matches 282, differences 4
ENSG00000089902 35 35
     matches 35, differences 0
ENSG00000090054 28 28
     matches 28, differences 0
ENSG00000090061 327 327
     matches 318, differences 9
ENSG00000090273 117 117
     matches 116, differences 1
ENSG00000090470 99 99
     matches 98, differences 1
ENSG00000090861 40 40
     matches 40, differences 0
ENSG00000090889 129 129
     matches 129, differences 0
ENSG00000090989 182 182
     matches 179, differences 3
ENSG00000091140 311 311
     matches 306, differences 5
ENSG00000091157 103 103
     matches 103, differences 0
ENSG00000091651 81 81
     matches 81, differences 0
ENSG00000092010 121 121
     matches 119, differences 2
ENSG00000092020 52 52
     matches 52, differences 0
ENSG00000092036 189 189
     matches 181, differences 8
ENSG00000092094 70 70
     matches 70, differences 0
ENSG00000092108 152 152
     matches 150, differences 2
ENSG00000092148 130 130
     matches 128, differences 2
ENSG00000092199 334 334
     matches 327, differences 7
ENSG00000092201 93 93
     matches 92, differences 1
ENSG00000092330 76 76
     matches 75, differences 1
ENSG00000092439 128 128
     matches 126, differences 2
ENSG00000092853 134 134
     matches 131, differences 3
ENSG00000092871 7 7
     matches 7, differences 0
ENSG00000093009 92 92
     matches 92, differences 0
ENSG00000094804 192 192
     matches 190, differences 2
ENSG00000094880 177 177
     matches 176, differences 1
ENSG00000094914 212 212
     matches 210, differences 2
ENSG00000095059 66 66
     matches 66, differences 0
ENSG00000095139 333 333
     matches 325, differences 8
ENSG00000095787 162 162
     matches 160, differences 2
ENSG00000095906 153 153
     matches 153, differences 0
ENSG00000096080 121 121
     matches 121, differences 0
ENSG00000096401 99 99
     matches 95, differences 4
ENSG00000097046 95 95
     matches 95, differences 0
ENSG00000099194 24 24
     matches 24, differences 0
ENSG00000099246 43 43
     matches 43, differences 0
ENSG00000099326 128 128
     matches 128, differences 0
ENSG00000099341 22 22
     matches 22, differences 0
ENSG00000099381 69 69
     matches 69, differences 0
ENSG00000099783 258 258
     matches 255, differences 3
ENSG00000099795 74 74
     matches 73, differences 1
ENSG00000099800 178 178
     matches 173, differences 5
ENSG00000099817 225 225
     matches 220, differences 5
ENSG00000099821 214 214
     matches 211, differences 3
ENSG00000099942 120 120
     matches 120, differences 0
ENSG00000099956 182 182
     matches 182, differences 0
ENSG00000099995 332 332
     matches 322, differences 10
ENSG00000100023 130 130
     matches 127, differences 3
ENSG00000100027 72 72
     matches 72, differences 0
ENSG00000100028 182 182
     matches 177, differences 5
ENSG00000100029 65 65
     matches 65, differences 0
ENSG00000100033 379 379
     matches 374, differences 5
ENSG00000100084 341 341
     matches 329, differences 12
ENSG00000100109 61 61
     matches 61, differences 0
ENSG00000100129 57 57
     matches 57, differences 0
ENSG00000100142 337 337
     matches 320, differences 17
ENSG00000100209 86 86
     matches 86, differences 0
ENSG00000100216 104 104
     matches 103, differences 1
ENSG00000100220 171 171
     matches 169, differences 2
ENSG00000100296 32 32
     matches 32, differences 0
ENSG00000100297 90 90
     matches 90, differences 0
ENSG00000100316 1996 1996
     matches 1717, differences 279
ENSG00000100319 100 100
     matches 99, differences 1
ENSG00000100347 102 102
     matches 101, differences 1
ENSG00000100353 186 186
     matches 181, differences 5
ENSG00000100387 57 57
     matches 57, differences 0
ENSG00000100401 130 130
     matches 129, differences 1
ENSG00000100410 231 231
     matches 226, differences 5
ENSG00000100413 109 109
     matches 109, differences 0
ENSG00000100462 127 127
     matches 126, differences 1
ENSG00000100479 56 56
     matches 56, differences 0
ENSG00000100519 151 151
     matches 147, differences 4
ENSG00000100522 112 112
     matches 112, differences 0
ENSG00000100554 139 139
     matches 136, differences 3
ENSG00000100564 85 85
     matches 85, differences 0
ENSG00000100567 372 372
     matches 365, differences 7
ENSG00000100575 201 201
     matches 199, differences 2
ENSG00000100603 226 226
     matches 220, differences 6
ENSG00000100632 86 86
     matches 85, differences 1
ENSG00000100664 175 175
     matches 174, differences 1
ENSG00000100697 158 158
     matches 156, differences 2
ENSG00000100726 74 74
     matches 74, differences 0
ENSG00000100764 316 316
     matches 300, differences 16
ENSG00000100804 270 270
     matches 265, differences 5
ENSG00000100811 82 82
     matches 81, differences 1
ENSG00000100813 191 191
     matches 189, differences 2
ENSG00000100836 148 148
     matches 147, differences 1
ENSG00000100865 78 78
     matches 77, differences 1
ENSG00000100883 81 81
     matches 81, differences 0
ENSG00000100890 42 42
     matches 42, differences 0
ENSG00000100902 40 40
     matches 40, differences 0
ENSG00000100911 151 151
     matches 151, differences 0
ENSG00000100941 86 86
     matches 86, differences 0
ENSG00000100949 116 116
     matches 116, differences 0
ENSG00000101003 186 186
     matches 180, differences 6
ENSG00000101057 106 106
     matches 101, differences 5
ENSG00000101132 34 34
     matches 34, differences 0
ENSG00000101138 141 141
     matches 140, differences 1
ENSG00000101146 59 59
     matches 59, differences 0
ENSG00000101158 201 201
     matches 200, differences 1
ENSG00000101161 232 232
     matches 229, differences 3
ENSG00000101166 273 273
     matches 261, differences 12
ENSG00000101181 146 146
     matches 145, differences 1
ENSG00000101182 41 41
     matches 41, differences 0
ENSG00000101189 74 74
     matches 74, differences 0
ENSG00000101246 138 138
     matches 136, differences 2
ENSG00000101343 261 261
     matches 251, differences 10
ENSG00000101361 99 99
     matches 99, differences 0
ENSG00000101407 151 151
     matches 146, differences 5
ENSG00000101421 71 71
     matches 71, differences 0
ENSG00000101444 147 147
     matches 145, differences 2
ENSG00000101639 202 202
     matches 200, differences 2
ENSG00000101654 114 114
     matches 113, differences 1
ENSG00000101773 117 117

In [168]:
import matplotlib.pyplot as plt

control_cells_ids_filtered_df = pd.DataFrame(pd.DataFrame(control_cells_ids_filtered).stack())
control_cells_ids_filtered_argm_df = pd.DataFrame(pd.DataFrame(control_cells_ids_filtered_argm).stack())
control_cells_ids_filtered_lsum_df = pd.DataFrame(pd.DataFrame(control_cells_ids_filtered_lsum).stack())

In [163]:
control_cells_ids_filtered_df.head()

AAACCCAAGAAATCCA-27  ENSG00000145414    GAGGGATTCGTGGACC-27
AAACGAAAGTCATCGT-17  ENSG00000145414    AGTGCCGGTCATGACT-17
AATGCCACAGCTGTAT-47  ENSG00000145414    TGCGGCAAGACAACTA-47
ACAGAAATCAACTGAC-10  ENSG00000145414    AAATGGACAGAGTAAT-10
ACATCCCTCTGACGCG-34  ENSG00000145414    CAACCTCAGGCACTAG-34
dtype: object

In [166]:
pd.DataFrame(control_cells_ids_filtered_df).head()

                                                       0
AAACCCAAGAAATCCA-27 ENSG00000145414  GAGGGATTCGTGGACC-27
AAACGAAAGTCATCGT-17 ENSG00000145414  AGTGCCGGTCATGACT-17
AATGCCACAGCTGTAT-47 ENSG00000145414  TGCGGCAAGACAACTA-47
ACAGAAATCAACTGAC-10 ENSG00000145414  AAATGGACAGAGTAAT-10
ACATCCCTCTGACGCG-34 ENSG00000145414  CAACCTCAGGCACTAG-34